### ISSUE TITLE
Detect and handle re-entrancy patterns

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#10]
Re-entrancy attacks have been a huge plague on Ethereum smart contract development. Consider the following contract:
```solidity
contract VulnerableContract {
    mapping(address => uint256) balances;

    function deposit() public payable {
        balances[msg.sender] += msg.value;
    }

    function withdraw(uint256 amount) public {
        require(balances[msg.sender] >= amount);
        msg.sender.call.value(amount)();
        balances[msg.sender] -= amount;
    }
}
```

If `msg.sender` is a contract, `call` calls the contract. A maliciously-crafted contract can then call `withdraw` again, and the `require` will pass since `balances` hasn't been updated. Repeating this potentially up to the block gas limit, the entire `VulnerableContract`'s balance can be drained.

This is resolved by the checks-effects-interactions pattern (more info: https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html), where effects (writing to state) are applied before interactions (contract calls).

Detecting this should be quite easy in the compiler, which should have a flag (by default on and by default error) to automatically provide feedback to developers if they don't follow the checks-effects-interactions pattern. Developers that want to can disable it for parts of the code via a pragma.

**Comment by emilyaherbert** [comment]
Pinging about this 😄 I'm hoping to include it as an example in the EthDenver talk.

**Comment by mohammadfawaz** [comment]
Can this be closed now? @nfurfaro

**Comment by mohammadfawaz** [comment]
Thanks! I'm assuming no.

**Comment by emilyaherbert** [comment]
@sezna  are you still hacking on this one or can I unassign you (and potentially assign myself)?
