### ISSUE TITLE
Contract calls via IR are still a bit iffy.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#1003]
The return type is still a mystery to IR and either needs to be provided somehow.  It could be fetched from the ABI although that might not always be possible.

An alternative might be to not return values in IR and have a workaround getting the value from `$ret` some other way, although I imagine we still need to know the type somehow.

Also, I eyeballed the recent ASM which sets up the args and I'm not convinced it's 100% correct.  I made the IR pass verification but it may not quite be right.

**Comment by mohammadfawaz** [comment]
Hmmm I did deploy and run some of our test contacts and they seemed okay, so I assumed the ASM is correct on both sides. I can take another look if there's something specific that worries you.

**Comment by mohammadfawaz** [comment]
Oh I see you already found some issues 🤔

**Comment by otrho** [comment]
I was thinking the ASM might be not-quite-right too, after my changes to the structs and `get_ptr`.

BTW, I was thinking about this last night, the `get_ptr` for the user args to convert a struct pointer to an address is casting to a `u64` but really it's casting to a `ptr u64` which isn't really right.  We should add a `bitcast` to convert the pointer, and what we have now shouldn't type check in the verification.

**Comment by mohammadfawaz** [comment]
Wait, regarding the return type - every `TypedExpression` carries its `return_type`: https://github.com/FuelLabs/sway/blob/75187e98d4e344d1e7efd27d27fa27054a57671a/sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs#L275
Can't we just use that here: https://github.com/FuelLabs/sway/blob/75187e98d4e344d1e7efd27d27fa27054a57671a/sway-core/src/optimize.rs#L526 by just passing `ast_expr.return_type`?

**Comment by mohammadfawaz** [comment]
We can convert that `TypeId` into an IR `Type` and rewrite the contract call as:
`v13 = contract_call <type> <method_name> v9, v10, v11, v12`, kinda following LLVM.
(LLVM does `%x = call <ty> @methodname( ... )`)
For methods that don't return anything, we would have a `Unit` type.

**Comment by otrho** [comment]
Yep, cool.  I know -- my recent struct changes were kinda the same, undoing some overthinking. :slightly_smiling_face: 

Putting the type in there makes sense.

**Comment by otrho** [comment]
Closed by #1020.
