### ISSUE TITLE
Skipping the `gas` parameter in contract calls always causes an `OutOfGas` error

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1015]
Example from the `basic_storage` E2E test:
```rust
fn main() -> u64 {
    let addr = abi(StoreU64, 0xc664e47a0de686a029134e5122383d99d0d29e54179e14c92dd433413a07620a);
    let key = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
    let value = 4242;

    addr.store_u64 {
        gas: 10000
    }
    (key, value);

    let res = addr.get_u64 {
        gas: 10000
    }
    (key);
    res
}
```
Skipping either of the `gas` parameters for the contract calls causes an `OutOfGas` error. I looked at the assembly generated, and we seem to be passing `$cgas` directly to the `CALL` instruction when `gas` is omitted above, which seems reasonable. So, not sure what's going on. @adlerjohn said this shouldn't happen.

**Comment by adlerjohn** [comment]
Testing myself on a small script, I get the following:

`
[Call { id: 5277d0d9e5acf84a3a680c4031c2fdef62592da7becfb20e1ed82b396a010d03, to: 5277d0d9e5acf84a3a680c4031c2fdef62592da7becfb20e1ed82b396a010d03, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 0, a: 3409119176, b: 42, pc: 1552, is: 1552 }, Panic { id: 5277d0d9e5acf84a3a680c4031c2fdef62592da7becfb20e1ed82b396a010d03, reason: 156853325914963968, pc: 1552, is: 1552 }, ScriptResult { result: InstructionResult { reason: OutOfGas, instruction: Instruction { op: 45, ra: 16, rb: 20, rc: 19, rd: 21, imm06: 213, imm12: 1237, imm18: 83157, imm24: 4277461 } }, gas_used: 446 }]
`

**Note the `gas: 0` for the call!**

The asm does properly use `$cgas` as far as I can tell
```
lw   $r5 $cgas i0             ; loading $cgas (gas) into abi function
...
call $r0 $r4 $r3 $r5          ; call external contract
```

My guess is that the VM might not be setting `$cgas` properly?

**Comment by adlerjohn** [comment]
Oh wait I know @mohammadfawaz...

```
lw   $r5 $cgas i0
```

This loads the memory at `$cgas` into `$r5`, rather than copying `$cgas` into `$r5`. Need to use [`MOVE`](https://github.com/FuelLabs/fuel-specs/blob/63b2cf416917c23822c9a44af643460d598145f2/specs/vm/opcodes.md#move-move) instead.

**Comment by mohammadfawaz** [comment]
Wow! Okay - that solves that mystery. Easy fix.

**Comment by otrho** [comment]
> Need to use [`MOVE`](https://github.com/FuelLabs/fuel-specs/blob/63b2cf416917c23822c9a44af643460d598145f2/specs/vm/opcodes.md#move-move) instead.

Or just use it directly: `call $r0 $r4 $r3 $cgas`.

**Comment by mohammadfawaz** [comment]
For IR, we just need to translate `read_register` to a `MOVE` instead of a `LW`. I'm hoping the register allocator can then coalesce the two registers and we end up with `$cgas` inlined in `CALL`.
