### ISSUE TITLE
Operators ">=" and "<=" are not working as expected

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1056]
While working on Swayswap, I noticed that the operators above were not doing the right thing. I had to change
* `x >= y` to `x > y - 1`
* `x <= y` to `x < y + 1`

I will post an actual example later.

**Comment by ControlCplusControlV** [comment]
Ge and Le are implemented as `!<` and `!>`, but that should be equivalent with integers. I can fix this in a PR though now that Supertraits exist so `>=` and `<=` can be properly implemented unless you already a had a fix in mind?

**Comment by mohammadfawaz** [comment]
@sezna have an open PR already here https://github.com/FuelLabs/sway/pull/1092
