### ISSUE TITLE
Review approach to parsing in `sway-fmt`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1057]
There were some concerns raised at the tooling sync today around some possible duplication in work around `sway-fmt`'s approach to parsing. We should make sure to attempt to share as much of this logic with `sway-core` as is feasible and avoid having multiple implementations.

cc @ControlCplusControlV 
also cc @canndrew - if I remember correctly you're currently working on reworking sway's parser - is that right?

**Comment by canndrew** [comment]
Yeah. I've written a new parser though it's not merged into master yet. i would certainly make sense to re-use that.

**Comment by eureka-cpu** [comment]
I think (if I remember correctly) one of the problems is that the current formatter isn't making use of the type knowledge from the compiler and instead has separate logic to determine how to format each type.

**Comment by mitchmindtree** [comment]
Assigning @eureka-cpu as designated driver for this one after our tooling chat today :smile: :tada: 

A couple ways to move forward that come to mind:

- Evaluate the approach taken by existing formatters (like `rustfmt`) - how/why are they different? Can we take inspiration or learn lessons? What are the higher-level steps taken to get from unformatted src -> formatted src?
- Review the new parser and see if it has what we need in terms of spans and "best effort" parsing. I.e. will attempt to construct and return the rest of the tree even if a branch is malformed. If missing anything, open issues to discuss desired features / best approaches.

**Comment by mitchmindtree** [comment]
Going to close this in favour of the new tracking issue for the revamped swayfmt at #1516.
