### ISSUE TITLE
Move issues from `sway-lib-core` and `sway-lib-std` into `sway` issue tracker

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1059]
There are steps on how to go about this [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository).

We should remember to add the necessary labels too.

Speaking of, perhaps we should update the labels with something like:

- Change `stdlib` -> `lib-std`
- Add `lib-core`

@adlerjohn did you want to take care of this? Otherwise I'm happy to have a go.

**Comment by adlerjohn** [comment]
I can handle it.

**Comment by adlerjohn** [comment]
It is done
