### ISSUE TITLE
Authentication module

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1061]
## Problem

In Ethereum, authentication (i.e. knowing _who_ called an ABI method) is a key component of enabling repeated actions against the same contract and assigning them to a single identity. As an example, if a user bonds some tokens, that same user (and only that same user) must be able to then unbond their tokens at a later time. This requires being able to identify accounts in a persistent way.

Ethereum (specifically, Solidity) exposes this functionality as [`msg.sender`](https://docs.soliditylang.org/en/v0.7.6/units-and-global-variables.html#block-and-transaction-properties), a globally-available variable that provides the address (i.e. account) of the caller. This can either be the contract that called the ABI method or the transaction sender, since Ethereum transactions have a native sender.

Transactions in the UTXO model don't have a concept of "sender" or ["from" address](https://en.bitcoin.it/wiki/From_address). Therefore, we can't rely on a uniform mechanism for authenticating ABI method callers.

## Proposal

I propose a standard library module to perform authentication in three ways:
1. Contract caller. This is as simple as checking that the parent context is not external, then fetching the parent context's contract ID.
1. Signature. Check that the parent context is external, then perform signature verification on `(nonce, selector, args...)`, where `nonce` is the nonce of the user signing the action. This nonce is stored in the contract's storage, as opposed to Ethereum where nonces are associated with accounts globally.
1. All-the-same. Check that the parent context is external, then check that all non-contract inputs are all owned by the same address (which could be a predicate hash or a pubkey hash). If so, then consider that address as the caller. This is a heuristic that does not work in all cases, so should be a feature users can optionally use.

**Comment by nfurfaro** [comment]
Re: Auth method # 2:
>Signature. Check that the parent context is external, then perform signature verification on (nonce, selector, args...), where nonce is the nonce of the user signing the action. This nonce is stored in the contract's storage, as opposed to Ethereum where nonces are associated with accounts globally.

I want to tackle this and try to wrap it up, but I have a few comments:
- The actual recovery part is easy as it would just be a wrapper around `ec_recover_address()`.
- As for the (nonce, selector, args...), an example scenario of the method in use would really help me to better understand the specifics.
- We may need a stdlib module to manage nonces (as mentioned by @adlerjohn) :
>and there should be some libraries to handle nonce management.

I think we're finally at a place where this can be completed with a bit of feedback on how we foresee this being used.
cc @SilentCicero @simonr0204

**Comment by adlerjohn** [comment]
I'm not sure this is really needed any time soon (if ever) in the standard library. The design space for how to handle nonces is so wide, and storage is still so new. There are much higher-priority things that could be worked on, and this can be revisited if there's concrete demand for the feature.

**Comment by nfurfaro** [comment]
makes sense. I'm going to close, and we can reopen if the need arises.
