### ISSUE TITLE
Create a new type-alias `AssetId`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1064]
I think it could be helpful to add a type alias for the `ContractId` type: `AssetId`.
It would be purely for the added semantic context, as all `AssetId`s  (with the exception of the NATIVE_ASSET_ID) are also `ContractId`s, but not all `ContractId`s represent assets.

cc @sezna @adlerjohn

**Comment by nfurfaro** [comment]
I'm wondering if Sway (and this issue) might be better served with Newtype rather than type aliases.
Adding a new EthAddress type would be another place we could use NewType and actually get type safety as a benefit.
As I understand it, type aliases don't give us that.

**Comment by sezna** [comment]
This is true, but also supported by the fact that Sway doesn't have type aliases 😄

**Comment by otrho** [comment]
Rust has newtype via `struct AssetId(ContractId);` AFAICT although I've personally never used them.  We should have those.

**Comment by nfurfaro** [comment]
Cool. I think the only reason I hadn't implemented the  `AssetId` type yet was a lack of type aliases 😅. But now I think NewType is a better fit.

**Comment by otrho** [comment]
In Rust it looks a bit like a tuple and you index the inner with `.0` (at zero cost).  I say I've never used them but they're everywhere in the IR for the context arenas, e.g., `pub struct Block(pub generational_arena::Index);`

So you either explicitly use `.0` to 'unwrap' the newtype, or yeah you could use a simple `from()` but if you're passing the newtype to something that expects the inner type then explicit unwrapping is probably desirable?

**Comment by sezna** [comment]
It's called a [tuple struct](https://doc.rust-lang.org/1.9.0/book/structs.html) in rust (scroll down a bit on that page). We could add tuple structs in general, or we could keep using the named inner field pattern for newtypes, since it's the same thing but with a name instead of `.0`?

**Comment by nfurfaro** [comment]
Bumping this :)

**Comment by mohammadfawaz** [comment]
This is now done.
