### ISSUE TITLE
Add the ability to recover an ethereum address.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1068]
We can currently recover a fuel public key or address.
We should add a module (maybe external to lib-std) to allow recovery of ethereum addresses:
ie: `ec_recover_eth_addr` (will probably require a new `B160` type as a prerequisite).

**Comment by nfurfaro** [comment]
I'm guessing (but don't want to assume) that with this module we'd be targeting canonical ethereum signatures which have 3 separate parameters (r, s, yParity) and are 65 bytes long, as opposed to compact 64-byte signatures?

**Comment by adlerjohn** [comment]
Yes and no. Yes that we should be able to convert 65-byte sigs to 64-byte sigs. But that's only on the _input_ side. On the _output_ side, we should be able to output a 20-byte EVM address.

Also, to be practical rather than academic, I suggest the namespace `std::vm::evm` for placing EVM-specific standard library components.

**Comment by nfurfaro** [comment]
## on the input side
>we should be able to convert 65-byte sigs to 64-byte sigs

I'll look for a preexisting way to do this. 
It would certainly simplify things in sway if we only pass in 64 byte sigs as we can then reuse our `B512` type.

## on the output side
>we should be able to output a 20-byte EVM address.

yes. 
are we ok with using a zero-padded b256 for the output, or do we need a new `b160` type?
I'm not sure this would be very clean  to implement in the stdlib, ie:
```
// eth address:
pub struct B160 {
    bytes: [u8; 20]
}
```
cc @adlerjohn @SilentCicero

**Comment by adlerjohn** [comment]
Input: just follow what the specs say to bitshift and stuff.

Output: a `[u8; 20]` would take up 20 words. My suggestion would be to just use a `b256` for now, and document which way it's aligned. Since whatever you're comparing to can just be aligned the same way, it's not problem.

**Comment by simonr0204** [comment]
Is this the motivation for this : #1065 , or is this for general ecrecover on any/all EIP-191 signed data?

**Comment by nfurfaro** [comment]
I believe the original motivation was just a general purpose way to recover the ethereum address that signed a message, so pretty much on par with with er_recover does in Solidity.
