### ISSUE TITLE
Implement the Eq trait for the Result Type

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1073]
This is needed for testing and working with results in general, ie, to do this sort of thing:
`assert(result == Result::Err(AuthError::ContextError));`

**Comment by emilyaherbert** [comment]
This is waiting on trait constraints #1162, as the definition for `Eq` on `Result` would be:

```rust
impl<T, E> Eq for Result<T, E> where T: Eq, E: Eq {
  ..
}
```

because you would need those constraints to be filled before you could compare the internal values.

**Comment by nfurfaro** [comment]
Closing this as `match` serves this purpose.
