### ISSUE TITLE
Add module to the stdlib with wrapper functions for common (all?) opcodes

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1074]
Like FuelLabs/sway-lib-std#38 , the goal here would be to minimize the usage of assembly needed while building out the stdlib (and other libraries) by providing utilities for calling opcodes in a simpler way (in terms of writing , reviewing and reading/maintaining).
wrapper functions could be chained together to achieve whatever is needed for the current task at hand.
Idea by @otrho .

- [ ] extract overflow FLAG wrapper functions  `enable_overfow()` and `disable_overflow()` from `U128` type module.

**Comment by mohammadfawaz** [comment]
I'm thinking we should start by transforming the implementation of all core ops into intrinsics (instead of asm blocks) that become IR instructions such as `add`, `mul`, etc. These would make writing optimization passes like "instruction combining" so much easier.

**Comment by vaivaswatha** [comment]
> I'm thinking we should start by transforming the implementation of all core ops into intrinsics (instead of asm blocks) that become IR instructions such as `add`, `mul`, etc. These would make writing optimization passes like "instruction combining" so much easier.

https://github.com/FuelLabs/sway/pull/1948#issue-1268611016

**Comment by mohammadfawaz** [comment]
I'm going to close this now given that we have such wrappers in the form of intrinsics for most of the useful opcodes. We are now adding new intrinsics as the need arises.
