### ISSUE TITLE
Proposal to add equivalent of the `Vec` type

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1077]
When writing Sway code I have been finding myself wanting the `Vec` type, it would be awesome if we had it 😄 

Dependent on this issue (https://github.com/FuelLabs/sway/issues/428) and on dynamic size arrays

Rust's implemenation of `Vec`: https://doc.rust-lang.org/std/vec/struct.Vec.html

**Comment by AlicanC** [comment]
How would this be represented in the ABI and coded?

From the impl at #1118:
```rs
struct RawVec<T> {
    ptr: u64,
    cap: u64,
}
pub struct Vec<T> {
    buf: RawVec,
    len: u64,
}
```

This would be coded like `(ptr: u64, cap: u64, len: u64)` which lacks the actual data.

**Comment by otrho** [comment]
Do we plan to send heap oriented data across the FFI?  This will be very tricky, fairly brittle IMO, easy to get wrong, other than for raw pointers to individual heap allocations.

**Comment by AlicanC** [comment]
I have to send data from the heap in my Multicall script which was the reason for `mem::Buffer`. Currently the MC script has a fixed-length section that can be represented in the ABI (and can be coded with our AbiCoder) and a dynamic-length part managed with a Buffer.

**Comment by adlerjohn** [comment]
Yes, we plan to support heap types across the ABI. The SDKs will have to be smart enough to know about particular heap types and set their pointers correctly. The data can be somewhere in `scriptData`, it doesn't have to be on the actual heap.

**Comment by mohammadfawaz** [comment]
TIL! But yeah that makes sense.

![image](https://user-images.githubusercontent.com/59666792/170702042-a3607611-0b8b-4503-9616-fe5cbe593e87.png)
