### ISSUE TITLE
Commit working `Forc.lock` files to ensure that `core` is pinned to a working state

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1080]
Just a reminder to commit the `Forc.lock` files for the test projects. This will ensure that even if `sway-lib-core` breaks, tests will continue to work until they are explicitly updated with `forc update`.

**Comment by adlerjohn** [comment]
I don't think this is need anymore since they're all in one repo now? @mitchmindtree

**Comment by mitchmindtree** [comment]
Yes it should be fine to close this as the `sway` repo is already setup correctly. We can commit the lock files when we work out where to put the `sway-lib-std` tests (#1058).

---

Side note: During #1052, it crossed my mind that we could remove all the example and E2E test `Forc.lock` files now that they all depend via `path`s, however in the end I decided it might be best to leave them in. My thinking is that 1. they shouldn't change or contribute to noise anyway and 2. in the rare future case we do need to pin some test or example for whatever reason, we won't accidentally omit their `Forc.lock` files by forgetting about an entry in the `.gitignore`.
