### ISSUE TITLE
Automatically build all test projects and their dependencies when running tests

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1082]

**Comment by nfurfaro** [comment]
Now that we have a build script (`build.sh`) for the stdlib test projects, this is not an issue for me anymore. I'm not sure if we still want to pursue this or close it.

**Comment by adlerjohn** [comment]
`build.sh` doesn't error when a project doesn't compile successfully.

**Comment by nfurfaro** [comment]
>doesn't error when a project doesn't compile successfully
What I'm seeing is that If I introduce an error into either a stdlib module or a test-project, `build.sh` does error out...
But maybe certain cases are slipping through?
cc @adlerjohn

**Comment by adlerjohn** [comment]
I have to test that again. Regardless, this also needs to be ran in CI.

**Comment by nfurfaro** [comment]
@adlerjohn I think it is:
https://github.com/FuelLabs/sway/blob/1549a1f84cdbfd05bdce809ae81a131dcd6968ec/.github/workflows/ci.yml#L171

**Comment by adlerjohn** [comment]
Ah so it is.
