### ISSUE TITLE
`forc` has substantial duplicate code

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#1107]
As mentioned by @mitchmindtree in #863. Please feel free to add instances here so we can track progress:

- [x] create abstraction for checking Sway `tree_types` in `forc_abi_json`, `forc_deploy` & `forc_run` @eureka-cpu #1105 
- [x] update the `Manifest::from_dir` function to automatically check parent directories in the case that the immediate directory doesn't contain a manifest. This might save us from always having to call `find_manifest_dir` everywhere before we can call `Manifest::from_dir`. @eureka-cpu #1232 @mitchmindtree #1249

**Comment by eureka-cpu** [comment]
@mitchmindtree @JoshuaBatty if you find any other instances of dup code feel free to add them here and I'll tackle them regularly until we manage it to the point of closing the issue

**Comment by mitchmindtree** [comment]
Closing now that these have been solved. Future areas of code cleanup/refactoring can get highlighted in dedicated issues.
