### ISSUE TITLE
Compiler error when using a generic struct as a field in another generic struct

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1116]
```rust
script;

struct Generic1<T> {
    a: T,
}

struct Generic2<T> {
    b: Generic1<T>,
}

fn main() {
}
```

```console
error
 --> /home/devel/tmp/sw/generic_2/src:8:17
  |
6 | 
7 | struct Generic2<T> {
8 |     b: Generic1<T>,
  |                 ^ Could not find symbol "T" in this scope.
9 | }
  |
____

error
 --> generic_2/src/main.sw:8:17
  |
6 | 
7 | struct Generic2<T> {
8 |     b: Generic1<T>,
  |                 ^ Unknown type name.
9 | }
  |
____
```

**Comment by sezna** [comment]
I did a bit of digging.

When type checking struct declarations [here](https://github.com/FuelLabs/sway/blob/master/sway-core/src/semantic_analysis/ast_node/mod.rs#L629), we see if the type of the field is generic and, if it is, use the type parameters to provide a type ID. If it isn't one of the generic arguments, we type check it against the namespace.

Nested structs/generics which themselves have inner generics do not fall into the former category and end up getting checked against the namespace as-is, where that type argument name doesn't exist.

A valid solution here would be to add a third state to this checking -- whether something _contains_ a generic. We could abstract the following block:
```rust
                                    let r#type = match r#type.matches_type_parameter(&type_mapping)
                                    {
                                        Some(matching_id) => {
                                            insert_type(TypeInfo::Ref(matching_id))
                                        }
                                        None => check!(
                                            namespace.resolve_type_with_self(
                                                r#type, self_type, type_span, false
                                            ),
                                            insert_type(TypeInfo::ErrorRecovery),
                                            warnings,
                                            errors,
                                        ),
                                    };
```

into a function which drills down into a type, replacing all generic references to the provided type mapping, and then resolves the types in the namespace with all generics mapped. This function could then be reused in enums, as well.
