### ISSUE TITLE
Add `is_reference_type()`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1119]
Similar to #818, add a `is_reference_type::<T>()` function that is replaced by `true` or `false` at compile time depending on if the type is a reference type or not. This is needed so that the stdlib can do different run time logic depending on whether a type is a pointer to data vs data in a register.

Note that currently structs with a single single-word field are actually reference types, so the stdlib cannot use `size_of::<T>()` against the word size exclusively for such runtime checks.

**Comment by mohammadfawaz** [comment]
In the near future, we won't really know if a type is going to be implemented in registers or not. It is very reasonable for the IR to decide to unwrap a local `struct` of 2 ints into 2 two separate ints, or an array into its individual elements (if the array accesses have fixed indices), in which case the result of `is_reference_type::<T>()` becomes incorrect. Where a variable is implemented is really just an implementation detail. We can imagine a (legal but really horrible) compiler that implements everything in storage!

That being said, I may have to catch up on some Slack message to understand the context better. I imagine this has something to do with the `asm` blocks.

**Comment by otrho** [comment]
Correct.  This isn't something we want to keep once we add intrinsics and remove the ASM blocks from the stdlib.  But until then we need something to help out.
