### ISSUE TITLE
Domain-separate intrinsics

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1122]
Following up on #818 and #1119, we should:
- [ ] #1531
- [ ] #1533
- [x] #1532

**Comment by otrho** [comment]
Do we prefer `__size_of()` to just using `intrinsics::size_of()` in user code?

**Comment by adlerjohn** [comment]
We would prefer users use `intrinsics::size_of()`, so that they never need to know that intrinsics even exist.

**Comment by mohammadfawaz** [comment]
A lot of work went in recently to clean intrinsics up (both in the standard library and the compiler). I think this can be closed now.

Future intrinsics can now be added quite easily, as needed.
