### ISSUE TITLE
Add a language test that defines consts and uses them in a library

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1125]
The following code compiles and runs as expected, returning `4` from the script:
```
script;

fn main() -> u64 {
    const ONE: u64 = 1;
    const TWO: u64 = 2;
    let three: u64 = ONE + TWO;
    asm(sum, r1: ONE, r2: three) {
        add sum r1 r2;
        sum: u64
    }
}
```

However, when the const values are in a library this seems to break down.
For example, if this script:
```
script;

use consts::adder;

fn main() -> u64 {
    adder()
}
```
uses a library:
```
library consts;

const THREE: u64 = 3;
const FOUR: u64 = 4;

pub fn adder() -> u64 {
    THREE + FOUR
}
```
We get the following error:
```
error
 --> consts/src/main.sw:7:5
  |
5 |
6 | pub fn adder() -> u64 {
7 |     THREE + FOUR
  |     ^^^^^ Internal compiler error: Unknown variable in assembly generation. This should have been an error during type checking.
Please file an issue on the repository and include the code that triggered this error.
8 | }
```

**Comment by mohammadfawaz** [comment]
Looks like this is not a problem with IR. @otrho is meant to switch us to IR any time now.

**Comment by otrho** [comment]
I was surprised by this bug considering we have the `const_decl_in_library` E2E test already, but in there it declares the const values which are used in `main.sw` but the library itself doesn't try to use them.

**Comment by nfurfaro** [comment]
Probably a good idea to add a test case for this so it doesn't regress.

**Comment by mohammadfawaz** [comment]
I'm removing the `bug` label and turning this issue into a testing issue.
