### ISSUE TITLE
Have `forc init` fail when the project name is `test`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1126]
When creating a new project called `test` with `forc init test`, `forc` doesn't complain. However, it complains when we try to build the project with:
```
Error: the name `test` cannot be used as a package name, it conflicts with Sway's built-in test library
```
I think `forc init test` should just error out.

**Comment by eureka-cpu** [comment]
Do we want this to extend to containing test or only if it's exactly `test`?

**Comment by mohammadfawaz** [comment]
Hmm whatever matches the behavior of `forc build`. Anything that `forc build` does not allow should not be allowed by `forc init`.

**Comment by eureka-cpu** [comment]
Gotcha, should we make this check for case sensitivity as well?

**Comment by mohammadfawaz** [comment]
Depends on whether something like `Test` is allowed or not. Can we build a project whose name is `Test`?

**Comment by eureka-cpu** [comment]
At this time, yes you can since it's only checking for "test"
