### ISSUE TITLE
Forbid heap types in storage

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1131]
Heap types don't play well with storage, as they inherently rely on memory.

Add a static analysis pass that emits an error if a struct that uses the `ALOC` instruction in any of its implemented methods is the type of a storage field.

**Comment by mohammadfawaz** [comment]
Added this as a task in https://github.com/FuelLabs/sway/issues/1006. Closing this for now and creating a link to it there.

**Comment by sezna** [comment]
I think this is no longer necessary with the new storage design. I know you're off in conferenceland, but, @mohammadfawaz have you had a chance to look at the new storage design that I proposed?

**Comment by mohammadfawaz** [comment]
I have not unfortunately. I will clean up all cases related to storage once I spec the design out.

**Comment by mohammadfawaz** [comment]
As per @sezna's comment, this is no longer required in the compiler.
