### ISSUE TITLE
Missing Rust Testing Example in Sway Book

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#1164]
https://fuellabs.github.io/sway/latest/testing/testing-with-rust.html

Will try and provide a PR today to fix.

**Comment by mohammadfawaz** [comment]
Ah yes... there is not `harness.rs` here: https://github.com/FuelLabs/sway/tree/master/examples/hello_world

Here's how the test harness could look like: https://github.com/FuelLabs/ETHDubai-2022-Workshop/blob/master/exercise3/solution/incrementor_contract/tests/harness.rs

**Comment by adlerjohn** [comment]
None of the examples actually have a test harness since they're not tested, see https://github.com/FuelLabs/sway/blob/1549a1f84cdbfd05bdce809ae81a131dcd6968ec/docs/src/testing/testing-with-rust.md?plain=1#L29

**Comment by SilentCicero** [comment]
Okay, what would be the best way to resolve this for now? @adlerjohn @mohammadfawaz 

Not good having any incomplete docs, maybe something I can work on this weekend.

**Comment by adlerjohn** [comment]
Add a basic test for one of the contracts in the examples directory, and add example testing to CI if it's not in there already, basically.

**Comment by adlerjohn** [comment]
There is now a harness
