### ISSUE TITLE
Struct destructuring

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1167]
This Sway code should work:

```
script;

struct Data<T> {
    value: T
}

impl<T> Data<T> {
    fn new(value: T) -> Data<T> {
        Data {
            value: value
        }
    }
}

fn main() {
    let data = Data::new(7);
    let Data { value } = data;
    // use value to do something
}
```

The equivalent Rust code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a745f0543c5c918f865e130de85dd6da

**Comment by matt-user** [comment]
How difficult would this be to implement for someone with limited compiler experience?  I'm interested in working on this issue, and learning more about sway and its compiler, but I don't want my inexperience to be a development blocker.  Would this feature be implemented primarily in `parse_tree` and `semantic_analysis`?  If someone could point me in the right direction it would be appreciated.

**Comment by emilyaherbert** [comment]
Hi @matt-user , this is a good first issue to start with because there is a pretty good example of how to get started here: https://github.com/FuelLabs/sway/blob/19586172e455a499d09d03b0aaca3d44bb47665c/sway-core/src/convert_parse_tree.rs#L2606

In Sway, tuple patterns on the LHS like `let (a, b) = (0, 1);` are desugared as syntactic sugar. So the LOC:

```rust
let (a, b) = (0, 1);
```

gets desugared into:

```rust
let <new name> = (0, 1);
let a = <new name>.0;
let b = <new name>.1;
```

So, I recommend approaching structs similarly:

```rust
let Data { value } = data;
```

would get desugared to:

```rust
let <new name> = data;
let value = <new name>.value;
```

**Comment by matt-user** [comment]
Thank you so much for the information!  I'll be sure to ask questions as I go along :)
