### ISSUE TITLE
`forc build` panics if project is renamed

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1172]
Steps:
1. Run `forc build`.
2. Change the `name` field in the manifest.
3. Run `forc build` again.
4. ???
5. Panic!

**Comment by ra0x3** [comment]
@adlerjohn 
- I can't seem to reproduce this after a few attempts
- I tried creating fresh projects on each attempt and renaming the project in both the cargo manifest as well as the forc manifest.
- Everything seems to be working as expected.
- Could you maybe try this again, and include a video or specs? 
- Else we can close this out and see if it pops up again

**Comment by adlerjohn** [comment]
I can no longer repro. Must have been fixed incidentally. Thanks for looking into this!
