### ISSUE TITLE
Parse document and publish Diagnostics after each did_change event

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#1177]
Currently, we are only parsing the document on the `did_open` and `did_save` events in the LSP server. Internally, these events are parsing the entire open document and then publishing diagnostics back to VScode. 

When parsing happens, the `Vec` and `HashMap`s that store the documents tokens are populated. We use these for doing things like goto, rename, hover etc.. 

### Problem:
At the moment, when the server receives a `did_change` event, we modify the internal document in memory with just the changes reported by the client. However, we don't update the documents internal `HashMap`s or `Vec` of tokens to reflect this, nor do we report any diagnostics. 

### Proposition:
Considering we most likely aren't likely to see multi-thousand line sway files, perhaps we could just reparse the entire document on every change. This would allow for an easy way to ensure everything stays in sync, and give users real-time diagnostics feedback for any errors or warnings that were detected. It would also mean issues like #1147 would be eliminated from happening. 

I have seen a few LSP server implementation examples that seem to be taking this approach. Perhaps we could adopt re-parsing the document on every change for now as a quick win, and only look to optimize if we notice any performance issues? 

any thoughts @adlerjohn @mitchmindtree @leviathanbeak ?

**Comment by adlerjohn** [comment]
Re-parsing every on change and re-building on save seems fine. If and when it becomes an issue, then we can spend cycles to optimize.

**Comment by JoshuaBatty** [comment]
Ok great, i'll move ahead with implementing this now.
