### ISSUE TITLE
Warn on unnecessary storage annotations

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1183]
Example:
```rust
contract;

abi MyContract {
    #[storage(write)] // Or any other storage annotation
    fn foo() -> u64;
}

impl MyContract for Contract {
    #[storage(write)] // Or any other storage annotation
    fn foo() -> u64 {
        0
    }
}
```
should emit a warning saying that the annotations are not necessary.

**Comment by mohammadfawaz** [comment]
@otrho have we decided against emitting warnings on unnecessary storage annotations? Or is this something that we want but hasn't been implemented yet? We don't seem to be emitting any warnings for the example above.

**Comment by otrho** [comment]
This could be a regression?  I would expect the above to emit warnings and for there to already be tests to confirm.  There was a lot of debate around it though, so maybe I've forgotten whether we decided otherwise.

**Comment by mohammadfawaz** [comment]
Yeah no warning is generated with `master`. Could be a regression, but I think we would want the warning to be emitted? Seems like a useful warning to have because addressing makes the user code more readable.

**Comment by otrho** [comment]
_I_ think there should be warnings, yeah.

**Comment by mohammadfawaz** [comment]
Wait I do see a warning now 🤔 , but the warning does seem that useful:
```console
  --> /Users/mohammad/Desktop/fuel/sway/test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/src/main.sw:12:5
   |
10 |
11 |       #[storage(write)] // Or any other storage annotation
12 |       fn foo() -> u64 {
   |  _____-
13 | |         0
14 | |     }
   | |_____- The 'write' storage declaration for this function is never accessed and can be removed.
15 |   }
   |
____
```
Well, it is useful but it can be improved.
