### ISSUE TITLE
Implement `mut` arguments

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1188]
The following shouldn't compile today but it does:
```rust
struct A {
    a: u64,
}

impl A {
    fn f(self) {
        self.a = 42;
    }
}
```
because `self` is not passed to `f` as `mut`.
The change I'm proposing to fix https://github.com/FuelLabs/sway/issues/908 rightfully breaks the above. However, there is no way to un-break it because we can't yet write:
```rust
impl A {
    fn f(mut self) {
        self.a = 42;
    }
}
```
More generally, we want to be able to annotate any argument as `mut`:
```rust
fn bla(mut a: u64, mut b: u64) {
    a = 0;
    b = 0;
}
```
Edit: the case with arbitrary arguments implies that we support passing arguments by ref, which still has to be property designed and thought of. So, for now, we should just enable `mut self`.

**Comment by mohammadfawaz** [comment]
We need to establish some ground rules around how different types are passed into functions. One proposal is as follows:
```
struct A {
    a: u64,
}

struct B {
    b1: u64,
    b2: u64,
}

impl A {
    fn f1(self, x: u64, b: B) {
        // Read-only access to self, self.a, x, b.b1, b.b2
    }

    fn f2(mut self, mut x: u64, mut b: B) {
        // Read/write access to self, self.a, x, b.b1, b.b2
    }

    fn f3(ref self, ref x: u64, ref b: B) {
        // Read-only access to self, self.a, x, b.b1, b.b2
    }
   fn f4(ref mut self, ref mut x: u64, ref mut b: B) {
        // Readwrite access to self, self.a, x, b.b1, b.b2
    }
}

fn main() {
    let mut a_data = A { a: 0 };
    let mut x_data = 0;
    let mut b_data = B { b1: 0, b2: 0 };

    a_data.f1(x_data, b_data); // No changes to a_data, x_data, or b_data expected.

    a_data.f2(x_data, b_data); // No changes to a_data, x_data, or b_data expected.

    a_data.f3(x_data, b_data); // No changes to a_data, x_data, or b_data expected.

    a_data.f3(x_data, b_data); // Potential changes to a_data, x_data, or b_data.
}

```

Note: I don't think there should be any distinction between copy types (such as `u64`) and non-copy types (such as `struct`) with regards to the above, even though `structs` are really just pointers to data with our implementation.

**Comment by sezna** [comment]
>  I don't think there should be any distinction between copy types (such as u64) and non-copy types (such as struct) with regards to the above, even though structs are really just pointers to data with our implementation.

Rust does use the `Copy` trait to show this distinction explicitly. We could do the same?

This all makes sense. I don't think we should necessarily _modify_ how things are passed around, instead just modifying the semantic analysis. Structs shouldn't be copied if they're passed in immutably. In that sense, we could just introduce the `mut` keyword and disallow mutation by default (unlike now).

The complexity comes in when you want to pass in a single mutable copy type. We copy those into new registers at this point. They're technically never persisted in memory. In fact, a reference to a number like this is itself not currently possible, as types this small exist only in a register.

**Comment by mohammadfawaz** [comment]
> I don't think we should necessarily modify how things are passed around, instead just modifying the semantic analysis.
Totally agree. All the above makes sense, thanks.

**Comment by sezna** [comment]
I don't necessarily have a clean solution to the problem of `mut` single-register types. Is it possible in the IR to signal that a register _must not be copied_ and instead mutated in place? cc @otrho

**Comment by mohammadfawaz** [comment]
> Is it possible in the IR to signal that a register must not be copied and instead mutated in place?

I have a feeling that the inliner will just do this for us by default... Let me remove the mutability check and see what I get.

**Comment by otrho** [comment]
> We need to find a solution to the problem of `mut` single-register (copy) types. Is it possible in the IR to signal that a register _must not be copied_ and instead mutated in place? cc @otrho

The IR itself has no concept of registers, just values.  If we add explicit mutability to Sway we will add it to the IR in the same fashion.   And the it and the codegen can manage the copying or non-copying of registers.

The IR already has pointers, although not quite fully realised as types, but we can add that and then the IR can truly have by-reference semantics, even if we keep it implicit in Sway.  That way mutable arguments can work whether they end up being registers or memory locations.

**Comment by mohammadfawaz** [comment]
How about we start by allowing the `mut` keyword only for `self` so that something like this works:
```
script;

struct A {
    a: u64,
}

impl A {
    fn f(mut self) {
        self.a = 0;
    }
}

fn main() {
    let mut a = A { a: 0 };
    a.f();
}
```
This is a fairly easy to change to make and would unblock `Vec<T>`. If we do this, then we don't have to worry (for now) about:
1. Dealing with mutable copy types. These require some modification to the IR to handle well (due to `store` and `load` expecting pointers etc.)
2. Dealing with the `ref` keyword 
3. Disallowing mutable arguments in ABI methods
and maybe other stuff.

The lack of (2) bugs me a bit but we seem to be treating `self` as a ref anyways already.
@FuelLabs/sway-compiler thoughts?

**Comment by otrho** [comment]
This actually sounds quite reasonable: :+1:

**Comment by mohammadfawaz** [comment]
Now that `Vec<T>` is under way, I think this is now even more important because users will probably want to pass `Vec<T>` to functions as an argument, and they can't actually call any of the methods that modify `Vec<T>` without the `mut` keyword.

**Comment by mohammadfawaz** [comment]
One option here that was brought up in a discussion earlier is to allow `mut` arguments _only_ for reference types and error out when the `mut` keyword is used with copy type arguments. That would help the `Vec<T>` case. The syntax here would still not require `ref`.

**Comment by mohammadfawaz** [comment]
https://github.com/FuelLabs/sway/pull/2363 closes this. We probably won't ever support mut args without ref but we will see if that ever comes up in the future.
