### ISSUE TITLE
Add a minimal `forc` plugin example, `forc-gm`, along with a chapter in the book

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1200]
It would be very useful to have a minimal-as-possible forc plugin demonstration for developers who are considering writing their own plugins.

Including this in the `sway` repo would also allow us to include code snippets directly into a dedicated chapter in the book while ensuring that the code snippets remain tested and up-to-date.

We already have `forc-lsp`, `forc-explore` and soon `forc-fmt` which each act as nice demonstrations, however a more minimal case may be easier to digest and document in the book.

This could be a minimal `forc-gm` plugin that responds to `forc gm` with `gn`. cc @SilentCicero 

---

For anyone looking to pick up this issue, I recommend referring to the `forc-lsp` plugin as a reference for how to add this.

**Comment by binggh** [comment]
can I have a go at this? :)

**Comment by mitchmindtree** [comment]
Absolutely!
