### ISSUE TITLE
Library crates should prefer `thiserror` to `anyhow` for error handling

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1201]
The primary reason to prefer `thiserror` to `anyhow` for libraries is because `thiserror` enables users of the library to handle different types of error conditions.

The `thiserror` crate is aimed at making it trivial to declare a set of custom `*Error` `struct`s and `enum`s. Enums are particularly useful for this as they allow downstream users of your library to exhaustively check error conditions in order to handle them correctly and with confidence that they have all cases covered.

On the other hand, `anyhow` is aimed at making error handling quick and easy for application crates, and does not at all make it easy for devs to actually handle certain conditions without inspecting the contents of strings.

Edit: I'll add that both `thiserror` and `anyhow` were published by the same author around the same time, and that this use-case distinction is intentional. Both are useful, but should be used for their particular use-cases.

**Comment by eureka-cpu** [comment]
Closing in favor of #4817
