### ISSUE TITLE
Remove `*.in_ir` and `*.out_ir` from `.gitattributes` once `FileCheck` is finalized.

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1206]
Once `FileCheck` is finalized, remove the two lines in `.gitattributes` that correspond to file extensions `*.in_ir` and `*.out_ir`. (See https://github.com/FuelLabs/sway/pull/1204#discussion_r846541548)

**Comment by otrho** [comment]
Fair enough.  Good way not to forget. :wink:
