### ISSUE TITLE
Have `forc fmt` limit text width to 100 characters

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1210]
Just like `rustfmt`, have the formatter limit text width to 100 characters. There is probably no need to make this number configurable.

Related: https://github.com/FuelLabs/sway/issues/1209

**Comment by eureka-cpu** [comment]
Tracking this for `swayfmt-v2` with #2001

**Comment by mohammadfawaz** [comment]
Will close this then as a dup of https://github.com/FuelLabs/sway/issues/2001
