### ISSUE TITLE
Utilize the sway-core parser directly in sway-lsp instead of duplicating work.

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#1224]
In issue #1017 I identified all of the `AstNode` enum variants returned from `SwayParseTree` that we are currently not parsing as tokens in the language server. As I have been working through this, I have come to suspect there is potentially a ton of duplicated effort going on between `sway-core` and `sway-lsp`. After spending the last few days just reading through the `sway-core` codebase, it seems that a more viable approach is to utilize either the `SwayParseTree`  or `TypedParseTree` from `sway-core` and call methods on them for finding definitions, references etc...

I think the current layout of `sway-lsp` was written before a lot of the functionality in `sway-core` existed, and that perhaps we should be leaning more heavily into it going forward. This seems to be the approach the rust compiler and `rust-analyzer` are taking now that it has been adopted as the official rust language server. 

This is currently how I'm imagining it to work. 

* Either a hover, goto, or rename request is made VScode, the client then sends the `line_number` and `character_position` that the request was made on. 
* We use the `line_number` and `character_position` to find the `AstNode` that has a `Span` within these ranges.
* We can then use this `AstNode` reference to call methods in `sway-core` such as, `find_all_references` which returns a `Vec<AstNode>`, or `find_definition` etc..
* We can then construct an appropriate LSP message to send back to the client for the requested action.  

Keen to get people's thoughts, especially those that have worked in `sway-core` if they think this is a viable approach. @otrho @sezna @mitchmindtree also @leviathanbeak ... perhaps there is already functionality in `sway-core` for getting this information?

**Comment by sezna** [comment]
Would  a generic AST traversal function that yields an iterator get you most of this? Then you can do something like (pseudo):
```rust
fn find_containing_span(ast_nodes, span) -> AstNode {
  ast_nodes.breadth_first().filter(|node| node.span().contains(span))
}
```

**Comment by otrho** [comment]
> * We use the `line_number` and `character_position` to find the `AstNode` that has a `Span` within these ranges.

You may have noticed, but our use of `Span` AFAICT is really inconsistent.  I hope this will change in the future.

The implementation of `pest::Span` is by convention -- there's a comment in there which says the start and end offsets must be valid indices within the string it holds.  There's no mention of the source file or anything, hence our `Span` wrapper which adds a `PathBuf`.  Pairing a path with a substring from the source and string-relative offsets really isn't that useful without knowing where the substring starts.  The source string would need to represent the entire source file for the offsets to be useful, and when Pest makes the spans initially that's what is does -- shares a single string of the entire source between all the spans.

But I have seen plenty of places where `Span`s have indices which are obviously file oriented and not within the bounds of the string.  And I have seen `Span`s effectively with zero length but still seem to work.  The the `empty_span()` method -- the indices are both zero but it still works.

When the new parser lands we should be able to fix all this though.

**Comment by JoshuaBatty** [comment]
Thanks for your input @otrho and @sezna. I have a better understanding regarding the current architecture after looking more in depth in how to traverse the parse tree. Because we want to ultimately map tokens to `[lsp_types](https://crates.io/crates/lsp-types)` it does make sense for the language server to create another representation of the tokens. Then we only need to traverse the tree once after a change has been made and gather all information we require to then map to compatible `lsp_types`.

Going to close this issue for now.
