### ISSUE TITLE
Add storage `store` and `get` for `b256`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1229]
Currently, `store` and `get` from the `storage` library in `lib-std` only allow basic copy types as they use `srw` and `sww` under the hood (read/write 1 word). It would be useful to also allow reading/writing a `b256` using `srwq`/`swwq`. Even though the new storage syntax (via the `storage` keyword) is now implemented, it is still not possible to use it for mappings. Therefore, something like `store_b256` and `get_b256` would be useful to implement `b256 -> b256` mappings. 

E.g. (courtesy of @SilentCicero):
```rust
library storage_b256;

pub fn store_b256(key: b256, value: b256) {
    asm(r1: key, r2: value) {
        swwq r1 r2;
    };
}

pub fn get_b256(key: b256) -> b256 {
    asm(r1: key, r2) {
        srwq r2 r1;
        r2: T
    }
}
```
More generally, the `store<T>` and `get<T>` functions would accept a `b256`, but that would require checking wheter `T` is a `b256` before deciding what to do. The `is_reference_type<T>` function may come in handy here.

**Comment by adlerjohn** [comment]
Note that this was one of the primary motivations of #1119: https://github.com/FuelLabs/sway/issues/1119#issuecomment-1084539569

No `store_xxx` is needed, since `store` is already generic.

**Comment by SilentCicero** [comment]
@adlerjohn so should the above library be implemented for now?

Just until we can depreciate with proper reference checking where we can just use `store` `get` with proper generics?

**Comment by adlerjohn** [comment]
No, it should not. See the above-linked issue for what should be implemented.
