### ISSUE TITLE
forc init --template counter project_name gives system error

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#1233]
## Summary

1. `forc init` gives me an error when creating a template counter project
2. The counter example provided uses new syntax which doesn't work with the SDK (currently)
3. No Rust test harness file generated for the example

## Behaviour

```bash
forc init --template counter my_sway_counter
```

Gives me:
```bash
Error: No such file or directory (os error 2)
```

However, it did create the `my_sway_counter` directory and copied the files in by the looks of it.

On MacOS ARM M1, latest `forc 0.10.1`, I was expecting it to create a project directory `my_sway_counter` then have the counter example copied in with **no error message**.

The error was confusing. It should exit successfully.

## Doesn't Work With SDK

The `counter` example provided doesn't work with the current SDK (the storage syntax should be made with the old storage system until it works with the SDK) and gives me the error below when running `forc test`:

```
Creating a new `Forc.lock` file
    Cause: pinned `path` dependency "std" source missing
Error: failed to read manifest at "/Users/nick/github/my_sway_counter/../../sway-lib-std/Forc.toml": No such file or directory (os error 2)
```

I assume this is because the `Forc.toml` file has this set as a dependency, which is not valid:
```
std = { path = "../../sway-lib-std" }
```

After removing the above, the contract compiles.

## Expected Rust Test Harness

There is no test file created either, which would be nice for this counter example (i.e. all the proper SDK wired in).
 
## Be Opinionated
 
 I would be opinionated with the `counter` example and provide the Rust cargo file and the test harness. It's the primary way to run tests and we want them to do it that way. It also is of great help to the developer to have the harness in there. That way I can just go `forc test`.
 
## Success Message Idea

Once an example project is `init`ed, we should also have a big healthy `success` message and a `Now try and run "forc test"` or something like this to be welcoming.

**Comment by mitchmindtree** [comment]
It looks like `forc init my_sway_counter` works as expected, so this must be to do with the `--template` argument. cc @JoshuaBatty in case he has any input off the top of his head.

**Comment by mitchmindtree** [comment]
> Second, the counter example provided doesn't work with the current SDK

Currently each of the `examples/` are only checked for a successful `forc build` and aren't yet tested alongside the SDK - #771 and #972 are related.

**Comment by SilentCicero** [comment]
Left my thoughts above @mitchmindtree thanks for pointing those out.

We want this `init` experience to be magical, just work, and give me the basic tools to start developing. It's really the front door to the tooling.

**Comment by mitchmindtree** [comment]
> I assume this is because the Forc.toml file has this set as a dependency, which is not valid:

Good spot! The `std` dependency should likely be removed when then template is copied in order to allow forc to fetch the implicit `std`.

**Comment by adlerjohn** [comment]
There are a few orthogonal issues here. Can we break this up into sub-issues that can be resolved independently?

**Comment by SilentCicero** [comment]
@adlerjohn yes, it was late when I posted this, happy to break it up.
