### ISSUE TITLE
Revamp the `ContractCaller` type 

### ISSUE THREAD

**Issue by simonr0204** [FuelLabs/sway#1261]
When instantiating a `ContractCaller` "manually" as per : 

https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_as_type/src/main.sw#L26

and attempting to call a function implemented for that abi on a deployed contract (i.e. `caller.foo()`), the function is not recognized.

Minimal example : https://github.com/FuelLabs/sway/blob/simon-abi_wrapper/sway-lib-std/tests/test_projects/abi/src/main.sw

**Comment by mohammadfawaz** [comment]
It looks like the type `ContractCall<SomeAbi>` doesn't have access to the methods of `SomeAbi`. E.g.:
```rust
script;

abi SomeAbi {
  fn foo() -> u64;
}

fn main() {
  let caller:ContractCaller<SomeAbi> = abi(SomeAbi, 0x1111111111111111111111111111111111111111111111111111111111111111);
  caller.foo();
}
```

**Comment by mohammadfawaz** [comment]
I have a fix for the simple reproducer above but not for the full problem. There are some remaining complications with the type engine for `ContractCaller`.

**Comment by emilyaherbert** [comment]
@mohammadfawaz what are the remaining complications?

**Comment by mohammadfawaz** [comment]
Basically, returning a `ContractCaller` from a function and trying to call contract methods on the result still doesn't work.
