### ISSUE TITLE
Rename `crate_namespace` bindings to `root_namespace` or `init_namespace`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1268]
The binding name `crate_namespace` is used throughout type checking to refer to the initial, root namespace populated only by the dependencies of the package being compiled, or nothing at all in the case that the package has no dependencies.

I believe we don't have the concept of a `crate` or `crate::` in sway. In that case, we should rename this to `root_namespace` or `init_namespace` for clarity.

**Comment by otrho** [comment]
Didn't we decide 'package' was our synonym for 'crate'?  'root' is ok too IMO.

**Comment by mitchmindtree** [comment]
I'm leaning towards `root` for a couple reasons:

1. The term `package` isn't really introduced until the `forc-pkg` level and neither are the concept of "dependency packages". From the `sway-core` perspective, the `compile_*` functions just receive some initial namespace and operate on one package, which I guess is a nice distinction and keeps its responsibilities clear.
2. It could be argued that it should be called `pkg_namespace` as it only contains the names of the dependency *packages*, however I imagine that if we want to introduce the concept of a `prelude` down the line we might want to bring those items from `std::prelude` into this root namespace too.

**Comment by mitchmindtree** [comment]
Closed as of #1213.
