### ISSUE TITLE
Document how to regenerate `forc` command docs in readme

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1270]
Add instructions to regenerate the documentation for `forc` subcommands to the README.md in https://github.com/FuelLabs/sway/tree/417a73c16c7926d58f53aca1f434886528244a58/docs

Ref: #1047

**Comment by mitchmindtree** [comment]
Currently these docs are in the `forc-documenter` crate here:

https://github.com/FuelLabs/sway/tree/417a73c16c7926d58f53aca1f434886528244a58/scripts/forc-documenter

Perhaps we could link to these from the `docs` README.

**Comment by adlerjohn** [comment]
Those are pretty good. Even a simple link to that would be sufficient than the current _nothing_ :joy:
