### ISSUE TITLE
Add and implement Exponentiation Trait

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1273]
We should provide Sway users convenient methods for calculating exponents of values.

This would take the form of a wrapper around the `exp` instruction, most likely in `core::ops`.

Also a slack comment here re a dedicated token for this op: https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1650642887038259

**Comment by adlerjohn** [comment]
Isn't there an exponent instruction?

**Comment by nfurfaro** [comment]
As a general direction, I think this should be implemented as a pub trait in `core::ops`, and impl it for `u64`.
Then, any other types which want to implement the trait can do so in their respective libs.

**Comment by otrho** [comment]
My first intuition is that the trait should have a `pow(base, exponent)` method as that's common for other languages and  `exp()` is usually related to base `e` exponentials.

**Comment by mitchmindtree** [comment]
Yeah, searching `exp` and `pow` in the Rust docs is a good example of how tricky things can get. That said, we don't have to think about floats (:pray:) which simplifies things a lot for Sway.

**Comment by nfurfaro** [comment]
I've got something drafted for this now, but blocked by `MemoryOverflow`.

Also, I  need to think about how to handle overflows. 
Possibly blocked by https://github.com/FuelLabs/fuel-vm/issues/104 ?
The spec say:
>If the result cannot fit in 8 bytes, $of is set to 1, otherwise $of is cleared.

I'm not sure if this applies to `u8`, `u16` and `u32` as well, but it seems to as at the VM level we're dealing with registers regardless of the unit size in Sway.

So if I did `4u8.pow(4u8)`, the result is > `max_u8`, but it still fits in 8 bytes... 
so does it return `max_u8` & set `$of` to 1, or does it return a larger size unit?
cc @adlerjohn

**Comment by mohammadfawaz** [comment]
The result of any binary operation should retain the type. So, if the result of `u8*u8` for example doesn't fit in a `u8`, then this should be an overflow, at least at the language level.

Now, in bytecode, we only have 64-bit registers, and I'm assuming that the VM only overflows if the result of an operation doesn't fit in 64 bits.

**Comment by nfurfaro** [comment]
I have this `pow` method that is mostly working:
```
impl Exponentiate for u64 {
    fn pow(self, exponent: Self) -> Self {
        asm(r1: self, r2: exponent, r3) {
            exp r3 r1 r2;
            r3: Self
        }
    }
}
```
What I don't know is what the expected behaviour is in this case: `100.pow(10)`.
My original thought was that `100.pow(10) == max_u64`, and `$of` is set to `1`, but I'm not certain of this.
`log_u64(100.pow(10));` logs `7766279631452241920`, not what I was expecting. 
cc @adlerjohn

**Comment by adlerjohn** [comment]
Ah I see. Maybe the implementation truncates off higher bytes rather than saturating to `u64::MAX`.

The VM uses `u64::overflowing_pow` under the hood, which looks like it doesn't saturate. https://github.com/FuelLabs/fuel-vm/blob/72ee94908ef2400b41966e927124b05c924a7c4b/src/interpreter/executors/instruction.rs#L107

The value returned isn't really relevant (though should be clarified in the specs) so long as `$of` is set.

**Comment by nfurfaro** [comment]
So, I would have to check the value of `$of` inside the `pow()` implementation in order to know whether the returned value can be used or should be discarded, otherwise, there's no way to know whether the value is the correct result or garbage.
This is assuming that there's no panic on overflow, which I think is actually supposed to be the default for some operations, but not others.

**Comment by adlerjohn** [comment]
The entire VM panics on overflow by default. If you turn that off, then yes you'll have to check the `$of` register, _but that's true regardless of what the value is_. E.g. if you raise `u64::MAX` to the power of `1`, then the value would be `0xFF...FF`, but `$of` would be zero.

**Comment by nfurfaro** [comment]
>The entire VM panics on overflow by default

Great, this is easy to reason about!

However, this is not what I'm experiencing. See above:
`log_u64(100.pow(10));` logs `7766279631452241920`, not what I was expecting. This should panic as 100.pow(10) should overflow a `u64`, no?

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-vm/blob/db315a8565ed0fd5820b6527843ba6b25f0ec026/src/interpreter/alu.rs#L19-L20

**Comment by nfurfaro** [comment]
Ah, I see. We literally just "wrapped" back around to that unfinished TODO in the VM again 😆 .
