### ISSUE TITLE
Document how to return a tuple or other complex types from an `asm` block

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1274]
For certain use cases, it would be helpful to return more than 1 register from an asm block.

**Comment by otrho** [comment]
Is it possible to instead use a Sway tuple as an 'out' parameter?  Something like:
```rust
let mut foo = (0, 0);
asm(out: foo) {
    // Do stuff, assuming out+0 and out+8 refer to the tuple elements... not great, but this ASM...
}
```
I guess if you're going to get gnarly anyway you could just construct a tuple:
```rust
asm(out) {
    move out $sp;
    cfei i16;
    // out+0 and out+8 are the tuple elements.
    out: (u64, u64)
}
```
Does this work?  I'm writing this off the top of my head...

Once you start adding complex types to ASM blocks it starts to extend beyond what is safe and stable.

**Comment by nfurfaro** [comment]
@otrho That works for me!
I think the first option makes sense, why construct a tuple in asm if I don't have to, that's why we have sway!

**Comment by adlerjohn** [comment]
If this works and doing it in asm directly isn't going to be supported any time soon, then the "workaround" should be documented in The Book.

**Comment by nfurfaro** [comment]
PR open for adding an example to The book.
The "workaround" works fine, and is sufficient for me for the foreseeable future.

**Comment by mohammadfawaz** [comment]
Updated the title.. This is a documentation issue now.

**Comment by nfurfaro** [comment]
This is now documented in the sway book.
