### ISSUE TITLE
Improve documentation for native assets.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1281]

**Comment by adlerjohn** [comment]
Specifically, documentation how to send and receive.

**Comment by nfurfaro** [comment]
We might also consider revamping the Subcurrency example. It certainly confused me while trying to understand assets on Fuel, so it will probably confuse others.
We should instead strive to provide a reference implementation of a subcurrency which leverages the native asset support of Fuel.

**Comment by SilentCicero** [comment]
@nfurfaro I think we want to define the sub-currency example as maybe an "App Level Token" (i.e. application level), and then the native one as a "Native Token".

**Comment by nfurfaro** [comment]
Re: sub-currency example
Beyond the naming of the example, I'm referring to the fact that nowhere in the sub currency example do we actually call the `mint` opcode. We're still treating it like an ehtereum-based subtoken rather than highlighting what makes Fuel unique && better.

**Comment by SilentCicero** [comment]
Yeah, I think both could be more clearly specified, in that vein.

I'm happy to take a stab at this in the docs @nfurfaro just to get something started.

It's also how I learn Sway, i.e. doing examples to improve the docs :)
