### ISSUE TITLE
Apply `forc-fmt`'s pathless AST fix in `sway-lsp`'s formatter

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1299]
A reminder issue to investigate landing the fixes made in #1283 in `sway-lsp`.

See [these comments](https://github.com/FuelLabs/sway/pull/1283/files#r852021772) for context.

cc @JoshuaBatty might have the best idea of how feasible this is. cc @amadeusluntz.

**Comment by eureka-cpu** [comment]
Is this issue solved?

**Comment by JoshuaBatty** [comment]
closed in #2801
