### ISSUE TITLE
Unnecessary warning when a struct member is not accessed but the struct is returned

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1305]
Compiling the following causes a warning:
```rust
contract;

abi MyContract {
    fn foo(s: S) -> S;
}

struct S {
    x: u:64,
}

impl MyContract for Contract {
    fn foo(s: S) -> S {
        s 
    }
}
```
Result:
```bash
❯ forc build
  Compiled library "core".
  Compiled library "std".
warning
  --> proj/src/main.sw:15:5
   |
13 |
14 | struct S {
15 |     x: u64,
   |     - This struct field is never accessed.
16 | }
   |
____

  Compiled contract "proj" with 1 warning.
  Bytecode size is 76 bytes.
```
The warning is out of place here since this is perfectly legal code and even though `x` is never accessed in `foo` directly, it is being implicitly used.

**Comment by mohammadfawaz** [comment]
@tritao can https://github.com/FuelLabs/sway/pull/2468 be extended to avoid the warning for struct/enum fields as well? I just tested the above and still seems to be an issue. I don't think we should be emitting a warning.

**Comment by mohammadfawaz** [comment]
My reasoning is that there is nothing wrong with the example above. I see a warning as something that the user has to address which usually means that they did something wrong, which is not the case here.

> Or are you thinking we just enable it in the cases of contract ABIs, like https://github.com/FuelLabs/sway/pull/2468 was originally implemented before we generalized it? In that case, then I think it would work.

Maybe! I think that actually makes sense. Basically, `x` does not need to be accessed inside the contract because it may actually be accessed outside. This applies to both input structs and output structs. Now that I'm thinking about it, `s` here is _kind_ of `pub` or `external`, not in the sense that it can be used in other Sway files, but in the sense that the SDK can access it.

**Comment by mohammadfawaz** [comment]
I think the same reasoning applies to library functions. So, a library function that takes a struct and just returns it without accessing any of its element should not cause a warning because the elements _may_ be accessed outside the library.

**Comment by mohammadfawaz** [comment]
> The only thing that comes to mind is we can assume structs to always have public visibility for contracts (but not libraries) which would fix this particular case. What do you think?

@tritao If we do this, then unused structs in contract won't cause a warning right?

I think the issue here is that you have to assume that `return s;` _consumes_ all of `s`'s fields, so no warning is required. Maybe we just need to special case returns and implicit returns to connect all struct fields.

**Comment by otrho** [comment]
> I think the issue here is that you have to assume that `return s;` _consumes_ all of `s`'s fields (because you don't know what the caller will do with `s`), so no warning is required. Maybe we just need to special case returns and implicit returns to connect all struct fields.

I also think this makes sense in the general case.

**Comment by mohammadfawaz** [comment]
> > I think the issue here is that you have to assume that `return s;` _consumes_ all of `s`'s fields (because you don't know what the caller will do with `s`), so no warning is required. Maybe we just need to special case returns and implicit returns to connect all struct fields.
> 
> I also think this makes sense in the general case.

Another example that Joao and I discussed today is https://github.com/FuelLabs/sway/issues/3012 where `log` is basically just like a return without the control flow implication... it basically consumes the whole struct.
