### ISSUE TITLE
Enable to deploy a contract to another node

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/sway#1308]
When developing a contract using `forc` we should be able to deploy it to a different node address.  

### Use case

`forc deploy --url https://node.swayswap.io/`

**Comment by nfurfaro** [comment]
Just to be forward thinking here, we may want to use a solution which is flexible with regards to networks as well. 
A user will eventually need to specify which live network to deploy to. I'm not sure how Foundry deals with this, but Hardhat has a `hardhat_config.ts` file where networks can be configured and given a name. The name can then be passed around in scripts or the cli when deploying.

Perhaps we could treat node configuration in a similar way?

**Comment by mitchmindtree** [comment]
I think we should start with getting the `--url` behaviour right first and pass any necessary parameters via the CLI.

Once we have this working we can look into declaring short-hand networks in the manifest and implement them on top of the logic we produce for handling URLs directly.

I think we might want to sketch out what `[workspace]`s might look like for `forc` before settling on a way of supporting `[network]`s in the manifest, as the former might influence the latter.

That said, `[workspace]`s will likely also influence how `forc deploy` works (e.g. deploying several contracts from a workspace in a particular order), but I think we should keep it simple to start by getting `--url` working with individual forc projects first.
