### ISSUE TITLE
Update test harness for `forc init --template counter`

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#1313]
Currently, we are just using the default_test_program. Ideally, we want it to reflect what is mentioned in the sway book [here](https://fuellabs.github.io/sway/latest/testing/testing-with-rust.html).

There seems to be a bug related to the whole by-copy v.s. by-ref issue that the IR introduced. The example in the book fails with the below output.

```
---- harness stdout ----
Contract deployed @ e0e4b8e32cde9b060a1fd62887a8e7024032ba85863a59cefb6e39ce39f94125
thread 'harness' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `0`', tests/harness.rs:38:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Once this is resolved, we can update the test harness file.

**Comment by mohammadfawaz** [comment]
This should have been fixed in `forc 0.10.3`.

**Comment by JoshuaBatty** [comment]
Excellent, thanks @mohammadfawaz! I'll update this now then.

**Comment by JoshuaBatty** [comment]
We removed the --template flag in favor of in language testing. closing.
