### ISSUE TITLE
`forc build` builds projects above its directory

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#1319]
When I run `forc build` in one of the Sway examples, it actually tried to build all examples.

`forc build` should only build the project I'm in the directory of, and ignore the higher directories.

**Comment by mitchmindtree** [comment]
Could you provide some steps on how to recreate this?

I've tried switching to `master` and then `cd`ing into each of the `examples/` under the sway repo and running `forc build`, but each time it behaves as expected and only builds that project.

**Comment by SilentCicero** [comment]
@mitchmindtree weird, for me it doesn't do that. It starts to build everything. I'll investigate further.
