### ISSUE TITLE
Guide for installing forc plugins

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#1320]
There is currently no guide for installing and managing forc plugins.

I'd be nice to have this in the Sway Book.

**Comment by mitchmindtree** [comment]
Related #1200, though I guess that's more related to *developing* plugins.

**Comment by eureka-cpu** [comment]
This is in line with #1220

**Comment by SilentCicero** [comment]
@eureka-cpu I think I cover this in my installation doc for now, going to close. I think having a list of available plugins is a separate issue.
