### ISSUE TITLE
Compiler should error when the argument types of a trait/abi method implementation do not match the declaration.

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1327]
The contract below compiles without any errors even though the definition of `foo` in the ABI has a different signature than its implementation in the `impl` block (note the `u64` argument v.s. `str[7]`).

```rust
contract;

abi MyContract {
    fn foo(x: u64) -> str[7];
}

struct S {
    x: u64,
}

impl MyContract for Contract {
    fn foo(s: str[7]) -> str[7] {
        s
    }
}
```

**Comment by mitchmindtree** [comment]
@mohammadfawaz @sezna do you mind if I have a crack at this?

**Comment by mohammadfawaz** [comment]
Go for it!

**Comment by mitchmindtree** [comment]
Looking into this now, I've reduced the abi test case a little:

```rust
contract;

abi MyContract {
    fn foo(x: u64) -> str[7];
}

impl MyContract for Contract {
    fn foo(s: str[7]) -> str[7] {
        s
    }
}
```

Also, can confirm that we have the same issue with trait methods, which makes sense considering they share most of type-checking. I.e. this also passes when it should produce an error:

```rust
library test;

trait Foo {
    fn foo(x: u64) -> str[7];
}

struct S {
    x: u64,
}

impl Foo for S {
    fn foo(s: str[7]) -> str[7] {
        s
    }
}
```

If I add or remove an argument from the implemented method, I do get an arity error which is good! It looks like we might just be missing a check for the argument _types_.

**Comment by otrho** [comment]
I'm looking at 'purity checking' the ABIs and traits now, and am looking through the code to find where to do it, and it's been harder than it should be because I was looking for the type checking stuff, to do it nearby.  But this issue is proving that there is no such code. :)
