### ISSUE TITLE
Hide normal lockfile creation reason behind verbosity flag

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1347]
Running `forc build` on a new project creates a lockfile and emits a scary cause that's entirely expected. The cause should be hidden behind a verbosity flag, or removed entirely.

```console
$ forc build
  Creating a new `Forc.lock` file
    Cause: failed to read /home/john/tmp/foo/Forc.lock: No such file or directory (os error 2)
```

cc @mitchmindtree for thoughts.

**Comment by mitchmindtree** [comment]
Yeah totally agreed, nice job on opening this. I think I've already seen one or two peeps mistake this for an error.

Perhaps even having a more concise short-form (rather than the raw error description) but on the same line might be nicer? e.g.

```
$ forc build
  Creating a new `Forc.lock` file (cause: lock file does not yet exist)
```
