### ISSUE TITLE
Error annotation window snippets and empty 'dummy' spans aren't compatable.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#1365]
Spans now have a 'dummy' which is empty, which replaces the original 'empty' span.  `Span::dummy()` has a start and end of 0 and an empty string "".  `Span::empty()` used to have a non empty string `"Source span not available"`, which isn't great (and has been described as cryptic elsewhere) but was still printable.

In `forc-util/src/lib.rs` there is `format_err()` which tries to construct a nice source annotation from the span.  If the start and end are equal then it just increments the end, which is a little bit broken, especially for an empty span.  In turn the new size of (end - start =) 1 doesn't match the empty span and we get a panic:
```
thread 'main' panicked at 'SourceAnnotation range `(0, 1)` is bigger than source length `0`'
```
The solution is probably to recognise empty spans and not even try to create a `SourceAnnotation`.  This might not be the only place where this is an issue though.

Or maybe the solution is not to have an empty span ever as they don't make sense.  This though would require everywhere a span can't be provided to instead use `Option` which is quite an invasive change.

**Comment by canndrew** [comment]
> Or maybe the solution is not to have an empty span ever as they don't make sense.

Using `None` is definitely more correct/type-safe than using `DUMMY_SPAN`. Ideally we should always know the span of an error though. `DUMMY_SPAN` was added with the intention of it being a temporary hack that could be removed.

Adding one to the end of an empty span is still broken though. Arbitrary `usize` values aren't valid `str` indexes, even if they're within the range of the string.

**Comment by canndrew** [comment]
I've made a PR to fix the crash: https://github.com/FuelLabs/sway/pull/1394

**Comment by Braqzen** [comment]
Note: `forc --version` is 0.11.0

Steps to reproduce:
1. `forc init span_bug`
2. Copy and paste the code presented below into the `main.sw` and save the changes
3. `forc build`

```
contract;

abi Escrow {
    fn constructor();
}

storage {
    approved: bool
}

impl Escrow for Contract {

    fn constructor() {
        storage.approved = true;
    }

}
```

Note the warning too
![1](https://user-images.githubusercontent.com/103777923/165627895-23bc18f8-c1c9-4a96-af8c-1cb6d8d81e94.png)

**Comment by adlerjohn** [comment]
I might be missing some context, but how is `This storage declaration is never accessed and can be removed.` related to this issue?

**Comment by Braqzen** [comment]
> I might be missing some context, but how is `This storage declaration is never accessed and can be removed.` related to this issue?

The panic seems to be caused when the line in the constructor is used.
If that line is commented out then the build succeeds.

What is strange is that despite it being used in the constructor, and making the build fail, it thinks that it is never accessed. 
It seems like that may be somewhat related to the issue given the behaviour.

**Comment by mohammadfawaz** [comment]
The warning shows up because the storage location is never read I believe.

**Comment by Braqzen** [comment]
> The warning shows up because the storage location is never read I believe.

Am I understanding this correctly?
That assignment is treated as a write operation without a read so in order to make the warning go away I would need to e.g. perform a check on the value in an `if`?

That sounds wrong to me at least in the sense that the linter should not complain about it even if those 2 operations are different.

**Comment by otrho** [comment]
@Braqzen It feels like you've accidentally pasted your stuff into an unrelated issue. :)  This bug is about the compiler panicking on empty spans.   Your thing is about dead code analysis related to storage.  Should maybe this go in a new issue?

**Comment by Braqzen** [comment]
> @Braqzen It feels like you've accidentally pasted your stuff into an unrelated issue. :) This bug is about the compiler panicking on empty spans. Your thing is about dead code analysis related to storage. Should maybe this go in a new issue?

The span issue is one that I have recently encountered when trying to build some code in Sway. @sezna has recommended to post the code in the issue so that it can be replicated. The PR from @canndrew contains questions about how to reproduce.

**Comment by otrho** [comment]
OK, sorry, it wasn't obvious that you also get the `SourceAnnotation` error from your comment!  The comment about unused storage was a misdirection... 🙂 Thanks.
