### ISSUE TITLE
Handling of complex types at the interfaces between internal and external contexts.

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1368]
(The below is as of `forc v0.12.1`)
## Overview
I'm creating this issue to keep track of the current state of the interfaces between internal and external contexts. Specifically, this includes two types of interfaces:
* Contract method arguments
* Contract method return data

## Contract Method Arguments
In an internal context (the contract itself), the method arguments are loaded from the call frame. Specifically `param2` [here](https://github.com/FuelLabs/fuel-specs/blob/master/specs/vm/main.md#call-frames) which may contain the actual data passed into the contract or a pointer to the data. To load `param2`, we use `lw $rA $fp i74`. 

The agreed on implementation of the above is as follows: if the data passed into the contract method is an integer or a boolean, then the data itself should be stored in `param2`. Otherwise, `param2` should simply contain a pointer to the data in memory. Below is a summary of the possible cases in Swayland, the desired behavior, and the current behavior. In the table, "value" means `param2` contains the actual data while "pointer" means `param2` contains a pointer to the data.

#### Case 1: Single Argument
| Type        | Desired Behavior | Compiler Behavior | Scripts Behavior | Rust SDK Behavior |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| `u8`, `u16`, `u32`, `u64`, `bool`  | value | value | | value |
| `str[1]`, ..., `str[8]`  | pointer | pointer | | value (to fix: https://github.com/FuelLabs/fuels-rs/issues/239)|
| `struct` of size <= 8 bytes  | pointer| pointer | | pointer |
| `tuple` of size <= 8 bytes  | pointer | pointer | | pointer |
| `array` of size <= 8 bytes | pointer |  pointer | | value (to fix: https://github.com/FuelLabs/fuels-rs/issues/239) |
| `enum` of size <= 8 bytes | pointer | pointer | | pointer |
| `b256` | pointer | pointer | | pointer |
| `str[9]`, ... | pointer | pointer | | value (to fix: https://github.com/FuelLabs/fuels-rs/issues/239) |
| `struct` of size > 8 bytes  |pointer | pointer | | pointer |
| `tuple` of size > 8 bytes  | pointer | pointer | | pointer |
| `array` of size > 8 bytes| pointer | pointer | | value (to fix: https://github.com/FuelLabs/fuels-rs/issues/239) |
| `enum` of size > 8 bytes | pointer | pointer | | pointer |

#### Case 2: Multiple Arguments
`param2` should always contain a pointer to the data. This behavior is currently consistent between the compiler 
and the Rust SDK.

## Contract Method Return Data
There are two ways to return from a contract method. 
* `ret $rA` which returns with value `$rA`.
* `retd $rA, $rB` which returns with value `MEM[$rA, $rB]`.
Following the logic we used for arguments, `ret` should be used if the data we want to return is an integer or a boolean. `retd` should be used otherwise. Again, here's a summary of the possible cases in Swayland, the desired behavior, and the current behavior:

| Type        | Desired Behavior | Compiler Behavior | Scripts Behavior | Rust SDK Behavior |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| `u8`, `u16`, `u32`, `u64`, `bool`  | `ret` | `ret` | | `ret` |
| `str[1]`, ..., `str[8]`  | `retd` | `retd` | | `ret` (to fix: https://github.com/FuelLabs/fuels-rs/issues/239) |
| `struct` of size <= 8 bytes  | `retd`| `retd` | | `ret` (to fix: https://github.com/FuelLabs/fuels-rs/issues/239) |
| `tuple` of size <= 8 bytes  | `retd` | `retd` | | `ret` (to fix: https://github.com/FuelLabs/fuels-rs/issues/239) |
| `array` of size <= 8 bytes | `retd` | `retd` | |  `retd` |
| `enum` of size <= 8 bytes | `retd` | `retd`  | | `retd` |
| `b256` | `retd` | `retd` | | `retd` |
| `str[9]`, ... | `retd` | `retd` | | `retd` |
| `struct` of size > 8 bytes  |`retd` | `retd` | | `retd` |
| `tuple` of size > 8 bytes  | `retd` | `retd` | | `retd` |
| `array` of size > 8 bytes| `retd` |  `retd` | |  `retd` |
| `enum` of size > 8 bytes | `retd` | `retd` | | `retd`|

**Comment by otrho** [comment]
Oh man, thanks so much for this. ❤️‍🔥

**Comment by mohammadfawaz** [comment]
I think it's safe to close this issue now.
