### ISSUE TITLE
Error Handling Discussion

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#1378]
We will want a way to handle and interpret error cases during contract execution with Sway.

Currently Sway only really has `assert` which just fails and doesn't tell you "what" failed unless you change the code or interpret all other context.

### Some ideas:
- Trivial: Return an error code (enum) with the assert, which is then sent to the final `panic` in the failure case
- Moderate: Use a log to return an error code or string message
- Non-trivial: have the client interpret the failure PC counter and area of code, interpret the failure case, and present the error
- Non-trivial: allow the compiler to output `enum` and `struct` data as JSON in the build output (i.e. just output the raw AST or spans as JSON). Then the panic error code would specify the data structure and error code referenced. The SDK or other tools could pickup the error code and match it to the correct data structure and property. The error code could be a specially encoded u64, with the first two bytes describing a specific enum or struct retrieved from compile time, and the rest specifying the specific error.

**Comment by nfurfaro** [comment]
I can see myself using a simple wrapper around and `if` and a panic, allowing me to pass a custum value through to the panic. Might even call it `require` 😏. 
But this is only helpful if the custom value is reflected somehow in the output after a failure.

**Comment by mohammadfawaz** [comment]
@nfurfaro I believe the current state of error handling is sufficient to handle the requirements here. Do you think this issue can be closed?

**Comment by nfurfaro** [comment]
@Mohammad I think we're good on the sway side of things now. There's still probably some work to do in the SDK. Atm,a failing `require` just shows up as a `Revert(42)`. We log a custom value before the revert, but it's not currently decoded so is basically unreadable.
I'll look at the rust SDK repo and see if there's an issue open and give it a nudge.

**Comment by mohammadfawaz** [comment]
> We log a custom value before the revert, but it's not currently decoded so is basically unreadable

Hmmm shouldn't the logged value of a require be captured in the APIs described here? https://fuellabs.github.io/fuels-rs/v0.27.0/calling-contracts/logs.html?highlight=log#logs

**Comment by mohammadfawaz** [comment]
Error handling is now fully implemented in the compiler including, handling of revert error codes and logging events. Closing this issue.
