### ISSUE TITLE
Extending `forc init --template <source>` with support for arbitrary `git` sources (+ short-hand for Sway examples and GitHub)

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1380]
## Current State

Currently, `forc init --template <source>` assumes that the specified `<source>` is a name of a sway example, and will attempt to fetch a forc project from the sway repo's `examples/` directory.

## Goal

Our goal is to not only support sway examples, but to enable 3rd-parties to also provide their own custom templates, inspired by [the `cargo generate` command](https://github.com/cargo-generate/cargo-generate).

## How

The plan is to implement this on top of `git` and our existing support for [finding forc projects within subdirectories of git repositories](https://github.com/FuelLabs/sway/blob/fe4f296ab9afaaf10e52f027e617f41e0945f214/forc-pkg/src/pkg.rs#L1104).

Curiously, even though the current `forc init --template` implementation only supports sway examples, it *is* implemented by fetching the sway repo (rather than shipping the examples in the binary) via an ad-hoc GitHub REST API approach.

Depending on GitHub's REST API is unsustainable, as it omits more general `git` support and centralises our tooling around GitHub. Further, if we were to extend it, we would likely end up duplicating existing work in our more generalised `git` support for forc dependencies.

Instead, we should remove the GitHub REST API approach in favour of more general git support. E.g.

```
forc init --template <git-repo-url> <proj-name>
```

The above assumes that a template forc project (indicated by a `Forc.toml`) exists at the root of `<git-repo-url>`.

In order to support pulling an example from the subdirectory of a repo (e.g. the `examples/` directory within the `sway` repo), we could allow for indicating the name of the template forc project to search for with something like:

```
forc init --template <git-repo-url> --template-name <template-proj-name> <proj-name>
```

This still makes the assumption that we only care about whatever commit happens to be at the HEAD of the repository. We could possibly also support specifying particular git references (e.g. `--tag "v1.0.0"`), but we could keep this simple to start by assuming HEAD.

This is of course quite verbose, but could act as the foundation for some short-hand commands.

## Short-hand

While we should avoid *depending* on github's REST API in our tooling, I think it's fine to add some high-level sugar seeing as it's by far the most common way of sharing repositories. Likewise, while we don't want to *only* 

- `forc init --template github:owner/repo proj-name` expands to:
   - `forc init --template https://github.com/owner/repo proj-name`
- `forc init --template github:owner/repo:template-name proj-name` expands to:
   - `forc init --template https://github.com/owner/repo --template-name template-name proj-name`
- `forc init --template example:counter proj-name` expands to:
   - `forc init --template github:fuellabs/sway:counter proj-name`

Very open to suggestions/improvements on the above syntax, but more wanted to show that we can add friendly support for things like github repositories or sway examples as short-hand on top of a more general git support - a lot of which we already support through our support for forc git dependencies.

## `forc init` implies template?

Perhaps we should have a dedicated command for initialising from a template? We could do something like:

- `forc new <proj-name>` - Creates a new empty project called `<proj-name>`.
- `forc init <template-source> <proj-name>` - Using `init` instead of `new` could imply we're initialising from some template, removing the need for a separate `--template` option.

By having `forc init` imply the use of a template, we could simplify the short-hand commands further too, e.g.

- `forc init example:counter proj-name`
- `forc init github:fuellabs/swayswap proj-name`

And so on.

---

cc @SilentCicero @adlerjohn @Braqzen @JoshuaBatty I've noticed lots of fuzzy discussion around `init` and `template` stuff lately so thought I'd get some thoughts down and try lay out a rough design. Thoughts?

**Comment by Braqzen** [comment]
I like the idea of splitting up `forc init --template` into separate `new` and `init` commands. 
The only issue I have is the naming of `init` vs `new`. 
Those terms do no intuitively distinguish between the behaviour of one type or the other. 
It makes more sense to me to have a `new` command for an empty program type (as discussed in #1186) and a `template` command instead of `init` because it is more literal than `init` ... what exactly?

At the moment I am unsure about the shorthand because my preference is to use the literal / verbose syntax that I am familiar with namely copy and pasting links however over time I can see how becoming familiar with the examples makes the sugar significantly nicer to use although I question why someone would become that familiar with it in the first place. That's not for me to say.

**Comment by adlerjohn** [comment]
`forc template` isn't a bad alternative!

Here I'm inclined to not use `new` and `init` as described in OP because it collides with `cargo`'s `new` and `init` (https://users.rust-lang.org/t/cargo-new-vs-cargo-init/40794).

**Comment by mitchmindtree** [comment]
TIL cargo has an `init` command :woozy_face:

**Comment by JoshuaBatty** [comment]
Nice, thanks for putting these thoughts down clearly in one place. I'm also a fan of using `forc template` and keeping `forc init` for creating barebone starting projects.
