### ISSUE TITLE
Update CI's `cargo build/check/test` invocations to use `--frozen` flag to ensure `Cargo.lock` is up to date

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1382]
This will cause CI to fail in the case that the `Cargo.lock` file is not up-to-date.

This should stop the occasional issue where a contributor will add a new dependency or update a version, but forget to update the `Cargo.lock` file.

**Comment by ra0x3** [comment]
@mitchmindtree Is there any reason we specifically want `--frozen` here versus `--locked`?

Specifically referring to this part of `--offline`:
> Beware that this may result in different dependency resolution than online mode. Cargo will
restrict itself to crates that are downloaded locally, even if there might be a newer version as
indicated in the local copy of the index. See the cargo-fetch(1) command to download
dependencies before going offline.

**Comment by mitchmindtree** [comment]
> @mitchmindtree Is there any reason we specifically want --frozen here versus --locked?

I think `--locked` is preferred. I only knew of `--frozen` until stumbling across the `--locked` alternative a few days ago!
