### ISSUE TITLE
Clean up how `build-all-examples` checks for formatting

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1386]
Overall, putting formatting checks into a script called `build_all_examples` seems hacky. Even if its just CI, this is tooling/code other people will have to read and maintain. Would prefer to see the main logic abstracted into a function along the lines of `for_all_examples` that was shared between separate `build_all_examples` and `fmt_check_all_examples` scripts or something like that.

_Originally posted by @mitchmindtree in https://github.com/FuelLabs/sway/pull/1384#pullrequestreview-951182832_

**Comment by binggh** [comment]
I think I can pick this up and include this in my PR #1398: was already refactoring the original script since I was moving it into the `/scripts`
