### ISSUE TITLE
Docs: the "subcurrency" example doesn't emit a "sent" event

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/sway#1391]
The documentation for Subcurrencies (https://fuellabs.github.io/sway/latest/examples/subcurrency.html) defines a "Sent" event, but doesn't emit it

**Comment by SilentCicero** [comment]
@dmihal yes, we will have more complex logs. Is logging facility something you need right away? If so we can fast track prioritization.

**Comment by adlerjohn** [comment]
Depends on #823

**Comment by mohammadfawaz** [comment]
This is done 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/59666792/215292084-80220b31-20c6-4422-aea0-ca6bb245d6fd.png">
