### ISSUE TITLE
A new type "EthAddress"

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1392]
Not high priority, but still worthy of a discussion.
some discussion already here:
ref #1374

**Comment by adlerjohn** [comment]
Piling on: if there is ever a need to distinguish between a Fuel address and an EVM address, then that distinction should be in the type system (i.e. a zero-cost abstraction) rather than a runtime check.

**Comment by simonr0204** [comment]
Ok, sounds like a unanimous yes. Removing bikeshedding tag and will get to it.

**Comment by mohammadfawaz** [comment]
Can we not create a `B160` type int the standard library and use it instead?

**Comment by nfurfaro** [comment]
yeah, could just be:
```
pub struct B160 {
    bytes: [u8;20],
}
```

**Comment by simonr0204** [comment]
Deferring to https://github.com/FuelLabs/sway/issues/1068#issuecomment-1095353832

**Comment by nfurfaro** [comment]
Ah, right. I forgot that part. While there's technically no need to zero the bytes, I like it when parsing logs, etc.
Maybe we can zero out the first 12 bytes as part of the cast to an `EthAddress` ?

**Comment by simonr0204** [comment]
So the choices are:

-  automatically downcast to a valid ethereum address (zero the bytes)
- require the address to already be a valid ethereum address (i.e. bytes _already_ zeroed or panic)
- do nothing

**Comment by nfurfaro** [comment]
I would vote for 1, or else 3.
There should be no need to downcast a `b256` to a valid ethereum address _unless_ you're also going to cast it as an `EthAddress`, so I don't see the value in separating these operations.
