### ISSUE TITLE
Sway parser returns garbage Identifier for TupleIndex  

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#1395]
The new `asm_return_tuple_pointer` example is causing the language server to crash, see #1385. 

On further investigation, it seems the cause is a corrupted `VariableDeclaration` returned from the parser when traversing the tree. 
Line 17 of the example is the cause of the error `let (first, second) = adder(1, 2, 3);`

When printing the returned `VariableDeclaration` I get the following.

```
variable = VariableDeclaration {
    name: Ident {
        name_override_opt: None,
        span: Span {
            src (ptr): 0x00007f08a0011170,
            path: None,
            start: 524,
            end: 529,
            as_str(): "first",
        },
    },
    type_ascription: Unknown,
    type_ascription_span: None,
    body: TupleIndex {
        prefix: VariableExpression {
            name: Ident {
                name_override_opt: Some(
                    "vD7oEl_vtsXbMkCWSGtc0Qf0CvvkP6Fy",
                ),
                span: Span {
                    src (ptr): 0x00007f08a0011170,
                    path: None,
                    start: 519,
                    end: 556,
                    as_str(): "let (first, second) = adder(1, 2, 3);",
                },
            },
            span: Span {
                src (ptr): 0x00007f08a0011170,
                path: None,
                start: 519,
                end: 556,
                as_str(): "let (first, second) = adder(1, 2, 3);",
            },
        },
        index: 0,
        index_span: Span {
            src (ptr): 0x00007f08a0011170,
            path: None,
            start: 519,
            end: 556,
            as_str(): "let (first, second) = adder(1, 2, 3);",
        },
        span: Span {
            src (ptr): 0x00007f08a0011170,
            path: None,
            start: 519,
            end: 556,
            as_str(): "let (first, second) = adder(1, 2, 3);",
        },
    },
    is_mutable: false,
}
```

Here we can see that the token name is `vD7oEl_vtsXbMkCWSGtc0Qf0CvvkP6Fy`. This changes to a random string on each run. I have a branch called `josh/TupleIndex_bug`. If you navigate to the tests located in `sway-lsp/src/server.rs` you can run the test named `run_asm_return_tuple_pointer_example()`. This prints the `VariableDeclaration` variants returned by the `sway-core` parser which shows the error.

**Comment by canndrew** [comment]
@JoshuaBatty: Are you sure the existence of the garbage name is what's causing the problem? The reason the name is there is that sway's AST doesn't have a primitive for destructuring a tuple into it's components. Instead it has a primitive for extracting a specific field from a tuple. So what this code gets desugared to is this:

```
let randomly_generated_name = adder(1, 2, 3);
let first = randomly_generated_name.0;
let second = randomly_generated_name.1;
```

What you're showing in the OP is the is the second variable declaration (the one for `first`). It's a `TupleIndex` operation on `randomly_generated_name` which is extracting `index: 0`. If you look at the other variable declarations that get generated you'll see the one where `randomly_generated_name` is declared and assigned the result of `adder(1, 2, 3)`, and another where `second` is declared as `garbage_name.1`.

> so when we traverse the tree to collect tokens, the token name is an incorrect large string. This is leading to the attempt to subtract with overflow error in the semantic_tokens code as the token name is incorrect.

I'll start looking into this, but can you say any more about it? Is it the existence of randomly-generated names that causes the problem? Or is it that these names need to be registered somewhere?

**Comment by mohammadfawaz** [comment]
The randomly generated names for Tuples (the ones using the `nanoid` crate) are causing non-determinism issues In the bytecode because the names are not consistent between different compilations of the same program. Not sure if this is related.

**Comment by JoshuaBatty** [comment]
Thanks for the explanation @canndrew! That does make a lot of sense, I can see that the 2 subsequent VariableDeclerations do have the correct names. Now that @mohammadfawaz introduced a determanistic way to identify tuples using the `constants::TUPLE_NAME_PREFIX`, I should be able to ignore collecting tokens if the `ident.name.contains(TUPLE_NAME_PREFIX)` 

I'll put a PR up for this now which should allow us to close this issue. Thanks.
