### ISSUE TITLE
Investigate the new trait-based approach for storage.

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1399]
From @sezna:

What if Storage was exposed by a trait Store? When you implement Store for a type T, you define how it can be stored in state. Then the compiler can just refer to the store() method with its syntax instead of doing lots of custom work.
e.g.:
```rust
impl Store for u64 {
   fn store(self, domain_separator: b256, key: b256) {
      asm(r1: self, r2: domain_separator, r3: key) {
         // do the storage for just a u64; too lazy to write asm rn
      }
   }
}
impl Store for b256 {
   fn store(self, domain_separator: b256, key: b256) {
      asm(r1: self, r2: domain_separator, r3: key) {
         // do the storage for just a b256; too lazy to write asm rn
      }
   }
}
```
then impling Store for more complex types becomes easier:
```rust
impl Store for Foo {
   fn store(self, domain_sep: b256, key: b256) {
     self.field_1.store(domain_sep, key);
     self.field_2.store(domain_sep, key + 1);
     self.field_3.store(domain_sep, key + 2);
    }
}
```
the above interface is just an initial thought, we could change it w/ regards to how we handle domain separators and stuff. But it could be similar to rust's Hash interface which uses a stateful hasher: https://doc.rust-lang.org/std/hash/trait.Hasher.html

This eliminates the need to ban heap types -- we instead just require that the trait Store is implemented for T (edited) 

And then storage hash maps fall out of that trivially!

We'd want to include impls of Store for all stdlib types. Since users will likely make new types out of our stdlib building blocks, it's unlikely they'd ever need to write asm. They can just do the thing I did in the Foo example above (call .store() on contained values). Additionally  (once we have a derive system) this would be derivable trivially.

The new approach would have the same syntax as it does currently, that would just use the trait under the hood:
```rust
storage {
  field_1: Foo,
}

storage.field_1 = 'yo'
```
The trait will need to be more complex than what I wrote above to handle writing and partial writes

**Comment by nfurfaro** [comment]
My initial reaction is, I like it!
A few questions that immediately come to mind:
1.) Cost. In the example, storing `Foo` seems like it would be writing to storage 3 x (but maybe this has to happen anyway, regardless how we expose this to the user...)
2.) Data locality. The inner calls to storage, ie: `self.field_1.store(domain_sep, key)` would have no knowledge of being a part of  a larger whole (`Foo`), so when reading from storage, `field_1`, `field_2` and `field_3` are not going to be adjacent (I'm just speculating here; I don't really know how this would work under the hood). Would this have performance penalties?

**Comment by mohammadfawaz** [comment]
Yeah the new implementation would not be any more expensive than the current implementation. Today, each subfield gets its own storage slot that is not adjacent to any of the other fields.

**Comment by mohammadfawaz** [comment]
### Some Code 
In `core::ops`, we can have:
```rust
pub trait Storable {
    fn write(self, key: b256);
    fn read(key: b256) -> Self;
}

impl Storable for u64 {
    fn write(self, key: b256) {
        asm(r1: key, r2: self) {
            sww r1 r2;
        };
    }
    fn read(key: b256) -> u64 {
        asm(r1: key, r2) {
            srw r2 r1;
            r2: u64
        }
    }
}

// Also implement `write` and `read` for other types.
```

In the user code, we may have something like this:
```rust
contract;

use core::ops::*;

abi TestContract {
    fn increment_counter(amount: u64) -> Foo;
}

struct Foo {
    x: u64,
    y: u64
}

impl core::ops::Storable for Foo {
    fn write(self, key: b256) {
        self.x.write(key);
        self.x.write(key + 1); // Need to implement addition for `b256`
    }
    fn read(key: b256) -> Self {
        Foo {
            x: ~u64::read(key),
            y: ~u64::read(key+1) // Need to implement addition for `b256`
        }
    }
}

storage {
    f: Foo,
}

impl TestContract for Contract {
    fn bar(amount: u64) -> Foo {
        const SOME_KEY = 0x0000000000000000000000000000000000000000000000000000000000000000;
        Foo{x: 56, y: 42}.write(SOME_KEY); // user should write storage.f = F {x: 56, y: 42};

        ~Foo::read(SOME_KEY) // user should write storage.f
    }
}
```

### Problems to solve:

* Implement addition for `b256` or some other deterministic operation that changes the key.
* The compiler has to replace `storage.f = ...` and ` .. = storage.f` with calls to `read()` and `write()`. This is fine when accessing the full data (i.e. all of `Foo` for example), but becomes trickier for partial reads and write (e.g. `storage.f.y` = ... or `... = storage.f.x`). An option is have additional trait methods that the compiler calls under the hood. Not sure how those would be encoded with respect to the 
* Semantic checking against the `storage` block needs to be done at some point. So, replacing `storage.Foo` with `read()` or `write()` may have to be done later in the flow (not in the parser as we do for core ops). 
* Is it a usability issue to have to ask users to create an `impl` block for each type they want to use storage for? Especially that the `impl` block relies on keys which really should be hidden from the user altogether I think.

**Comment by nfurfaro** [comment]
For the first point, "Implement addition for b256 or some other deterministic operation that changes the key.", we don't have addition for `b256` yet, but we have bitwise ops almost ready. So It could be just clear `n` bits from the end of the key and `&` it with an incremented value which starts at 1.

**Comment by sezna** [comment]
> Implement addition for b256 or some other deterministic operation that changes the key.

Yeah, that makes sense, so we can increment keys. We should force the user to be able to store their type at a _key provided by the compiler_, though, otherwise users can collide and cause vulnerabilities. Then the compiler can assign keys as it sees fit.

* The compiler has to replace storage.f = ... and .. = storage.f with calls to read() and write(). This is fine when accessing the full data (i.e. all of Foo for example), but becomes trickier for partial reads and write (e.g. storage.f.y = ... or ... = storage.f.x). An option is to have additional trait methods that the compiler calls under the hood. Not sure how those would be encoded in the impl block. The approach we have today (full example here https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/src/main.sw) is efficient in the sense that storage.f.x only accesses x and not the whole struct first.

I may be off here, but can we use IR to say we are loading a struct and then loading a field from that struct, and let optimizations say "hey, we actually can get away with just loading this chunk of the struct"? This could get tricky with manual memory mapping though, where `Store` is defined by the user and they can store things however they please...Hm...I wonder if there's a way for the trait to allow `PartialRead` -- maybe that's something we should bikeshed.

> Semantic checking against the storage block needs to be done at some point. So, replacing storage.Foo with read() or write() may have to be done later in the flow (not in the parser as we do for core ops).

Core ops just calls the functions with no type knowledge, and then the functions themselves are what generate type errors in semantic analysis. Why wouldn't that work here? We could convert the syntax into function calls based on the trait's API, then it is up to the function type checking system to handle type checking.

> Is it a usability issue to have to ask users to create an impl block for each type they want to use storage for? Especially that the impl block relies on keys which really should be hidden from the user altogether I think.

I don't think it is a usability issue. This will only really be used by library developers who are defining new data types. For the most part, people will just use our standard library collections and mappings. It is analogous to Rust, which implements lots of traits (`Debug`, `Display`, `Hash`) etc. for standard library types, but if you want to define your own type, you must define these things yourself.  Similar to how Rust's `Hash` trait requires you take in a mutable hasher state, we would require the user takes in a key to use as the basis of storage.


> How to implement mappings with the scheme above. The hope is that we can create a library StorageHashMap with insert() and get(), which probably can be done using the Storable trait without any additional compiler changes.

If we use a trait based system for storing the mapping itself, we should be able to define a data structure that uses `.get()` and `.set()` I believe? I'm going to pseudocode this and post it here.

**Comment by mohammadfawaz** [comment]
> Core ops just calls the functions with no type knowledge, and then the functions themselves are what generate type errors in semantic analysis. Why wouldn't that work here? We could convert the syntax into function calls based on the trait's API, then it is up to the function type checking system to handle type checking.

What I meant was that if we do this in the parser, then the content of the `storage` block is nowhere to be used except to generate keys. So, before converting something like `storage.f` to a `read` or a `write`, we should check that `f` actually exists in the `storage` block and that its type ascription is taken into account.

**Comment by mohammadfawaz** [comment]
Actually I see we've done this type of replacement in `semantic_anslysis` before. I'm just gonna try that!

**Comment by mohammadfawaz** [comment]
> I may be off here, but can we use IR to say we are loading a struct and then loading a field from that struct, and let optimizations say "hey, we actually can get away with just loading this chunk of the struct"?

That could probably work in most cases... If the user implements their `store()` in a weird, then that's on them. The job of the optimizer is to try its best and make sure that the common case is as optimal as it can be. What I worry about though is writing. For example, we want to be able to do 
```rust
storage.f.x = 5;
```
One way is to change the above (in the AST) to:
```
let temp = storage.f;
temp.x = 5;
storage.f = temp;
```
and then let the optimizer do its best. Again, with a reasonable "store" method, this should be doable.

**Comment by mohammadfawaz** [comment]
### Storage Mappings
Question. Does StorageMapping really need to be a trait? Can’t we do something like this:
```rust
struct StorageMapping<K, V> {
    seed_key: b256    
}

impl<K, V> StorageMapping<K, V> {
    fn insert(self, key: K, value: V) {
        // Generate the real b256 hash key from seed_key and the map key passed in
        // Use the `write` function from the Storable trait. V has to be Storable.
    }

    fn get(self, key: K) {
        // Generate the real b256 hash key from seed_key and the map key
        // Use the `read` function from the Storable trait. V has to be Storable.
    }
}

storage {
    var: u64,
    mapping: StorageMapping<u8, u64>,
}

int main() {
    storage.var = 0;
    let x = storage.var;

    storage.mapping.insert(1, 42);
    let res1 = storage.mapping.get(1);

    storage.mapping.insert(2, 77);
    let res2 = storage.mapping.get(2);
}
```
`seed_key` gets populated by the compiler based on where the mapping is declared in the storage block.
Essentially, only metadata (the seed key) about the mapping is in the `storage` block and then `insert/get` would use that metadata to generate more keys.

**Comment by mohammadfawaz** [comment]
We're missing a few components for the above to work such as generic hashing and trait constraints as I think want `V` to be `Storable` and we should enforce that using the `where` keyword. Also, the whole thing with `seed_key` is still an open question. We have some options:
* Storage initializers where we would be able to do something like
```
storage { 
    mapping: StorageMapping = StorageMapping { seed_key: __builtin_get_storage_key() }
} 
```

* Calling a builtin such as `__builtin_get_storage_key()` everywhere to give us the seed key. That would work but `__builtin_get_my_own_key()` has to be evaluated at compile time (i.e. pre-IR), just like `size_of` and `is_reference_type`. So, calling it inside the `insert()` function doesn’t exactly work because `insert()` gets inlined later (after IR-gen).

* Having the user write something like:
```
let seed_key = __builtin_get_storage_key(m1);
storage.mapping1.insert(seed_key, key, value);
```
but that’s not very user-friendly.

* Introduce compiler magic to specifically handle the `StorageMapping ` type or member variables named `seed_key`. Basically, when I load the mapping using `storage.mapping`, I magically populate `seed_key` in the result with the seed key chosen by the compiler. Later, we could rely on an annotation on `seed_key` that would tell us to do that.

**Comment by Braqzen** [comment]
> I think @Braqzen is maybe going to work on a generic hashing function... If not I can do it.

I probably will however atm I'm working on some further additions to the multisig.
I'll need generic hashing for the Tx creation in the multisig soon (similar to abi.encodePacked) so if you want to start it yourself then you can otherwise I should get around to it soon.

**Comment by SilentCicero** [comment]
> 

```
storage {
    var: u64,
    mapping: StorageMapping<u8, u64>,
}
```

This option seems nice. Very understandable. Then I could do a Tuple as the key type:

```
storage {
    var: u64,
    mapping: StorageMapping<(u8, b256, u64), u64>,
}
```

**Comment by mohammadfawaz** [comment]
Alright, so given what we have in the compiler now, we can have two possible implementation of `Mapping`. 

## A Short Term Solution:

```rust
library mapping;

use ::hash::*;
use ::storage::*;

pub struct Mapping<K, V> {
    seed: b256,
}

impl<K, V> Mapping<K, V> {
    fn new() -> Self {
        Mapping { seed: __generate_uid() }
    }

    fn insert(self, key: K, value: V) {
        let key = sha256((key, self.seed));
        store(key, value);
    }

    fn get(self, key: K) -> V {
        let key = sha256((key, self.seed));
        get(key)
    }
}
```
Just adding the above to the standard library is meant to work but I get the following error:
```
error
 |
0 | unknown source location
 | ^^^^^^^^^^^^^^^^^^^^^^^ Internal compiler error: Generic type cannot be resolved in IR.
Please file an issue on the repository and include the code that triggered this error.
 |
```
which I think should go away with @sezna's WIP fix for `Vec`.

## A Longer Term Solution:
Very similar to the above but would use the `Storable` trait. This is mostly blocked by trait constraints (i.e. the `where` keyword).

## Notes
We currently need to call `new()` in some `init()` contract method just like we would for any other storage initialization. Once we have storage initializers, we can potentially allow moving that `new()` call to the `storage` block itself (or even git rid of it altogether if we want, i.e. make it explicit).
