### ISSUE TITLE
sway-lib-std errors when compiling simple contract from the Sway Book

### ISSUE THREAD

**Issue by bobincrypto** [FuelLabs/sway#1405]
I was going through the Sway Book, following the [Getting Started](https://fuellabs.github.io/sway/latest/introduction/overview.html#implementing-the-abi-methods-in-wallet_contract) section, when compiling the `wallet_contract` I got a lot of errors that seemed not directly related to the contract I was writing. You can take a look at the errors here: https://bobincrypto.github.io/assets/forc_error.txt , and also in this [Stream](https://www.twitch.tv/videos/1467522511) at minute 22.

**Comment by mohammadfawaz** [comment]
Thank you for filing this issue. There is indeed a small bug in the docs here where `main.sw` in `wallet_contract/src` should look like:

```rust
contract;
use wallet_lib::*;

impl Wallet for Contract {
    fn receive_funds() {
    }

    fn send_funds(amount_to_send: u64, recipient_address: b256) {
    }
}
```
The first two lines are missing from the docs.

Also, make sure you are using the latest version of `forc` as I noticed that you have some outdated behaviours with regards to `forc init`.

Thanks for using Sway!

**Comment by bobincrypto** [comment]
I updated `forc` to version `0.11.0` (I was previously using v  `0.10.3`), after adding the missing lines the contract was compiled correctly. Thanks!. 

I created a PR to add the missing lines to the Sway Book.
