### ISSUE TITLE
Sway LSP should not allow renaming keywords or tokens from std

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#1418]
When a rename request is made, the `textDocument/prepareRename` method should check if the token belongs to the `std` library, eg `assert` or if the token is a language keyword. If so, then send a notification back to the client to cancel the rename request. 

We still want to gather the tokens from `std` as we need these for `go_to` requests.

**Comment by mitchmindtree** [comment]
Yeah we might want to make this the case w.r.t. dependencies in general?

Currently, the formatter and LSP use the compiler to `parse` code and produce spans, but this also includes spans into local copies of dependencies that might exist within the user's `~/.forc/git` directory which should really be read-only.

I haven't checked whether or not this is currently happening, but we should ensure that any actions from the LSP or formatter that modify files in any way *only* act on files within the directory enclosing the "current" package being worked on.
