### ISSUE TITLE
Eliminate the need for `~` to access associated functions

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1436]
It seems that the following doesn't work today:
```rust
script;

trait A {
    fn get_zero() -> Self;
}

impl A for u64 {
    fn get_zero() -> Self {
        0
    }
}

fn main() {
    let zero_val:u64 = u64::get_zero();
}
```
I think we always expect trait interfaces to have methods that take `self` as the first argument. The error we get when calling `u64::get_zero()` is
```
   |                         ^^^^^^^^ Could not find symbol "get_zero" in this scope.
```
We're probably looking for a free function called `get_zero` but can't find any.

Relevant: https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name

Edit: 
The above doesn't work because a `~` is required before the type. Changing this issue to track the removal of the need for `~`.

**Comment by adlerjohn** [comment]
```rust
fn main() {
    let zero_val:u64 = A::get_zero();
}
```

shouldn't that be

```rust
fn main() {
    let zero_val:u64 = u64::get_zero();
}
```

**Comment by mohammadfawaz** [comment]
Interestingly, both work in Rust 🤔  but neither work in Sway.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc62ee143500c37e3f417ad9617df1ef
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d1c8446b363a457a71a8f7ba9d16b0ec

**Comment by mohammadfawaz** [comment]
The reason why this is important to implement is because the trait-based approach for storage requires associated functions to implement the `read` or `get` function:

An example starting point:
```rust
pub trait Storable {
    fn write(self, key: b256);
    fn read(key: b256) -> Self;
}

impl Storable for u64 {
    fn write(self, key: b256) {
        asm(r1: key, r2: self) {
            sww r1 r2;
        };
    }
    fn read(key: b256) -> Self {
        asm(r1: key, r2) {
            srw r2 r1;
            r2: u64
        }
    }
}
```

**Comment by mohammadfawaz** [comment]
Ok so I've been completely blind here. I totally forgot that a "~" is needed for associated functions 😱  

The syntax that works is:
```
    let zero_val:u64 = ~u64::get_zero();
```

**Comment by adlerjohn** [comment]
I thought the new parser removed this requirement?

**Comment by mohammadfawaz** [comment]
Looks like the new parser also expects a `~`. However, it is probably the case that getting rid of the `~` is now possible.

**Comment by otrho** [comment]
The new parser briefly had a bug around this (`~` for built in types) but the solution was just to parse it like the old parser.  I think the overall issue is when seeing `bool` is it a type or a path element?  Depends if it's followed by a `::` or not... should be fixable in the new parser.

**Comment by emilyaherbert** [comment]
I was under the impression that Sway was being designed to require a `~` in front of associated methods that do not take a self.

> I think we always expect trait interfaces to have methods that take self as the first argument

What do you mean by this? `get_zero` should not take `self`

**Comment by otrho** [comment]
@mohammadfawaz corrected himself about the not needing `self` thing, it was actually that he was forgetting the `~`.  My impression is that the `~` was added only due to Pest parser limitations, which should be fixable now with the new parser.

Rust doesn't need `~`, so why should Sway? 🙂
