### ISSUE TITLE
Fix the build-forc-test-project CI job to correct test the local forc

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1458]
See failure in https://github.com/FuelLabs/sway/pull/1457

The failure is related to the fact that building the project created with `forc init` requires the standard library version `0.12.0` which doesn’t exist yet.

Potentially, that job should change the manifest file of the generated project to add an explicit std dep that's local.

**Comment by ra0x3** [comment]
<img width="1678" alt="Screen Shot 2022-05-03 at 7 18 12 AM" src="https://user-images.githubusercontent.com/17253182/166470882-4dab165f-eabf-4889-b23b-003e5854ec79.png">

**Comment by adlerjohn** [comment]
This could be as simple as `echo "std = { path = \"../sway-lib-std/\" }" >> test-proj/Forc.toml` before the `forc build`.

**Comment by ra0x3** [comment]
@adlerjohn Ah, yes. There are no actual dependencies in the file anyway 👍
