### ISSUE TITLE
Add new type `U128`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1478]
We need a type to contain the result of multiplying 2 `u64`s for example.
This should be opt-in, as in the default when performing math ops with a type should be to return the same type.

Bikeshedding discussion here: https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1651596324523349

**Comment by simonr0204** [comment]
Should methods on the U128 type be over and underflow safe by default?

**Comment by adlerjohn** [comment]
> Should methods on the U128 type be over and underflow safe by default?

Start with the minimum (panic on overflow), then add more functionality as we need.
