### ISSUE TITLE
Improve compiler message when you use an ABI method inside the same contract

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1491]
When writing a contract in `Sway` you must declare an `ABI` and then template the methods in the contract in order to run `forc build`.

When writing the contract itself it is possible to use one of your own `ABI` methods in the contract by mistake and thus when you `forc build` the build will fail with an error message `Could not find symbol "<name of your ABI method>" in this scope`.

This error message is not descriptive enough as to what that means and why it happens.
The message should be updated to be more informative e.g. "Cannot call **external** ABI methods of contract Test in the Test contract"

Below is an example which should generate the error upon running `forc build`

```
contract;

abi Test {
    fn method_a() -> bool;
    fn method_b() -> bool;
}

impl Test for Contract {
    fn method_a() -> bool {
        // This is illegal and will cause an error
        Self::method_b()
    }

    fn method_b() -> bool {
        true
    }
}
```

**Comment by mohammadfawaz** [comment]
Yup that makes sense.

**Comment by Braqzen** [comment]
> I'm probably missing something but why exactly is this incorrect behavior? Why contract methods cannot call each other? For instance, analogous Rust code is perfectly fine.
> 
> ```rust
> trait Test {
>     fn method_a() -> bool;
>     fn method_b() -> bool;
> }
> 
> enum Foo {}
> 
> impl Test for Foo {
>     fn method_a() -> bool {
>         Self::method_b()
>     }
> 
>     fn method_b() -> bool {
>         true
>     }
> }
> ```
> 
> What if we allow something like `Self::` in Sway?

Your example uses a trait instead of a contract; however, you have mentioned a contract. I don't know about the compiler side but I have been told that the `abi` for a contract is meant to be external only and thus a contract cannot call its own functions.

**Comment by mohammadfawaz** [comment]
As @Braqzen said, ABI methods are only meant to be used externally and cannot call each other. 

This is also relevant: https://github.com/FuelLabs/sway/issues/3798
