### ISSUE TITLE
Expand the `hash` test #1490

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1492]
https://github.com/FuelLabs/sway/pull/1490 adds a new test for the `hash` library from `lib-std`. That test is quite small and needs to be expanded to test all hash functions and validate their output against Rust.

**Comment by mohammadfawaz** [comment]
@Braqzen can this be closed now?

**Comment by Braqzen** [comment]
@mohammadfawaz yup, all of the tests are now done via the sha256 and keccak256 issues. Those cover all of the types including more complex structs.
