### ISSUE TITLE
Investigate using custom mdbook preprocessor to generate forc command documentation

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1510]
This section in the mdbook docs about writing custom preprocessors looks really interesting:

https://rust-lang.github.io/mdBook/for_developers/preprocessors.html

I wonder if we could take advantage of this to build the forc command and plugin documentation at mdbook build time rather than using `forc-documenter` to regenerate and replace all the text separately?

If we can work out how to include the command content at `mdbook build` time, we could also remove the whole forc-documenter CI check and save on some diff noise related to keeping the forc command docs up to date.

cc @binggh it could be worth investigating this before diving deeper into more `forc-documenter` issues in case we can come up with a solution that removes the need for `forc-documenter` altogether? Edit: Or alternatively `forc-documenter` could be refactored toward _being_ a mdbook preprocessor plugin?

**Comment by binggh** [comment]
think it looks to be possible to use a preprocessor, but we would probably still have to rely on a huge part of the current `forc-documenter` script since we would have to call `forc --help` (unless we parse the Rust source files directly). Refactoring the script into a preprocessor plugin would definitely make sense.

> If we can work out how to include the command content at mdbook build time, we could also remove the whole forc-documenter CI check and save on some diff noise related to keeping the forc command docs up to date.

By this, do you mean to automatically build the book based on changes to the commands, instead of making the developer responsible for manually changing it?

**Comment by mitchmindtree** [comment]
> but we would probably still have to rely on a huge part of the current forc-documenter script since we would have to call forc --help

Sounds good, that makes sense to me!

> By this, do you mean to automatically build the book based on changes to the commands, instead of making the developer responsible for manually changing it?

Yes! Just to clarify, what I mean is that, because the documentation for all commands would be generated automatically at `mdbook build` time, there would be nothing to be checked at CI time. We would *know* that the book will always be up-to-date, as the book [gets built (via `mdbook build`) and published during CI](https://github.com/FuelLabs/sway/blob/master/.github/workflows/gh-pages.yml#L21). Does that make sense?

**Comment by binggh** [comment]
Ah yeah, I see what you mean now, that definitely makes sense - allows us to shave off a CI job and will probably improve dev productivity (no need to manually check docs now), i will prioritise this

**Comment by binggh** [comment]
Going to assign myself this - actively working on it
