### ISSUE TITLE
Generic stack type hashing

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1511]
Related: #823

Outline:

Check if type is a reference type with `is_reference_type()`.

If not. then it's in the register:
1. Grow stack with [`CFEI`](https://github.com/FuelLabs/fuel-specs/blob/84cff9a590a28d7c5e6cb62d91b52e8e30c6ef67/specs/vm/opcodes.md#cfei-extend-call-frame-immediate) by one word.
2. Save value in register to memory with [`SW`](https://github.com/FuelLabs/fuel-specs/blob/84cff9a590a28d7c5e6cb62d91b52e8e30c6ef67/specs/vm/opcodes.md#sw-store-word).
3. Hash with [`S256`](https://github.com/FuelLabs/fuel-specs/blob/84cff9a590a28d7c5e6cb62d91b52e8e30c6ef67/specs/vm/opcodes.md#s256-sha-2-256).

If yes:
1. Get size with `size_of()`.
2. Hash with [`S256`](https://github.com/FuelLabs/fuel-specs/blob/84cff9a590a28d7c5e6cb62d91b52e8e30c6ef67/specs/vm/opcodes.md#s256-sha-2-256).

**Comment by mohammadfawaz** [comment]
Actually I'll be working in this in the coming weeks. I need it to implement generic mappings.

**Comment by mohammadfawaz** [comment]
Ah excellent. We'll be in touch then!
