### ISSUE TITLE
Mismatched types results in an "unresolved B512" when passing in a `B512` type into `ec_recover_address` which takes a `B512`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1525]
In the following [commit](https://github.com/FuelLabs/sway-applications/pull/25/commits/046bfca926cf2de956b06c71ed928099266c307a) for the multisignature wallet the [CI](https://github.com/FuelLabs/sway-applications/runs/6395532763?check_suite_focus=true#step:11:23) fails to build while running `forc build` on version `0.12.1` locally works as expected.

The `signatures` variable is `[B512; 2]` and the parameter type to `ec_recover_address` is `B512`.

Preview of error:
![1](https://user-images.githubusercontent.com/103777923/167949923-e8a9889f-f929-49b4-a9a2-f51767d54b1b.png)

**Comment by otrho** [comment]
This was almost certainly resolved (yesterday) by #1522 and so we might need to ship it for the CI to work.  @mohammadfawaz?

**Comment by mohammadfawaz** [comment]
I can create a release today.

**Comment by mohammadfawaz** [comment]
@Braqzen is this fixed in `v0.12.2`?

**Comment by emilyaherbert** [comment]
Taking you off this one @sezna because my PR fixes this.
