### ISSUE TITLE
Graph-coloring register allocator

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#155]
The register allocator right now simply reuses registers when they are not referenced again, and it is not an optimal solution. A fully featured register allocator would follow the techniques listed in these two papers.

https://c9x.me/compile/bib/irc.pdf

https://c9x.me/compile/bib/pcc-rega.pdf

This issue tracks the implementation of these strategies in our register allocator.

**Comment by mohammadfawaz** [comment]
Closed with https://github.com/FuelLabs/sway/pull/816

**Comment by mohammadfawaz** [comment]
Closed with https://github.com/FuelLabs/sway/pull/816
