### ISSUE TITLE
Tuple Types

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#156]
Tuple types, as they behave in Rust, should exist in our language. This issue tracks the parsing, type-checking, and code generation of tuple types.

**Comment by emilyaherbert** [comment]
@canndrew  is this closed?

**Comment by sezna** [comment]
I think it could remain open until destructuring is complete? Since tuple fields are inaccessible as of now, the tuples feature isn't exactly ready

**Comment by sezna** [comment]
Closing and opening a new issue, against my own words above ^
