### ISSUE TITLE
Broken test case, maybe related to while loops + implicit return expressions + functions

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1567]
When working on #579 I came across an unusual bug in a test case.

Currently, this test case is commented out, because it fails for an unusual reason and is preventing development:
https://github.com/FuelLabs/sway/blob/243dbd813ac26d65e47188d94dc759e8477ea93d/test/src/sdk-harness/test_projects/reentrancy/mod.rs#L63

If we add this line back in run the test, we see that it fails. My initial debugging shows that the while loop loops exactly once, then it fails and triggers a revert somewhere between reevaluating the conditional, reentering the loop a second time, or progressing to the implicit return statement that follows it.

But, if we add `log_u64(0);` at this line, then the test passes!
https://github.com/FuelLabs/sway/blob/243dbd813ac26d65e47188d94dc759e8477ea93d/sway-lib-std/src/reentrancy.sw#L36

Which reinforces the idea that this bug is likely related to the while loop -> implicit return ordering.

**Comment by otrho** [comment]
To be clear(er): the above test works in `master` but is failing in Emily's `emilyaherbert-579/expand-match-expressions` branch.

**Comment by otrho** [comment]
OK, I'm fairly confident that #1611 fixes this. :smile:

If you switch to `emilyaherbert-579/expand-match-expressions` and re-enable the test and run it, it fails.  If you then `git cherry-pick` the fix from `mohammadfawaz/1602` and try again, it is fixed.

It makes sense too, both issues are around `while` loops followed by implicit returns.
