### ISSUE TITLE
Introduce the `+=` and `-=` operators

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1574]
In Sway, I'd like to be able to do:

```
let mut counter = 0;
while counter < 10 {
  counter += 1;
}
```

instead of what you currently have to do:

```
let mut counter = 0;
while counter < 10 {
  counter = counter + 1;
}
```

For ease of implementation, `+=` and `-=` could be syntactic sugar.

**Comment by adlerjohn** [comment]
How about `*=`, `/=`, `<<=`, and `>>=`?

**Comment by emilyaherbert** [comment]
SGTM!
