### ISSUE TITLE
Change Sway Book `latest` to point to latest semver release, not master branch.

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1577]
@binggh raised a valid concern in a recent chat that currently the book hosted under `latest` is always the current state of `master`, and does not necessarily match the state of `forc` that you get when you `cargo install forc`.

We should do something like the following:

1. Rename the URL suffix of the `master` branch book to `master`, e.g. `https://fuellabs.github.io/sway/master` (rather than `latest`).

2. Add some CI automation where, on each new version release of `forc`, we also host the current state of the book under a URL for that version, e.g. `https://fuellabs.github.io/sway/0.12.2`.

3. Change the behaviour of the `https://fuellabs.github.io/sway/latest` URL to point to the latest versioned release, i.e. the version you get when  you do `cargo install forc`, **not** the latest master release.

**Comment by binggh** [comment]
In this way it also assures us that we know for sure that code examples and forc command documentation are accurate for a certain version.
