### ISSUE TITLE
Fix `std::tx::tx_script_length()` script padding issue

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/sway#1585]
```rs
script;

const TX_SCRIPT_LENGTH_OFFSET = 10280;

struct MyStruct {
    arg_one: bool,
    arg_two: u64
}

fn main() -> MyStruct {
    // You need an odd amount of these in your code for `std::tx::tx_script_length()` to work.
    asm(r1: 0x0000000000000000000000000000000000000000000000000000000000000000) {};
    asm(r1: 0x0000000000000000000000000000000000000000000000000000000000000000) {};
    asm(r1: 0x0000000000000000000000000000000000000000000000000000000000000000) {};
    
    // Adding any amount of these doesn't change anything
    asm(r1) {addi r1 r1 i0;};
    asm(r1) {noop;};
    asm(r1: 1337) {};
    asm(r1: 1337) {};

    asm(r1: TX_SCRIPT_LENGTH_OFFSET) {
        // Maybe if you add some stuff here??? No.
        noop;
        addi r1 r1 i0;

        // Actual code
        lw r1 r1 i0; // let script_length = std::tx::tx_script_length();
        add r1 is r1; // let script_data_offset = is + script_length;
        r1: MyStruct
    }
}
```

**Comment by AlicanC** [comment]
cc @sezna

**Comment by mohammadfawaz** [comment]
@AlicanC I'm not following what's going on here. Do you think there's a fix to the standard library that needs to be made or is this an issue somewhere else?

**Comment by otrho** [comment]
`std::tx::tx_script_length()` just fetches the value from the transaction, pretty much like the ASM block above, so there's not much to change there.  If it's genuinely not working as expected then it could be a VM bug.

Those empty ASM blocks at the top shouldn't be adding anything to the bytecode... 🤔

**Comment by adlerjohn** [comment]
Ah, so this could be related to https://github.com/FuelLabs/sway/pull/1984#discussion_r902085172!

**Comment by AlicanC** [comment]
@mohammadfawaz I don't have a clear answer on that really.

As @adlerjohn pointed out, a similar issue exists with predicates and is solved by doing `len + len % 8`: https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/tx.sw#L240-L244

So we could do the same trick here, but:
- If we need this it means `scriptLength` and the length of the `script` in the tx in the memory doesn't match.
- If this is how they are in the actual tx, then that tx is invalid and SDKs shouldn't build these invalid txns and `fuel-core` shouldn't accept them.
- If the actual txns are correct then it's somehow being written or read wrongly.

---

FYI, @sezna said:
> this feels like opcode padding but would need to look deeper

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-tx/issues/150 should get to the bottom of this

**Comment by mohammadfawaz** [comment]
`tx_script_length()` is now implemented using `gtf` as follows
<img width="562" alt="image" src="https://user-images.githubusercontent.com/59666792/215292245-faf25a2e-99da-49fd-a9cb-1d1e2cac1a8f.png">
so I believe this can now be closed.
