### ISSUE TITLE
Add annotation for ABI method payability

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1608]
Add an annotation to ABI method _declarations_, `#[payable]`. The lack of this annotation implies the method is nonpayable.

When calling an ABI method that is nonpayable, the compiler must emit an error if the amount of coins to forward is not guaranteed to be zero.

**Comment by mohammadfawaz** [comment]
This seem like a low hanging fruit. We should be able to do this soon and quickly.

**Comment by anton-trunov** [comment]
Is there a minimal example of contract/script that should produce an error?

**Comment by mohammadfawaz** [comment]
Say we have a contract that has the following ABI:
```rust
abi MyContract {
    fn test_function() -> bool;
}
```
and we have the following in a script:
```rust
fn main() -> bool {
    let caller = abi(MyContract, <contract_id>);
    caller.test_function{coins: 1000}()
}
```
`test_function` here forwards 1000 coins of the base asset ID. Now, we know, at compile time, that this value is non-zero. As `test_function` does not have the `#[payable]` annotation, I expect the script to fail to compile. The same applies when calling the contract from another contract.

If you look at the script bytecode, you see:
```
lw   $r1 data_2               ; literal instantiation
...
call $r3 $r1 $r0 $r2          ; call external contract
...
data_2 .word 1000
```
Here, `$r1` is the amount of coins to forward which should be exactly zero if the method is non-payable. If that value is non-zero or some other dynamic value, then we should error out.

Now the challenge is how do we enforce this when calling a contract method from the SDKs 🤔
