### ISSUE TITLE
Support nightly releases

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/sway#1616]
In a recent chat with @mitchmindtree, we discussed how it might be a good time to consider supporting nightly releases in the near future, especially with `fuelup` in the works. Justification is that Fuel devs would be able to easily grab the most recent changes without having to manually clone, build and install all the tools.

Seems like we already have a nightly cargo audit CI job - we can further extend this to support nightly releases for our binaries

**Comment by adlerjohn** [comment]
Fun fact but we used to have https://github.com/FuelLabs/sway-nightly-binaries. Time to revive that repo?

**Comment by bingcicle** [comment]
Previously it seems like we had nightly releases implemented in the format stated here #175

Proposing to use `nightly-YYYYMMDD-hash` instead (without the hours). Happy to pick this up once myself once we agree on a format for forc and fuel-core releases
https://github.com/FuelLabs/fuel-core/issues/503#issuecomment-1210037014

**Comment by mitchmindtree** [comment]
@bingcicle SGTM!

**Comment by bingcicle** [comment]
> Fun fact but we used to have https://github.com/FuelLabs/sway-nightly-binaries. Time to revive that repo?

Question about releasing nightlies - I think we should revive this repo and release binary assets there instead of within this repo, so that we do not pollute the releases under this repo. The CI yaml will be vastly different as well since we can skip most of the CI steps and go straight to building and releasing, so I think it's fair to have a different repo and workflow for this.

**Comment by adlerjohn** [comment]
Un-archived the repo. Feel free to nuke the default branch's current contents and use it at will.

**Comment by bingcicle** [comment]
Will also create a `fuel-core-nightly` as well - will mention this in the `fuel-core` issue

**Comment by bingcicle** [comment]
Ah wait, is this something we want^? Or do we want both in the same repo?

**Comment by adlerjohn** [comment]
Up to you. For this, I'm not necessarily sure what the benefit of two repos is.

**Comment by bingcicle** [comment]
Nightlies are live on https://github.com/FuelLabs/sway-nightly-binaries along with their respective workflows. Did this because the workflows are significant shorter (no testing, since commits to master would've already passed the CI steps anyway) + includes extra steps to create releases.

Can we also add protection rules to that repo? @adlerjohn 

I think this issue can be closed once we resolve the above
