### ISSUE TITLE
Can't assign to array indexes

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/sway#1626]
```rs
script;

fn main() {
    let mut arr: [u8; 1] = [0];
    arr[0] = 1;
//  ^^^^^^^^^^ This expression is not valid on the left hand side of a reassignment.
}
```

**Comment by mohammadfawaz** [comment]
Ah yes.. mutable arrays are not implemented yet. Related: https://github.com/FuelLabs/sway/issues/428

We're prioritizing `Vec` at the moment which will enable this and more.

Closing in favor of #428
