### ISSUE TITLE
Create a `tx_id()` std library function

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1629]
The transaction ID is simply at address zero: https://github.com/FuelLabs/fuel-specs/blob/0d56640183c3fc1eee055ab380f796565955a973/specs/vm/main.md#vm-initialization

**Comment by nfurfaro** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/17053076/173577888-765c2861-e04e-481f-a814-ead14f9c3f6b.png">

@mohammadfawaz It seems like a `tx_id()` function would just be a wrapper around the preexisting `start_stack_ptr()` function?

**Comment by mohammadfawaz** [comment]
John wrote the on Discord IIRC and looked something like:
```
asm() {
    zero: b256
}
```
That's it 😄
