### ISSUE TITLE
Add proper git authentication handling to `forc-pkg`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1636]
Git is used by `forc` to enable support for remote git dependencies and remote project templates. The fetching and handling of git repositories is performed in `forc-pkg`.

## Problem

Currently we don't do any sort of authentication handling for git within `forc-pkg`.

So far this hasn't caused too many issues as all existing forc projects only have public repository dependencies and they all use `http`/`https` URLs. However, once we start opening up to more users I can see us quickly getting a bunch of issues about this.

The main issues with not handling git authentication are:

1. **URL types other than http/https don't seem to work without it**. I don't think git URLs like `git@github.com:FuelLabs/sway.git` work at the moment, and I believe this might be due to our lack of authentication handling.
2. **No support for private dependencies**. Normally git can support fetching and updating private repositories via ssh as long as the git URL format is used, however trying to do so with forc just panics at the moment.
3. **Some git URL rewrite rules don't work**. Some users use re-write rules so that URLs starting with `http`/`https` automatically get rewritten to git URLs. As a result of 1. forc will just panic. This is the source of this issue:
   - https://github.com/FuelLabs/sway/issues/998.

## Potential Solution

We should investigate how `cargo` handles this.

Some high-level docs about cargo's support for git authentication can be found here: https://doc.rust-lang.org/cargo/appendix/git-authentication.html.

Investigate cargo's [`git::utils::with_authentication` function](https://github.com/rust-lang/cargo/blob/b1636fc1e049e977ae542ec2b2191ffab075b049/src/cargo/sources/git/utils.rs#L448) which provides a scope with valid git auth. This function seems to be the primary part of `cargo`'s code-base responsible for handling git authentication.

**Comment by ra0x3** [comment]
@mitchmindtree  This is metioned in [the Git Authentication link](https://doc.rust-lang.org/cargo/appendix/git-authentication.html) but wanted to call it out specifically since your example above uses the shorthand URL
> Note: Cargo does not support git's shorthand SSH URLs like git@example.com:user/repo.git. Use a full SSH URL like ssh://git@example.com/user/repo.git.

**Comment by ra0x3** [comment]
@mitchmindtree (thinking out loud)
- In regards to password auth, curious to know how this issue relates to [Support for password authentication was removed on August 13, 2021](https://stackoverflow.com/questions/68781928/support-for-password-authentication-was-removed-on-august-13-2021)
- Even just now locally while trying to pull a private (personal) repo after setting up Git password authentication [mentioned in the Cargo docs](https://doc.rust-lang.org/cargo/appendix/git-authentication.html) I'm getting that error
```text
➜  fuel git clone https://github.com/ra0x3/avacorp.git
Cloning into 'avacorp'...
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/ra0x3/avacorp.git/'
```
- I am familiar with [Github personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), but I'm wondering if the two things are related
  - Hoping so 🤞 as access token auth seems much easier to work with
- As for the SSH side, seems like it should be relatively straightforward to just pull the private repo, since setting up SSH (starting the agent, adding keys, etc) is the user's responsibility

**Comment by mitchmindtree** [comment]
> Even just now locally while trying to pull a private (personal) repo after setting up Git password authentication [mentioned in the Cargo docs](https://doc.rust-lang.org/cargo/appendix/git-authentication.html) I'm getting that error

Yeah I've never had much luck with password authentication even with cargo. I remember trying to set it up years ago and just running into issues. After realising how much easier and safer SSH is I've tended to focus on that since.

> I am familiar with [Github personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), but I'm wondering if the two things are related

I don't think we should worry about any GitHub-specific auth here. We should avoid introducing any GitHub-specific interaction in our packaging system as `git` is so much more general than GitHub, and there are so many other git hosts out there (e.g. gitlab, gitea, bitbucket, google code, source forge, raw git repos on servers, etc).

If we can support SSH then we support all of those including GitHub automagically.

**Comment by paulrberg** [comment]
I just bumped into this issue while creating a sample project with `forc`. Just like @iqdecay, I have this setting in my global gitconfig:

```toml
[url "git@github.com:"]
    insteadOf = https://github.com/
    pushInsteadOf = github:
    pushInsteadOf = git://github.com/
```

So what's the solution for now? Do I have to remove this from my gitconfig?

**Comment by paulrberg** [comment]
To follow up on this issue - is there any way to locally override the URL rules in a specific git project?

This would allow me to keep my global settings as is, while avoiding the authentication issue with Forc.

**Comment by mitchmindtree** [comment]
Sorry about the delayed response here @paulrberg! This hasn't been forgotten and is on our priority list to address over the next couple months.

> is there any way to locally override the URL rules in a specific git project?

Good question, I'm not sure off the top of my head, but if you do come across a decent temporary workaround please do report back :pray:

**Comment by paulrberg** [comment]
No worries, thanks for confirming, @mitchmindtree!

**Comment by mdipanjan** [comment]
I'm trying to build a small demo project with beta-2 toolchain. And while I run `forc build`, I'm getting this error: 
`Error: failed to fetch `https://github.com/fuellabs/sway`. Check your connection or run in `--offline` mode
`
I think this is the same authentication issue.
