### ISSUE TITLE
`forc new` and `forc init` should match `cargo new` and `cargo init` behaviour respectively

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1638]
Currently `forc init` acts more like `cargo new`. We should change it to `forc new`, and then add a new `forc init` command that behaves like `cargo init`.

Adding critical label as this is a large breaking change that should be done before we start getting more users.

cc @JoshuaBatty @adlerjohn does this sound OK?

**Comment by ra0x3** [comment]
@mitchmindtree @JoshuaBatty 
- Are there any default flags/opts we want from `cargo init`, as a merge-able MVP?
- https://doc.rust-lang.org/cargo/commands/cargo-init.html

**Comment by JoshuaBatty** [comment]
Those flags sound good to me @ra0x3.
