### ISSUE TITLE
Allow `TypeInfo::Custom`s with `CallPath`s

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1644]
I want to be able to do this:

```rust
enum Foo {
  A: (),
  B: (),
}
```

```rust
use ::foo;

struct Bar {
  baz: foo::Foo
}

let x = Bar {
  baz: foo::Foo::A(())
};

match x {
  Bar { baz: foo::Foo::A(_) } => { .. },
  _ => { .. }
}
```

But right now that does not work because `TypeInfo::Custom` does not contain a `CallPath`: https://github.com/FuelLabs/sway/blob/17b9e2473001d9ab91a8f4237673a9ae8baeb492/sway-core/src/type_engine/type_info.rs#L67

**Comment by esdrubal** [comment]
I tried to reproduce this error, but the following error was thrown: 
 ```
7 | struct Bar {
8 |     baz: foo::Foo
   |          ^^^^^^^^ Fully specified types are not supported in this position. Try importing the type and referring to it here.
9 | }
```
This issue no longer make sense, unless we want to support fully specified types in this position.

**Comment by emilyaherbert** [comment]
There is not any bug here, this is a lack of implemented feature. We will want to support fully specified paths in this position, yes.

**Comment by mohammadfawaz** [comment]
@esdrubal this seems related to what you're currently working on. I'm assigning this to you.
