### ISSUE TITLE
Allow simulating txs with `forc run`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1652]
Instead of actually sending the transaction to be included in the chain, add an option to just simulate it.

**Comment by ra0x3** [comment]
@adlerjohn 
- For someone without the context. What is the difference between simulating vs actually sending?
- Is this similar to [dry_run](https://github.com/FuelLabs/fuel-core/blob/master/fuel-tests/tests/tx.rs#L38) in the tests?

**Comment by adlerjohn** [comment]
Simulating here means the node executes the transaction and returns the final mutated transaction along with receipts (which includes whether the transaction reverted or not). The transaction is _not_ inserted in the node's view of the blockchain, i.e. it does not affect the chain state. Sending here means the node executes then inserts the transaction into the blockchain.

It is similar to dry_run from fuel-core tests from what I can tell, but @Voxelot would be able to give a more definitive answer.

**Comment by Voxelot** [comment]
Yes this would be using the dry_run api without a utxo_validation override (default to node setting for utxo_validation).
