### ISSUE TITLE
Allow accessing struct members directly from a function application that returns a struct

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1657]
The should should compile but it doesn't:
```rust
script;

struct Person {
    name: str[4],
}

fn ret_struct() -> Person {
    Person {
        name: "john"
    }
}

fn main() {
    let val = ret_struct().name; // (ret_struct()).name doesn't work either
}
```
Error:
```
Internal compiler error: Unsupported instruction as struct value for field expression: Call(Function(Index { index: 1, generation: 0 }), [])
```
The workaround today is:
```rust
let s = ret_struct();
let val = s.name;
```

**Comment by Braqzen** [comment]
I've had the same issue when trying to call [contract_id().value](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/context/call_frames.sw#L23)

**Comment by mohammadfawaz** [comment]
So the `P: critical` label here is for tracking improving the error message. It shouldn't be an internal compiler error. It should be improved to a cleaner actionable error.

Fixing the actual problem is probably `P: medium` or `P: high`.
