### ISSUE TITLE
`forc init` needs more coloured output

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1659]
There's a little bit of green here but we can make this look much better with more colours!
![1](https://user-images.githubusercontent.com/103777923/170194009-d99707b2-8ae1-4054-8b36-faad6e832a9c.png)

I think this is a _critical priority_

**Comment by kayagokalp** [comment]
Currently, the init message is printed with `tracing::info!` but we don't have a solid way of coloring this output with tracing. Maybe, for now, we can switch back to good old `print`. We likely need coloring with `tracing`, so I am opening a new issue to track that. Once that is closed, we can also output with colors with `tracing`.
