### ISSUE TITLE
Can't use binary or hex literals for ints

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1664]
Can only use for `b256` and...byte?

**Comment by otrho** [comment]
Yeah, I remember commenting on this yonks ago.  But I can't find an issue, so cool.   The other thing is WTF is a byte for, as opposed to a `u8`?

**Comment by mohammadfawaz** [comment]
The Sway Book still says that those should work: https://fuellabs.github.io/sway/latest/basics/built_in_types.html#numeric-types. We should at least change that temporarily if we don't plan on fixing this, though I think the fix is pretty trivial and might be worth doing now?

**Comment by adlerjohn** [comment]
Being able to specify numbers in hex is pretty important in the blockchain domain, so would prefer a fix.

**Comment by mohammadfawaz** [comment]
Will raise the priority then.
