### ISSUE TITLE
Exhaustivity checker assumes catchall exists on an empty enum.

### ISSUE THREAD

**Issue by canndrew** [FuelLabs/sway#1679]
The following code fails to compile and complains that the match is non-exhaustive:

```
enum Empty {}

fn foo(empty: Empty) -> u32 {
    match empty {}
}
```

**Comment by emilyaherbert** [comment]
What behavior are you looking for this to produce?

In my opinion, Sway should error for enum declarations that have no variants (https://github.com/FuelLabs/sway/issues/1697). Consequently, an empty match expression is not a bug.

**Comment by canndrew** [comment]
> What behavior are you looking for this to produce?

It should just compile without errors. It has no run-time behaviour because the function can't be called.

**Comment by emilyaherbert** [comment]
Note that @sezna 's PR description in this link adds some important additional context about the reason why this is necessary (although that PR was closed because it is a duplicate of this PR).

https://github.com/FuelLabs/sway/issues/3420#issue-1462027042
