### ISSUE TITLE
Add a declaration engine

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1692]
The declaration engine allows the compiler add a layer of separation between AST nodes and declarations.

The goal of adding the declaration engine is to:
1. unlock trait constraints
2. stop inlining function bodies during type checking
3. perform optimizations during monormorphization

See the relevant RFC here: https://github.com/FuelLabs/sway-rfcs/pull/11

The prototype can be used to guide implementation: https://github.com/emilyaherbert/declaration-engine-and-collection-context-demo/tree/master/de

- [x] #2630
- [x] #2675
- [x] #2642
- [x] #2643
- [x] #2631
- [x] #2632
- [x] #2633
- [x] #2634
- [x] #2635
- [x] #2679
- [x]  #2680
- [x]  #2786
- [x] #2784

**Comment by emilyaherbert** [comment]
This is now done! 🥳 

I've moved where we are tracking the monomorphization cache into this issue: #1819

**Comment by mohammadfawaz** [comment]
This is now, hopefully for real this time 🥳
