### ISSUE TITLE
Error `ContractNotInInputs` when trying to deploy example via `forc deploy`

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/sway#1713]
Assigning to myself, I don't really work much on Sway if someone else wants to hop in go ahead. Describe by 0xOsprey on our discord, and was able to replicate. 

**To Replicate**
- Follow this part of the Sway Docs: https://fuellabs.github.io/sway/latest/introduction/overview.html

Results in an error similar to

```
Contract id: 0xcb975bca3da3c56d2f4fbf6b8d1d4022d9167eb131b4f789e2f53eb8e80b4341
Error: Response errors; unexpected block execution error VmExecution { error: Panic(ContractNotInInputs), transaction_id: 24fe719c2bcbd763927452b059297deddfd21d0c26c35af5f8b272ac7d0086a9 }
```

**Comment by adlerjohn** [comment]
I was not able to repro locally.

**Comment by ControlCplusControlV** [comment]
Do you have local changes?

**Comment by adlerjohn** [comment]
Ah nevermind I was running on `master`, which includes #1683

**Comment by adlerjohn** [comment]
This can be fixed with a new release of `forc`.
