### ISSUE TITLE
Investigate the possibility of statically linking `forc`'s `openssl` dependency required for `git2`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1742]
Motivated by https://github.com/FuelLabs/fuelup/issues/39.

Requiring `openssl` to be available on the system as a dynamic library is inconvenient and adds an extra system-specific step to installation that's non-trivial to support.

Ideally we'd statically link openssl instead.

#920 is also a potential solution, but a lot more involved and it's still unclear whether or not gitoxide is feature-complete enough, or will be maintained as consistently as `libgit`, for the kind of git support we desire.

**Comment by kayagokalp** [comment]
I can link with `openssl` statically on my local by running:

`export OPENSSL_STATIC=1` and then `cargo build --bin forc `

Is it possible to apply the same thing to our releases?

**Comment by adlerjohn** [comment]
Looks like `OPENSSL_STATIC` might not be enough: https://users.rust-lang.org/t/how-to-link-openssl-statically/14912
