### ISSUE TITLE
Unable to find associated methods for types in some cases

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1747]
Potentially related: a recurring issue where `unwrap()` can't be found when trying to call `result.unwrap()`. Turns out this can be worked around by explicitly annotating the type:

```rs
let sender: Result<Sender, AuthError> = msg_sender(); // if you remove `: Result<Sender, AuthError>` this doesn't work!
sender.unwrap();
```

_Originally posted by @adlerjohn in https://github.com/FuelLabs/sway/issues/1734#issuecomment-1139883131_

**Comment by emilyaherbert** [comment]
Reopening because it is actually not a direct dupe of #1628, just related to it.

**Comment by bitzoic** [comment]
I am getting `method not found` for the following snippet of code:

```
struct MyStruct {
    int_option: Option<u64>
}

storage {
    stored_struct: MyStruct,
}

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {

        let stored_struct = storage.stored_struct;
        let stored_option_in_struct = stored_struct.int_option;
        require(stored_option_in_struct.is_some(), "Error");

        true
    }
}
```
![stored_option_error](https://user-images.githubusercontent.com/54727135/173640401-31d2e142-b853-4941-84d8-c2f24eb42c53.png)

**Comment by Braqzen** [comment]
> I am getting `method not found` for the following snippet of code:
> 
> ```
> struct MyStruct {
>     int_option: Option<u64>
> }
> 
> storage {
>     stored_struct: MyStruct,
> }
> 
> abi MyContract {
>     fn test_function() -> bool;
> }
> 
> impl MyContract for Contract {
>     fn test_function() -> bool {
> 
>         let stored_struct = storage.stored_struct;
>         let stored_option_in_struct = stored_struct.int_option;
>         require(stored_option_in_struct.is_some(), "Error");
> 
>         true
>     }
> }
> ```
> 
> ![stored_option_error](https://user-images.githubusercontent.com/54727135/173640401-31d2e142-b853-4941-84d8-c2f24eb42c53.png)

`use std::option::*;`

**Comment by emilyaherbert** [comment]
@Braqzen the bug here was coming from a different problem---i.e. manually annotating the type made this example compile. There is a PR up right now that fixes this though.
