### ISSUE TITLE
Matching on variables results in unreachable code warnings while using literal values does not

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1765]
# Describe the bug
Matching on variables seems to match on the Rust equivalent of the "catch all" variable that is used to exhaustively match instead of first checking if those variables resolve to anything within the contract. 
This results in warnings of "unreachable code" - see screenshots below.

# How to reproduce
The following code produces errors (screenshot 1)

```
contract;

use std::{address::Address, chain::auth::{AuthError, Sender, msg_sender}, result::*};

abi MyContract {
    fn test_function() -> bool;
}

const ORACLE_1: b256 = 0x6b63804cfbf9856e68e5b6e7aef238dc8311ec55bec04df774003a2c96e0418e;
const ORACLE_2: b256 = 0x54944e5b8189827e470e5a8bacfc6c3667397dc4e1eef7ef3519d16d6d6c6610;
const ORACLE_3: b256 = 0xe10f526b192593793b7a1559a391445faba82a1d669e3eb2dcd17f9c121b24b1;

impl MyContract for Contract {
    fn test_function() -> bool {
        let sender: Result<Sender, AuthError> = msg_sender();
        let is_one_of_signers = match sender.unwrap() {
            Sender::Address(address) => {
                match address.value {
                    ORACLE_1 => true, 
		    ORACLE_2 => true, 
                    ORACLE_3 => true, 
                    _ => false, 
                }
            },
            _ => {
                false
            },
        };
        is_one_of_signers
    }
}
```

The variables `ORACLE_2`, `ORACLE_3` and the `_` are deemed unreachable however it will successfully build.
It's probably because it deems them all equal to `ORACLE_1` - not because of the value or the type but because of the variable name used to catch all.

Here is further evidence that it sees the variable and instead of trying to resolve it within the contract it falls back to the "catch all" (screenshot 2)

```
contract;

use std::{address::Address, chain::auth::{AuthError, Sender, msg_sender}, result::*};

abi MyContract {
    fn test_function() -> bool;
}

const ORACLE: b256 = 0xe10f526b192593793b7a1559a391445faba82a1d669e3eb2dcd17f9c121b24b1;

impl MyContract for Contract {
    fn test_function() -> bool {
        let sender: Result<Sender, AuthError> = msg_sender();
        let is_one_of_signers = match sender.unwrap() {
            Sender::Address(address) => {
                match address.value {
                    0x6b63804cfbf9856e68e5b6e7aef238dc8311ec55bec04df774003a2c96e0418e => true, 
		    0x54944e5b8189827e470e5a8bacfc6c3667397dc4e1eef7ef3519d16d6d6c6610 => true, 
                    ORACLE => true, 
                    _ => false, 
                }
            },
            _ => {
                false
            },
        };
        is_one_of_signers
    }
}
```

# Code that works
The following code builds without warnings. Notice how I am hardcoding the `b256` in the `match`.
This is not ideal since we want to use the `const` declarations (defined in the erroneous codeblocks above) i.e. variables since they may get passed into the function.

```
contract;

use std::{address::Address, chain::auth::{AuthError, Sender, msg_sender}, result::*};

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        let sender: Result<Sender, AuthError> = msg_sender();
        let is_one_of_signers = match sender.unwrap() {
            Sender::Address(address) => {
                match address.value {
                    0x6b63804cfbf9856e68e5b6e7aef238dc8311ec55bec04df774003a2c96e0418e => true, 
		    0x54944e5b8189827e470e5a8bacfc6c3667397dc4e1eef7ef3519d16d6d6c6610 => true, 
                    0xe10f526b192593793b7a1559a391445faba82a1d669e3eb2dcd17f9c121b24b1 => true, 
                    _ => false, 
                }
            },
            _ => {
                false
            },
        };
        is_one_of_signers
    }
}
```

# Screenshots

Here is the warning for the first code block that uses 3 `ORACLE` variables
![1](https://user-images.githubusercontent.com/103777923/170894811-6298c12b-6f40-4375-9540-e46d8f40bd58.png)

Here is the warnings for the second codeblock which only uses one `ORACLE` variable
![2](https://user-images.githubusercontent.com/103777923/170895971-ebc8d1c7-5a6e-40a8-b57f-d24f12992802.png)

cc @mohammadfawaz @emilyaherbert @sezna @otrho

**Comment by mohammadfawaz** [comment]
Yeah this is coming from a complex analysis that's specific for `match`: https://github.com/FuelLabs/sway/blob/master/sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/usefulness.rs
@emilyaherbert is the best person to comment on this as she's the original author of that code.

**Comment by emilyaherbert** [comment]
Can you clarify what you would like the fix to be for this issue? Would you like support for matching directly on constant values _only_? Or _all_ values, including dynamic ones?

For example, Rust supports direct matching on constant values, but requires match guards for matching on dynamic values: https://stackoverflow.com/questions/70344352/how-do-i-match-based-on-a-dynamic-variable

> The following code produces errors (screenshot 1)

This is definitely splitting hairs, but the example code here only produces _warnings_. This is expected because the compiler is interpreting each use of `ORACLE_X` to be a variable binding. The first variable binding in this case binds to any pattern that `address.value` could be, meaning the rest are unreachable.

So, right now, there is no bug. If we wanted to add the ability to match directly on constant values or dynamic values, we would need to add that as a new feature.

**Comment by Braqzen** [comment]
> Can you clarify what you would like the fix to be for this issue @Braqzen ? Would you like support for matching directly on constant values _only_? Or _all_ values, including dynamic ones?
> 
> For example, Rust supports direct matching on constant values, but requires match guards for matching on dynamic values: https://stackoverflow.com/questions/70344352/how-do-i-match-based-on-a-dynamic-variable
> 
> > The following code produces errors (screenshot 1)
> 
> This is definitely splitting hairs, but the example code here only produces _warnings_. This is expected because the compiler is interpreting each use of `ORACLE_X` to be a variable binding. The first variable binding in this case binds to any pattern that `address.value` could be, meaning the rest are unreachable.
> 
> So, right now, there is no bug. If we wanted to add the ability to match directly on constant values or dynamic values, we would need to add that as a new feature.

As a user I would like to be able to use a `match` statement without having to think about what I can put in there.
E.g.

```rust
fn test(arr: [u8; 4]) {
  const numbers = [1u8, 2, 3, 4, 5];
  let ten = 10; // not sure if I must type this as a u8 too because of the typing
  let five: u8 = 5;
  
  match ten % 2 {
      numbers[0] => do_thing(),
      numbers[1] => do_thing(),
      arr[3] => do_thing(),
      8 => do_thing(),
      five => do_thing(),
      _ => do_thing(),
  }
}
```

**Comment by emilyaherbert** [comment]
Hmm, I suppose that it would be _possible_ to do this, although its not clear to me if we _should_ do this. The downside would be that match exhaustivity checking would have to be turned off for any match expressions that contain dynamic values, so the user would be required to add a `_` case at the end in those circumstances, even if they had covered all the possible cases.

**Comment by adlerjohn** [comment]
+1 to don't know if we should do this. If users want to do runtime comparisons that aren't guaranteed to be exhaustive at compile-time, they can always use if-else chains.

**Comment by otrho** [comment]
We tend to ask WWR(ust)D?  And in your example it wouldn't be happy.  Putting an identifier to the left of a `=>` match assigns the matched value to that name for that arm body.  So you'd be introducing new variables `five` and `one` in the above code, AFAIK.  Trying to matchMatching against array members just isn't a thing either.

Matching against a `const` like `ORACLE` should be fine.
