### ISSUE TITLE
"Unsupported instruction as struct value for field expression" error related to `contract_id()`

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#1771]
____

```error
  --> sway-lib-std/src/context/call_frames.sw:23:1
   |
21 |   
22 |   // @dev If called externally, will actually return a pointer to the transaction ID.
23 | / pub fn contract_id() -> ContractId {
24 | |     ~ContractId::from(asm() {
25 | |         fp: b256
26 | |     })
27 | | }
   | |_^ Internal compiler error: Unsupported instruction as struct value for field expression: Call(Function(Index { index: 84, generation: 0 }), [])
Please file an issue on the repository and include the code that triggered this error.
28 |   
29 |   /// Get the asset_id of coins being sent from the current call frame.
   |
____

  Aborting due to 1 error.
Error: Failed to compile FRC721
```

Full code can be seen here -> https://github.com/SwayStar123/FRC721/blob/b4337e4f910f516abeddf2cb3e268698f35b9ec0/src/main.sw
I dont know which one of my contract_id() calls is causing this so cant pinpoint the code

**Comment by mohammadfawaz** [comment]
Hmm that is odd. I'll look through the code but this error often shows up when you try do something like `foo().field_1` where `foo()` returns a struct and one of the fields is `field_1`. The workaround is to store the result of `foo()` in a temporary value and _then_ trying to access `field_1`. See here: https://fuellabs.github.io/sway/latest/reference/known_issues_and_workarounds.html (third known issue).

**Comment by otrho** [comment]
This is more of an IR IMO, as it's in the IRgen phase.  As opposed to the parser.  I'll take a look at it.

**Comment by mohammadfawaz** [comment]
I'll trust you on this. Updated the labels.

**Comment by mohammadfawaz** [comment]
Yeah this is because of `contract_id().value`.. Same problem as https://github.com/FuelLabs/sway/issues/1657. Closing as a dup.
