### ISSUE TITLE
`BuildPlan::from_lock()` should be able to create a `BuildPlan` even there is a package removal in the manifest file

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#1778]
Currently `BuildPlan::from_lock()` fails when there is a package removal in the manifest file. We should be able to get some sort of an "unsafe" `BuildPlan` rather than a complete failure. Because #1686 needs to be able to generate a `diff` on the `BuildPlan` generated from the `lock` file and the updated manifest file. 

## Proposed Solution

We can do that by introducing an "unsafe" version of the `graph_to_path_map()`. Current `graph_to_path_map()` returns an error ("dependency required for path reconstruction has been removed from the manifest") when the dependency coming from the graph is not included in its parent manifest file (which is the case for the removed packages). Instead, we can point them to a default removed path (something like `$HOME/.forc/removed`). This way we can create an unsafe version of the BuildPlan which can be used to produce the diff. Once we have the diff `apply_new_manifest()` from #1686 will use that diff to create an actual BuildPlan representing the updated manifest file.

**Comment by mitchmindtree** [comment]
Just to clarify, I think the steps to reproduce this bug are:

1. `forc init foo`- initialise new project
2. `forc build` - generate new lock file and build project
3. Add `implicit-std = false` to manifest, removing the implicit std dependency.
4. `forc build` - Fails with "dependency required for path reconstruction has been removed from the manifest". Specifically, this error is produced by the `core` dependency as it is a `path` dependency of `std`.

Does that sound right @kayagokalp ? If so I might look into this soon.

I'm looking at `graph_to_path_map` and it's not immediately clear to me why this occurs just yet. E.g. even if `std` is removed from the manifest dependencies, it was introduced as a `git` dependency and as a result when loaded from the old lock file it should still be able to reconstruct it's path into the associated `~/.forc/git/checkouts/std-*` directory :thinking:
