### ISSUE TITLE
Proposal to always automatically import `core` into every Sway project

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1781]
The `core` library is what allows the compiler to handle operations like `1 + 2`, `true == false`, etc. When the `core` library isn't listed as a dependency (or `std` isn't listed as a dependency, because it automatically brings in `core`), then the user gets a confusing error message about how `core::ops::Add` isn't imported, etc. I feel that because operations like `1 + 2` and `true == false` are so ubiquitous, that `core` should be automatically imported always. It also isn't a very good user experience to have to remember to import a library in order to use `+`, IMO.

- Related to #841

**Comment by adlerjohn** [comment]
Note that the only people that would be affected by this are us, since users are always expected to disable implicit std importing.

**Comment by tritao** [comment]
FWIW just hit this issue while trying to match an enum and was pretty confused at first what was going on.

```
21 | 
22 |     match(x) {
   |           ^ Module "core::ops" could not be found.
23 |         MyEnum::Point(x, y) => {
24 |         }
```

At the very least we should probably add to the error message here to mention that `core` needs to be imported.

**Comment by mohammadfawaz** [comment]
This is complete. We have a pretty extensive `core` and `std` preludes now and `Forc.toml` imports `std` and `core` automatically.
