### ISSUE TITLE
Replace `Option<MetadataIndex>` with `Vec<MetadataIndex` in IR `Value`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1782]
That allows multiple metadata nodes to be attached to a single IR value. https://github.com/FuelLabs/sway/pull/1760 adds a new metadata but does it by adding another `Option`. This should be changed to use `Vec` instead.

**Comment by otrho** [comment]
In a separate branch I'm adding several metadata to `FunctionContent` too.  I think we should think about a more general model for adding and querying any number of metadata to any IR object which needs them.

**Comment by mohammadfawaz** [comment]
@vaivaswatha are you working on this already? I'm proposing that this should be done while working on https://github.com/FuelLabs/sway/issues/1906 and so I'm hoping to be able to close this as a subset of the #1906.

**Comment by vaivaswatha** [comment]
> @vaivaswatha are you working on this already? I'm proposing that this should be done as part of #1906 and so I'm hoping to be able to close this as a subset of #1906.

No I haven't started working on this. Please feel free to close it.

**Comment by mohammadfawaz** [comment]
Thanks! Closing in favour of #1906.
