### ISSUE TITLE
Introduce `forc` build `[profile]`s in anticipation of introduction of compiler optimisation passes

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1785]
Currently, `forc`'s support for different build profiles is non-existent. We *do* currently anticipate their support within the compiler output artifact directory by placing artifacts in a profile subdirectory which is currently assumed to be "debug", e.g. `<project>/out/debug/` where `debug` is the default profile.

## Motivation

Build profiles should allow for describing a set of options for guiding compilation. This could include an "optimisation level" as a short-hand for a particular list of optimisation passes to run, or debug options for including extra kinds of annotations/symbols in the output that might be required for debugging in certain cases.

There has recently been some discussion around introducing optimisation passes into `sway-core`. In order to easily enable/disable these, we should prepare support for build profiles so that devs can easily enable/disable certain paths and set the precedent for feeding project-specific build parameters into compilation in general. This could also be a useful place for introducing flags for experimental compiler features (rather than needing to add CLI flags to `forc` on every invocation).

## Cargo's `[profile]`

Cargo uses a `[profile]` table for this which might act as a good reference for the kinds of options that we might want available. It's worth keeping in mind that many (most?) of these options are specific to Rust, and that upon introducing this feature it's OK to start with a very minimal set of support (e.g. optimisation level).

https://doc.rust-lang.org/cargo/reference/profiles.html

## Forc `[build-profile]`?

Seeing as the `Forc.toml` manifest will likely also include support for certain kinds of *deployment* configuration, we may wish to name this `[build-profile]` to clarify that this table of options is specifically designed to be received as an input to *compilation*. The CLI option flag given to `forc build` could still be `--profile` as the command makes it clear we are referring to the project's `build` process.

## Default build profiles

To be consistent with cargo and the vast majority of languages out there, we should provide two profiles by default:

- `debug` - little to know optimisations applied and any useful debugging options enabled.
- `release` - all stable optimisations applied and stripped of all debugging options that would affect performance/size in any way.

If no `--profile <profile>` option is specified, we should likely default to `debug` as is currently case and consistent with cargo behaviour.

CLI shorthands could be provided for these common default profiles so that rather writing `forc build --profile release`, users can instead write `forc build --release` (similar to cargo).

## Implementation

1. Introduce a `[build-profile]` table to the `Manifest` within `forc-pkg`.
2. Add some `const` `BuildProfile`s for the default debug and release profiles.
3. Add a `forc build` `--profile <profile>` for specifying which profile to use by its name.
4. In `forc build`, determine which build profile was specified.
5. Forward `BuildProfile` options to compilation via `sway_core::BuildConfig`. This will involve ensuring that the `BuildConfig` has the necessary params.
6. Ensure the output artifact directory used actually matches the name of the build profile.
7. Document the feature in the forc manifest reference within The Sway Book.

**Comment by kayagokalp** [comment]
This looks perfect thanks for the detailed explanation! I can take a look at this. Let me start with a quick question. I am guessing we will want to have all of the fields that we are currently creating the `BuildConfig from. 

These are:

1. `use_orig_asm`
2. `print_ir`
3. `print_finalized_asm`
4. `print_intermediate_asm`
5. `silent`

If any of these is missing from the supplied `[build-profile]` should we produce an error or use some default values (`false` ?)

**Comment by kayagokalp** [comment]
Do we have any idea of what needs to be passed with `BuildProfile`? I have the general structure ready but I am not sure what to pass to the compiler? Currently the draft PR I linked (#1800), just uses the old `BuildConfig` fields.

**Comment by mitchmindtree** [comment]
Yeah I think just starting with the `BuildConfig` fields makes sense.
