### ISSUE TITLE
When `--offline` flag specified for `forc build`, attempt to use local git checkouts for git dependencies before failing

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1787]
Supporting `forc build --offline` is trivial for the case where the `[dependencies]` table in the `Forc.toml` manifest remains untouched, as `forc` can recreate the dependency graph entirely from the lock file. However, if the `[dependencies]` table is edited whatsoever, forc will try to recreate the whole graph by re-fetching dependencies.

This behaviour will be greatly improved by #1686 which makes more concise modifications to the package graph based on the difference between the dependencies read from the lock file and those read from the manifest. These means we can now at least support dependency removal and editing/adding `path`-sourced dependencies without failing in `--offline` mode. 

We should also do our best to support editing/adding `git` dependencies in `--offline` mode.

## Potential Approach

In the case that `--offline` was specified, we should attempt to find an existing git checkout for the specified dependency within `~/.forc/git/checkouts` that adheres to the described git source.

For example, In the case that the following dependency was added:

```toml
foo = { git = "https://domain.com/owner/repo", branch = "bar" }
```

We should attempt to find all existing checkouts of the `foo` package whose commit is known to be of the `bar` branch from the `https://domain.com/owner/repo` repo and select the most recent one. Finding local checkouts for git sources that specify a `tag` or `rev` should be easier, as they should map to a specific commit.

We could possibly consider maintaining an index that maps from `GitSource` to the path of the latest known checkout for that git source. However, we should be weary that if we maintain an index it will need to handle the case where multiple processes or threads are attempting to read-from, add-to or edit it simultaneously. Ideally we shouldn't have to introduce a whole db crate just for this case.

Alternatively, when checking out local git repositories into `~/.forc/git/checkouts/`, we can copy over the `.git` directory too (currently we omit it). Doing so would allow us to use the `git2` crate to check whether the existing checkout is valid for the specified git source.

It's worth noting that searching and checking `~/.forc/git/checkouts` without and index should not be a major performance hit, as we only require checking out directories that start with the same package name, and the search only needs to be performed once as consecutive calls to `forc build` will retrieve the dependency directly from the lock file.

**Comment by kayagokalp** [comment]
I was planning to start this but moved formatter stuff to the front in my current work queue. Removing my assignment for now so that if someone wants to tackle it until we are done with formatter stuff. Otherwise, I can take a look after formatter as I am pretty excited about the offline support 😄

**Comment by kayagokalp** [comment]
I implemented the logic for git sources other than `branch` as it seemed to be easier to start with and I am providing some benchmarks so that we can confirm the searching for a local version is manageable. For comparison i created an empty project which (implicitly) depends on `std`. 

Building the empty project without searching for a local repo (and doing the fetch & pin stuff takes) **11.5 seconds** on my system 
Building the empty project with searching for a local repo takes **1.35 seconds** on my system which feels like butter

I think it is worth searching for a local copy even if we are in `online` mode and if we cannot find one then we can fetch & pin (as a `TODO` suggests at the relevant part of the code).
