### ISSUE TITLE
Improve error messaging for `StorageMap` when used illegally (or allow those cases?)

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1796]
Here are some cases that we need to think about and either support or simply disallow with clear error messages:

### Case 1:

```rust
storage {
    map1: StorageMap<u64, u64>,
}

...

let local_map1 = storage.map1;
local_map1.insert(..);

```
This currently emits an internal compiler error that should be improved. 

### Case 2
```rust
let local_map1: StorageMap<u64, u64> = StorageMap {};
local_map1.insert(..);
```
This currently errors out with a type inference issue.

### Case 3
```rust
Struct Wrapper {
    map1: StorageMap<u64, u64>,
    map2: StorageMap<u64, u64>,
}

storage {
    w: Wrapper
}

...

storage.w.map1.insert(..);
```
This does compile but I _think_ it will cause collision between `map1` and `map2` because they have the same `storage` index (that of `w`), so we need additional information which is available but not yet propagated. But then again, we should think about whether we should even allow this.

### Case 4
Storage maps that contain other storage maps. Not sure what the semantics of this would be really. And this is not going to work with the way we do things (i.e. using an intrinsic that relies on the state index in the `storage` block). We need some sort of `storage` reference here.

**Comment by adlerjohn** [comment]
Makes sense for all three of these for be forbidden.

Some variation of case 1 (but with some explicitness around the variable being storage) would be nice to allow libraries to take in storage pointers.
