### ISSUE TITLE
Improve error messages for unknown types

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1797]
# Repro

```rust
contract;

// Correct path
// use std::vm::evm::evm_address::EvmAddress;

use std::vm::evm::EvmAddress;

abi MyContract {
    fn test_function() -> EvmAddress;
}

impl MyContract for Contract {
    fn test_function() -> EvmAddress {
        ~EvmAddress::from(0x0000000000000000000000000000000000000000000000000000000000000000)
    }
}
```

# Screenshots
![1](https://user-images.githubusercontent.com/103777923/171486072-836b700f-e213-46c3-b14b-4c8a8f512973.png)
![2](https://user-images.githubusercontent.com/103777923/171486086-31bcbe6f-edec-40a5-bf8a-66bd92ceb48e.png)
![3](https://user-images.githubusercontent.com/103777923/171486098-daa8db11-004a-42bb-a151-a38bf4287972.png)

cc @mohammadfawaz @emilyaherbert @sezna @otrho

**Comment by mohammadfawaz** [comment]
A lot of this was addressed in https://github.com/FuelLabs/sway/issues/1740. The only thing remaining is:
```console
  --> /Users/mohammad/Desktop/fuel/sway/test/src/e2e_vm_tests/test_programs/should_pass/language/const_decl_and_use_in_library/src/main.sw:14:22
   |
12 |
13 |     fn test_function() -> EvmAddress {
14 |         ~EvmAddress::from(0x0000000000000000000000000000000000000000000000000000000000000000)
   |                      ^^^^ No method named "from" found for type "unknown due to error".
15 |     }
16 | }
   |
____
```
which is a bit weird. We can do a bit better than that.
