### ISSUE TITLE
Add math & bitwise ops to `U256` type

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1798]
Probably not critical at this point, but it may be something we want to have eventually. 
Possible uses:
- handle _**very**_ large integers (ie: overflowing `U128` maths)
- a convenient way to pack 4 `u64`'s together as a single logical entity. Currently, users are trying to pack `u64`s into a `b256` which is not really what a `b256` is for semantically. This may in part be due to a misunderstanding of storage slots and word size in the FuelVM; Devs familiar with Solidity are often familiar with packing as much data as possible into a `uint256` (a single storage slot). 

Note: The basic `U256` is implemented in #2103.
TODO:
- [ ] add math operations to `U256`
- [ ] add bitwise operations to `U256`

**Comment by mohammadfawaz** [comment]
Seems that this is now implemented in https://github.com/FuelLabs/sway/pull/2445
