### ISSUE TITLE
Add support for `enums` in `storage {}`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1813]
As a user I would really like to store an `enum` inside `storage {}`.

Currently I must use another variable type, `u64`, with some number to perform the same state checks etc.
This isn't the worst thing in the world however when it comes to an `enum` that uses the common `Address` and `ContractId` that becomes a different story as now I must use additional variables or add additional code to figure out which type I am using.

**Comment by mohammadfawaz** [comment]
I have a branch with the fix. I'll put up a PR today.
