### ISSUE TITLE
Remove the unused `sway.pest` file

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1815]
Remove this file, I don't believe it is used anymore. https://github.com/FuelLabs/sway/blob/ed600e98af2b1733a98e0b2d12799ef176829ac3/sway-core/src/sway.pest

**Comment by adlerjohn** [comment]
In the absence of this file, is there a concise specification of the language's grammar?

**Comment by emilyaherbert** [comment]
> In the absence of this file, is there a concise specification of the language's grammar?

No, but we should definitely have one, probably in the Sway book somewhere! However, we should _not_ base it off of the `.pest` file, as the grammar has drifted since the `.pest` file was last used in the main compile path.

**Comment by emilyaherbert** [comment]
> In the absence of this file, is there a concise specification of the language's grammar?

In other words, there isn't an up-to-date specification of the grammar right now, even with this file in the repo.

**Comment by mohammadfawaz** [comment]
We could have "The Sway Reference" like ["The Rust Reference"](https://doc.rust-lang.org/reference) but that's actually a huge undertaking.

**Comment by PrajwalBorkar** [comment]
I can work on this :)
