### ISSUE TITLE
Add a module to the stdlib to expose `LDC` opcode

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1846]
Many common patterns will require this functionality. A few examples include:
- upgradeable contracts
- proxies

I thought we would also expose `SLDC` but found this issue to remove that instruction in the spec: https://github.com/FuelLabs/fuel-specs/issues/313

**Comment by otrho** [comment]
I had to look it up. :) https://github.com/FuelLabs/fuel-specs/blob/master/specs/vm/opcodes.md#ldc-load-code-from-an-external-contract

**Comment by nfurfaro** [comment]
I'm thinking maybe 2 functions here, `load_contract()` and `load_contract_fragment()`
(Names are not set in stone). 
The alternative would be having optional params (`Option<T>`) which is `None` mean load the entire contract. I think I prefer 2 separate functions.

**Comment by nfurfaro** [comment]
I'm going to focus on getting the first function up and running (& tested).
Loading a portion of a contract can be added as a further enhancement.

**Comment by nfurfaro** [comment]
Q: Is the outcome of calling `LDC` persistent, or would I need to call `LDC` each time I want to load code from contract`B` into contract`A`?
I feel like the former would be nice, but copying the bytecode of contract `A` into the stack space of contract `B` sounds like a temporary thing.
cc @adlerjohn

**Comment by adlerjohn** [comment]
You need to do it each time.

**Comment by nfurfaro** [comment]
Blocked by: https://github.com/FuelLabs/fuel-specs/issues/346

**Comment by nfurfaro** [comment]
Update: WIP on a stdlib wrapper for `ldc` can be found on the `furnic/ldc` branch of the Sway repo.
