### ISSUE TITLE
Make the `transfer_to()` from `token.sw` in the `std-lib` non-specific to the `contract_id()`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1851]
Currently the function uses the `contract_id()` to automatically transfer the asset - being itself.

I find myself transferring variable assets frequently and thus [transfer_to()](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/token.sw#L46) should be deprecated to allow any assets to be transferred rather than just the contract that it is being called from.

Here is the new function to take its place.

```rust
fn transfer(to: Identity, asset: ContractId, amount: u64) {
    match to {
        Identity::Address(address) => {
            transfer_to_output(amount, asset, address);
        },
        Identity::ContractId(address) => {
            force_transfer_to_contract(amount, asset, address);
        }
    }
}
```

**Comment by Braqzen** [comment]
cc @nfurfaro Dropping it in your inbox for a reference

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/sway/pull/1856

**Comment by adlerjohn** [comment]
The order of parameters needs to be consistent across all 3 functions. Also, would be good to see tests.

**Comment by Braqzen** [comment]
> The order of parameters needs to be consistent across all 3 functions. Also, would be good to see tests.

Why does it need to be the same order if we are bumping to v0.15.0 soon (which is a breaking change)?

**Comment by otrho** [comment]
Every function in `token.sw` currently takes the amount first and the destination last.  Should keep it consistent.

**Comment by adlerjohn** [comment]
To clarify: I was saying the order of parameters between the 3 functions must be consistent. Not that it has to remain the same as it is now.
