### ISSUE TITLE
Bug with using match expressions on `self`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1852]
# Reproduce

The following code produces a compilation error.

```rust
library breaking_matching;

use core::ops::Eq;

enum Initialized {
    True: (),
    False: (),
}

impl Eq for Initialized {
    fn eq(self, other: Self) -> bool {
        match (self, other) {
            (Initialized::True, Initialized::True) => true,
            (Initialized::False, Initialized::False) => true,
            _ => false,
        }
    }
}
```

# Screenshot
![1](https://user-images.githubusercontent.com/103777923/172064625-0800f8e5-200e-4759-8f6e-47a9491a3f3f.png)

cc @emilyaherbert

**Comment by emilyaherbert** [comment]
Just a note for this issue: tuple matching is implemented. I think this is happening because of the match on `self`.

**Comment by mohammadfawaz** [comment]
@emilyaherbert I'm marking this as critical, same as #1628. Hopefully they are fixed simultaneously. Please let me know if you disagree!

**Comment by Braqzen** [comment]
> @emilyaherbert I'm marking this as "P: critical", same as #1628. Hopefully they are fixed simultaneously. Please let me know if you disagree!

![image](https://user-images.githubusercontent.com/103777923/173086097-6516ee6c-b5b4-4e30-a975-c48a5e5cf33b.png)

**Comment by emilyaherbert** [comment]
Sounds good @mohammadfawaz ! I am hoping to tackle this issue, #1628,  #1143, and #1103 all at the same time.
