### ISSUE TITLE
The Sway Book should have all embedded code removed and moved into `examples/`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1862]
# Summary

The Sway Book has many pages and some of them contain code-blocks.
These code-blocks should not be hardcoded into the markdown files and instead should reference examples from the `sway/examples/` directory using the `{{#include <path to example>}}` syntax.

This means that the book itself will require a lot of revisions in how it presents the information - which is good because the book is out of date.

**Comment by mohammadfawaz** [comment]
I'm marking this as critical because we're at a point where we really shouldn't have code that doesn't compile in the Sway Book. Some code block are hard to move because they're just snippets and not full programs, but there are ways (I think) to only show parts of a full example.

**Comment by adlerjohn** [comment]
Anchors can be used to only show parts of the code.

**Comment by Braqzen** [comment]
Old issue. Books should be merged and thus cleanup will inevitably happen,
