### ISSUE TITLE
Extend LSP and VSCode plugin with DAP debugger support

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/sway#1864]
Extend our [language server protocol](https://microsoft.github.io/language-server-protocol/) server ([sway-lsp in this repo](https://github.com/FuelLabs/sway/tree/master/sway-lsp))  with [debug adapter protocol](https://microsoft.github.io/debug-adapter-protocol/) support. This makes in-editor debuggers like the one in VS Code work with Sway. This also requires some changes to per-editor plugins, i.e. [FuelLabs/sway-vscode-plugin](https://github.com/FuelLabs/sway-vscode-plugin/).

**Comment by adlerjohn** [comment]
@Dentosal Can you file a sister issue in sway-vscode-plugin with a few more details for a prospective implementer?

**Comment by Dentosal** [comment]
I have an implementation in progress, and it's likely easier to just submit a PR to track the progress. The code there will be heavily dependent on the debug adapter itself, and they have to be developed together.

**Comment by Dentosal** [comment]
Sway issue for tracking missing compiler features https://github.com/FuelLabs/sway/issues/2055

**Comment by sdankel** [comment]
Duplicates https://github.com/FuelLabs/sway/issues/5394
