### ISSUE TITLE
Tuple destructuring results in warnings about variables being ignored when `_` is used 

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1867]
# Reproduce

```rust
library tuples;

fn tuple() {
    let tuple = (5, true, ("Sway", 8));

    let(_, truthness, _) = tuple;
}
```

The variables are intentionally ignored. There should not be any complaints (warnings) in this case.
Tangentially, line 6 (in screenshot) clearly "uses" the variable.

# Screenshots
![1](https://user-images.githubusercontent.com/103777923/172161436-60811d1c-484f-4f72-a915-cdbb48487e40.png)

**Comment by vaivaswatha** [comment]
Note:

- `let _ = 13;` for example also results in a warning whereas 
- `let _foo = 13` does not. 
- Similarly, no warnings for `let(_a, truthness, _b) = tuple;`
