### ISSUE TITLE
Add `send_message()` function to the stdlib to expose the `SMO` opcode

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#1868]
The current work on the bridge project requires passing of `MessageOutput`s via the `SMO` opcode.
This functionality needs to be exposed in the stdlib.

reference: 
https://github.com/FuelLabs/fuel-specs/blob/bd6ec935e3d1797a192f731dadced3f121744d54/specs/protocol/tx_format.md#outputtype

https://github.com/FuelLabs/fuel-specs/blob/bd6ec935e3d1797a192f731dadced3f121744d54/specs/vm/instruction_set.md#smo-send-message-to-output

**Comment by nfurfaro** [comment]
Blocked by: Opcode not yet implemented in FuelVM

**Comment by emilyaherbert** [comment]
@nfurfaro  these links generate 404's. Can you update them?

**Comment by adlerjohn** [comment]
For future reference, you should also link with permalinks @nfurfaro. You can press "y" when you have a page open on GitHub to convert to a permalink.

**Comment by nfurfaro** [comment]
closed by #2796
