### ISSUE TITLE
sway-fmt-v2 should be able to handle indentations correctly.

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#1888]
Since we are building the formatted code from AST items we may need to have a common way of building the formatted code (something like a `CodeBuilder` that keeps track of the current indentation level). So that we can build the code with correct indentations. 

I can see this kind of logic is present in the current formatter but would love to discuss if there are other ways we can reconstruct the code with correct indentations. 

If this is indeed something we need I can implement it before #1873 

cc @eureka-cpu

**Comment by eureka-cpu** [comment]
Going to add some handling of newlines today

**Comment by eureka-cpu** [comment]
Now just need to handle block indentation handling and this should be good to go

**Comment by eureka-cpu** [comment]
Take a look at `shape.rs` from `rustfmt` I think that will give you the answer for handling indents!

**Comment by eureka-cpu** [comment]
I think with #1894 & #1911 this should be closed but feel free to reopen if not
