### ISSUE TITLE
Add a test to ensure we produce a nice error when detecting a dependency cycle

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1904]
This could be two or three packages which depend on each other under the E2E `should_fail` tests. We want to ensure that 1. we don't attempt to infinitely fetch (I don't think we do) and 2. we produce a decent error.

**Comment by kayagokalp** [comment]
I just tried to build a package with cyclic dependency. It fails as it should but maybe we can touch the error produced a little.

Current output:

```
Error: dependency cycle detected: Cycle(NodeIndex(2))
```

I am not sure if NodeIndex(2) part means something to the user but maybe something like the following would be easier to understand if that ever happens to a user:

```
Error: dependency cycle detected between 'dependency_a' and `dependency_b` 
```

**Comment by kayagokalp** [comment]
I am quickly adding two libraries that depend on each other so that we do not forget about https://github.com/FuelLabs/sway/pull/1910#issuecomment-1150801323
