### ISSUE TITLE
Refactor to generalise IR metadata.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#1906]
### Problem

At the moment we have only a couple of types of metadata in IR, spans and storage indices.  I'm adding storage attributes now too.  The spans are actually two different types: a path type and a segment type.

So each of these types of metadatum are hard coded in the IR library.  If we want to add more then we need to add new data structures and types to the IR library.  This is not really general enough, especially since the IR usually doesn't care what is in the metadata.

### Fix

I propose that we refactor the metadata to use a general structured type which can reasonably represent anything in metadata but without needing specifics in the IR library.  A bit like JSON or s-exprs.

Each metadatum could have an identifying tag or key, and then tuples or nested tuples of strings and ints.  A special metadata index would also be a usable type, to reference other metadata.

e.g., a Span would be tagged with `span`, and have a `(idx, int, int)` tuple, for path index, start and end.  When serialised it would look similar to what we have now: `!11 = span (!0 10 20)`.

**Comment by mohammadfawaz** [comment]
Can https://github.com/FuelLabs/sway/issues/1782 be closed in favour of this issue?

**Comment by otrho** [comment]
They're not really the same thing, though I guess they can be done at the same time.  Now that we have an explicit link between the two it should be OK to close it. 🙂

**Comment by mohammadfawaz** [comment]
Yeah this issue seems like a superset as generalizing metadata seems like it would require moving away from individual `Option`s to a vector of metadata.
