### ISSUE TITLE
Cargo.toml SDK not updated to v0.15 on "forc init"

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#1907]
When creating a new project using forc init, the Cargo.toml SDK is not updated to version 0.15.

```
[dependencies]
fuels = "0.14"
fuels-abigen-macro = "0.14"
```

**Comment by mohammadfawaz** [comment]
Two steps to get this done for anyone who wants to take this on:
* Update the standard library tests to use `fuels 0.15`: https://github.com/FuelLabs/sway/blob/master/test/src/sdk-harness/Cargo.toml#L13-L14 and make sure nothing breaks. That ensures that everything is stable. 
* Update the defaults for `forc init`: https://github.com/FuelLabs/sway/blob/master/forc/src/utils/defaults.rs#L33-L34
