### ISSUE TITLE
Process changes for the `sway` repo

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1923]
Two items:
- [x] Create "teams" of PR reviewers on GitHub so that these teams could be added as reviewers, instead of individuals (i.e. one for the Sway team, one for the standard library team, SDK, etc, with individual members being in multiple teams where it makes sense).
- [x] Add the ability for GitHub to automatically squash and merge when a PR is approved.

**Comment by adlerjohn** [comment]
> Add the ability for GitHub to automatically squash and merge when a PR is approved.

It is done
