### ISSUE TITLE
`swayfmt` doesn't format function attributes correctly

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#1931]
```
#[storage(read)]
fn foo() { ...
```
turns into:
```
#[storage(read)]fn foo() { ...
```

**Comment by otrho** [comment]
Can't decide whether it's called `forc-fmt` or `sway-fmt`. :smile: It's both I guess. :wink:

**Comment by eureka-cpu** [comment]
Thanks for this issue! I'll add it to the MVP and get a PR soon

**Comment by eureka-cpu** [comment]
Just out of curiosity, what happens when you use `sway-fmt-v2`, or was that what you were using?

**Comment by otrho** [comment]
I actually only noticed when all the examples were reformatted in the CI.  https://github.com/FuelLabs/sway/pull/1716/files

**Comment by eureka-cpu** [comment]
I've opened #2012 to track it for swayfmt-v2

**Comment by eureka-cpu** [comment]
Once `abi` gets in via #2044 , this will no longer be a problem for `sway-fmt-v2` (:
