### ISSUE TITLE
Consider removing the type `byte`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#1936]
It is not really documented in the Sway Book and it's pretty similar to a `u8`. One added benefit to `byte` is that it doesn't cast to other integer types like `u8`.

Edit: actually we do mention `byte` in passing here: https://fuellabs.github.io/sway/latest/basics/built_in_types.html#numeric-types
> All of the unsigned integer types are numeric types, and the _**byte**_ type can also be viewed as an 8-bit unsigned integer.

**Comment by otrho** [comment]
Just do it.  :yoda: There is no consider.

**Comment by adlerjohn** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0
