### ISSUE TITLE
Modify our fork of Inflector to not singularize/pluralize _or_ write a new crate for determining case.

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#194]
See #193  for details -- we don't actually want to warn when the singularity/plurality of a type is "incorrect" according to [Inflector](github.com/sezna/Inflector). We should either rip that functionality out or implement a new crate that just handles snake/screaming snake/class/sentence case with no regard for plurality.

**Comment by otrho** [comment]
I'm pretty sure this was resolved by #384.
