### ISSUE TITLE
Improve error message when passing in the `storage` keyword as a `type` into a function

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1946]
# Reproduce

```rust
contract;

storage {
    var: u64,
}

abi MyContract {
    fn test_function(s: storage) -> bool;
}

impl MyContract for Contract {
    fn test_function(s: storage) -> bool {
        let mut s = s;
        s.var = s.var + 1;
        true
    }
}
```

Error should state something similar to `"storage" cannot be used as a type` / `Cannot pass in "storage" as a type into a function`.

# Screenshot
![1](https://user-images.githubusercontent.com/103777923/173226125-0a0521d0-fb19-440c-9097-a42dcd291ac5.png)

cc @FuelLabs/sway-compiler

**Comment by mohammadfawaz** [comment]
So, we have almost no checks in the compiler against using keywords in places where they don't belong. This is just one example. There are may more such as:
```rust
let mut mut = 0;
```
which compiles without any errors. I think a full solution needs to be implemented in the parser that protects against using keywords where identifiers should go. cc @canndrew, what is the best way to do this?

**Comment by mohammadfawaz** [comment]
I'm closing this in favour of https://github.com/FuelLabs/sway/issues/1996 which is tracking a general solution for all keywords.
