### ISSUE TITLE
Internal compiler error: State index for get_storage_key is not available as a metadata

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1947]
# Reproduce

Passing in a mapping into a function, not just in a library, produces an ICE.

Related: #1809 

```rust
contract;

use std::storage::StorageMap;

storage {
    map: StorageMap<u64, u64>,
}

fn insert(mapping: StorageMap<u64, u64>) {
    mapping.insert(1, 1);
}

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        insert(storage.map);
        true
    }
}
```

# Screenshot
![1](https://user-images.githubusercontent.com/103777923/173227256-acef500b-53b2-4d1f-97aa-b6494f6c97db.png)

cc @FuelLabs/sway-compiler

**Comment by mohammadfawaz** [comment]
@vaivaswatha I just assigned this to you as it fits well with https://github.com/FuelLabs/sway/issues/1796
