### ISSUE TITLE
Dead Code Analysis suspiciously slow (up to 28x slower than `type_check`) particularly for `std`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1952]
I've noticed the E2E tests and stdlib tests have been progressively getting slower and slower as we add new APIs to `std`.

This is particularly problematic for `sway-lsp`. @JoshuaBatty is in the process of updating `sway-lsp` to use `compile_to_ast`, however the current state of things (taking multiple seconds just for `std`) is unfeasible for the kind of feedback a user would normally expect in an IDE environment.

To work out what's going on, I added some basic time-stamping between all of the major compiler phases to see where most time was being spent. You can see the exact approach in [this commit](https://github.com/FuelLabs/sway/commit/1576f1dfdcb0c45c96b7b505cba1102d398f4034).

Here is the output of `forc build --path examples/counter` with `forc` built in `debug`:

```sh
$ cargo run --bin forc -- build --path examples/counter
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/forc build --path examples/counter`
Parsing: 1.06626ms
Type Check: 1.344043ms
Dead Code Analysis: 294.733µs
Return Path Analysis: 146.552µs
  Compiled library "core_utils".
Parsing: 12.502972ms
Type Check: 75.687842ms
Dead Code Analysis: 113.27732ms
Return Path Analysis: 4.030499ms
  Compiled library "core".
Parsing: 26.412109ms
Type Check: 159.818236ms
Dead Code Analysis: 4.463190539s
Return Path Analysis: 9.589824ms
  Compiled library "std".
Parsing: 566.406µs
Type Check: 861.018µs
Dead Code Analysis: 209.432µs
Return Path Analysis: 89.74µs
Finalize Types: 51.21µs
Compile IR: 1.146012ms
Purity Check: 16.96µs
Inline Fn Calls: 54.66µs
Combine Constants: 3.84µs
Compile ASM: 2.341203ms
  Compiled contract "counter".
  Bytecode size is 256 bytes.
```

Curiously, the Dead Code Analysis phase is taking vastly longer than everything else when compiling `std`: `Dead Code Analysis: 4.463190539s`.

Compiling `forc` in `--release` does run significantly faster:

```sh
$ forc build --path examples/counter
Parsing: 202.012µs
Type Check: 311.453µs
Dead Code Analysis: 32.1µs
Return Path Analysis: 20.86µs
  Compiled library "core_utils".
Parsing: 1.419324ms
Type Check: 8.038199ms
Dead Code Analysis: 10.101929ms
Return Path Analysis: 585.396µs
  Compiled library "core".
Parsing: 2.477274ms
Type Check: 20.874826ms
Dead Code Analysis: 215.495149ms
Return Path Analysis: 1.455874ms
  Compiled library "std".
Parsing: 79.69µs
Type Check: 139.272µs
Dead Code Analysis: 19.1µs
Return Path Analysis: 7.08µs
Finalize Types: 6.3µs
Compile IR: 123.721µs
Purity Check: 1.94µs
Inline Fn Calls: 5.301µs
Combine Constants: 410ns
Compile ASM: 220.282µs
  Compiled contract "counter".
  Bytecode size is 256 bytes.
```

However Dead Code Analysis still takes ~10x the type-check stage for `std`. It appears there might be an exponential blow-up the bigger the program/library.

It would be worth investigating this soon in order to speed up the debug build, cut down our CI times and improve responsiveness in the upcoming LSP update. It also looks like sway could get close to instantaneous / real-time build times in release mode which would be a nice impression to leave :)

cc @sezna I think I remember saying you had an idea of what might be causing this?

**Comment by otrho** [comment]
Hrmm, maybe the [mark-and-sweep GC](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Na%C3%AFve_mark-and-sweep) idea I had might apply.  Absolutely depends on what the actual problem is though.

**Comment by mitchmindtree** [comment]
Ah nice, sounds like we might be able to get a major win with some easy fixes!

> We check certain nodes waaaay too many times due to the deterministic abortion check.

Sounds like we might want to do something like the common graph traversal trick where you plumb through a `visited: HashSet<NodeIndex>` to keep track of and skip already checked nodes? Maybe something along these lines anyway.

**Comment by otrho** [comment]
I thought the abort check was part of the type checking, rather than dead code analysis..?
https://github.com/FuelLabs/sway/blob/f1632e5437ccb329baa780175b95e2d1627b6eb1/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs#L581

So that might reduced the type check numbers but not the control flow.

**Comment by otrho** [comment]
With my recent attributes stuff I tried to add flags to the nodes at creation time, since the deterministically aborts property and annotations are known from the start, but found it would be very invasive... would require a non-trivial refactor of the parse tree and/or typed AST.

We currently do the aborts check just as a part of the recursive conversion to typed AST, so we query nodes for that property as we go, and this is why we might query nodes multiple times.  So to solve this in a recursive way we need to pass some extra context around with memos, either pre-populating it or growing it as we go like how most memoisation works.

So this would also be fairly invasive -- it's passing another data structure around to the type checker, though it could probably go in that type-check-arguments struct.

**Comment by mitchmindtree** [comment]
> So this would also be fairly invasive -- it's passing another data structure around to the type checker, though it could probably go in that type-check-arguments struct.

Sounds like this might be better addressed after the decl engine stuff then? Then it could possibly be done in a dedicated phase _following_ type check?

**Comment by otrho** [comment]
No, the aborts check is a part of the type checking AFAICT -- I didn't write it, but I think it's needed to know whether it's OK for an expression to have the 'wrong' type because it doesn't return.
