### ISSUE TITLE
Implement `WidthHeuristics` to set maximum width of code lines

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#2001]
This configuration can be found under `heuristics::WidthHeuristics` with some helpful methods.

**Comment by kayagokalp** [comment]
I think this is already implemented for `fmt-v2`. If that is the case maybe we can close this one.

**Comment by eureka-cpu** [comment]
If it has we should add tests that confirm this and let that PR close this issue

**Comment by eureka-cpu** [comment]
#2338 closed this by adding a `width_heuristics` field to `Shape`
