### ISSUE TITLE
sway-fmt-v2 should be leaving the source code untouched if there is no match to any item

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2008]
Currently, if there is no match to any item (such as `use`, `const`, `fn`, etc) `sway-fmt-v2` just deletes that part of the code.  This resulted in the #1995. 

But it actually should just leave them untouched and just format the parts that are matched to an item.

We currently have a quick-fix addressing this (#1995) specific case but we should think about how to refactor the general structure of the formatter to leave other parts untouched.

**Comment by eureka-cpu** [comment]
After some bikeshedding, the current direction of the formatter is OK and we can close this issue
