### ISSUE TITLE
Fix pointer types and use `std::mem` on `std::tx`

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/sway#2015]
`std::tx` uses `u32`s for pointers while it should use `u64`.

It could also use the new `std::mem` to simplify things. (https://github.com/FuelLabs/sway/pull/1928#discussion_r899366977)

**Comment by mohammadfawaz** [comment]
https://github.com/FuelLabs/fuel-specs/pull/353/files will also help make `std::tx` a lot cleaner I believe.
