### ISSUE TITLE
Make `BASE_ASSET_ID` a constant `ContractId`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#2020]
Now that #1948 is in, https://github.com/FuelLabs/sway/blob/3ce5945cbe8d169f5ec17a2b731521c0284de553/sway-lib-std/src/constants.sw#L3 should be

```rust
const BASE_ASSET_ID = ~ContractId::from(0x0000000000000000000000000000000000000000000000000000000000000000);
```

**Comment by r-sitko** [comment]
I will take it.
