### ISSUE TITLE
Implemented traits on data structures do not get imported unless you import everything from the module using the glob operator

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2030]
# Summary

If you take a look at the test in this [pull request](https://github.com/FuelLabs/sway/pull/2028/files#diff-8e0e25ea6a03877374683337a0dcd779c226b8756c9624bec1bd687f399f2283) you'll notice that I must import `identity::*` instead of `identity::Identity`.

The reason for this is that the `trait` does not exist unless you import _everything_. 
This has happened in multiple other instances before.
That is far from desirable and correct behaviour.

Resolution: When importing a type such as `Identity` all of the traits that are implemented for it should be imported as well.

cc @FuelLabs/sway-compiler

**Comment by mohammadfawaz** [comment]
Related: https://github.com/FuelLabs/sway/issues/1387

**Comment by mohammadfawaz** [comment]
We do that for structs though 🤔 

I have a quick resolution here: https://github.com/FuelLabs/sway/pull/2034

**Comment by Braqzen** [comment]
> To follow the rust spec, you must import a trait in order for its implementations to be in scope. Just importing a type doesn't import every known trait implementation for it. So, there should be two ways to import a trait implementation:
> 
> 1. Import the trait itself
> 2. Star-import the file which contains the trait
> 
> I think we only test 2, so we should introduce a test for 1 and make sure it works.

That seems like a design flaw.
Why would I have to import everything from a file or have to know every trait implementation for the type that I want?

**Comment by mohammadfawaz** [comment]
Edit 2: With https://github.com/FuelLabs/sway/pull/2034, @Braqzen's test builds with `use std::identity::Identity`. @sezna are you saying this is now against the spec? What do you recommend we do?
