### ISSUE TITLE
Add `std` & `core` libraries formatting job to CI

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2031]
# Summary

At the moment if you take a look at CI ([lib](https://github.com/FuelLabs/sway/blob/master/.github/workflows/ci.yml#L42) & [core](https://github.com/FuelLabs/sway/blob/master/.github/workflows/ci.yml#L24)) it appears that the code is run through the formatter.

I have just submitted a PR which I have first run through the formatter. 
It looked really strange so I have checked the `master` branch for the `standard library` and the formatting is clearly not being applied there (and perhaps `core` as well).

Resolution: change the CI path to make the formatter run on both the `core` and `std`.

**Comment by adlerjohn** [comment]
Note that the above-linked jobs do _not_ run the formatter on `std` or `core`, only build.

**Comment by eureka-cpu** [comment]
@mohammadfawaz you recently did this iirc?

**Comment by mohammadfawaz** [comment]
I think this is referring to running a format checker in CI for std and core. Basically this is a CI task.

**Comment by mohammadfawaz** [comment]
Closing this in favour of https://github.com/FuelLabs/sway/issues/2917. #2917 has the milestone field set so i don't want to mess with that :)
