### ISSUE TITLE
Decide on how we want to handle `Events`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2033]
At the moment, events are simple structs which are logged with the generic `log(...)` function in `std::logging`.
Moving forward, we will want to provide better support for events, such as a way to differentiate between events and low-level logs for downstream tooling.

**Comment by nfurfaro** [comment]
**From slack:**
@syd: 
"what do you think of adding an event.sw? I haven't thought it through completely but I find that emitting events is common and importing logging and having to define a structure myself is not ideal.
It would be nice to have some struct which takes in any field: value, perhaps via a vector, and unpacks that data into the event as field attributes.
The event struct would have a log method or perhaps emit or something so you could import event and pass in any data that you want to it and do something like var.log() or var.emit(). Idk about actually setting the field: values onto the struct dynamically though.
I think the compiler might need some work for that."

@nfurfaro:
"A few thoughts:
you would still need to import std::event , so no savings there. Perhaps if logging is part of a prelude this need to import will go away.
It seems like you would still need to do about the same amount of work?
In Solidity, we:
define an event :event MyEvent(…);
emit it: emit MyEvent(…);
Currently in Sway, we:
define our event struct: struct MyEvent{…};
emit it: log(MyEvent{…});
I’m ok with the current workflow, as I don’t see the added value of what you’re describing.
But I could be missing something here?"

**Comment by adlerjohn** [comment]
IMO, there's not really a distinction. Ethereum for example has logs == events, and so should we. Logs, despite the name, aren't meant for diagnostic purposes. They're meant to enable off-chain systems to follow along state changes. I.e. events.

**Comment by mohammadfawaz** [comment]
So are we okay with the `log` function as is? It allows logging any type and with https://github.com/FuelLabs/sway/pull/2689, the SDK will be able to decode the data properly so that we can emit something meaningful instead of just raw bytes.

If so, can this be closed?

**Comment by mohammadfawaz** [comment]
@nfurfaro another question about this.. Now that logs are emitted in the JSON ABI and parsed in the SDKs, I consider this feature complete. Can we close?
