### ISSUE TITLE
`contract_id` variable name and `call_frames` library function conflict

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#2036]
Using `std::context::call_frames::contract_id` and needing the value of a variable named `contract_id` is problematic. The current workaround is to not name anything `contract_id` when the `b256` value will be needed.

![contract_id_error](https://user-images.githubusercontent.com/54727135/174387993-0441553a-67e1-443d-a994-6987c6ce8dce.png)

Example Contract:

```
contract;

use std::{
    context::call_frames::contract_id,
    contract_id::ContractId,
};

abi MyContract {
    fn test_function(contract_id: ContractId);
    fn some_other_function();
}

abi ExternalContract {
    fn external_test_function();
}

impl MyContract for Contract {
    fn test_function(contract_id: ContractId) {
        let external_abi = abi(ExternalContract, contract_id.value); // Error
    }

    fn some_other_function() {
        let contract_val = contract_id().value;
    }
}
```

Example 2:
```
    fn test_function() {
        let contract_id = ~ContractId::from(BASE_ASSET_ID);
        let external_abi = abi(ExternalContract, contract_id.value); // Error

        let contract_val = contract_id().value;
    }
```

A possible solution would be to change the `contract_id()` function name in the `call_frames` library.

**Comment by mohammadfawaz** [comment]
@bitzoic if we change the name of the function from `contract_id()` to something else, we're still going to have the same problem if that new name is used for a local variable, right? What I mean is that this is an unsolvable problem and it feels that `contract_id()` is the right name for a function that returns the ID of a contract and it's on the user to avoid using a conflicting name. This is a common problem even in Rust, right? What are your thoughts on this?

**Comment by bitzoic** [comment]
Yes, I believe you are right. I'm going to go ahead and close this issue.
