### ISSUE TITLE
Code examples for struct and enums is in the wrong section

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#2046]
https://github.com/FuelLabs/sway/blob/2cbbfccb0b6d8b5276be05cc47dc71cdf6eeb890/docs/src/basics/methods_and_associated_functions.md?plain=1#L41-L65

Should be in the structs and enums page.

**Comment by mohammadfawaz** [comment]
This was addressed here: https://github.com/FuelLabs/sway/pull/2741
