### ISSUE TITLE
`new()` for `Vec<T>` requires type information

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2049]
Currently, we need to write: 
```rust
let vector = ~Vec::new::<u8>();
```
The type annotation `u8` has to be supplied to `new()`. The following, however, doesn't work:
```rust
let vector: Vec<u8> = ~Vec::new();
```
The second syntax is a bit more intuitive to users and should probably work.

**Comment by adlerjohn** [comment]
The second syntax should be possible, but I don't find it better since it requires the user to provide the type explicitly instead of using inference.

**Comment by mohammadfawaz** [comment]
They're equally suboptimal really. Ideally, the type would be inferred from the elements we're pushing into the vector.

**Comment by adlerjohn** [comment]
Can you file an issue for that?

**Comment by mohammadfawaz** [comment]
Done https://github.com/FuelLabs/sway/issues/2050
