### ISSUE TITLE
Incorrect `This code is unreachable` warning

### ISSUE THREAD

**Issue by vaivaswatha** [FuelLabs/sway#2054]
With #1948, we can call functions (that can be evaluated statically) when initializing constants. Unreachable code analysis is unaware of this and ends up throwing an incorrect warning.

```
script;

struct A {
   a : u64
}

fn foo(a : u64) -> A {
  A { a }
}

const B : A = foo(32);

fn main() -> u64 {
    B.a
}
```

produces:
```
 --> /home/vaivaswatha/c/working/sway2/src/main.sw:8:3
  |
6 | 
7 | fn foo(a : u64) -> A {
8 |   A { a }
  |   ------- This code is unreachable.
9 | }
  |
____

```

**Comment by mohammadfawaz** [comment]
Are the following issues related?
https://github.com/FuelLabs/sway/issues/705
https://github.com/FuelLabs/sway/issues/1914
https://github.com/FuelLabs/sway/issues/1258

**Comment by tritao** [comment]
They might be related, I can take a look once I get some cycles to look into this.
