### ISSUE TITLE
Fix bug in std::auth::get_coins_owner()

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2056]
The changes needed are:
1. a pre-check on the value of inputs_count:  i.e: `assert(inputs_count < 1);`
2. return a Result<AuthError::NoCoinInputs> from the code path where `inputs_count` is set to 1, but there are no `InputCoins`.
This leads to the while loop exiting, but `candidate` still being `Option::None`. Then, when trying to return a `Result::Ok` value the function will revert when unwrapping `candidate`.

Discovered by @emilyaherbert 
cc @adlerjohn

**Comment by adlerjohn** [comment]
> a pre-check on the value of inputs_count

This isn't really necessary, if the user is expected to do the check themselves beforehand. Would be duplicating the check.

> but there are no `InputCoins`

The consensus rules require that valid transactions must have at least one coin input. So that case should never be hit for valid transactions.

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-specs/pull/353 should be landed soon to avoid having to deal with offsets!
