### ISSUE TITLE
Remove the global `TypeEngine` and `DeclarationEngine` in favour of moving them into the `TypeCheckContext`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#2063]
As mentioned [here](https://github.com/FuelLabs/sway/pull/2004#pullrequestreview-1012828683), this is an important follow-up to #2004.

It should make it much easier to enable type-checking the same program multiple times within the same process. Currently this might be possible, but doing so will endlessly bloat the global arena as it's never cleaned up.

Accumulating the type state from the beginning of `TypedProgram::type_check` and returning it within the `TypedProgram` will allow us to take advantage of Rust's ownership semantics and leave its cleanup to RAII.

**Comment by emilyaherbert** [comment]
Note for the future: This issue requires some scaffolding with Rust, due to the heavy use of the `lazy_static` objects in the Rust standard traits like `PartialEq` and `Hash`. @canndrew demo'd great workaround on this separate PR here: #2627

**Comment by emilyaherbert** [comment]
@Centril one of the solutions to this problem is to add instrumentation to thread the `TypeEngine` and `DeclarationEngine` through all of the types that require them. But on the other hand, one of the ideas that I have been wanting to explore is to update the type system to remove `TypeId` and instead use references to types, so that we can compare them directly. Just food for thought 😄

**Comment by mitchmindtree** [comment]
Was doing a bit more profiling of the compiler today, and simple memory allocations are showing up a lot, particularly during typecheck.

It looks like one of the big culprits might be the global type engine. In particular, `look_up_type_id` (which `clone`s the inner `TypeInfo` rather than returning a reference) and wrappers around it are used _everywhere_, and each invocation can end up cloning multiple `Vec`s at a time depending on the underlying `TypeInfo` variant.

I started refactoring it before realising it would be a big job, then remembered _this_ issue is in progress anyway! @Centril just thought I'd share as a heads-up, I imagine it'll be a lot easier to work with references from the type/decl engines once we can wrangle the type and decl engines out of global memory :)

**Comment by mohammadfawaz** [comment]
The `TYPE_ENGINE` lazy static has been removed. The `DECLARATION_ENGINE` lazy static is being removed by @emilyaherbert
