### ISSUE TITLE
The test `e2e_vm_tests/test_programs/should_fail/excess_fn_arguments` is erroneously passing.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#2081]
While implementing a fix for #1580 this test was discovered to be failing because it didn't import `core` properly, and once that was fixed the compilation succeeds when it definitely shouldn't.

```rust
script;

fn bar(a: bool, b: u64) -> u64 {
  if a {
    b * 2
  } else {
    0
  }
}

fn main() -> u64 {
  bar(true, 0, true) // <--- an extra arg.
}
```

After fixing this issue the test must be reverted from currently passing back to failing.  See its `test.toml`.

**Comment by tritao** [comment]
This is happening because of the way typed argument checking is done in, which drops the extra arguments:

```rust
    let typed_call_arguments = arguments
        .into_iter()
        .zip(function_decl.parameters.iter())
```

Working on a fix.
