### ISSUE TITLE
Eq trait implementation bug

### ISSUE THREAD

**Issue by Rubyt0x** [FuelLabs/sway#2089]
```
impl core::ops::Eq for Players {
    fn eq(self, other: Self) -> bool {
        match(self, other) {
            (Players::PlayerOne(address1), Players::PlayerTwo(address2)) => {
                address1 == address2
            },
            (Players::PlayerTwo(address1), Players::PlayerOne(address2)) => {
                address1 == address2
            },
            _ => {
                false
            },
        }
    }
}
```

<img width="630" alt="image" src="https://user-images.githubusercontent.com/43066067/175131371-376b9963-860c-4290-ae9b-ba3c466c67ea.png">

**Comment by otrho** [comment]
This is specifically about matching `self` I think, which isn't supported yet.  I thought there might be another issue about this but I can't find it.

**Comment by Rubyt0x** [comment]
Any idea how to overcome this error before we actually support it?

**Comment by mohammadfawaz** [comment]
But this works: https://github.com/FuelLabs/sway/blob/91b8eee1208fc47efea607e8820ed08ca0028975/sway-lib-std/src/identity.sw#L15 🤔

**Comment by Rubyt0x** [comment]
Yeah that's what I used to write the above code

**Comment by otrho** [comment]
OK, so I just did a search for 'cannot yet compare this pattern with this type' and it's not in the source anywhere.  Do you have the latest compiler?  I see now that @emilyaherbert added a fix for this last week in #2009.

**Comment by emilyaherbert** [comment]
Matching on `self` _should be_ supported. ^ what @otrho said, are you on `master`?

**Comment by Rubyt0x** [comment]
I'm on forc 0.15.2 and on this branch (https://github.com/FuelLabs/sway-applications/tree/eureka-cpu/sway-tac-toe)

**Comment by otrho** [comment]
That's a couple of weeks old, so it won't have the latest fixes.  So this issue should be closed and in the future before creating new issues please make sure they're still reproducable with the latest `master` branch.
