### ISSUE TITLE
Add `ty` formatting to `sway-fmt-v2`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2101]
Currently, if we come across a `ty` during the formatting, we simply push its string version without any formatting. This can be seen in https://github.com/FuelLabs/sway/blob/a43aec0d3fb61b7ff7875ecd0259f055cf2a32e3/sway-fmt-v2/src/items/item_enum.rs#L66-L68

I think if we have a re-usable method for formatting `ty` that would come in handy since there are a couple of more places we will need the same logic (i.e, `storage` formatting).

### Possible motivations to format a `ty`:

I am not sure how we should be formatting `ty` but if we can create a list of the motivations that might be helpful while implementing this.

1. It might not fit the total line width.
2. ?

any thoughts @eureka-cpu?

--------
## TODO

- [ ] Address #2163 
- [ ] Address #2164 
- [ ] Address #2165 
- [ ] Address #2166 
- [ ] Address #2167

**Comment by eureka-cpu** [comment]
I think for now the line width can be tackled with `Shape` if we continue to use the `max_width` from `Formatter.config`. @mohammadfawaz has had some good input lately, do you have any ideas?

**Comment by eureka-cpu** [comment]
We should continue with this method and if issues arise from it, tackle them as they become apparent

**Comment by eureka-cpu** [comment]
impl Format for Ty {
    fn format(
        &self,
        formatted_code: &mut FormattedCode,
        formatter: &mut Formatter,
    ) -> Result<(), FormatterError> {
        match self {
            Self::Array(arr_descriptor) => { /* formatting... */ }
            Self::Infer { underscore_token } => { /* formatting... */ }
            Self::Path(path_ty) => { /* formatting... */ }
            Self::Str { str_token, length } => { /* formatting... */ }
            Self::Tuple(tup_descriptor) => { /* formatting... */ }
        }
        Ok(())
    }
}

**Comment by kayagokalp** [comment]
I created separate issues for each of the possible cases we need to address to handle `Ty` formatting as they might require other things first. This way if they end up needing something implemented first we can easily track that.
