### ISSUE TITLE
`forc fmt` creates illegal syntax with imports in some cases

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#2106]
When running `forc fmt` on the following imports, it will create an illegal syntax that will no longer compile nor format again. Example 1 can be recreated in the base init contract created by `forc init`. Example 2 was taken from the [English Auction](https://github.com/FuelLabs/sway-applications/blob/31f17fe4b72bd759b9b2b2877f5b13d54529899a/auctions/english-auction/src/main.sw#L13) Sway application and uses a custom library. 

Adding or removing any additional imports will result in the correct syntax for Example 1.

Example 1 Before:

`use std::{assert::assert, contract_id::ContractId, identity::Identity, option::Option, storage::StorageMap};`

Example 1 After:

```
stduse:: {
    assert::assert, contract_id::ContractId, identity::Identity, option::Option, storage::StorageMap
};
```

Example 2 Before:

`use utils::{approved_for_nft_transfer, owns_nft, send_tokens, sender_identity, transfer_nft, validate_asset};`

Example 2 After:

```
utiuse ls:: {
    approved_for_nft_transfer, owns_nft, send_tokens, sender_identity, transfer_nft, validate_asset
};
```

**Comment by eureka-cpu** [comment]
Thanks for the issue @bitzoic ! With the new formatter this will no longer be an issue, and we can expect it to be available within the next few weeks I think
