### ISSUE TITLE
Handle `break` and `continue` in `sway-lsp`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2117]
https://github.com/FuelLabs/sway/pull/2112/files introduces `break` and `continue` but doesn't do anything with them in `sway-lsp`.

**Comment by JoshuaBatty** [comment]
We can store these tokens as keywords in the language server. However, in order to do so, the `break` and `continue` variants in the `Declaration` enum need to have a `span` associated with them. Currently, no span data is reported.

**Comment by mohammadfawaz** [comment]
I can fix that @JoshuaBatty. I'll do that this week 😊

**Comment by JoshuaBatty** [comment]
Excellent, thanks @mohammadfawaz  :)

**Comment by JoshuaBatty** [comment]
related to #3369

**Comment by mohammadfawaz** [comment]
Anything left to do here? @JoshuaBatty

**Comment by JoshuaBatty** [comment]
Nothing left to do here. Happy to close this.
