### ISSUE TITLE
Problems with paths and dependencies

### ISSUE THREAD

**Issue by canndrew** [FuelLabs/sway#2125]
In my effort to design a [collection phase](https://github.com/FuelLabs/sway/issues/1819) for the compiler I've been trying to sort out exactly how dependencies and name-resolution work in sway. The current design has some issues with things being either broken or under-specified, in no particular order:

1) A package's transitive dependencies appear in the namespace while the package is being compiled. eg. If my `library` lists a dependency on `dependency_library` in its Forc.toml, and `depency_library` lists a dependency on `transitive_dependency_library` in its Forc.toml then `library` will be allowed to refer to `transitive_dependency_library` in its code. This breaks encapsulation by exposing the implementation details of `dependency_library` to `library`.

2) It's possible to have two dependencies which depend on two different transitive dependencies with the same name (but different file-system location). Rather than causing an error this currently makes the compiler very confused.

3) The name of a library, as specified in the `library name;` line of its root module, doesn't have to match the name specified in the package's Forc.toml. When the package is used as a dependency it seems that only the name given in Forc.toml is actually used. The other name is completely ignored - except that if it's omitted (eg. because the package is a script) then the compiler will crash.

4) Similarly but oppositely, the name of a submodule dependency given in a `dep some_submodule;` declaration doesn't have to match the name that the submodule gives itself. In this case the name that the submodule gives itself in its `library name;` line is used as the submodule's name whereas the name given in the `dep` declaration is only used to determine the file name.

5) Two submodules can have the name same but different file names. They can both be imported along-side each other, causing weird name-resolution issues.

6) A submodule of a package's root module can have the same name as a dependency without causing an error and with no way to disambiguate between them.

Given all of these above, these are the fixes that I'd like to see:

* A package's transitive dependencies should not be visible to that package. This fixes (1) and (2).

* `dep` declarations should be replaced with `mod` declarations a.la. rust. The name given in the declaration should act as the canonical name of the module and should also be used to find its source file/directory. This fixes (5).

* Rather than a source file specifying what type of program it is with a `script`/`library foo`/`contract`/`predicate` line this should be specified in Forc.toml. This fixes (3) and (4).

* To fix (6), we should decide on some concrete rules for how name resolution works - ie. how to refer to things from external libraries, from under the root of the current package, and from under the current module. We shouldn't repeat rust's mistakes of having to change the rules in a later edition, having the rules work differently between `use` statements and everywhere else, and having the syntax be ambiguous with special rules that are only invoked to resolve ambiguous edge-cases. My proposed rules are: paths beginning with `::` must be followed by the name of a library. You'd refer to `foo` in the std library by writing `::std::foo`, if you want to just write `std::foo` then you'd need to have a `use ::std` declaration in scope. You'd refer to `foo` under the root of the current package by writing `::name_of_this_package::foo`, not `::foo` (since `::foo` would refer to an external library named `foo`). Optionally, we could also allow `::self` to refer to the current package, similar to how rust uses `crate` for this purpose. Paths that don't start with `::` are always relative to the current module, making paths beginning with `self` unnecessary. Paths should work exactly the same in `use` declarations as they do everywhere else.

What are other people's thoughts on all this? @sezna, @otrho, @emilyaherbert, @mitchmindtree?

**Comment by otrho** [comment]
Yep, these are obviously issues which need to be resolved properly ASAP.  I think all your proposals sound great.
- Not sure why Sway uses `dep` instead of `mod`, @sezna can answer that.
- Putting `script` or `predicate` or `contract` or `library` in Forc.toml makes sense I think.  But only if the current `dep` -> `library` thing is dropped and replaced with a `mod` equivalent.  But that's what you're suggesting.
- So using `::crate` doesn't fit (Sway isn't Rust) but I don't really like `::self` much.  We could use `::pkg` or perhaps as you suggest only allow the explicit package name.

**Comment by mitchmindtree** [comment]
> A package's transitive dependencies should not be visible to that package. This fixes (1) and (2).

Good catch! I think this is just a bug in `forc-pkg`. I've opened #2136 which should address points 1 and 2.

I totally concur with everything else!
