### ISSUE TITLE
Document how to run all of the tests in `sway/test`.

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#2129]
It is currently difficult for new contributors to glean that they need to have `fuel-core` running in in-memory mode or with a fresh db, etc. We should have this process documented.

**Comment by anton-trunov** [comment]
Looks like this is documented in the Sway book here: https://fuellabs.github.io/sway/v0.24.5/reference/contributing_to_sway.html#building-and-testing

**Comment by mohammadfawaz** [comment]
I think https://github.com/FuelLabs/sway/issues/2961 + https://github.com/FuelLabs/sway/tree/master/test/src/sdk-harness cover everything we need here.
