### ISSUE TITLE
Repurpose `BASE_ASSET_ID` `b256` value as the zero value

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2131]
# Summary

There is an issue which wants to turn the `BASE_ASSET_ID` into a `ContractId` type. Ref: #2020 
This makes sense however that "zero address" is used beyond the contract type.

We should still have the following

```rust
const ZERO_B256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
```

**Comment by adlerjohn** [comment]
What purpose does a zero address serve? The base asset is used to pay tx fees, so it's special compared to other assets. That it has a value of zero is actually a detail.

**Comment by Braqzen** [comment]
> It wouldn't really be consistent because as above, the fact that the base asset has an ID of zero is a detail. We could have given it the ID `0xddec0e7e6a9a4a4e3e57d08d080d71a299c628a46bc609aab4627695679421ca` if we wanted to, and everything would work as it does now.
> 
> I would also argue that having a special zero address in the stdlib will encourage people to use it as an empty value instead of `Option::None`, which is undesirable.

Perhaps this issue should be edited to keep the zero address as it is instead of replacing it with the ContractId issue. That way people can import the constant and instantiate various types without needing to define the type themselves.

**Comment by Braqzen** [comment]
> > Or, close this issue and have that issue only add the base contract type while renaming the current base asset id to zero_address.
> 
> Better. I would suggest even naming it `ZERO_B256` since it's untyped.
> 
> An alternative would be to impl `b256::zero()`.

I don't know about that name for the untyped var and I really don't know about having to import the entire `b256` from `core::num` to get access to it (and consequently all of that module since we cannot explicitly import those).

**Comment by r-sitko** [comment]
So if you could sum up this discussion, do we need const ZERO_ADDRESS of type Address or something different or should we resign from adding this kind of constant?

**Comment by adlerjohn** [comment]
Can be implemented as

```rust
const ZERO_B256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
```
