### ISSUE TITLE
Struct & Enum formatting in `sway-fmt-v2` should take formatted length into account while deciding single line formatting

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2138]
Currently, to decide whether to format it into a single line or not, the formatter looks at the length of the unformatted enum/struct block. But it should actually get the length of the formatted (to a single line) version of that block and use it for deciding whether the single line construct would fit into the constraints we have for that line. Just like #2124 does it.

**Comment by eureka-cpu** [comment]
I think we could also move the `get_item_len` function into `item.rs` instead of having its own file

**Comment by kayagokalp** [comment]
I am planning to quickly tackle this after #2124 is merged.
