### ISSUE TITLE
Add a function to the std-lib to wrap the CALL opcode for low-level calls

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/sway#2144]
It would be useful to have a function in the std that wraps the low-level CALL opcode specified [here](https://github.com/FuelLabs/fuel-specs/blob/1be31f70c757d8390f74b9e1b3beb096620553eb/specs/vm/instruction_set.md#call-call-contract)

The function would be used to call external contracts not known at compile time.  For example, a proposal in a DAO voting contract.

The signature for such a function might look like `make_call(call_data: CallData, amount: u64, asset: ContractId, gas: u64)`

**Comment by sezna** [comment]
Hm, I'm not sure this is necessary. `CALL` requires a pointer to very specifically laid-out data. This will be difficult to implement in the standard library, but moreover, is already implemented within the compiler via `abi` casts.

If your objective is to use the `CALL` opcode on contracts not known at compile time, you can do something like this:
```rust
contract;
use std::contract::ContractId;

abi MyContract {
    fn test_function() -> bool;
}

fn caller(address: ContractId) -> ContractCaller<MyContract> {
  abi(MyContract, address.0)
}

fn foo() {
  let x = caller(0x000...);
  x.test_function();
}
```

Unfortunately, we have had a recent regression: #2341, so this is blocked right now, but this would be the correct way to do this behavior. 2341 is a critical bug so it should get addressed soon.

Would this work for your use case? If so, I think we should close this issue.

**Comment by matt-user** [comment]
Also if `abi` casts can handle this use case is it still worth it to implement issue #2331 ?

**Comment by matt-user** [comment]
This issue is no longer relevant once #2341 and #1261 and fixed

**Comment by simonr0204** [comment]
Reopening this as we have a path forward for low-level calls. The `bytes` type [here ](https://github.com/FuelLabs/sway/issues/3078) would allow the SDK to [encode ](https://github.com/FuelLabs/fuels-rs/issues/709) the calldata according to the ABI (known to the SDK but unknown to the calling contract). The calling contract would then just point to the function selector and these bytes and everything should justWorkTM.
