### ISSUE TITLE
Const evaluator fails when initializing a `const` with another `const`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2151]
Example:
```rust
script;

const ZERO_B256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
const KEY = ZERO_B256;

fn main() { }
```
Error:
```console
3 | const ZERO_B256 = 0x0000000000000000000000000000000000000000000000000000000000000000;
4 | const KEY = ZERO_B256;
  |             ^^^^^^^^^ Could not evaluate initializer to a const declaration.
```

cc @vaivaswatha

**Comment by vaivaswatha** [comment]
This seems to be related to the order in which `const` declarations are processed. Renaming `ZERO_B256` to `AERO_B256` gets it compiled fine. `get_all_declared_symbols()`, on whose results `compile_constant_expression` is called, stores an ordered (by name) list of symbols and returns that, not based on actual dependences.

**Comment by otrho** [comment]
Are these not ordered properly by the `order_ast_nodes_by_dependency()`?  Sounds like a bug!

**Comment by vaivaswatha** [comment]
> Are these not ordered properly by the `order_ast_nodes_by_dependency()`? Sounds like a bug!

That's done when type-checking. This is afterwards, when compiling to the IR.

**Comment by otrho** [comment]
Hrmm, so why is this specifically a new problem?

We have a typed AST which we're trying to compile to IR.  The current method will start with 'main' or contract entry points and recursively compile nodes as they're needed.

Is it that until now, function declarations and traits, etc. have been embedded/inlined into the AST and so finding them has been straight forward, and type declarations like structs and enums are just recompiled each time they're used..?  But now with top-level `const` declarations depending on each other there isn't a direct link between them in the AST already, and they aren't found unless they've already been compiled?

**Comment by vaivaswatha** [comment]
> Hrmm, so why is this specifically a new problem?

It's a new problem only because until now we didn't allow a global (top level) `const` declaration to depend on anything else (the RHS had to be a literal).

>But now with top-level const declarations depending on each other there isn't a direct link between them in the AST already, and they aren't found unless they've already been compiled?

That's right. `const_eval`, when it tries to evaluate an initializer looks up `get_global_constant`, and in this case doesn't find it because of the order not being right.
