### ISSUE TITLE
Consider making `Not` a trait.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2152]
Currently, it is not a trait, but the comment below suggests we should consider it.

ref: https://github.com/FuelLabs/sway/blob/1a64db984992e6700b3c3c558fdb2b22239d88fd/sway-lib-core/src/ops.sw#L368

Also relevant to the discussion here: 
ref: #2147
as we want to implement `not` for unsigned integers (and probably `b256`s as well).

**Comment by Braqzen** [comment]
Just a helpful tip. If you select the entire area and then click the `...` followed by `Copy permalink` then you can fetch the entire section instead just 1 line

https://github.com/FuelLabs/sway/blob/1a64db984992e6700b3c3c558fdb2b22239d88fd/sway-lib-core/src/ops.sw#L368-L376

![1](https://user-images.githubusercontent.com/103777923/176284034-df14c86f-3ec1-4038-b40c-6fcdf4e83f26.png)

**Comment by adlerjohn** [comment]
Does this require compiler support?

**Comment by nfurfaro** [comment]
It _looks_ like this is a simple addition to `core` from what I see. I'm in favor of doing it.

**Comment by otrho** [comment]
If you want the `!` operator to perform bitwise negation, which [apparently it does in Rust](https://doc.rust-lang.org/stable/std/ops/trait.Not.html#tymethod.not), then we would need to implement `not` for each of the built-in types (#2147 and #2148), in which case it might as well be a trait.

The parser automatically converts the `!` token to `core::ops::not` already, so it should only be a change to the lib, I think.

**Comment by mohammadfawaz** [comment]
> The parser automatically converts the ! token to core::ops::not already, so it should only be a change to the lib, I think.

Yes exactly. However, if we introduce a `Not` trait, then the `not()` call becomes a method call instead of a free function application so that handling in the parser probably needs to change. (i.e. instead of `!x` becoming `not(x)`, it becomes x.not()`, and this is strictly in the parser before any type checking... the compiler will later know what `not()` to call based on the type as if the user wrote `x.not()`).

**Comment by nfurfaro** [comment]
@mohammadfawaz Sounds good, I can take this on.

**Comment by mohammadfawaz** [comment]
@rostyslavtyshko addressed this in https://github.com/FuelLabs/sway/pull/2909.
