### ISSUE TITLE
methods in a impl block can't see each other?

### ISSUE THREAD

**Issue by XFFXFF** [FuelLabs/sway#2157]
```rust
script;

struct Foo {}

impl Foo {
    fn bar(self) {}
    fn baz(self) {
        self.bar();
          // ^^^ No method named "bar" found for type "Foo".
    }
}
```
The above example fails to compile, showing `No method named "bar" found for type "Foo"`. Not sure if this is a bug or we don't currently support this

**Comment by otrho** [comment]
Yep, this is a known issue: #1548, #870 and is unfortunately blocked for now until we refactor the compiler to use a declaration engine : #1692.

I think it's implied but not really spelled out in the book: https://fuellabs.github.io/sway/v0.16.2/reference/known_issues_and_workarounds.html  Maybe we should be more explicit.

**Comment by XFFXFF** [comment]
Thanks! I see.
feel free to close this issue
