### ISSUE TITLE
Implement tests for `SMO` and `TRO` opcodes once `fuel-core` supports them

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2202]
## Summary
Currently `fuel-core` does not support `SMO` and `TRO` opcodes therefore tests cannot be written for them.
The `TRO` opcode has a test but it is simply `disabled` while #2176 makes sure that it only compiles.

## Resolution
Those opcodes need to be tested once `core` supports them.

**Comment by adlerjohn** [comment]
`fuel-core` supports `TRO` already. But even then, it's non-trivial to test in the Sway testing harness because it involves dealing with the transaction. It's much easier to test in the SDK repo (which I think it is) and of course in `fuel-core` itself.

**Comment by mohammadfawaz** [comment]
We already have `transfer_to_output` in the standard library and it's well tested. So, `tro` is indirectly being tested:
https://github.com/FuelLabs/sway/blob/8889ba032182fee96ec730e1fe173164708b9987/sway-lib-std/src/token.sw#L115

**Comment by nfurfaro** [comment]
Yes, the approach I took when adding `tro` was the add a simple test to show that it compiles (via an asm block), and the immediately added the stdlib function wrapper for the opcode and then add some real tests via the SDK. 
I think this is acceptable for some of these opcode that have non-trivial testent requirements.
They end up being tested in the VM (I'm guessing here) and the stdlib, but not so much directly in the compiler.

**Comment by Braqzen** [comment]
> Yes, the approach I took when adding `tro` was to add a simple test to show that it compiles (via an asm block), and then immediately add the stdlib wrapper function for the opcode and then add some real tests via the SDK. I think this is acceptable for some of these opcode that have non-trivial testing requirements. They end up being tested in the VM (I'm guessing here) and the stdlib, but not so much directly in the compiler.
> 
> If having a short lapse in testing of the `smo` opcode is unacceptable (i.e: the time between adding the opcode and adding the stdlib function with tests), you could just add some SDK tests along with your `smo` opcode PR, and then refactor them to use the stdlib function when it lands.

Thread continues from [here](https://github.com/FuelLabs/sway/pull/2178#issuecomment-1172750337)

**Comment by nfurfaro** [comment]
Closing as these opcodes are now supported in `fuel-core`
