### ISSUE TITLE
Swap order of operands for `std::mem::copy`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#2203]
https://github.com/FuelLabs/sway/blob/850e0de4434d412f458692760fd0de019ed03687/sway-lib-std/src/mem.sw#L18

Rust's `std::ptr::copy` uses source then dest, instead of the more C-link dest then source. https://doc.rust-lang.org/std/ptr/fn.copy.html

**Comment by adlerjohn** [comment]
cc @otrho @AlicanC

**Comment by AlicanC** [comment]
I'm all for following Rust here which was always my intention. I probably just missed this.

I can make the change if there are no objections.

**Comment by AlicanC** [comment]
Note: This was initially an intrinsic so I was copying `std::intrinsics::copy`, but that's src-first too: https://doc.rust-lang.org/std/intrinsics/fn.copy.html
