### ISSUE TITLE
Forbid the use of storage variables without initializers

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2238]
Refer to the discussion in https://github.com/FuelLabs/sway/pull/2222

Currently, all storage slots are initialized to zero in the VM but zero is not always the _desired default_ initializer for a given type. Zero initializers may be desired for integers and booleans but are certainly not desired for enums. `Option<T>` is a good example where the default value should be `None` but `Option::None` is not necessarily stored as zeros (it is in fact _not_ stored as zeros because the tag for `None` is 1). 

We don't currently have a way to specify default values for particular types like Rust:
```rust
impl<T> const Default for Option<T> {
    /// Returns [`None`][Option::None].
    ///
    /// # Examples
    ///
    /// ```
    /// let opt: Option<u32> = Option::default();
    /// assert!(opt.is_none());
    /// ```
    #[inline]
    fn default() -> Option<T> {
        None
    }
}
```
In the absence of the above, we can start by forcing all storage variables to have initializers. In fact, this would be consistent with the behavior of local variables today where the following does not compile because it expects an `=` after `x: u64`.
```rust
fn main() {
    let mut x: u64;
}
```
Once we have the ability to initialize variables (local and in storage) implicitly using `default()`, we can then allow such variables to be declared without explicit initializers.

**Comment by Braqzen** [comment]
StorageMap will be fun

**Comment by mohammadfawaz** [comment]
So that's indeed a drawback. This will work:
```
storage {
    map: StorageMap<u64, u64> = StorageMap { },
}
```
