### ISSUE TITLE
Fix Forc lockfiles that point to github

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#2239]
Instances such as

https://github.com/FuelLabs/sway/blob/9ebdf6cae8ff0c2153c2995ab6ce57c5a7ae4dd3/test/src/e2e_vm_tests/test_programs/should_pass/language/xos_opcode/Forc.lock#L3

**Comment by mohammadfawaz** [comment]
This test has been removed because the `xos` opcode is gone. Closing.
