### ISSUE TITLE
Sanity check for the intermediate assembly

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2272]
It is possible that the intermediate assembly generated uses registers that are not assigned. This showed up several times in the past and usually points to an actual functional bug. We should probably introduce a sanity check after generating intermediate assembly (before running the register allocator) to make sure that this pattern does not arise. We can emit an internal compiler error in that case which would help us easily detect that something is wrong and tell us where to look.

**Comment by otrho** [comment]
Oh wow, I didn't know this happened in the intermediate ASM.  A check here would be easy and very valuable. :+1:
