### ISSUE TITLE
Calling `std::mem::addr_of` on a copy type should not be a runtime panic

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2281]
Example:
```rust
let number0 = 1u8;
let xyz = std::mem::addr_of(number0);
```
currently panics. It's better to emit a compile-time error instead given that we know the type of `number0` at compile-time.

**Comment by mohammadfawaz** [comment]
Ah yes what I meant is that `forc run` reverts, not `forc build`. The same code runs without issues if `number0` is a `b256`  (or any reference type).

**Comment by vaivaswatha** [comment]
> Ah yes what I meant is that `forc run` reverts, not `forc build`. The same code runs without any issues if `number0` is a `b256` (or any reference type).

Ah got it. Thanks.

**Comment by vaivaswatha** [comment]
`addr_of` is implemented as below in `mem.sw`. I see two ways to achieve what this Issue requires:

1. We provide an `__addr_of` intrinsic and during type checking detect copy-types and throw the error.
2. Provide something like C++'s `static_assert` (rust has a crate that provides similar functionality) and use that in the below implementation. I vote for this.
3. We could just detect, in the compiler, using the path `std::mem::addr_of` and check if the argument type is acceptable. Simple, but IMO not neat.

What do you suggest?

```
/// Returns the address of the given value.
pub fn addr_of<T>(val: T) -> u64 {
    if !__is_reference_type::<T>() {
        revert(0);
    }
    asm(ptr: val) {
        ptr: u64
    }
}
```

**Comment by otrho** [comment]
`static_assert` sounds good, but how would it work?  The above code would have?
```rust
 static_assert(__is_reference_type::<T>())
```

This would require compile time evaluation of `__is_reference_type` which isn't the hardest thing, but we then need to categorise it as `constexpr`, to use C++ terminology.  Sway devs may want to use `static_assert` but they need to be able to know exactly what expressions can be passed to it.

So to me it's probably the nicest solution but also a lot of work and probably not worth it.

The Rust `static_assertions` crate just has very specific macros, like `assert_eq_size`.  We could do the same, although Sway doesn't have macros, so it'd have to be an intrinsic anyway.

So I think we either just accept that this sort of check is a runtime check which reverts, or we introduce a new intrinsic for it.

**Comment by vaivaswatha** [comment]
>but we then need to categorise it as `constexpr`, to use C++ terminology. Sway devs may want to use `static_assert` but they need to be able to know exactly what expressions can be passed to it.

We need to do that for `const` initializers as well, but we don't (yet). So we could handle this the same way. As long as the compiler (whatever it's state on the day) can evaluate the argument to a constant, we compile it. Otherwise we say "can't evaluate" and not compile it. "what can be evaluated" will improve over time, until we define what exactly can constitute a `constexpr`.

**Comment by vaivaswatha** [comment]
But I do agree with you that the `static_assert` route is more complicated and we could just introduce a new intrinsic.

**Comment by mohammadfawaz** [comment]
An intrinsic sounds reasonable to me.
