### ISSUE TITLE
no sig mathod for msg function

### ISSUE THREAD

**Issue by ankitsaini9** [FuelLabs/sway#2284]
sway doesn't have msg_sign function which return The first four bytes of the calldata for a function that specifies the function to be called.

**Comment by adlerjohn** [comment]
Hint for implementer: `param1` in the call frame is where the first parameter to `CALL` (the function selector, by convention), is placed: https://github.com/FuelLabs/fuel-specs/blob/0f22d6257ba5ee631559bbad21fc679711de95ea/specs/vm/main.md?plain=1#L149

**Comment by mohammadfawaz** [comment]
> Hint for implementer: `param1` in the call frame is where the first parameter to `CALL` (the function selector, by convention), is placed: https://github.com/FuelLabs/fuel-specs/blob/0f22d6257ba5ee631559bbad21fc679711de95ea/specs/vm/main.md?plain=1#L149

I believe `lw $result $fp i73` is the way to do it.

**Comment by adlerjohn** [comment]
@matt-user noticed that https://github.com/FuelLabs/sway/blob/f588d8a078f1d6d0689123fcea6c147c1b4c5ca1/sway-lib-std/src/context/call_frames.sw#L46 actually returns the function selector, it's just not documented. Suggest resolving this issue by simply documenting that function.

**Comment by adlerjohn** [comment]
Correction: the above does return a pointer actually, instead of the actual value. It should be fixed to return the value with https://github.com/FuelLabs/sway/blob/f588d8a078f1d6d0689123fcea6c147c1b4c5ca1/sway-lib-std/src/mem.sw#L33
