### ISSUE TITLE
Panic while displaying a compile error related to unavailable struct field

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2297]
The following fails to compile with a panic:
```rust
script;

struct Data<T> {
    value: T
}

impl<T> Data<T> {
  fn new(value: T) -> Data<T> {
    // this ↓↓↓↓↓
    Data {
        val // val is not a data member so this should be a compile error
    }
  }
}

fn main() -> bool {
    false
}
```
Panic:
```
thread 'main' panicked at 'SourceAnnotation range `(33, 57)` is bigger than source length `53`', /Users/mohammad/.cargo/registry/src/github.com-1ecc6299db9ec823/annotate-snippets-0.9.1/src/display_list/from_snippet.rs:286:9
```
We're likely generating an error but not actually printing it correctly.
Note that replacing `val` with `value` does work and compiles as expected.

**Comment by vaivaswatha** [comment]
I see this error out gracefully, no panic.

<pre><font color="#F66151"><b>error</b></font>
  <font color="#2A7BDE"><b>--&gt;</b></font> /home/vaivaswatha/c/working/sway1/src/main.sw:9:5
<font color="#2A7BDE"><b>   |</b></font>
<font color="#2A7BDE"><b> 7 |</b></font>   
<font color="#2A7BDE"><b> 8 |</b></font>     fn new(value: T) -&gt; Data&lt;T&gt; {
<font color="#2A7BDE"><b> 9 |</b></font>       Data {
<font color="#2A7BDE"><b>   |</b></font>  <font color="#F66151"><b>_____^</b></font>
<font color="#2A7BDE"><b>10 |</b></font> <font color="#F66151"><b>|</b></font>         val // val is not a data member so this should be a compile error
<font color="#2A7BDE"><b>11 |</b></font> <font color="#F66151"><b>|</b></font>     }
<font color="#2A7BDE"><b>   |</b></font> <font color="#F66151"><b>|_____^</b></font> <font color="#F66151"><b>Initialization of struct &quot;Data&quot; is missing field &quot;value&quot;.</b></font>
<font color="#2A7BDE"><b>12 |</b></font>     }
<font color="#2A7BDE"><b>13 |</b></font>   }
<font color="#2A7BDE"><b>   |</b></font>
____

<font color="#F66151"><b>error</b></font>
  <font color="#2A7BDE"><b>--&gt;</b></font> /home/vaivaswatha/c/working/sway1/src/main.sw:10:9
<font color="#2A7BDE"><b>   |</b></font>
<font color="#2A7BDE"><b> 8 |</b></font> 
<font color="#2A7BDE"><b> 9 |</b></font>     Data {
<font color="#2A7BDE"><b>10 |</b></font>         val // val is not a data member so this should be a compile error
<font color="#2A7BDE"><b>   |</b></font><font color="#F66151"><b>         ^^^</b></font> <font color="#F66151"><b>Struct &quot;Data&quot; does not have field &quot;val&quot;.</b></font>
<font color="#2A7BDE"><b>11 |</b></font>     }
<font color="#2A7BDE"><b>12 |</b></font>   }
<font color="#2A7BDE"><b>   |</b></font>
____
</pre>

**Comment by mohammadfawaz** [comment]
Hmmmm interesting... I'm actually still getting a panic with latest `master`. However, when I delete the comment:
```
    // this ↓↓↓↓↓
```
I get the same errors you're getting. So I'm assuming this is related to: https://github.com/FuelLabs/sway/pull/2267... there maybe some more work to be done along those lines.

**Comment by vaivaswatha** [comment]
I can confirm. I deleted that comment as I my editor displayed it with escaped bytes (and I didn't expect that to be relevant).

**Comment by otrho** [comment]
So this is a self fulfilling bug?  The act of pointing out a panic in a comment actually causes the panic.  Bit of a paradox!  :grin:
