### ISSUE TITLE
Change `--verbose` flag behaviour to increase the level of verbosity within the logger

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#2305]
Currently as of #2244 we handle the `--verbose` flag by manually checking the `command.verbose` condition before outputting certain content via `info!`.

Instead, we should switch back to using `debug!`, but have the `--verbose` flag increase the log level. E.g. if the default is `info!`, using `--verbose` would increase it to `debug!`.

This will allows us to avoid checking a `command.verbose` condition everywhere, and allow us to take advantage of the existing logging support in supporting `--verbose`.

**Comment by mitchmindtree** [comment]
For future reference, I've elaborated a little further on what the implementation for this might involve in [this comment](https://github.com/FuelLabs/sway/pull/2308#pullrequestreview-1036769377).

**Comment by sdankel** [comment]
> but have the --verbose flag increase the log level. E.g. if the default is info!, using --verbose would increase it to debug!

I wonder if it would be better to have `--verbose`/ mean the same thing across all systems (DEBUG level) and have a `-vv` option for the most verbosity (TRACE level). It *looks* like that's how cargo's `--verbose` and `-vv` work. If users want to target a level other than DEBUG/TRACE they can set `RUST_LOG`.

**Comment by mitchmindtree** [comment]
Yeah I think that sounds good, I suggested something similar in [the linked comment](https://github.com/FuelLabs/sway/pull/2308#pullrequestreview-1036769377), but clarifying that `-v` could be DEBUG and `-vv` could be TRACE sounds good!
