### ISSUE TITLE
Add support in CLion for using `sway-lsp`

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#2306]
I'm not sure what's involved but there might be a way to add a syntax file to CLion similar to what we have in the VSCode plugin [here](https://github.com/FuelLabs/sway-vscode-plugin/blob/master/syntaxes/sway.tmLanguage.json) that allows for syntax highlighting rules to be defined.

**Comment by adlerjohn** [comment]
Is it possible for the LSP server to provide enough info that IDEs can use for syntax highlighting, instead of requiring a different syntax file per IDE?

**Comment by JoshuaBatty** [comment]
Yeah it may be possible. I'll download CLion and start having a play around. It does seem like quite a lot of devs prefer IntelliJ IDE's so it would be good to support them.

**Comment by JoshuaBatty** [comment]
Reading [this post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001627960-IntelliJ-support-for-Language-Server-Protocol-as-a-client-) and although there is no official support for LSP in any IntelliJ IDE, the official recommendation from them is to "use [https://github.com/ballerina-platform/lsp4intellij](https://github.com/ballerina-platform/lsp4intellij) to adapt your LSP server to an IntelliJ plugin with minimum extra effort"

Will see what's involved with getting it working.

**Comment by sdankel** [comment]
It doesn't look like it's possible to use `lsp4intellij` with CLion without adding a gradle/maven/sbt build file to the sway project

**Comment by sdankel** [comment]
It's possible to get rust-based syntax highlighting, hover docs, and go-to definition working for sway files by doing the following.

1. Install the Rust plugin in CLion

Under Settings -> Plugins, search for "Rust", install, and apply.

2. Create a file type association for .sw files

a. Navigate to Settings -> Editor ->  File Types
b. Select "Rust files"
c. Under "File name patters" click the plus sign and add `*.sw`
d. Click Apply

![Image](https://user-images.githubusercontent.com/47993817/224190776-9d51a418-5c1c-49ba-a2f2-72281ea694f2.png)
