### ISSUE TITLE
Potential regression in `if let` and introspection for `method().method()`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2322]
## Summary

```rust
contract;

use std::{
    address::Address,
    chain::auth::msg_sender,
    identity::Identity,
    result::Result,
};

abi MyContract {
    fn test();
}

impl MyContract for Contract {
    fn test() {
        let sender = msg_sender().unwrap();
        if let Identity::Address(addr) = sender {
            let lalala = addr.into();
        }
    }
}
```

1. I need to import `Result` for the `sender` line to pick up on `.unwrap()`. I thought this was the issue that was resolved for introspection so that e.g. `some_func().struct_field` could work, likewise I'm pretty sure that this worked before on chained method calls
2. The `lalala` line does not find `addr` (and I also need to import `Address` for the `.into()`)

cc @FuelLabs/sway-compiler

**Comment by mohammadfawaz** [comment]
As (2) has now been fixed in https://github.com/FuelLabs/sway/pull/2344, and (1) is a dup of https://github.com/FuelLabs/sway/pull/2344, I am going to close this issue and copy the example above into #2344.
