### ISSUE TITLE
Create an `int_to_ptr` IR instruction

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2324]
Roughly similar to https://llvm.org/docs/LangRef.html#inttoptr-to-instruction. The goal is to be able to interpret a `u64` value in IR as a pointer. That allows us to do the equivalent of the following cast:
```rust
asm(x: u64) {
    x: b256
}
```
in IR.

**Comment by otrho** [comment]
Off the top of my head, wouldn't it be pretty much like `get_ptr`? It's an instruction which still returns a `Value`, but it's a pointer.  I guess there's other places where we assume a pointer value is a `get_ptr` but now it could be an `int_to_ptr` too?
