### ISSUE TITLE
StorageInitializers are not (correctly) added to the formatted output

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2339]
After #2279, we still have some room for improvements / couple more problems regarding storage initializers formatting as they are not added in `test_storage_single_line` and `test_storage_with_alignment`. Since this blocks #2311's tests, I pushed a quick fix for this to there  (https://github.com/FuelLabs/sway/pull/2311/commits/f2a3ab10b5210979926c3acc3b1789fa3ed727ba). But we should have a separate clean look to this as currently formatter, does not produce good-looking results (it can even produce formatted code that will result in compile errors). Examples can be seen in the tests themselves at the commit. 

I can take a look at this after #2311 is done, or if anyone wants to dive a little deeper into initializer formatting stuff we can use this issue to track progress.

**Comment by sezna** [comment]
Since initializers are just expressions, it is probably reasonable to pick this up after #2338 goes in.

**Comment by eureka-cpu** [comment]
#2338 did end up closing this
