### ISSUE TITLE
Comment lexing misses trailing `/` for multi-line comments

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2355]
Comment lexing works perfectly while the comments are single-line comments like the following:

```
// This is a comment
```

but if the comments are in the form of multiline we are missing the trailing `/` in the comment's span. So for this example:

```
/*This is a comment*/
```

`.span().as_str()` returns  `/*This is a comment*`

I feel like this shouldn't be hard to tackle so added the "good first issue" label but I did not touch lexer enough to be sure about that so please remove it if that is not the case 🙌 . 

Depending on the discussion at https://github.com/FuelLabs/sway/pull/2311#discussion_r926167383 I can either fix it in #2311 or take a look at this after that is merged.

Related to https://github.com/FuelLabs/sway/pull/2311#discussion_r926167383

**Comment by mitchmindtree** [comment]
I'll address this now :+1:
