### ISSUE TITLE
Lexer misses the last comment after a const declaration

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2356]
`lex_commented()` does not pick up `// This is a comment next to a const` with the following example:

```rust
contract;

const /* TEST: blah blah tests */ TEST: u16 = 10; // This is a comment next to a const
```
I believe this example is a valid sway program so while lexing we should include the last comment to the token stream.

I do suspect this happens not just after `const` but after the last semicolon in the source file (if there is no encapsulating braces etc). (Need to test this feeling and if that is the case I will update the title)

Realized while testing #2311

**Comment by mohammadfawaz** [comment]
I'm assuming the fix for this issue is purely in `sway-parse` right? I'm going to add the `P: critical` label and remove the `formatter` label. Please let me know if you disagree.

**Comment by AlicanC** [comment]
Fixed in https://github.com/FuelLabs/sway/pull/2516 as a side effect.
