### ISSUE TITLE
StructExpression Ident's differ between AstNode and TypedAstNode

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#2372]
Given the following small example: 

```
struct X{}

fn main() {
  let var = X{};
}
```

If we inspect the `Ident` of our `let` expression as an `AstNode` we get.

```
name: Ident {
    name_override_opt: None,
    span: Span {
        src (ptr): 0x000000012a64ea90,
        path: Some(
            "/Users/joshuabatty/Documents/rust/fuel/sway/sway-lsp/test_programs/array_basics/src/main.sw",
        ),
        start: 45,
        end: 46,
        as_str(): "X",
    },
    is_raw_ident: false,
},
```

And if we inspect this line as a `TypedAstNode` we can see the `Ident` is actually pointing to the struct declaration and the `Span` information of the token has been discarded. 

```
struct_name: Ident {
    name_override_opt: None,
    span: Span {
        src (ptr): 0x0000000121ed1f70,
        path: Some(
            "/Users/joshuabatty/Documents/rust/fuel/sway/sway-lsp/test_programs/array_basics/src/main.sw",
        ),
        start: 16,
        end: 17,
        as_str(): "X",
    },
    is_raw_ident: false,
},
```

We need to carry forward the original `Span` information during type checking as this is required for the language server.

**Comment by otrho** [comment]
What if `Span` didn't have the source and only had the (non-optional) path?  I'm guessing you'd then have to maintain your own cache of source strings based on the paths, yeah?

I've never been a fan of the source + start + end spans that we have, their consistency is not enforced.  We are able to concoct them out of strings, give them random start and end values, do whatever we did to cause the above problem for this issue.

As far as the IR goes (and I imagine this would apply to other tooling) I'd rather just have a path and indices.  If the path doesn't point to a file (any more) then too bad, no span for you, oh well.

(This comes up every few weeks and I have this whinge and nothing much comes of it, from me or others, but I might as well go again... :wink:)

**Comment by JoshuaBatty** [comment]
> What if `Span` didn't have the source and only had the (non-optional) path? I'm guessing you'd then have to maintain your own cache of source strings based on the paths, yeah?
> 
> I've never been a fan of the source + start + end spans that we have, their consistency is not enforced. We are able to concoct them out of strings, give them random start and end values, do whatever we did to cause the above problem for this issue.

Sure, that sounds reasonable. I'm not using the `src` field for anything in the language server so can't really comment on their usefulness (or not). 

This issue above is that the `start` and `end ` fields of the `Ident` are coming from the `TypedStructDeclaration`, in this case: `start: 16` & `end: 17`. Where they originally are `start: 45` and `end: 46`. 
```
TypedStructDeclaration {
    name: Ident {
        name_override_opt: None,
        span: Span {
            src (ptr): 0x0000000121ed1f70,
            path: Some(
                "/Users/joshuabatty/Documents/rust/fuel/sway/sway-lsp/test_programs/array_basics/src/main.sw",
            ),
            start: 16,
            end: 17,
            as_str(): "X",
        },
        is_raw_ident: false,
    },
    ..,
},
```

I'm not sure why the local `Ident` is being replaced by the `Ident in the `TypedStructDeclaration` but we need to carry the local `Ident` information forward.

**Comment by otrho** [comment]
Actually, yeah, take the `Span` out of `Ident` altogether here, IMO.  But that mightn't change anything here if a whole new Ident is getting created for some reason.

**Comment by JoshuaBatty** [comment]
It looks like the `Ident` of the declaration is coming from [this line](https://github.com/FuelLabs/sway/blob/02b7e94eb1821c6f57203b1faf96bc8da369452d/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs#L958) 

The correct `Span` can actually be found like this though. `call_path_binding.inner.suffix.1`

just tagging @emilyaherbert for any comment / insight on this?
