### ISSUE TITLE
Repeated function or method argument name does not cause a compile error

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2392]
Example:
```rust
contract;

fn foo(x: u64, x: u64) {

}

abi MyContract {
    fn test_function(x: u64, x: u64) -> bool;
}

impl MyContract for Contract {
    fn test_function(x: u64, x: u64) -> bool {
        true
    }
}
```
I expect both `foo` and `test_function` not to compile but they do.

**Comment by otrho** [comment]
Curious!  Have you tested what actually happens?  Is the second one shadowing the first one?

**Comment by mohammadfawaz** [comment]
The behavior is quite weird actually. For example, the following returns 1:
```
script;

fn foo(x: u64, x: u64) -> u64 {
    x
}

fn main() -> u64 {
    foo(1, 2)
}
```
but when I try to change the type of the second `x` to `bool`, I get type checking errors. Same if I switch the types around. 

The code below actually gave me an ICE from the IR verifier:
```rust
script;

fn foo(x: bool, x: u64) -> u64 {
    x
}

fn main() -> u64 {
    foo(true, 2)
}
```
