### ISSUE TITLE
Internal compiler error: Attempted to construct return path error but no source span was found

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2401]
## Summary

The while loop seems to be causing an ICE for the vector. 
It might also occur for other types. 
If the return type is omitted and the while loop is removed then a sensible message stating that a return type is expected is presented to the user.

```rust
contract;

use std::vec::Vec;

abi MyContract {
    fn test_function() -> Vec<u64>;
}

impl MyContract for Contract {
    fn test_function() -> Vec<u64> {
        let mut my_vec = ~Vec::new();
        let mut count = 0;

        while count < 10 {
            my_vec.push(1);
            count += 1;
        }
    }
}
```

## Error
![1](https://user-images.githubusercontent.com/103777923/181457551-ef775871-c18a-4bcb-9407-8d2b1b1a051b.png)

cc @FuelLabs/sway-compiler

**Comment by otrho** [comment]
It's not `Vec`specific, though it might be `while` specific.  I managed to pare the repro down to this:
```rust
impl MyContract for Contract {
    fn test_function() -> u64 {
        while true {
            true;
        }
    }
}
```

If the `while` loop has no body then it returns a different ICE, from the IR verifier:
```rust
impl MyContract for Contract {
    fn test_function() -> u64 {
        while true {
        }
    }
}
```
```
error: Internal compiler error: Verification failed: Function test_function return type must match its RET instructions.
Please file an issue on the repository and include the code that triggered this error.
```
