### ISSUE TITLE
bug: ABI with string array input & output returns a Panic receipt 

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/sway#2410]
Not sure this is 100% a Sway issue - 

Given the contract below. When I interacted with via the TS SDK  the function`take_array_string_return_single_element` returns a panic receipt.  [See here.](https://github.com/FuelLabs/fuels-ts/pull/419).  

```sway
contract;

abi TestContract {
    fn take_array_string_shuffle(a: [str[3];3]) -> [str[3];3];
    fn take_array_string_return_single(a: [str[3];3]) -> [str[3];1];
    fn take_array_string_return_single_element(a: [str[3];3]) -> str[3];
    fn take_array_number(a: [u64;3]) -> u64;
    fn take_array_boolean(a: [bool;3]) -> bool;
}

impl TestContract for Contract {
    fn take_array_string_shuffle(a: [str[3]; 3]) -> [str[3];3] {
        [a[2], a[0], a[1]]
    }
    fn take_array_string_return_single(a: [str[3]; 3]) -> [str[3]; 1] {
        [a[0]]
    }
    fn take_array_string_return_single_element(a: [str[3]; 3]) -> str[3] {
        a[0]
    }
    fn take_array_number(a: [u64;3]) -> u64 {
        a[0]
    }
    fn take_array_boolean(a: [bool;3]) -> bool {
        a[0]
    }
}
```

I'm Not sure what labels to add, feel free to edit the issue.  I'll keep poking around with the SDKs and double check.

https://github.com/FuelLabs/fuels-rs/pull/506 - fuels-rs is also running into memory overflow errors

**Comment by hal3e** [comment]
After fixing the issue on the Rust SDK side, we also get a MemoryOverflow Error on the `fn take_array_string_return_single_element(a: [str[3];3]) -> str[3];` function.

**Comment by mohammadfawaz** [comment]
I believe this line: https://github.com/FuelLabs/sway/blob/7491159983982bf8c1b5d0660a5d5101d21d5f18/sway-core/src/asm_generation/from_ir.rs#L891 needs to be changed to: `if ty.get_elem_type(self.context).unwrap().is_copy_type()`. 

Probably the same for https://github.com/FuelLabs/sway/blob/7491159983982bf8c1b5d0660a5d5101d21d5f18/sway-core/src/asm_generation/from_ir.rs#L1180

**Comment by mohammadfawaz** [comment]
Whoever takes this on needs to test the fix with this branch of `fuels-rs`: https://github.com/FuelLabs/fuels-rs/pull/506
