### ISSUE TITLE
Additional checks for unnecessary visibility qualifier

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2419]
Similarly to https://github.com/FuelLabs/sway/pull/2276, we should
1. Check for unnecessary visibility qualifier in ABIs:
```rust
abi MyContract {
    pub fn test_function() -> bool;
}
```
2. Check for unnecessary visibility qualifier in ABI `impl` blocks:
```rust
impl MyContract for Contract {
    pub fn test_function() -> bool {
        true
    }
}
```
3. Check for unnecessary visibility qualifier in trait `impl` blocks:
```rust
trait A {
    fn foo();
}

struct S {}

impl A for S {
     pub fn foo() {}
}
```

**Comment by kayagokalp** [comment]
I was looking for a weekend project and wanted to give this a shot 😄
