### ISSUE TITLE
Expand prelude

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#2433]
Currently the standard library prelude is way too short. Essentials are required to be imported nearly in every contract. Heres some nominations for addition to the prelude

- Address
- ContractId
- Identity
- transfer()
- msg_sender()
- msg_amount()
- msg_asset_id()
- StorageMap
- Vec
- assert
- require
- revert

**Comment by mohammadfawaz** [comment]
If I'm not mistaken, we need to create the prelude first and have the compiler include it in every module. https://github.com/FuelLabs/sway/issues/841 seems to be tracking that work.

**Comment by otrho** [comment]
Yeah, I was going to say, zero sized probably is too short. :slightly_smiling_face:

**Comment by mohammadfawaz** [comment]
Closing in favour of https://github.com/FuelLabs/sway/issues/841
