### ISSUE TITLE
Begin work on a brand new `Sway Book` to replace the current version

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2443]
## Summary

Note: The original issue has been hijacked and completely reworked to contain significantly more work than the original issue.

This issue is now the first issue tracking a brand new sway book which will eventually take place of the current book. It's purpose is to make the book intuitive, organized and concise.

The book is meant to be self contained and thus the source code and documentation is in a brand new directory `sway-book`. Once the book is completed the current `./docs` and `./examples` directories are planned to be deleted since the new book will contain all of the information and much more.

Another future enhancement is to add further anchor tags into the standard library so that any section that is re-written in the source code of the new book can reference the literal standard library without having to re-write that component in its own `src` directory.

The structure is split into two sections.

- `src`
- `documentation`

Those two structures follow each other closely so that it's easy to navigate from once section to the other while keeping the separation of source code and documentation.

**Comment by eureka-cpu** [comment]
Would you mind adding `annotations` in general here as well? The book is missing field annotations, to be specific but we could use better examples overall.

**Comment by Braqzen** [comment]
> Would you mind adding `annotations` in general here as well? The book is missing field annotations, to be specific but we could use better examples overall.

Sure, could you provide a reference example so that I have an idea of what you'd like to see?

**Comment by eureka-cpu** [comment]
> > Would you mind adding `annotations` in general here as well? The book is missing field annotations, to be specific but we could use better examples overall.
> 
> Sure, could you provide a reference example so that I have an idea of what you'd like to see?

There are probably more direct examples, but just in general we don't have any in the book as of now (in the section regarding enum/struct) so something like: 
```rust
enum Annotated {
    #[foo(bar)]
    foo: u64,
    bar: u64,
}
struct Annotated {
    #[foo(bar)]
    foo: u64,
    bar: u64,
}
```
