### ISSUE TITLE
mdbook-forc-documenter needs a more sophisticated way of handling nested sections

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2452]
With #2440, we needed to document with the following structure:

```md
...
- 11.4. Plugins
  - 11.4.1 forc client
    - 11.4.1.1 forc deploy
    - 11.4.1.2 forc run
  - 11.4.2 forc explore
 ```

But `mdbook-forc-documenter` does not support this kind of nesting. Related to https://github.com/FuelLabs/sway/pull/2440#discussion_r936602561 and https://github.com/FuelLabs/sway/pull/2440#discussion_r936745062

I introduced some intermediate implementations to create the structure above at that PR but it only supports a single level of nesting. We may need to have a graph-like structure to hold this nesting information.

**Comment by mitchmindtree** [comment]
I think the intermediate implementations are close enough but could just use a little tweaking for readability - see [this comment](https://github.com/FuelLabs/sway/pull/2440#discussion_r943074559).

**Comment by kayagokalp** [comment]
> I don't think this should be necessary, I'm happy for us to draw the line at one level of nesting. I think all we're after is a way for a single plugin crate to support more than one command.

I think this is completed/not-planned as the linked comment is addressed and further enhancements are not needed. Feel free to re-open it otherwise.
