### ISSUE TITLE
Remove unused import in `Getting Started` for the Sway Book

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2462]
## Summary

In the screenshot below it can be seen that there is an import for `BASE_ASSET_ID` however it is not used nor necessary.
It should be removed.

[Book Ref](https://fuellabs.github.io/sway/v0.19.1/introduction/overview.html#write-a-sway-script-to-call-a-sway-contract)

## Screenshot

![1](https://user-images.githubusercontent.com/103777923/182937228-e3c5e3c6-481f-482c-867f-fbbbee9872ff.png)

**Comment by mohammadfawaz** [comment]
@Braqzen I'll close this in favour of https://github.com/FuelLabs/sway/issues/1766 in which I copied your description above.
