### ISSUE TITLE
`std` contains a duplicate function for getting the gas in the current context

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2464]
## Summary

Two functions exist under different names in two different places. I will argue that the first one should remain (because of the explicit name that differentiates from the global gas) and the one at the bottom should be removed. Although "context_gas" may not be the best name imo.

https://github.com/FuelLabs/sway/blob/a3ffd94c413ca62a8fc130a55b296ee61d6ab1e5/sway-lib-std/src/context/registers.sw#L54-L66

https://github.com/FuelLabs/sway/blob/a3ffd94c413ca62a8fc130a55b296ee61d6ab1e5/sway-lib-std/src/context.sw#L23-L28

**Comment by jtriley-eth** [comment]
The name `context_gas` is fairly intuitive imo. What about `local_gas`?

**Comment by otrho** [comment]
All of those `registers.sw` functions are named after the opcode that they're wrapping.  They're such small functions I'm not sure it's worth worrying about, we could keep both, though I see everyone up-thumbing it, so I guess `gas()` can go.

**Comment by mohammadfawaz** [comment]
Yeah "context" is a term that is [well defined in the specs](https://fuellabs.github.io/fuel-specs/master/vm/index.html?highlight=context#contexts). It's probably best to keep the name to avoid confusion.
