### ISSUE TITLE
`examples-checker` script doesn't work if the name of the directory enclosing the repo is not `sway`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#2474]
Reported by @otrho.

The `examples-checker` is mostly just used for CI, but even still we shouldn't be assuming the name of the directory that encloses the git repository as this can easily differ, e.g. via cloning the repo to a directory with a different name:
```
git clone https://github.com/fuellabs/sway foobar
```

**Comment by denizsurmeli** [comment]
Would this implementation solve the problem:
- adding a new optional argument to `cli` such as `folder_name` and set it to `sway` by default
- adding a new parameter `path` to `get_sway_path()` and return a valid path accordingly to parameter

I would like to work on it if it's available

**Comment by mitchmindtree** [comment]
@denizsurmeli that's a fair suggestion! That said, as this tool is very specific to the Sway repo, I think using some other heuristic (like @otrho's suggestions) would be a better approach so that we don't have to manually pass a directory name as a CLI argument every time we run it.

Apart from that - yes, feel free to have a go at tackling this!
