### ISSUE TITLE
Add `comment` tests for `expr` in `sfv2`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#2497]
>Currently we are supporting this kind of comments as long as it is parsed.
>
>Example
>
>// This can be parsed and supported
>```rust
>let number: /* this number is for counting */ u64 = 10;
>
>// This cannot be parsed and not supported
>let number: // this number is for counting u64 = 10;
>```

**Comment by eureka-cpu** [comment]
This may no longer be an issue, especially since there are new changes that should be preventing the formatter from panicking. Will need triaging.

**Comment by JoshuaBatty** [comment]
added in #5364
