### ISSUE TITLE
Introduce a new `raw_ptr` type a disallow it to be returned from scripts

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2551]
For example:
```rust
struct RawVec<T> {
    #[pointer]
    ptr: u64,
    cap: u64,
}
```
The immediate benefit of this is preventing [`RawVec<T>`](https://github.com/FuelLabs/sway/blob/88820bed80e9b7e68ec0e1a78c64f6b70d7e1dd4/sway-lib-std/src/vec.sw#L9) (and by extension `Vec<T>`) from being returned from a script because when we cross the script boundary, the `ptr` value is not meaningful.

This annotation may have future uses as well.

An alliterative is to introduce pointer/reference types (other than `mut ref` function parameters) but that's a rabbit hole we probably don't want to explore.

Edit: The above proposal has been voted against and the preferred way of doing this seems to be to introduce a `raw_ptr` type as @canndrew as described in https://github.com/FuelLabs/sway/pull/2699

**Comment by otrho** [comment]
This feels a bit hacky, as does a lot of our avoidance of pointers.  But I really don't want to add references.

Would an alternative be an 'address' type, which is very much locked down?  I.e. you can't create them from anywhere other than a heap or stack allocation.  It'd be different to a reference or pointer, where you would take the address of a value.  And then we limit it specifically to only do the operations we need in `Vec` and similar data structures.  :thinking:
