### ISSUE TITLE
Add conditional compilation to Sway

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#2552]
This will enable us to support multiple backends in the standard library among other things. We should minimally support something like `arch = EVM` vs `arch = FuelVM` in annotations (syntax is pseudo, follow Rust syntax)

Other cfg flags for conditional compilation can come later.

**Comment by AlicanC** [comment]
Some notes from my research are below. cc @mohammadfawaz 

---

So it looks like we want to go for `target_arch` first: https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch

It would look like this:
```rs
// The function is only included in the build when compiling for EVM
#[cfg(target_arch = "evm")]
fn evm_only() {
  // ...
}
```

This uses attributes which we have a very limited implementation of. This could be a good excuse to improve it and fix issues like https://github.com/FuelLabs/sway/issues/3576.

There is also a short form which we could implement along with the long form or just by itself:
```rs
#[cfg(evm)]
fn evm_only() {
  // ...
}
```

The short form shouldn't require any changes to the parser, so we could just go for this and not touch the parser at all, but I'm still for improving attr parsing a bit before we do this.

So the steps would be:
- Improve attribute support. This can be delivered early on a separate PR. This *should* serve all the parser/syntax needs.
- Add `cfg` attribute: https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg-attribute
- Add `cfg_attr` attribute: https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute
- Add `cfg` macro: https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg-macro
- Add `target_arch` configuration option: https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch

**Comment by AlicanC** [comment]
I think the least we have to do is:
- Improve attr parsing until building on it doesn't feel like a crime.
- Add `cfg` attr and macro, no `cfg_attr`, no `target_arch`, just `cfg(evm)`/`cfg(fvm)`. (Names should be bikeshed.)
