### ISSUE TITLE
`forc new` generates code that asks for too many coins

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/sway#2567]
[This bumping of the sdk version to 0.20](https://github.com/FuelLabs/sway/commit/3b9413f4ba21c7d12d06f371adf25046e389fa7b#diff-b3cc1ff7749f6a5157a3649a13c1f7eb820555bab130abcb267445e29674e659R104) changed the template for the `harness.rs` to ask for one wallet with a million coins each having a million amount. 

This causes the node initialization to hang due to the work needed to initialize the coins.

Originally there was only one coin generated with a million amount.

Investigate why this change was made and, if deemed needless/over the top, revert it to a more sensible value.

**Comment by mohammadfawaz** [comment]
This may have been the original change: https://github.com/FuelLabs/sway/pull/2332. If the project we get out of the box with `forc init` doesn't run properly, we need to fix this urgently.

**Comment by segfault-magnet** [comment]
The second change caused the issue bumping from 1 coin with 1 MIL of amount to 1MIL coins with 1 MIL amount.

I'd take a gamble and just create one coin. It seemed to be enough for most tests.

And if the user ever runs out of coins, they'll get a nice message saying so. Then they can bump the number as they see fit.
