### ISSUE TITLE
rework or possibly deprecate `forc plugins`

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/sway#2587]
Because of the new release of `fuelup v0.3` with support for multiple toolchains, I think we could possibly deprecate `forc plugins` or move this to a `fuelup` command, since each separate toolchain can have different plugins installed. Technically `fuelup check --verbose` already accomplishes this by checking for the version of each component that is installed (including plugins):

![Screenshot 2022-08-19 at 5 27 12 PM](https://user-images.githubusercontent.com/25565268/185589072-af166dba-087d-4ab4-bdb5-ae946573388b.png)

It is also right now not particularly useful since it prints duplicate plugins when I have multiple toolchains installed. Example:

![Screenshot 2022-08-19 at 5 25 19 PM](https://user-images.githubusercontent.com/25565268/185588774-ffbc7cf1-b3f9-4aea-9954-a3cbdf60bbc0.png)

Imo we could just deprecate it.

**Comment by mitchmindtree** [comment]
This assumes that `forc` will only ever be installed via `fuelup`, which is not a safe assumption to make.

While `fuelup` makes sense as a default installation approach that is mostly cross-platform and documentation friendly, there will be many users that will prefer to install `forc`, `fuel-core`, etc via their standard package manager, via src, or any other means.

> It is also right now not particularly useful since it prints duplicate plugins when I have multiple toolchains installed

This appears like a potentially useful way of identifying duplicate plugin instances on `PATH`. If we run the same command with the paths flag (i.e. forc plugins `--paths`) we can find where the duplicates are and know which are taking priority. Perhaps this might be useful when helping users work out why updating certain plugins appears not to be working? We've already had quite a few reports of our own devs getting confused between tools installed via `cargo` vs installed via `fuelup`, and we'll likely only have more of these issues as the fuel tools make their way downstream into official package managers.
