### ISSUE TITLE
`sha256` treats `u8` as `u64`

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#2594]
When using `sha256` with a `u8` type it is sized as a `u64`. This is problematic when attempting to implement [RFC-6962](https://datatracker.ietf.org/doc/html/rfc6962) which requires concatenation of a `u8`. 

The following implementation of _MTH({d(0)}) = SHA-256(0x00 || d(0))_ fails:
```
pub const LEAF = 0u8;
pub fn leaf_digest(data: b256) -> b256 {    
    sha256((LEAF, data))
}
```

This is seen as these two functions return the same result:

```
fn hash_u8() -> b256 {
    sha256((0u8, 1u8, 2u8))
}

fn hash_u64() -> b256 {
    sha256((0u64, 1u64, 2u64))
}
```

**Comment by Braqzen** [comment]
It's not that `sha256()` is the problem but it's the spec. Any type that is smaller than 1 word is padded to be a full word.

**Comment by adlerjohn** [comment]
The spec for Merkle trees (i.e. RFC-6962) is external to Sway, so it's not constrained by limitations of a blockchain VM. While we could come up with a new spec that's more conducive to compute in Sway, that wouldn't be a standard.

To the specific issue: it looks like hash function always hash the full 8 bytes for copy types. This could be changed to only use the exact number of bytes of the copy type's size.

https://github.com/FuelLabs/sway/blob/efbedb90aa8a49c83e09c579b2d4923a78fba0d2/sway-lib-std/src/hash.sw#L13

However, that only applies to a single primitive copy type. The tuple you're using there isn't actually a copy type! So we could also chalk this up to user error: you're passing in a reference type that _does_ pad the first element to word alignment.

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway/issues/3809
