### ISSUE TITLE
`return` statement with struct fails to compile

### ISSUE THREAD

**Issue by simonr0204** [FuelLabs/sway#2600]
If `s` is struct , then the statement `return s;` fails to compile, with `Internal compiler error: Verification failed: Function doesnt_compile return type must match its RET instructions.`

However, returning an expression `s` compiles.

Repro [here](https://github.com/simonr0204/sway-struct-return-bug/blob/master/src/main.sw) 

Note that this appears to be introduced as of `0.20.0`

**Comment by kayagokalp** [comment]
Out of curiosity, I did a little investigation on this one. Seems like this issue popped up after merging #2363. Following the provided repro, I saw that In the `verify_ret` we are trying to compare two types (one of them `Type::Pointer` and other `Type::Struct`) that [always](https://github.com/FuelLabs/sway/blob/0929300e967425f4ef1903de7b9c3ff1efb1af7e/sway-ir/src/irtype.rs#L91) returns "not equal". Should we get the pointed type while we are making a comparison between a `Type::Pointer` and some other Type?

**Comment by otrho** [comment]
Yeah, you can see the only thing different before and after that PR is the return type is now `ptr { u64 }`:

### Before
```
    fn doesnt_compile<d2cb8797>() -> { u64 }, !5 {
        local ptr { u64 } s

        entry:
        v0 = get_ptr ptr { u64 } s, ptr { u64 }, 0, !6
        v1 = const { u64 } { u64 0 }, !7
        store v1, ptr v0, !6
        v2 = get_ptr ptr { u64 } s, ptr { u64 }, 0, !8
        ret { u64 } v2, !8
    }
```
### After
```
    fn doesnt_compile<d2cb8797>() -> { u64 }, !5 {
        local ptr { u64 } s

        entry:
        v0 = get_ptr ptr { u64 } s, ptr { u64 }, 0, !6
        v1 = const { u64 } { u64 0 }, !7
        store v1, ptr v0, !6
        v2 = get_ptr ptr { u64 } s, ptr { u64 }, 0, !8
        ret ptr { u64 } v2, !8
    }
```
Since the return type declared by the function is just `{ u64 }` I think that needs to be fixed for `master`.
