### ISSUE TITLE
Running multiple instances of `forc` concurrently can (very occasionally) cause a git checkout race

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/sway#2603]
I'm working on a project that compiles multiple sway projects concurrently spawning several forc processes.

Locally everything worked. When I first ran the CI I got the following error ([link](https://github.com/FuelLabs/fuels-rs/runs/7939488743?check_suite_focus=true)):
```
Error: Following Sway projects could not be built:
- foo_caller_contract, Running command: '"/usr/local/bin/forc" "build" "--silent" "--output-directory" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/xtask/../assets/foo_caller_contract" "--path" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/sway_projects/foo_caller_contract"' failed with status: false.   Fetching git+https://github.com/fuellabs/sway?tag=v0.19.2#6808861389966f99887f71476918a562a9edd90e
Error: could not open '/home/runner/.forc/git/checkouts/std-57e47d01450577b4/6808861389966f99887f71476918a562a9edd90e/sway-core/src/ir_generation/function.rs' for writing: No such file or directory; class=Os (2)
 :
- auth_testing_abi, Running command: '"/usr/local/bin/forc" "build" "--silent" "--output-directory" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/xtask/../assets/auth_testing_abi" "--path" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/sway_projects/auth_testing_abi"' failed with status: false.   Fetching git+https://github.com/fuellabs/sway?tag=v0.19.2#6808861389966f99887f71476918a562a9edd90e
Error: failed to stat '/home/runner/.forc/git/checkouts/std-57e47d01450577b4/6808861389966f99887f71476918a562a9edd90e/scripts/prism/components.json': No such file or directory; class=Os (2)
 :
- contract_output_test, Running command: '"/usr/local/bin/forc" "build" "--silent" "--output-directory" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/xtask/../assets/contract_output_test" "--path" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/sway_projects/contract_output_test"' failed with status: false.   Fetching git+https://github.com/fuellabs/sway?tag=v0.19.2#6808861389966f99887f71476918a562a9edd90e
Error: failed to stat '/home/runner/.forc/git/checkouts/std-57e47d01450577b4/6808861389966f99887f71476918a562a9edd90e/docs/src/sway-program-types/index.md': No such file or directory; class=Os (2)
```

There seems to be a race on the checked-out sway stdlib. I don't know the exact cause but [this code](https://github.com/FuelLabs/sway/blob/0929300e967425f4ef1903de7b9c3ff1efb1af7e/forc-pkg/src/pkg.rs#L1308) seems to be doing git checkouts and deletions on deterministic folder names without any inter-process-locking surrounding it.

**Comment by mitchmindtree** [comment]
Copying some of my comments from slack:

> My suspicion is that perhaps two separate processes are attempting to perform a git checkout from the their respective temporary git repos to the same location at roughly the same time, and as the first process attempts to read the files from that directory the second process' checkout is still in progress and overrides some of those files, or something along those lines.

We have the following issue for coming up with some sort of directory lock that should make issues like this impossible in a more general manner (similar to cargo's inner Filesystem abstraction) #919. This is likely the proper solution.

## Temporary Workarounds

This issue should be an unlikely encounter unless running many instances of `forc` simultaneously on a completely fresh systemm (e.g. a system that hasn't yet downloaded and built `core` and `std`). The safest workaround would be to run `forc` tasks in a synchronous manner until #919 is addressed.

An alternative, less-safe workaround might be to manually build a minimal forc project that only contains `core` and `std` as dependencies to ensure they are already fetched and cached prior to running the larger asynchronous set of `forc` processes, as it is these two crates that have the highest likelihood of encountering conflicts.

**Comment by segfault-magnet** [comment]
@mitchmindtree @bingcicle 

Although this might go without saying, we'll just recap what @hal3e and I noticed while perusing the forc project:

The problem occurs when multiple projects share a sway dependency and see that it is not downloaded (the dep's folder is missing) and proceed to download it.

As part of the downloading process, there is a check again whether the folder exists, even though a moment ago it was concluded that it did not. If the folder turns out to exist after all, then it is promptly deleted.

The issue arises when one forc downloads the dependency, only [to have it deleted by](https://github.com/FuelLabs/sway/blob/f7a387467faef39ea8e96cb2515a7e7e9be89dad/forc-pkg/src/pkg.rs#L1511) another forc. This leaves the dependency in an undefined state and causes all sorts of issues.

We've looked into how cargo does it and noticed it is a thin wrapper around `flock`. It also contains a bunch of diagnostic messages making it unsuitable to include into forc as-is. Regardless, the code still has valuable insights around edge-cases pertaining to various filesystems and their support for locking files.

**Comment by bingcicle** [comment]
I was looking into how cargo handles its checkouts and found that it relies on a dummy `.cargo-ok` file within the directory ([source](https://github.com/rust-lang/cargo/blob/37cad5bd7f7dcd2f6d3e45312a99a9d3eec1e2a0/src/cargo/sources/git/utils.rs#L293-L325)). The motivation for this is explained [here](https://github.com/rust-lang/cargo/issues/6340#issuecomment-440777465).

I'm assuming the reason why we're doing [this](https://github.com/FuelLabs/sway/blob/f7a387467faef39ea8e96cb2515a7e7e9be89dad/forc-pkg/src/pkg.rs#L1510-L1513) is to ensure a fresh, up-to-date checkout of the git repo. If this is true, then it seems to me like the solution above directly addresses this issue rather than a `Filesystem` abstraction (#919) at the moment, even though the latter is still a nice-to-have.

**Comment by mitchmindtree** [comment]
@bingcicle Having a `.forc-ok` file or similar sounds like a nice way of ensuring a checkout was completed successfully. However I don't think it fixes the issue where:

1. Process 1 starts to checkout `foo` repo.
2. Process 2 also starts, but directory already exists so checks for `.forc-ok`.
3. Process 2 does not find `.forc-ok`, so starts deleting `foo` while Process 1 still checking out.

This might not be an issue if the checkout first occurs at a temp dir which is then moved to the desired location upon completion. That said, then we potentially run into issues with two processes checking out the same repo to temp dirs and moving them to the desired location at the same time, which is maybe less risky but still racey, potentially resulting in odd I/O errors?

Allowing a process to obtain a file lock for the desired checkout location would help to avoid any possible contention as other processes would have some mechanism to wait.

I *think* it's only these checkout repositories that have deterministic directory locations that can be written to from multiple processes at once, so it should only be these that require locking.
