### ISSUE TITLE
Move `forc-explore` into its own crate

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#2609]
As part of an initiative to move plugins unrelated to Sway from the sway repo.

Will need some consideration around fuelup's plugin handling, as well as mdbook doc generation.

**Comment by bingcicle** [comment]
To close this, the steps here need to be fulfilled:

- [ ] remove `forc-explore` from CI steps
- [ ] remove the `forc-explore` directory entirely

**Comment by bingcicle** [comment]
Since both #2926 and #3163 are merged, this can be closed now.
