### ISSUE TITLE
Migration to `fuel-core` v0.10+ is blocked

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2622]
While trying to make the switch to`fuel-core` v0.10` I'm encountering a number of issues.

### Context
I'm working on this PR here: https://github.com/FuelLabs/sway/pull/2482
The changeset is fairly large; multiple dependencies are being bumped, opcodes have been removed and added, and a big chunk of the stdlib has been refactored. These have to happen together in 1 PR to make it all work.

### Current Issues

- Multiple failing stdlib tests using the SDK

 The current released SDK version doesn't currently support `fuel-core` v0.10` so I'm using a patched version of the SDK for the stdlib tests with this patch:
```
[patch.crates-io]
fuels = { git = "https://github.com/FuelLabs/fuels-rs", branch = "hal3e/bump-fuel-core"}
```
Among other things, the failing tests indicate that the number of inputs returned by the `input_amount()` getter == `0`.
More discussion here: https://fuellabs.slack.com/archives/C02CX4JVCSJ/p1661344259170089

- Apparent bug in the `__gtf` intrinsic
If I log out the value returned by the intrinsic for a specific field, and then get that same field using raw `asm` + the `gtf` opcode I get different values.  For example:
```
    let type_1 = __gtf::<u8>(0, GTF_TYPE);
    let type_2 = asm(r1, r2: 0) {
        gtf r1 r2 i1;
        r1: u8
    };
    log(type_1); // 10376
    log(type_2); // 0 (the expected value
```
I've not tested extensively so I don't know if this is the case for more than 1 field.

- While trying to produce a minimal repro of the above (WIP can be found on the `furnic/gtf-intrinsic-bug` branch), I started hitting this new error:
```
Error: Response errors; TransactionCreateBytecodeWitnessIndex
```
More discussion here: https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1661440389568419

- and finally, some strange behavior around logging values in sway apparently affecting control flow?
More discussion here: https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1661430694033159

**Comment by mohammadfawaz** [comment]
@nfurfaro now that we're done with the migration to `fuel-core 0.10.1`, most of the items above are resolved. Do you mind creating separate descriptive issues of the remaining problems?

**Comment by nfurfaro** [comment]
All sub-issue in this have been resolved, closing.
