### ISSUE TITLE
Implement a compiler intrinsic to get the storage hash of any given struct (to support storage types in other storage types)

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#2639]
Right now, StorageMap and StorageVec use the compiler intrinsic `__get_storage_key()`. This returns a string which contains the index of the given variable when stored in a storage variable. The problem is that if you have a recursive Map or Vec, this will return the same string for all the Maps and Vecs involved, rendering it useless as a salt for more than one struct.

If the hash of the specific storage slot where the given struct is stored can be accessed with a intrinsic, then recursive maps and recursive vecs would become possible by just replacing any reference of `__get_storage_key()` with `__get_struct_storage_hash()` (name can be changed obvs)

**Comment by mohammadfawaz** [comment]
Before changing the intrinsic, I'd like to see how it's going to be used. How would you rewrite `StorageMap` for example to use the new intrinsic? And how would that help us with recursive maps?

**Comment by SwayStar123** [comment]
> Before changing the intrinsic, I'd like to see how it's going to be used. How would you rewrite `StorageMap` for example to use the new intrinsic? And how would that help us with recursive maps?

```
pub struct StorageMap<K, V> {
}

impl<K, V> StorageMap<K, V> {
    #[storage(write)]fn insert(self, key: K, value: V) {
        let key = sha256((key, __get_struct_storage_hash()));
        store::<V>(key, value);
    }

    #[storage(read)]fn get(self, key: K) -> V {
        let key = sha256((key, __get_struct_storage_hash()));
        get::<V>(key)
    }
}
```

a simple replacing of `__get_storage_key()` with the new intrinsic would expand the functionality of StorageMap and StorageVec while retaining its current functionality

This is assuming that every `storage` field has a corresponding hash which would be used in the `store` function

It would achieve recursive maps like this
in this example storage: 
```
storage {
    map: StorageMap<u64, StorageMap<u64, u64>>,
}
```
The outer StorageMap would have a corresponding storage hash `x`. When calling `insert`, it will `store` a new `StorageMap` at the hash of `(u64, x)`. This hash of `(u64, x)` would be the storage hash of the inner StorageMap `y`. When calling `insert` on the new inner Map, it would calculate the hash as `(u64, y)` now.

Currently, since `__get_storage_key()` resolves to the same salt no matter how many StorageMaps/StorageVecs are present in the given `storage` field (through recursive Maps/Vecs) it would result in overwriting of values if the same key is used.

One flaw of this implementation (correct me if im wrong on this one) is that structs would still not allow multiple `StorageMap`s and `StorageVec`s, since the entire struct would still be stored in the same hash

**Comment by mohammadfawaz** [comment]
Right, that makes sense to me. The intrinsic you're suggesting is a bit more complicated to implement than `__get_storage_key()`. The intrinsic `__get_storage_key()` only returns something useful if it is called inside a method of a struct that is instantiated in a storage block, which is very restrictive. Generalizing this to an intrinsic that returns the storage hash of *any* given variable is effectively equivalent to implementing storage references (hash are like addresses basically). We also have the problem of dealing variables that span multiple storage slots (like large structs).

**Comment by mohammadfawaz** [comment]
Essentially the challenge is that when you write 
```rust
storage {
    let vec: StorageVec<StorageVec<u64>>` = StorageVec {}
}
````
and then write
```rust
let inner_vec = storage.vec.get(0).unwarp(); // Assuming len >= 1
let first_elem = inner_vec.get(0).unwrap();
```
`inner_vec` is now a stack variable and we have no way of figuring out it's hash without storage references.

**Comment by mohammadfawaz** [comment]
Just an update: before attempting to allow `StorageVec<StorageVec<T>>` and other similar compositions, we're going to implement https://github.com/FuelLabs/sway/issues/3043 (and https://github.com/FuelLabs/sway/issues/2585) and see where that takes us. We should be able to do all kinds of compositions at that point.
