### ISSUE TITLE
Accessing methods using a fully qualified path does not work

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2648]
Example:

```rust
script;

fn main() {
    let x  = ~std::address::Address::from(0x0101010101010101010101010101010101010101010101010101010101010101);
}
```
Error:
```console
3 | fn main() {
4 |     let x  = ~std::address::Address::from(0x0101010101010101010101010101010101010101010101010101010101010101);
  |              ^ fully qualified paths are not supported here
5 | }
```

**Comment by otrho** [comment]
Are we able to remove the `~` now @canndrew ?  Wasn't it a parser issue which the new parser could resolve?

**Comment by mohammadfawaz** [comment]
We marked this as `P: low`: https://github.com/FuelLabs/sway/issues/1436 but I'm really tempted to just bump it to `P: critical` so that we don't have to look at a `~` anymore :D

**Comment by canndrew** [comment]
If it was always just a parser issue then yeah, it should be possible to remove it.

**Comment by mohammadfawaz** [comment]
The following works now so I'm closing this issue:
```
script;

fn main() {
    let x  = std::address::Address::from(0x0101010101010101010101010101010101010101010101010101010101010101);
}
```
