### ISSUE TITLE
Using `fuel-tx` directly in `forc-pkg` causes some issues with `cargo install`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2659]
This is referring to https://github.com/FuelLabs/sway/pull/2482...

With this branch, the problem is reproducible as follows:
- Use `fuel-tx` directly in `forc-pkg` instead of through `fuel-gql-client`
- Run `cargo install --debug --path ./forc`. You get the following error:
![image](https://user-images.githubusercontent.com/59666792/187533941-d5bee8ec-6a49-4b59-a196-4e1ff3e9a84e.png)

Note that `cargo build` compiles without any issues. It's only `cargo install` that exposes the problem.

**Comment by kayagokalp** [comment]
I am not sure but this might be happening because of a missing `serde` feature in the `fuel-tx` entry of `forc-pkg` manifest file. I had a similar issue while I was playing around at #2629 https://github.com/FuelLabs/sway/blob/184f6e4ec4a9a7b6a776531df7b04a68a5919a93/forc-pkg/Cargo.toml#L15

**Comment by mohammadfawaz** [comment]
Oh interesting. I'll play around with that, thanks!
