### ISSUE TITLE
Use `GTF_OUTPUT_VARIABLE_AMOUNT` and `GTF_OUTPUT_CHANGE_AMOUNT` fields when available

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2671]
In https://github.com/FuelLabs/sway/pull/2482, the function `output_amount` currently uses a manual method to compute the amount when the output type is `Change` or `Variable`. Switch to using `GTF_OUTPUT_VARIABLE_AMOUNT` and `GTF_OUTPUT_CHANGE_AMOUNT` when they are available (see https://github.com/FuelLabs/fuel-specs/issues/402)

**Comment by bitzoic** [comment]
As specified in https://github.com/FuelLabs/fuel-specs/issues/402 this is no longer planned
