### ISSUE TITLE
Consider `FromIterator` for `CompileResult`.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#2694]
In Rust it's handy to be able to `.collect()` a final `Result` from an iterator of `Result`s.  It would also be good for `CompileResult`.

```rust
impl<T, V: FromIterator<T>> FromIterator<CompileResult<T>> for CompileResult<V> {
    fn from_iter<I: IntoIterator<Item = CompileResult<T>>>(iter: I) -> Self {
        todo!()
    }
}
```
The `todo!()` here needs to gather the results, warnings and errors together into a single `CompileResult`, collecting all the results into a `V`.  Then we could e.g. `results.iter().collect::<CompileResult<Vec<_>>()`.

The only issue though is do we stop collecting from the results iterator when it hits its first `err`, or do we collect all the errors and warnings and return `err` if _any_ of the results are?

**Comment by andrewvious** [comment]
Is this issue still open?
