### ISSUE TITLE
Add "unused variable" warning to `if let` statements

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2700]
The following example will generate a warning `This match arm is unreachable.` for the second arm, but it should also give the user a, "Unused Variable" warning. 
```
enum Animal {
    Cat: (),
    Dog: (),
}
let pet =  Animal::Cat;

if let pet = Animal::Dog {
    // do thing 1
} else {
    // do thing 2
}

```

**Comment by emilyaherbert** [comment]
Closing this in favor of #3688, as this falls under the umbrella of a bigger ticket of adding "unused variable" warnings in general.
