### ISSUE TITLE
Internal compiler error: Store must be to a pointer

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2719]
Two different signatures, one with `ref mut`, causes an ICE.

```rust
contract;

abi MyContract {
    fn test_function(variable: u64) -> bool;
}

impl MyContract for Contract {
    fn test_function(ref mut variable: u64) -> bool {
        variable += 1;
        true
    }
}
```

![1](https://user-images.githubusercontent.com/103777923/188289229-62103589-ab8e-473c-ab89-f44b1ecb853e.png)

**Comment by otrho** [comment]
Note: the fix for this issue is to return a better non-ICE error, rather than to actually support this behaviour.
