### ISSUE TITLE
CI: Packed binaries for apple arm arch seems to be in intel arch

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2726]
Realized while installing on a fresh m1 system without any rosetta installed. For more information please see https://github.com/FuelLabs/fuelup/issues/177.

I think I narrowed down the issue to sway repo CI since looking at `file` output of the binaries I get from
https://github.com/FuelLabs/sway/releases/download/v0.23.0/forc-binaries-darwin_arm64.tar.gz
results:

```
forc: Mach-O 64-bit executable x86_64
```

But if I built them myself and check `file forc` I can see:

```
forc: Mach-O 64-bit executable arm64
```

So I am guessing the binaries placed in the arm64 zip seems to be in Intel arch. Because of this default installation with `fuelup` fails if rosetta2 is not installed and even if it is installed by default normally, it would be better to have native mac os arm binaries working as many people use these devices now.

**Comment by bingcicle** [comment]
Seems like people might be having trouble with binaries on M1 Mac ([Discord message link](https://discord.com/channels/732892373507375164/734213700835082330/1047202603257307238)). Going to pick this up and prioritize this.
