### ISSUE TITLE
Add `TIME` instruction support

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#2731]
https://github.com/FuelLabs/fuel-asm/pull/89

**Comment by mohammadfawaz** [comment]
I'm assuming this simply involves: 
- Adding `time` to opcode to the parser
- Adding `time` in codegen.
- Adding a standard library function in [`block.sw`](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/block.sw) called `timestamp()` that wraps the `time` instruction. Propsal:
  - `fn timestamp()`: returns the timestamp for the current block, i.e., it calls `height()` under the hood.
  - `fn timestamp_of_block(height: u64)`: returns the timestamp for block at height `height`.
