### ISSUE TITLE
Formatter unable to parse file with multiple single-line comments before module kind

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#2753]
When writing multiple single-line comments before declaring the module kind, the formatter will output the following error.

![formatter_error](https://user-images.githubusercontent.com/54727135/189159458-8fbea354-6358-4f26-8d63-5dc3bd877a79.png)

Example code that produced this output:

```
// This is a comment
// This is also a comment

library lib;

```

`forc`  version: 0.24.1

**Comment by mohammadfawaz** [comment]
Yeah I think @eureka-cpu is actively working on this - dup of https://github.com/FuelLabs/sway/issues/2739
