### ISSUE TITLE
Configuration-time constants should be defined in the contract

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2761]
Configuration-time constants (aka “immutable” variables in Solidity) is that they’re not apparent in the contract; That is, there’s no placeholder value like `const owner;` anywhere except for in the manifest.

I prefer the way a Solidity contract contains all the constants in the source for easy parsing, and even differentiates between `const` and `immutable` values, making it clear which ones a dev needs to set explicitly at a glance.

Arguably, a glance at the manifest does the same here, but I would much prefer to see all the const values in the code explicitly, even if we don’t have a different name for them.

I propose that our config-time constants:
1.) be defined in the contract (perhaps with a default value), but overridden in the manifest at compile-time
2.) potentially have a different name than `const`. `immutable` as per Solidity could work, but may be confusing with our usage of the `mut` keyword.

Alternately, we could make all configuration-time constants use the `Option` type, defined and initialized as the `None` variant in the contract, and set to a `Some` value in the manifest at compile time. This has the important benefit of ensuring a dev doesn't set some default value like `0x0000...` and then forget to change it, causing potential vulnerabilities as a  simple `require(value.is_some(), ...` check is sufficient to prevent this.

**Comment by adlerjohn** [comment]
concept ACK

For the last paragraph, I would avoid requiring things to be wrapped in an `Option` as it's not zero-cost.

**Comment by mohammadfawaz** [comment]
Closing in favor of https://github.com/FuelLabs/sway/issues/1498. The proposal is now described in https://github.com/FuelLabs/sway-rfcs/pull/19
