### ISSUE TITLE
Add a way to disginguish between "crate-relative" and external paths

### ISSUE THREAD

**Issue by Centril** [FuelLabs/sway#2780]
Currently, `::foo::bar` means crate-relative. There should be a way, like in Rust, to refer to `foo::bar` where `foo` is the external crate. Though this should probably be part of a complete overhaul of Sway's module system.

**Comment by esdrubal** [comment]
Module contains a field `is_external`. We can check if is a `mod_path` is related to an external crate by doing:
```rust
let submodule = src_ns.submodule(&[mod_path[0].clone()]);
if let Some(submodule) = submodule {
    is_external = submodule.is_external
};
```
