### ISSUE TITLE
Require statements are not formatted correctly

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#2785]
The following is an example of a formatted `require`:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/17053076/190244702-034a41f1-930d-4dba-9e81-475a93d3ab5a.png">

What I would prefer to see is something like this:
```
require(
    message_data.l1_asset == ~EvmAddress::from(LAYER_1_TOKEN), 
    BridgeFungibleTokenError::IncorrectAssetDeposited
);
```

**Comment by nfurfaro** [comment]
Adding another case with the same issue, but not related to `require`:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/17053076/191955236-30fbc4e9-7045-4c07-a9fe-64790d2b5c91.png">

When a `match` arm wraps, there should be at least one level of indentation I think. So rather than:
```
Input::Message => Option::Some(__gtf::<u64>(index, GTF_INPUT_MESSAGE_AMOUNT)),
```
we should see something like:
```
Input::Message => Option::Some(
    __gtf::<u64>(index, GTF_INPUT_MESSAGE_AMOUNT)
),
```

**Comment by mohammadfawaz** [comment]
@nfurfaro so can this be closed? :)

**Comment by nfurfaro** [comment]
Closing as this behaviour I observed was actually my editor wrapping configuration.
