### ISSUE TITLE
handle checking out repo for nightly builds

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/sway#2821]
Currently `forc check` (and also `build`) on a `nightly` build fails due to the version formatting:

![forccheck](https://user-images.githubusercontent.com/25565268/191439315-4882a61c-e874-41e4-94fd-420da9f6fa33.png)

We need to handle the case where the tag is appended with the build metadata of the date/commit hash for forc-pkg to work as intended for nightlies.

**Comment by mitchmindtree** [comment]
Ahhh of course! The version is used to pin down the version of `std` and `core` via the git tag.

https://github.com/FuelLabs/sway/blob/master/forc-pkg/src/manifest.rs#L447

I think we just need to strip off the metadata on the end if it exists before we construct the `DependencyDetails` there.

That said, this would mean the nightly `forc`'s sway and core version is always pointing to the last published version. That's probably fine for now as a temp fix.

A proper fix might be to ensure we have git tags for the commits used to produce nightlies in the Sway repo itself (not just the binary repo). They don't necessarily need to have a "github release", but the git tag must be present for `forc` to be able to use `git` to fetch the matching commit.

**Comment by bingcicle** [comment]
> this would mean the nightly forc's sway and core version is always pointing to the last published version. That's probably fine for now as a temp fix

wouldn't this mean that it won't contain the std/core changes from the tag up to the point of the commit? I'd thought the fix was to use the hash we append within the build metadata to fetch std, instead of just the tag.

**Comment by mitchmindtree** [comment]
> I'd thought the fix was to use the hash we append within the build metadata to fetch std, instead of just the tag.

Even better, sounds good :+1:
