### ISSUE TITLE
Self type inference/unification not working for trait method application

### ISSUE THREAD

**Issue by tritao** [FuelLabs/sway#2838]
This issue comes up on top of https://github.com/FuelLabs/sway/pull/2839 with the following test case:

```rust
script;

trait Store {
    fn store(self, key: b256);
}

impl Store for b256 {
    fn store(self, key: b256) {
        asm(r1: key, r2: self) {
            swwq r1 r2;
        };
    }
}

fn foo<T>(key: b256, value: T) where T: Store {
    value.store(key)
}

fn main() {
    let x: b256 = 0x000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF;
    foo(x, x);
}
```

The issue is that in the final AST after type checking, the `store` declaration attached to the `value.store(key)` call still contains references to the `Self` type.

Which later causes us to fail with:

```
3 | trait Store {
4 |     fn store(self, key: b256);
  |              ^^^^ Internal compiler error: Self type cannot be resolved in IR.
Please file an issue on the repository and include the code that triggered this error.
5 | }
```

**Comment by emilyaherbert** [comment]
Just took a look at this, and I think the error that your seeing is due to an issue with the implementation of #2839---closing this for now.
