### ISSUE TITLE
Add `core::num::*` to the prelude

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2841]
As per the title. That library includes simple things like `~u64::max()` and it wouldn't hurt to have them automatically available to every program.

**Comment by nfurfaro** [comment]
Ref: https://github.com/FuelLabs/sway/issues/2777

**Comment by mohammadfawaz** [comment]
https://github.com/FuelLabs/sway/pull/2828/files currently closes this issue so I'm just gonna close it now.
