### ISSUE TITLE
LSP Hover: Show number of implementations of type

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#2851]
eg 

<img width="405" alt="Screen Shot 2022-09-26 at 2 17 55 pm" src="https://user-images.githubusercontent.com/1289413/192192894-42689005-95c6-4796-9584-913e2a8274e2.png">

**Comment by sdankel** [comment]
https://github.com/FuelLabs/sway/issues/2852#issuecomment-1522503019 applies here too.
