### ISSUE TITLE
Parse errors in different files should not affect each other

### ISSUE THREAD

**Issue by Centril** [FuelLabs/sway#2855]
If we see something like `dep bar;`, this should not stop parsing from continuing, and not type checking either.
If there were lexing errors in `bar.sw`, we should just throw away the entire file.

**Comment by JoshuaBatty** [comment]
If there are lexing errors in `bar.sw` does the whole file need to be thrown away or can the compiler still return a best effort ParseProgram and TypedProgram's?

**Comment by JoshuaBatty** [comment]
Great, that makes sense. Thanks for clarifying.
