### ISSUE TITLE
`revert` in an `if` branch causes an IR verification error

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2876]
Example:
```rust
script;

pub fn revert(code: u64) {
    asm(r1: code) {
        rvrt r1;
    }
}

fn main() -> u64 {
    if true {
        revert(0)
    } else {
        42
    }
}
```
Error:
```console
error: Internal compiler error: Verification failed: Function main return type must match its RET instructions.
```

Basically, the type of the `asm` block resolves to `()` because `revert()` returns a `()`. But because `revert(0)` deterministically aborts, we don't emit a compiler error about mismatched types (i.e. type of `42` is different from the type of `revert(0)`). So this ends up being caught by the IR verifier. 

Note that switching the bodies of `if` and `else` compiles fine. I expect the above to compiler with or without a semicolon after `revert(0)` AND with or without a semicolon after the `asm` block. See https://github.com/FuelLabs/sway/issues/2822 for another issue related to that.

**Comment by mohammadfawaz** [comment]
Now that `rvrt` is not allowed in `asm` blocks, the reproducer looks like:
```
script;

fn main() -> u64 {
    if true {
        std::revert::revert(0) 
    } else {
        42
    }
}
```

**Comment by otrho** [comment]
I think this is supposed to be handled by the `is_diverging()` stuff which Andrew added.  It's most likely just a missed case in the `if` compilation.

**Comment by mohammadfawaz** [comment]
The issue is simply that the type of `revert(0)` is `()` because `fn revert` is defined as 
```rust
pub fn revert(code: u64) {
    __revert(code)
}
```
so that's a conflict of types between the `if` branch and the `else` branch.

**Comment by esdrubal** [comment]
This issue appears to no longer occur in master.


> Now that `rvrt` is not allowed in `asm` blocks, the reproducer looks like:
> 
> ```rust
> script;
> 
> fn main() -> u64 {
>     if true {
>         std::revert::revert(0) 
>     } else {
>         42
>     }
> }
> ```

Added the above test case in #3285
