### ISSUE TITLE
Introduce a `Never` type

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2881]
[Rust has a `Never` type](https://doc.rust-lang.org/std/primitive.never.html) which helps with expressions like `exit(0)`, `break` and `continue`. Sway could also benefit from that type for the following:
- `break`
- `continue`
- ASM blocks that revert. (e.g. `fn revert()`).

This seems to be somewhat required to solve https://github.com/FuelLabs/sway/issues/2876 and all the problems that showed up when I tried fixing the IR verifier here: https://github.com/FuelLabs/sway/pull/2880. We've had issues hiding behind a bug in the verifier.

**Comment by mohammadfawaz** [comment]
Right, this was discussed at some point here: https://github.com/FuelLabs/sway/issues/1697 but we never did anything about it.

**Comment by mohammadfawaz** [comment]
I guess the key point with this type is that we want it to coerce to any other type and we can do this in the type engine by allowing `enum {}` to cast to any other type.

**Comment by otrho** [comment]
> This could just be a standard library type in the prelude defined as `enum Never {}` perhaps.

I'm looking at this again now due to #3362 and I think if we're going to solve the diverging problem (again) properly then this won't be enough -- it needs to be a proper builtin type and special-cased in the type checker unification.  But I'm not a type system specialist.  @emilyaherbert ?
