### ISSUE TITLE
Sway formatter errors when parsing file that compiles

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2887]
Using `forc -V` = `0.24.5` and my alias `ffmt` (`forc fmt`) it can be seen in the image that the code has compiled but then the formatting fails. This is a brand new project created with `forc new --library cramps` (weird name because I'm trying to repro a different issue).

```rust
library cramps;

struct TaDa {
    // comment
}

```

![1](https://user-images.githubusercontent.com/103777923/192830454-001c907e-178c-422f-bea0-2e7d6a6a4ee0.png)

cc @eureka-cpu @kayagokalp

**Comment by bingcicle** [comment]
with `forc-fmt v0.33.0`, result:

```rust
library cramps;

struct TaDa {}
    // comment
```

Closing because this doesn't fail anymore, but leads to comment outside of struct, which is this issue: https://github.com/FuelLabs/sway/issues/2888
