### ISSUE TITLE
Tuple `arity` and formatter removing `()`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2927]
1. For some reason `x` is a `u64` and not a tuple containing a single element
2. When running the formatter the type annotation on `y` gets changed from `(u64)` to `u64` however this is documentation therefore we need the `()`

```rust
contract;

abi MyContract {
    fn test_function();
}

impl MyContract for Contract {
    fn test_function() {
        // x is of type u64
        let x: u64 = (42);

        // y is of type u64
        let y: (u64) = (42);

        // z is of type (u64), i.e. a one-arity tuple
        let z: (u64, ) = (42, );
    }
}
```

What should happen here? Is the compiler incorrect; is the formatter incorrect?

**Comment by Braqzen** [comment]
cc @eureka-cpu @mohammadfawaz

**Comment by eureka-cpu** [comment]
If this is happening after formatting it is the formatter, I'll take a look at how we are formatting `ty` at some point this weekend if nobody gets to it first

**Comment by eureka-cpu** [comment]
I've looked into this and if the `ty` of `x` was indeed `(u64)` on the compile side, it would parse and automatically get parenthesis from the formatter... @mohammadfawaz I'm not really sure where I should be looking on the compile side of things if it is indeed a compiler issue. If you point me in the right direction, I'll gladly tackle it tonight. To be more clear, any time a parsed `ty` is matched on in the formatter, it will always get parenthesis. https://github.com/FuelLabs/sway/blob/master/swayfmt/src/utils/language/ty.rs#L34

**Comment by eureka-cpu** [comment]
What I think may be happening is that the parsed type is `u64` and not `(u64)`, otherwise the formatter would have added the parens

**Comment by mohammadfawaz** [comment]
> What I think may be happening is that the parsed type is u64 and not (u64)

Yeah, the AST probably just have a `u64` instead of a `(u64)`. Emily implemented that here: https://github.com/FuelLabs/sway/pull/1774 if that helps. Interestingly, Rust has the same behavior and gives a warning that the parentheses are not used but the formatter does not drop them. Since our formatter is based strictly on the AST without any side information, I'm not sure how we would go about this.

**Comment by Braqzen** [comment]
> > What I think may be happening is that the parsed type is u64 and not (u64)
> 
> Yeah, the AST probably just have a `u64` instead of a `(u64)`. Emily implemented that here: #1774 if that helps. Interestingly, Rust has the same behavior and gives a warning that the parentheses are not used but the formatter does not drop them. Since our formatter is based strictly on the AST without any side information, I'm not sure how we would go about this. We will need some additional information in the AST to describe what's happening. How critical is this and do we really need to talk about this case in the Sway Book? Seems like one of those trivial things that no one cares about.

It is in the current sway book therefore it is one of the sections that I have ported for consistency. I had to look up what `arity` was when I saw this. I don't find this to be helpful and I'd rather remove it from the new book anyway.

**Comment by eureka-cpu** [comment]
> > What I think may be happening is that the parsed type is u64 and not (u64)
> 
> Yeah, the AST probably just have a `u64` instead of a `(u64)`. Emily implemented that here: #1774 if that helps. Interestingly, Rust has the same behavior and gives a warning that the parentheses are not used but the formatter does not drop them. Since our formatter is based strictly on the AST without any side information, I'm not sure how we would go about this. We will need some additional information in the AST to describe what's happening. How critical is this and do we really need to talk about this case in the Sway Book? Seems like one of those trivial things that no one cares about.

Personally, now that I understand what's happening, I don't think any change is necessary as it's just a nit and seems inconsequential to any case I can think of.

**Comment by eureka-cpu** [comment]
Maybe adding that the formatter will remove them in the warning message would be okay, though overly verbose in my opinion.

**Comment by mohammadfawaz** [comment]
Yeah so that's a non-issue and we can remove that example in the book.

**Comment by mohammadfawaz** [comment]
@Braqzen I'm closing this issue if that's okay with you. I think we all agreed that the example should just be removed from the new book as it's not particularly useful.
