### ISSUE TITLE
Introduce a way for `forc-build` to output deployment information

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2930]
Currently the information related to a specific deployment is only `print`ed and we do not have a non-volatile way of storing this information. We may want to output something like a deployment file which is output in a predetermined structure so that later on workspace members can be aware of some deployment information (like the contract id) of other members so that we can send that information in between them.

**Comment by mitchmindtree** [comment]
I wonder if we should instead generate this during `forc build`?

Previously, I was falsely under the assumption that we wouldn't know the ID of the contract until it was deployed, but one of the magic things about Fuel is that a contract's ID is reproducible and deterministic, so we *should* be able to produce this at build time which would be much nicer!

For now I think we can keep this super simple, e.g. only output the contract's ID to something like:

```
./out/<profile>/<name>-contract-id
```

Once we've finished #1777, we can revisit this and perhaps output a more detailed metadata file like `./out/<profile>/<name>-contract-ids.json` which outputs not only the top-level contract, but also the ID of all contract dependencies within the graph. This might look similar to the `Forc.lock` file but in JSON and only containing contracts, their IDs and their contract dependencies. I imagine something like this might make it easier for users to see exactly which contracts their own contract ended up interacting with.

**Comment by kayagokalp** [comment]
That sounds really nice to me but once slight problem with outputting contract's ID from `forc build` could be the `salt`. Since we have nice deterministic contract IDs, without a salt people cannot deploy the same contract. Currently `forc-deploy` does not offer this opportunity (through a flag) but I think we will want that at some point. If we indeed add to option to specify (or randomize) salt while deploying we will need to keep this in mind and possibly output this file from `forc-client` but that being said since we are not adding it right now we could continue with `forc build` approach 🙌

**Comment by mitchmindtree** [comment]
Yeah w.r.t. salt, perhaps we can even offer an optional command-line argument to `build` for this, e.g. something like:
```
forc build --salt "some-salt"
```
Then if necessary, `deploy` could just forward the unique salt to this argument?
