### ISSUE TITLE
Comments that use `/**/` syntax do not get formatted

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2933]
When using the following, supported, style of commenting the formatter ignores it completely. I have added arbitrary spaces however the example below demonstrates what it ought to be formatted to.

```rust
library comments;

fn block() {
    // ANCHOR: block
    /*
        You can write on multiple lines
        like this if you want
    */
    let baz = 8;
    // ANCHOR_END: block
}
```

**Comment by eureka-cpu** [comment]
Could use more information e.g. are they being removed entirely, what does the before and after look like?

**Comment by Braqzen** [comment]
> Could use more information e.g. are they being removed entirely, what does the before and after look like?

hm? In the description I've said "the formatter ignores it completely".

**Comment by eureka-cpu** [comment]
> > Could use more information e.g. are they being removed entirely, what does the before and after look like?
> 
> hm? In the description I've said "the formatter ignores it completely".

In the instance and with the context provided, I can't discern if by ignoring you mean that the formatter leaves it in the state it was prior to formatting, or if after formatting the multiline comment is no longer there. If it's the former, this is the current expected result. If you wouldn't mind provided context of how you think it should look after formatting that would be a huge help!

**Comment by Braqzen** [comment]
> > > Could use more information e.g. are they being removed entirely, what does the before and after look like?
> > 
> > 
> > hm? In the description I've said "the formatter ignores it completely".
> 
> In this instance and with the context provided, I can't discern if by ignoring you mean that the formatter leaves it in the state it was prior to formatting, or if after formatting the multiline comment is no longer there. If it's the former, this is the current expected result. If you wouldn't mind providing a before and after that'd be a huge help!

The formatter treats the entire block as if it does not exist, it does absolutely nothing to format it. I can do whatever I want inside and nothing changes. I don't recall if the opening and closing of the comment is affected but probably not.

I don't really use this style of formatting however the way it looks in the example is probably how it should look that is to say if I add spaces before `You` or `like`, or have trailing spaces, or the start/end of the comment section has incorrect indenting then the formatter should make it look like the example.

Otherwise we should stop supporting this as valid syntax and the formatter should remove it entirely.

**Comment by eureka-cpu** [comment]
The formatter does not currently have comment formatting in general, if that is what you mean?

**Comment by bingcicle** [comment]
Clearer example - the formatter ignores formatting this completely:

```rust
library comments;

fn block() {
    // ANCHOR: block
    /*
    a    b    c
ddd
 ee   f  g
    */
    let baz = 8;
    // ANCHOR_END: block
}
```

+1 on @Braqzen's point, I get a feeling that we might not necessarily need to be as fully featured as rust when it comes to comment syntax.

**Comment by sdankel** [comment]
I agree that we do not need to format inside of `/**/` comments. This is what rust does to that block:

```rust
fn block() {
    // ANCHOR: block
    /*
        a    b    c
    ddd
     ee   f  g
        */
    let baz = 8;
    // ANCHOR_END: block
}
```

Notice it indents everything, including the `*/`, which isn't desirable. 

However I found a case where the formatter clearly does the wrong thing with `/**/` comments. Inline comment with empty function:

```sway
fn my_function(my_parameter: u64 /* ... */ ) {}
```

formats to:

```sway
fn my_function(my_parameter: u64) { /* ... */ }
```
