### ISSUE TITLE
`forc fmt` hangs on an empty project

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#2934]
If `Forc.toml` is missing from a folder, `forc fmt` just hangs instead of emitting a clean error message.

**Comment by eureka-cpu** [comment]
Would you mind adding which project you ran this on? I've run it on projects without a `Forc.toml` and it _does_ produce the error message 🤔

**Comment by mohammadfawaz** [comment]
Ohhh I see what was happening. I had an empty project that lived inside another project that wasn't empty and so the `Forc.toml` from the parent project was kicking in, so `forc fmt` was taking a long time so I thought it was hanging. I will close this issue.
