### ISSUE TITLE
Add an `Either` type to the stdlib

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#2963]
It could look like this:

```rust
enum Either<L, R> {
	left: L,
	right: R,
}
```

**Comment by otrho** [comment]
I don't love `Either`, it's usually not that hard to whip up a custom struct which is more descriptive.  If `Either` were to turn up in the library it would need to impl a tonne of useful traits for it to be worth it, IMO.

I don't think we have many useful traits in Sway yet.

**Comment by anton-trunov** [comment]
FWIW, I find OCaml's standard `Result` type useful and a bit more descriptive than Haskell-inspired `Either`. In Sway-like syntax it would be 

```
enum Result<A, E> {
    ok: A,
    error: E,
}
```

**Comment by otrho** [comment]
Yeah, Haskell uses `Either` for `Result`, where we have a proper `Result` already.

**Comment by sezna** [comment]
Closing this since we seem to have reached consensus. Also, Rust's `either` is a third party library, so we can follow that trend if needed.
