### ISSUE TITLE
Add a way to specify salt with `forc-build`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2970]
Currently we do not have a CLI option to specify `Salt` while deploying contracts. https://github.com/FuelLabs/sway/pull/2958#discussion_r989633174

**Comment by adlerjohn** [comment]
#2958 seems like an overloading of `build`. Would it be better to instead add a new subcommand e.g. `forc contract-id`that does a `build` then outputs the contract ID, accepting a `--salt` parameter?

**Comment by mitchmindtree** [comment]
> https://github.com/FuelLabs/sway/pull/2958 seems like an overloading of build.

True, I guess we don't *need* the contract ID in `out/`, as the ID is more relevant to other scripts or contracts that will call into this contract :thinking:

---

Perhaps a better alternative might be to specify the `salt` for each entry under `[contract-dependencies]` instead, as the ID of a contract is generally only needed by dependents, E.g.

```toml
[contract-dependencies]
foo = { path = "../foo", salt = "blah" }
bar = { git = "https://host.com/user/repo", tag = "v1.0.0" }
```

In the above, `foo` would be built, have its contract ID generated using the salt "blah", and that ID would be provided via the const `foo::CONTRACT_ID` to our package. `bar` would be built similarly, but it's contract ID would be generated without salt (the default case with no `salt` specified) before being provided to our package as the const `bar::CONTRACT_ID`. This approach would also enable specifying a unique salt per contract dependency, which would likely be necessary for some folk.

Thoughts @kayagokalp @adlerjohn ?

**Comment by adlerjohn** [comment]
The salt is exactly and always 32 bytes, so you can't have "no salt." You could have 32 bytes of zeroes. Proposal seems fine I guess otherwise.

**Comment by kayagokalp** [comment]
I think specifying them with the `[contract-dependencies]` makes sense but if two different package depends on the same `contract` they should be providing the same `salt` to get the same contract id. Could this be confusing for the users? Maybe we could start like this and add a `salt` declaration to the members of the `WorkspaceManifest` later on. In that case we could check if the `[contract-deployment]` table entry consists the `salt` information. if it does we can use that. Otherwise check the `WorkspaceManifest`. In the absence of both we could fallback to 32 bytes of zeros.

**Comment by mitchmindtree** [comment]
> I think specifying them with the `[contract-dependencies]` makes sense but if two different package depends on the same contract (for deployment) they should be providing the same salt to get the same contract id. Could this be confusing for the users?

Good point! I think this is something that users will need to be very careful of either way, but I agree we should do our best to help them avoid make mistakes here. We should document the gotcha clearly, print the salts used and the resulting ID when building contract dependencies, and upon deployment we might even want to have an interactive step that prints the salt used for each contract dependency and asks for confirmation (with an optional flag to auto-accept)?

> Maybe we could start like this and add a salt declaration to the members of the `WorkspaceManifest` later on. In that case we could check if the `[contract-deployment]` table entry consists the salt information. if it does we can use that. Otherwise check the `WorkspaceManifest`.

Yeah I could see that being useful. One concern that comes to mind is if a project gets moved to a location outside of the workspace its `[contract-dependencies]` salts will change which might also be a bit confusing? That said, the user would likely need to change the contract dependency sources anyway, at which point they should update the salts too.

> we could fallback to 32 bytes of zeros.

Yeah I think this makes sense as a default if it's what we currently do.
