### ISSUE TITLE
Don't specify dependency versions for our internal crates

### ISSUE THREAD

**Issue by Centril** [FuelLabs/sway#2975]
Unfortunately, by specifying e.g.,:
```toml
sway-ast = { version = "0.25.2", path = "../sway-ast" }
```
we induce more merge conflicts when small version bumps are made.
Instead, we can use:
```toml
sway-ast = { path = "../sway-ast" }
```

**Comment by adlerjohn** [comment]
This doesn't work for dependencies (i.e. non-dev dependencies) for published crates, since each crate published must only depend on other crates on crates.io, not local crates.

**Comment by mohammadfawaz** [comment]
As per John's comment, I will close this.
