### ISSUE TITLE
Unused variants of the CompileError enum 

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#2977]
The following variants do not seem to be used:

- [ ] `UnknownVariablePath`
- [ ] `UnknownFunction`
- [ ] `NotAFunction`
- [ ] `InvalidByteLiteralLength`
- [ ] `ExpectedExprAfterOp`
- [ ] `ExpectedOp`
- [ ] `MultipleContracts`
- [ ] `MultipleScripts`
- [ ] `MultiplePredicates`
- [ ] `ReassignmentToNonVariable`
- [ ] `MultipleImmediates`
- [ ] `NotATrait`
- [ ] `StructNotFound`
- [ ] `DeclaredNonStructAsStruct`
- [ ] `AccessedFieldOfNonStruct`
- [ ] `MethodOnNonValue`
- [ ] `UnqualifiedSelfType`
- [ ] `ExpectedImplicitReturnFromBlockWithType`
- [ ] `ExpectedImplicitReturnFromBlock`
- [ ] `InvalidAssemblyMismatchedReturn`
- [ ] `DisallowedLw`
- [ ] `InvalidStrType`
- [ ] `TooManyInstructions`
- [ ] `FileNotFound`
- [ ] `TypeWithUnknownSize`
- [ ] `InfiniteDependencies`
- [ ] `MatchWrongType`
- [ ] `AsteriskWithAlias`
- [ ] `IfLetNonEnum`
- [ ] `InvalidVariableName`
- [ ] `ConvertParseTree`

**Comment by jtriley-eth** [comment]
Looks like `ConvertParseTree` is the only one used elsewhere, specifically for converting `ConvertParseTreeError` to `CompilerError` in these files in particular:
- [sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs](https://github.com/FuelLabs/sway/blob/master/sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs)
- [sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs](https://github.com/FuelLabs/sway/blob/master/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs)

All other errors appear to be unused and will be removed.
