### ISSUE TITLE
Reconsider Syntax/API for contract calls and decide on a final way forward.

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#298]
Right now, contract callers are not ergonomic. You must pass in the metadata as parameters to every contract call. This is not ideal.

Here are a few alternate APIs:

## Put the metadata in the initial `abi` cast.
```
let caller = abi(SomeAbi, 0x0...00, GAS, COLOR, COINS);
```
This would put those parameters in the caller itself, but of course that means you need to make a new caller for every abi call.

## Use a builder-ish 
Another option is to separate things out so that the ABI method is a builder method with defaults, for example if the default coin color is 0x00..00, coin amount is 0, and gas is all remaining gas:
```
let caller = abi(SomeAbi, 0x0...00); // default params
let caller = abi(SomeAbi, 0x0...00)  // set params explicitly using the builder
                   .forward_gas(10_000)
                   .set_color(0xff..ff)
                   .send_coins(20); 
```

## Use a proper builder with a `.build()` method
Same as above, but:
```
let caller = abi(SomeAbi, 0x0...00).build(); // default params
let caller = abi(SomeAbi, 0x0...00)  // set params explicitly using the builder
                   .forward_gas(10_000)
                   .set_color(0xff..ff)
                   .send_coins(20)
                   .build(); 
```

## Use a config struct
like `abi(SomeAbi, 0x00…, chain::call_params::default())`, and you can do `abi(SomeAbi, 0x00…, CallParams { gas: 10000, etc. })` to be specific

## Use different methods for `call()`

(from @adlerjohn):
Hmm how about something like `call` and `call_with_params`, the former forwards all gas and no coins? What's what solidity calls do. If you want to transfer ETH instead of just passing data you need to use inline assembly.

**Comment by mohammadfawaz** [comment]
Are we thinking something like this?
```rust
contract;

abi Test {
    fn call(param1: u64, param2: u64, param3: bool);
}

impl Test for Contract {
    fn call(param1: u64, param2: u64, param3: bool) {
                
    }
}

fn main() {
    let caller = abi(Test, 0xbaf516b8b50c51953a6d2f20ec1f5ff09ced2b80a9c72ea376aaf23dd6af467e);                       
    
    // Call with default values
    caller.call(42, 123);

    // Override the default values
    caller.call(33, 57, CallParams{gas:10000, 
                                 coins_to_forward:20, 
                                 asset_id:0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff});
}
```

**Comment by adlerjohn** [comment]
@mohammadfawaz your example has 3 params in the ABI and only 2 in the main 😂

**Comment by sezna** [comment]
Do we want the optional call params to be at the `.call()` site or at the point of `abi` casting? I'm mainly thinking about making successive contract calls with a non standard gas amount and needing to provide those params repetitively.

**Comment by adlerjohn** [comment]
I expect very few people will forward anything other than all the gas. What will be used often however is forwarding coins with a call, so that must be a first-class citizen essentially.

**Comment by nfurfaro** [comment]
I think in a perfect world, we start with a set of default params at the point of abi casting, but can optionally override with custom params, also at the site of abi casting.
Maybe a single call() could also override the initial custom params for a single call...

**Comment by adlerjohn** [comment]
There's no concept of `caller` though. An ABI cast is saying "this object represents a contract at this address that implements this ABI." Making the gas, amount, and asset ID part of the ABI cast rather than the call IMO is making ABI casting over-reaching in what it's doing.

**Comment by sezna** [comment]
Yes, the params struct is reusable. Another option is to attach these configurations on to the abi cast like the following:
```rust

// sane defaults
let caller = abi(Foo, 0xabcdef123456.....);

// with some conf
let caller = abi(Foo, 0xabcdef123456.....).gas(10).coins(20).asset_id(something);

```

That has the downside of being kind of complicated to implement in the compiler. `abi` results in a compiler-internal type and isn't a true function (that's how it accepts a trait name), so the above example would be difficult to implement. 

Mohammad's above example would be the most elegant from the compiler perspective, I think..

**Comment by mohammadfawaz** [comment]
If we go with my example, then we have two options:
1. Have the compiler define the struct `CallParams`. So, the code I wrote would just work without needing something like this defined in the scope of the call:
```rust
struct CallParams {
    gas: u64,
    coins_to_forward,
    asset_id,    
}
```
2. Have the compiler expect a struct of three elements in that order, of those specific types (or no struct at all, of course). Also, provide a definition of `struct CallParams { ... }` in the standard library so user don't have to define their own every time.

I like option 2. What do you think?

**Comment by mohammadfawaz** [comment]
Relevant: https://ethereum.stackexchange.com/a/97087

**Comment by nfurfaro** [comment]
>There's no concept of caller though.

This is just a naming convention that has been used in sway tests since before my time, ie:
`let caller = abi(Test, 0xbaf516b8b50c51953a6d2f20ec1f5ff09ced2b80a9c72ea376aaf23dd6af467e); `

I'm fine with @mohammadfawaz s option 2 above as well.

In the past (and in javascript) I've typically referred to this as the "contract", as it is the object which represents a given abi at a given address.

**Comment by mohammadfawaz** [comment]
Discussing this with John and Alex - it looks like the example in the stackoverflow link is the most reasonable. @nfurfaro let me know if you agree or disagree. So, something like this:
contract;
```
abi Test {
    fn call(param1: u64, param2: u64);
}

impl Test for Contract {
    fn call(param1: u64, param2: u64) {
        ...                
    }
}

fn main() {
    let caller = abi(Test, 0xbaf516b8b50c51953a6d2f20ec1f5ff09ced2b80a9c72ea376aaf23dd6af467e);                       
    
    // Call with default values
    caller.call(42, 123);

    // Override the default values
    caller.call{gas:10000, 
                    coins_to_forward:20, 
                    asset_id:0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff} (33, 57);
}
```
So the call syntax is basically `caller.call{gas: <>, coins_to_forward: <>, asset_it: <>) { .. }`.

**Comment by nfurfaro** [comment]
@mohammadfawaz That seems reasonable and easy to use.

nitpick: I think seeing the custom params passed inside the parens would make more sense to me visually, ie:
`caller.call({...}, 42, 123);`
but is perhaps more complicated to implement. I probably prefer it as I'm used to that approach from javascript, and we're not trying to imitate js :)

**Comment by mohammadfawaz** [comment]
> They actually should not be available at all directly, since they won't be parameters any more
I thought we still want them to be accessible through some compiler magic, though that's a bit convoluted. If the standard library functions are enough, then this just makes my job easier 😄

**Comment by mohammadfawaz** [comment]
@adlerjohn @nfurfaro 
We have [this test](https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/src/main.sw) that accesses the call parameters directly in the implementation of the contract methods. Is this a valid use case? 
Would this:
```rust
fn mint(gas: u64, coins: u64, asset_id: b256, mint_amount: u64) {
    mint(coins);
}
```
just become:
```rust
fn mint(gas: u64, coins: u64, asset_id: b256, mint_amount: u64) {
    mint(balance());
}
```
?

**Comment by adlerjohn** [comment]
> Is this a valid use case?

No, it's a bug in the test case.

> Would this:
> just become:

Yes.

**Comment by nfurfaro** [comment]
yeah, that's a bug in the test. it should be `mint(mint_amount) `

**Comment by nfurfaro** [comment]
this is now tested properly in the std lib

**Comment by mohammadfawaz** [comment]
@SilentCicero has provided some feedback on the new syntax so I'm reopening this issue to discuss it further. Whatever syntax we go with, the implementation that we now have will roughly be the same so I expect minimal work. However, we should all agree on what the best use model is, hopefully before the 1.0 release. I think Nick likes the version with `CallParams` struct applied somehow without the foreign syntax of adding `{ .. }` before the start of the list of arguments.

**Comment by mohammadfawaz** [comment]
I will close this case for now as there is no immediate action required. We will monitor the feedback from the community regarding the new syntax and make a decision to keep it or change it at that point.
