### ISSUE TITLE
Omitting `struct` variables in `storage` declaration crashes compiler

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#2989]
When declaring a `struct` in `storage` and omitting the struct's contents crashes the compiler. There should be an error message to handle this case and inform the user.

forc v0.25.2

Minimal Repro:

```
struct MyStruct {
    my_u8: u8,
}

storage {
    my_struct: MyStruct = MyStruct {},
}
```

![struct_in_storage](https://user-images.githubusercontent.com/54727135/195149807-703d9f5b-c617-4de8-9ffb-afd295cd064c.png)

**Comment by mohammadfawaz** [comment]
The same things happens with 
```rust
const my_struct: MyStruct = MyStruct {};
```
This is an issue in the constant evaluator which panics when it sees the `ErrorRecovery` type instead of stopping and emitting the errors that have been collected so far.
