### ISSUE TITLE
`forc test` used to implicitly `forc build` a project before running tests, whereas `cargo test` alone does not

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3026]
Previously, `forc test` was a tiny wrapper around `forc build` and `cargo test`.

# Problem

Since [removing Rust integration testing from the `forc test` command](https://github.com/FuelLabs/sway/pull/2264), users are instead encouraged to [use `cargo test`](https://fuellabs.github.io/sway/master/testing/testing-with-rust.html) directly. The current [test harness template](https://github.com/FuelLabs/sway/tree/master/templates/sway-test-rs) however does *not* automatically build the repository, and expects that the contract output artifacts available in `out/` are up to date.

# Temporary workaround

In the meantime, users can still get the original behaviour under a single command with:

```console
forc build && cargo test 
```

# Potential Solution

### `forc build` during test harness

We'll want to use `std::process::Command` rather than using `forc` or `forc-pkg` as a direct dependency to ensure that the version of forc in use matches the user's command line version of forc. Otherwise, we run the risk of incompatibilities resulting in strange behaviour. Using `std::process::Command` also keeps the build times much lower.

Ideally, we'd do something like this:

```rust
Command::new("forc").arg("build").output().expect("failed to build contract");
```
at the beginning of `get_contract_instance` or similar.

However, the problem is that by default tests are run in parallel, meaning that if the user has 10 tests, 10 `forc build` invocations will run at once. We can disable the default test harness with `harness = false`, however this adds a little complexity and means we lose lots of the nice benefits of the default harness like automatically running the test functions and printing nice output. Using something like the [`test_context` crate](https://docs.rs/test-context/latest/test_context/) might allow for both.

**Comment by mohammadfawaz** [comment]
Do we want the SDK to have a dependency on `forc`? One motivation for the [current design of configuration-time constants](https://github.com/FuelLabs/sway-rfcs/pull/19) is to avoid having the SDK recompile the contract every time the constant is updated. I think the SDK had a dependency on `forc` in the past but we change that to simplify things a bit.

That being said, do you feel that compiling the contract using `forc build` before testing is a real ergonomic issue? `forc test` used to do both and so we somewhat took this functionality away, but I feel like _compiling_ a program and _running_ its tests in two separate stages is a common pattern in standard software development flows.

**Comment by mohammadfawaz** [comment]
> To clarify, this issue does not propose adding the functionality to the SDK, but rather to the test harness template itself.

Ah yes, that makes sense to me. Sorry, I misunderstood earlier! Thanks.

**Comment by sdankel** [comment]
The templates use the `abigen!` macro which requires the project to be compiled already. The template could use a cargo [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to run `forc build` automatically before `cargo test` runs the test code.
