### ISSUE TITLE
Introduce storage references (or `StorageKey`)

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3043]
## Motivation

While the current use model model for storage is quite ergonomic, it is missing an important element to enable important features such as:

1. The ability to read/modify an arbitrary storage variable in functions.
2. The ability to read/modify an arbitrary storage variable in libraries.
3. The ability to compose storage collections such as `StorageVec<StorageVec<T>>`.
4. The ability to have a storage collection in a struct.

We always seem to come back to the idea of a "storage reference" every time any of the above use cases are discussed.

## Proposals

There are two ways of introducing storage references.

### Method 1

The first approach changes the expression `storage.<>` to return a storage reference. The reference can then be passed to function arguments and can be de-referenced via `deref()`. So, code that previously looked like
```rust
storage.x += 1;
```
would now look like
```rust
storage.x.deref() += 1;
```

The type of `storage.x` in this case would be some generic type called `StorageRef<T>` which contains enough information about the "location" of the storage variable. This could be a simple index or a list of indices in the case of a nested struct (i.e. whatever is needed to generate the storage keys for the variable).

### Method 2

The second approach is very similar to the the first one except that it does not modify the meaning of `storage.<>`. Instead, we make storage references opt-in via an `as_ref()` call or a `ref` prefix such as:
```rust
let some_ref = storage.x.as_ref();
```
or
```rust
let some_ref = ref storage.x;
```

## Implementation Details

A lot of the implementation details still have to be worked out, but we will need a special type called `StorageRef<T>` that represents the reference type in question. We have to decide on what it contains exactly and how "special" it is. 

## Code examples

Here's how accessing a storage variable in a library would look like:

```rust
// Library
library lib;

fn increment_var(storage_ref: StorageRef<u64>) {
    storage_ref.deref() += 1;
} 
```

```rust
// Contract

storage {
    x: u64,
}

fn some_contract_method() {
    // Local updates
    storage.x += 1; // or storage.x.deref() += 1 if we go with Method 1
    
    // Library update
    increment_var(storage.x.as_ref()); // or increment_var(storage.x) if we go with Method 1
}
```

Edit: I've started working on [this RFC](https://github.com/FuelLabs/sway-rfcs/pull/23) which follows mostly Method 2 above. Before we fully implement that RFC, we need to implement the following:
- [x] #4045
- [ ] #4010
- [x] #4046
- [x] #4047

**Comment by estill01** [comment]
How practical would it be to do this?:

# Method 3

Adopt **Method 1**, but manage the use of references in the compiler.

Backwards compatibility is maintained and additional `deref()` step is avoided. 

Then, also enable explicit use of `as_ref()` to allow people to do things with these pointers in their code / apps.

**Comment by mohammadfawaz** [comment]
Right, I do like backward compatibility :) Is Method 3 similar to Method 2? If not, how are they different? The compiler already handles references internally, and by references here I mean just keys really.

**Comment by estill01** [comment]
Maybe I'm misunderstanding things. Core idea is to not change what code app developers type, but instead 'invisibly' insert this reference syntax/functionality at compile.

**Comment by mohammadfawaz** [comment]
Also, a very long related discussion [here](https://github.com/FuelLabs/sway/issues/2585) may also be of interest to you.

**Comment by mohammadfawaz** [comment]
> Core idea is to not change what code app developers type, but instead 'invisibly' insert this reference syntax/functionality at compile.

Yup! Thanks for clarifying. 

Today, when you write `.. = storage.x` or `storage.x = ..`, the compiler will decide on a storage key (basically a hash) at which `x` will be stored (or read from). This key is effectively a reference/pointer. Unlike regular memory, storage is a set of key-value pairs and not sequentially memory-mapped. So, in a way, the compiler is already "invisibly" inserting the reference and they using it, all in one go. And then you suggest an `as_ref()` to actually get that reference if needed, which makes total sense. I think we're on the same page?

**Comment by estill01** [comment]
> I think we're on the same page?

I'm not sure

See:
> So, code that previously looked like
> 
> `storage.x += 1;`
>
> would now look like
> 
> `storage.x.deref() += 1;`

Goal is to get all the benefits of introducing the `StorageRef<T>` type without having to change how we write our code / breaking backward compatibility:

`storage.x += 1` remains `storage.x += 1`, but somewhere along the way - maybe in the definition of `+=` or maybe in a pre-compile stage or elsewhere, `storage.x +=1` effectively gets rewritten to `storage.x.deref() += 1`.

Maybe this makes no sense though(?); would need to do more homework to get up to speed on this all.

**Comment by mohammadfawaz** [comment]
@estill01 yeah I think this makes sense! We can definitely do some de-sugaring and transform `storage.x += 1` into `storage.x.deref() += 1`. If I understand correctly, you're suggesting that the expression `storage.x` _is a reference_ but when we write `storage.x += 1`, then this operation becomes `storage.x.deref() += 1`? My one worry with this is that when we write `let r = storage.x`, does this mean `r` is a reference? If yes, then do we still have to write `let r = storage.x.deref()` to get the actual data?

**Comment by otrho** [comment]
IMO storage is tricky (as in the constraints it imposes) and costly and most operations around using it should be fairly explicit.  We should not be pretending that storage values are just like globals and can be easily/cheaply accessed and modified.

**Comment by estill01** [comment]
> If I understand correctly, you're suggesting that the expression storage.x is a reference but when we write storage.x += 1, then this operation becomes storage.x.deref() += 1?
@mohammadfawaz  Yep!

> My one worry with this is that when we write let r = storage.x, does this mean r is a reference? If yes, then do we still have to write let r = storage.x.deref() to get the actual data?
Yes; does seem the same pattern should apply and the `deref` call should be sugared over and injected/managed during compile.

A user could still explicitly use `as_ref()` to get the reference object and manually manage it; this might require that `as_ref()` returns something like a `ManualStorageRef<T>` type.

**Comment by estill01** [comment]
@otrho Motivation is to enable resolution of #2465 which (IMO) significantly enhances developer experience / ease-of-use
