### ISSUE TITLE
Hanging Impl causes ICE

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/sway#3052]
Was writing some Sway code and ran into an ice, I froze it on a branch [here](https://github.com/sway-libs/amm/blob/ice_report/src/concentrated/I24.sw#L173), but that was the issue line

`impl core::ops::` caused the compiler to break with

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/controlc/.cargo/registry/src/github.com-1ecc6299db9ec823/sway-parse-0.24.5/src/parser.rs:42:14
```

**Comment by mohammadfawaz** [comment]
Yeah this is one of those situations where the span math is wrong. Removing the `+1` in https://github.com/FuelLabs/sway/blob/335f4b03ee37a650a0302a74d0e9b65bf5d097ba/sway-parse/src/parser.rs#L40 fixes this particular issue but breaking other stuff. We may need to recompute the limits in that function differently.
