### ISSUE TITLE
Language Server needs to work with multiple projects simultaneously 

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#3069]
Currently, the language server can only work when a single project is loaded into the users editor. 

However, if the user opens up a projects folder, and then opens up a split window, with one project on the left and another project on the right, the language server will crash because of internal access to the global memory in the compiler. For example

```
thread 'main' panicked at 'index out of bounds: the len is 165726 but the index is 165778', sway-core/src/concurrent_slab.rs:38:9
```

This is because in the server, we call `forc_pkg::check()` on a project to produce the AST's. However, at the beginning of this function, all the global memory `lazy_static!`s are cleared. 

I feel like this is causing such a terrible UX experience that we should prioritize ripping out using global memory in the compiler once and for all :) There is an issue for this in #2063

**Comment by mohammadfawaz** [comment]
Yeah we're prioritizing the removal of lazy statics; @Centril is going to work on this soon 😃

**Comment by mohammadfawaz** [comment]
I'm going to close this in favor of https://github.com/FuelLabs/sway/issues/2063
