### ISSUE TITLE
Consider moving FuelVM specific IR operations to a `fuelvm` specifc wrapper.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#3071]
There are some IR instructions like `gtf`, `get_storage_key`, `log`, `read_register`, `revert` and the `state_` operations which are specific to the Fuel VM.

They stick out a bit as being non-generic, and as we prepare to support other targets like the EVM it'd be good for them to be grouped together somehow.

A parent instruction like `fuelvm` could wrap them so logically we have a distinction between generic IR (for arithmetic, control flow and memory R/W) and these special ops.

**Comment by arzg** [comment]
Hiya 👋, I’ve had a go at implementing this, but I’m not sure if I’ve missed anything. I’ve locally prepared a PR with `Instruction::GetStorageKey`, `Instruction::Glf`, and all the other instructions in that list extracted into a separate `FuelVmInstruction` enum. Are there any such other FuelVM-specific instructions I should include? `Instruction::Smo` looks like it should be, but I thought I’d double-check first :)

(For context I’m starting work on a Polygon Mine backend for Sway, for which this should prove useful.)

**Comment by otrho** [comment]
Cool!  So yeah, the list above, plus `smo` as we introduced that more recently.

ASM blocks will also need to be abstracted somehow but that's for a different PR, and hopefully `contract_call`s will be generic enough to be back-end agnostic.  When designing the calling mechanism in Sway and then the IR we didn't yet plan on supporting anything other than FuelVM.

But for now having the above instructions wrapped in a `fuelvm` style instruction will be a good start.
