### ISSUE TITLE
Introduce a `Bytes` type in the standard library

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3078]
This would the same as ` Vec<u8>` without all the padding. So it would be a heap type like `Vec` but not generic, and allows and inserts bytes contiguously (so 8 separate bytes per words, etc.).

**Comment by otrho** [comment]
So a bit like `String` from rust except without the UTF-8...

**Comment by mohammadfawaz** [comment]
Yeah - We do have a Sway `String` library [here](https://github.com/FuelLabs/sway-libs/tree/master/sway_libs/src/string) but it's closer to `Vec` really.
