### ISSUE TITLE
Abort control flow in control flow analysis/dead code analysis when `std::chain::revert()` is called

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#308]
Similar to rust's `panic!()`

**Comment by nfurfaro** [comment]
I'm not sure how big a change this is, but it's one of 2 blockers to implementing `unwrap()` for the `Result` type, the other one being `if let`'s which are almost completed.
blocked PR: https://github.com/FuelLabs/sway-lib-std/pull/47

**Comment by adlerjohn** [comment]
Rather than relying on specifically `std::chain::revert()` (which may be moved/renamed, or there many be a number of functions that revert), the analysis should use the `RVRT` instruction in asm blocks (i.e. prior to code generation, just looking at the asm blocks that are in the code already).
