### ISSUE TITLE
Incorrect compiler warning "This declaration is never used"

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#3093]
In the following image you can see the compiler warning about a declaration never being used, but this error enum is used in 2 different files. For now this can be reproduced by checking out the branch `furnic/bridge-token-contract` in the repo: https://github.com/FuelLabs/bridge-fungible-token. from there, `cd` into the inner `bridge-fungible-token` directory and run `forc build`.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/17053076/197067029-a6c90c23-42c2-4d99-a948-3d0f4107512b.png">

**Comment by mohammadfawaz** [comment]
From @nfurfaro:

This issue is a bit of a blocker for the bridge. No idea how to repro this in a more minimal way, as we import and use deps like this all the time without an issue.

**Comment by pixelcircuits** [comment]
I ran into this same issue for the bridge predicates repo. Forc no longer supports testing, but they were Cargo tests anyway so all that's needed is to run the tests via Cargo vs Forc. See https://github.com/FuelLabs/bridge-message-predicates/pull/11/commits/2452de9d12fe6a7f85b65396c90edd904f9363b2

**Comment by nfurfaro** [comment]
thank you @tritao !
