### ISSUE TITLE
Disallow functions defined inside other functions

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3097]
Example
```rust
script;

fn main() {
    fn bla() { }
}
```
This fails to compile with an ICE:
```console
Internal compiler error: Unexpected function declaration found.
Please file an issue on the repository and include the code that triggered this error.
```

It would be better if this was a clean parser or frontend error instead.

**Comment by mohammadfawaz** [comment]
We may want to support this in the future, but we need a better error message for the time being.

**Comment by otrho** [comment]
I'd say we definitely want it in the future.  A 'coming soon' error would be better, yes.
