### ISSUE TITLE
Formatter deletes the rhs of an expression!

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#3104]
To reproduce this, paste the following into any valid sway code and format it.

```
let a = 12;
let a = 5;
let c = 27;
let d = c * (10 ** (a - b));
```

**Comment by mohammadfawaz** [comment]
So the parser does not currently handle `**` right? The above code does not compile. The first step is probably to add `**` as a valid token and make it de-sugar to `pow` just like we do with addition and other binary ops.

**Comment by nfurfaro** [comment]
@mohammadfawaz yeah, a few things going on here.
The formatter thing is one issue, but as you mentioned this doesn't currently compile.
Also, I started on an Exponentiation trait with a `pow` method, but it's not on `master` yet because of this issue: https://github.com/FuelLabs/fuel-vm/issues/150

**Comment by bingcicle** [comment]
Is this being worked on already or blocked by something? Would like to pick this up otherwise

**Comment by bingcicle** [comment]
> would you like to do the compiler work blocking this?

Wouldn't this just be handling the `Expr::Pow` case within `expr_to_expression` [here](https://github.com/FuelLabs/sway/blob/78065488091b6f0e4c1b21ebcf4930a90bb202e0/sway-core/src/convert_parse_tree.rs#L1130) or am I missing something more complicated here?

**Comment by mohammadfawaz** [comment]
Nothing complicated really. Basically what you suggested, starting with:
1. `**` should be handled like `+`. So first, you need the `**` token similarly to https://github.com/FuelLabs/sway/blob/37dbe4b3c13a5d24762ab520a240732cea0ced94/sway-ast/src/keywords.rs#L182 and https://github.com/FuelLabs/sway/blob/37dbe4b3c13a5d24762ab520a240732cea0ced94/sway-parse/src/keywords.rs#L135. 
2. You then have to handle it in `convert_parse_tree.rs`, like `Add` here https://github.com/FuelLabs/sway/blob/37dbe4b3c13a5d24762ab520a240732cea0ced94/sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs#L1571

**Comment by bingcicle** [comment]
OK, it seems like I was on the right track then (already started on it). For happy path tests, would a new test program be initialized within `should_pass/language`, with the same values tested [here](https://github.com/FuelLabs/sway/blob/e1f8702185aeedf3300f4b3cb107eb20acc6cedc/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/src/main.sw) be ok?

Also, perhaps unrelated question but what is the significance of initializing max values eg. `~u64::max()` in the above linked test? And is there any significance to the values tested as well?

**Comment by mohammadfawaz** [comment]
> For happy path tests, would a new test program be initialized within should_pass/language, with the same values tested [here](https://github.com/FuelLabs/sway/blob/e1f8702185aeedf3300f4b3cb107eb20acc6cedc/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/src/main.sw) be ok?

I would just add the new tests in the same program. Same ones but using `**` is probably fine.

> what is the significance of initializing max values eg. `~u64::max()`?

Nothing really.. Feel free to remove them 😄 

> And is there any significance to the values tested as well?

Not particularly. Mostly stress testing the operation with small and large numbers.
