### ISSUE TITLE
Extended character count on match arms with 2 arguments causes weird formatting

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#3131]
When implementing a match statement that has 2 arguments, we see weird formatting behavior if the character count reaches a threshold. There is an additional empty line added to the match arm arguments.

For example in the following, we do not reach the threshold with `short_name` and the formatting is as intended:

```
    let result = match (enum1, enum2) {
        (MyEnum::MyStruct1(short_name), MyEnum::MyStruct1(name_2)) => {
            MyEnum::MyStruct1(name_2)
        },
        _ => {
            revert(0)
        }
    };
```

However, when using longer variables names such as replacing `short_name` with `a_very_long_variable_name`, we see the following formatting:

```
    let result = match (enum1, enum2) {
        (

            MyEnum::MyStruct1(a_very_long_variable_name),
            MyEnum::MyStruct1(name_2),
        ) => {
            MyEnum::MyStruct1(name_2)
        },
        _ => {
            revert(0)
        }
    };
```

The resulting formatting has an empty line. This is not dependent on the variable name itself, but the length of the match arm statement. If we replaced `MyEnum` with `AVeryLongEnumName`, the same formatting error occurs.

```
    let result = match (enum1, enum2) {
        (

            AVeryLongEnumName::MyStruct1(short_name),
            AVeryLongEnumName::MyStruct1(name_2),
        ) => {
            AVeryLongEnumName::MyStruct1(name_2)
        },
        _ => {
            revert(0)
        }
    };
```

**Comment by Braqzen** [comment]
Has this been tested on the latest release?
