### ISSUE TITLE
Temporarily disallow `asm` blocks from writing an initialized registers

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3155]
This is due to the addition of `mem2reg` in https://github.com/FuelLabs/sway/pull/3128. Some odd patterns arise when you allow `asm` blocks to ~~read and write the same value in IR, which causes `mem2reg` not to behave well. In any case, we should disallow these patterns temporarily until https://github.com/FuelLabs/sway/issues/2819 is resolved and we have a better mental model regarding `asm` blocks in IR.~~ write an initialized register.

I think this change can be done in the parser or type checking. Example use cases:

~~Reading and writing the same register in the same instruction~~
Writing register `r1` even though `r1` is initialized to `ptr`.
```rust
    asm(r1: ptr) {
        lw r1 r1 i0;
        r1: u64
    }
```

~~Reading and writing the same register in different instructions~~
Writing registers `r1` and `r2` even though both are initialized.
```rust
    asm(r1: ptr1, r2: reg2) {
        lw r2 r1 i0;
        lw r1 r2 i0;
        r1: u64
    }
```

**Comment by otrho** [comment]
Checks like these could be permanent IMO, at least in the form of warnings.

**Comment by mohammadfawaz** [comment]
I spoke the @vaivaswatha and the real requirement here is that a register cannot be both _initialized_ in the args list of the `asm` block AND be assigned to in the body of the block. So my examples above are correct, but my accurate is not accurate.
