### ISSUE TITLE
`forc doc` - add a sidebar for quick navigation

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3170]
Currently, `forc doc` presents items in a single page. E.g. here's the doc root of `std`:

![Screenshot from 2022-10-27 23-27-35](https://user-images.githubusercontent.com/4587373/198286903-766cb525-9d1e-4ecb-9ac9-dd1587784fdd.png)

We should present a sidebar for easier navigation between items / sections at a higher level like `docs.rs`, e.g.

![Screenshot from 2022-10-27 23-37-32](https://user-images.githubusercontent.com/4587373/198287172-51edb0bb-609e-417e-9bbb-f80494cdacd5.png)

cc @eureka-cpu as I feel like I remember seeing something about a sidebar in #2869? Is this maybe implemented but just not showing up in certain contexts?

**Comment by eureka-cpu** [comment]
The sidebar is there it just doesn't have the items in it yet!
