### ISSUE TITLE
Generate an error when `raw_ptr` is used in storage

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#3180]
Just recently, there have been a few issues where discord users have tried to throw `Vec`s in storage. Since we have `raw_ptr` now, we should be able to throw a compile error if one is included in contract storage. We'd want to throw an error here since `raw_ptr` points to ephemeral memory, and it will become a dangling ptr as soon as the contract call ends.

**Comment by mohammadfawaz** [comment]
I believe this is nor resolved with https://github.com/FuelLabs/sway/pull/3777
