### ISSUE TITLE
Add a compiler flag that promotes compile warnings to compile errors

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#3190]
We should consider adding a user-facing compile-time flag that promotes compile warnings to compile errors. That way users have the ability to opt-in to having the Sway compiler fail to build/deploy their contract in the event of unused `mut` variable, etc.

This is related to upgrading E2E testing: #3189

**Comment by ef3n9r98** [comment]
Hi @emilyaherbert, Fuel has a _ton_ of open issues in the Sway repo. Are these meant for team members of Fuel or for all devs? And would you be willing to compensate devs if they solve an issue?

**Comment by otrho** [comment]
https://github.com/FuelLabs/sway/issues/3174#issuecomment-1347571454
