### ISSUE TITLE
Omitting `Option` type when calling `std::storage::get` results in internal compiler error

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#3196]
When calling the `get` method from the standard library's storage library and omitting the `Option` type will crash the compiler. 

For example, the following function results in the error shown below:

```
    #[storage(read)]
    fn test_function() {
        let result = get::<Option>(VAL);
    }
```

![generic_crash](https://user-images.githubusercontent.com/54727135/198845977-0e6d1208-5695-4747-94c5-d30419574289.png)

This has been tested with forc v0.25.2

**Comment by mohammadfawaz** [comment]
What is the use case for needing `store` and `get` insets of the usually storage syntax?

**Comment by bitzoic** [comment]
> What is the use case for needing `store` and `get` insets of the usually storage syntax?
> 
> I am actually thinking we should make those functions private (i.e. remove `pub`). I can think of two use cases for them, which is why we haven't done that yet:
> 
> * Arrays (not `Vec`) in storage because arrays are not supported in storage blocks yet.
> * Accessing storage in libraries (this is WIP).

I am currently using this for storage in libraries in https://github.com/FuelLabs/sway-libs/pull/42

**Comment by emilyaherbert** [comment]
Could you provide a MRE @bitzoic? I wasn't able to reproduce the error.

**Comment by mohammadfawaz** [comment]
bump @bitzoic

**Comment by sezna** [comment]
On forc `0.31.1`:
```rust
contract;

use std::storage::get;

pub const VAL = 0x0000000000000000000000000000000000000000000000000000000000000000;

abi MyContract {
    #[storage(read)]
    fn test_function();
}

impl MyContract for Contract {
    #[storage(read)]
    fn test_function() {
        let result = get::<Option>(VAL);
    }
}
```

-- from @bitzoic

**Comment by bitzoic** [comment]
Not the exact same error message I was getting before but still an internal compiler error:

`Internal compiler error: Error recovery type cannot be resolved in IR.
Please file an issue on the repository and include the code that triggered this error.`
