### ISSUE TITLE
`forc-client` fails to deploy contracts signed via `forc-wallet`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#3200]
Currently `forc-client` cannot deploy to any `fuel-core` version as it prints out wrong entity to sign. Trying to sign via `forc-wallet` or running test suite against utxo validation enabled `fuel-core` results in the following error:

```
Error: Response errors; Invalid transaction: Transaction validity: InputInvalidSignature {
    index: 0,
}
```

It looks like the default sign operation we are doing for preventing collisions also does not work but CI fuel-core does not enable `--utxo-validation` so it does not break testing suite.

**Comment by mohammadfawaz** [comment]
0.28.1 does not support fuel-core 0.11.2. That coming in the next release.

**Comment by kayagokalp** [comment]
Hmm, I will edit the issue then but currently `forc-client` cannot deploy to any version of `fuel-core` while . And linked PR can deploy to `fuel-core` v0.11.2 🤔. I cannot reach to slack rn but there was a long discussion about the issue

**Comment by mohammadfawaz** [comment]
> is the support for 0.11.2 already merged?

[Yup!](https://github.com/FuelLabs/sway/pull/3054), but not released yet.
