### ISSUE TITLE
Implement `ge` and `le` for `U128`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3221]
https://github.com/FuelLabs/sway/pull/3053 attempts to introduce `ge` and `le`. Sadly, to do this properly, we need to be able to write 
```rust
impl core::ops::OrdEq for U128 {
    fn ge(self, other: Self) -> bool {
        ...
    }

    fn le(self, other: Self) -> bool {
        ...
    }
}
```
which doesn't work (yet) due to https://github.com/FuelLabs/sway/issues/1667

**Comment by bitzoic** [comment]
Closed by https://github.com/FuelLabs/sway/pull/6048
