### ISSUE TITLE
improve LSP dealing with imports

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/sway#324]
current LSP implementation is oblivious to dependencies/imports from other files,
that is, it does not know from which (other) file was a value imported - so consequently we cannot make changes across the whole workspace, only within a single file.

@sezna informed me that Span contains path to a File, but for me that value is always None,
will update here, after discussing it some more with Alex, and then either fix it on my side or report a bug on compiler side

**Comment by JoshuaBatty** [comment]
This should be mostly resolved now.
