### ISSUE TITLE
Create an `assert_eq` function that checks for equality and reverts with the given value if inequality is found

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#3242]
I'd really like to see an `assert_eq` that reverted with the given value if inequality is found.

So in this example:

```rust
script;

use std::assert::assert_eq;

struct Data {
	value: u64,
}

fn main() {
	let data = Data {
		value: 7,
	};
	assert_eq(data.value, 1);
}
```

This would revert with the value "7". I haven't thought too hard about what this would look like for more complicated cases like structs and such though.

**Comment by mohammadfawaz** [comment]
> that reverted with the given value if inequality is found

What is the reasoning for this? I get that `assert_eq` would be useful, but why should the revert signal be the same as the first value?

**Comment by emilyaherbert** [comment]
> What is the reasoning for this? I get that `assert_eq` would be useful, but why should the revert signal be the same as the first value?

When an assert like `assert(foo == 42)` fails, all that I see as a user is `Revert(0)`. If I want to see what the value is of `foo` is, I have to either add a `log(foo)` before the assert (logs the value of `foo` even if the assert succeeds) or rewrite that bit to a manual `if` expression. So an `assert_eq` that reverts with that value (or does something comparable), might be a good solution to this.

In Rust for instance, `assert_eq` panics with the values contained on the left and right, I believe.

**Comment by mohammadfawaz** [comment]
> In Rust for instance, `assert_eq` panics with the values contained on the left and right, I believe.

Oh! If that's the case, then I'm all for it :)

**Comment by nfurfaro** [comment]
If `foo` is a struct what would that look like to the user, i.e: what would the receipt look like, `Revert(...)?
It could be implemented similar to `require` where a failing `assert_eq`:
- 1. logs the 2 values,
- 2. reverts with a special code to signify to toolling (SDK) to decode the preceding 2 log/logd receipts

**Comment by mohammadfawaz** [comment]
Yeah without a `rvrtd` opcode, we can't do much when comparing complex types. Instead, we can do what `require` does as you said:
```rust
fn assert_eq<T>(v1: T, v2: T) where T: Eq {
    if (v1 != v2) {
        log(v1);
        log(v2);
        revert(0xffff_ffff_ffff_0004);
    }
}
```

**Comment by nfurfaro** [comment]
@emilyaherbert Would the example above be a reasonable way forward for achieving what you want?
It would offload the work of decoding the logs to the SDK rather than the compiler I guess, buts that's what we do for requires already so maybe this is fine?

**Comment by emilyaherbert** [comment]
Sorry for the delay in reply---OOO.

> @emilyaherbert Would the example above be a reasonable way forward for achieving what you want?

Yes I think so!
