### ISSUE TITLE
implement LSP handling of multiple same names within a single file 

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/sway#325]
currently LSP does not differentiate variables with same names within different scopes, so could be a cause for potential bugs

**Comment by JoshuaBatty** [comment]
The language server now has infrastructure for mitigating this sort of problem. 

See the `all_references_of_token` fn [here](https://github.com/FuelLabs/sway/blob/master/sway-lsp/src/core/session.rs#L110).
