### ISSUE TITLE
Sway formatter removing generic traits type parameters

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3252]
E.g. 

```rust
script;

pub trait From<T> {
    fn from(b: T) -> Self;
    fn into(self) -> T;
}

fn main() {}
```
becomes
```rust
script;

pub trait From {
    fn from(b: T) -> Self;
    fn into(self) -> T;
}

fn main() {}
```
I'm assuming that trait type parameters are just ignored as this is a new feature.

**Comment by eureka-cpu** [comment]
At the time, I did implement generics as they were available. For any new language features we will need to make formatter issues to accompany them. For instance the recent removal of `~` !

**Comment by mohammadfawaz** [comment]
> At the time, I did implement generics as they were available. For any new language features we will need to make formatter issues to accompany them. For instance the recent removal of `~` !

That's a very good point. We'll be better at that, potentially via the PR description template I proposed in an issue recently.
