### ISSUE TITLE
Add a `#[test(should_revert)]` attribute to indicate a unit test should revert

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3260]
Tests decorated with `#[test(should_revert)]` should "pass" in the case that they exited with `ProgramState::Revert(_)`.

**Comment by mitchmindtree** [comment]
cc @kayagokalp IIRC, using the IR metadata could be the way to go here w.r.t. passing "revertness" information through to the compiled asm result.

#3266 is related, in that it's also about passing info through to the asm-gen stage.

Perhaps ideally, we'd have some way of mapping the generated test entry points to their matching function declarations - then rather than having to pass loads of information through IR metadata, we would just need to pass through the TypeId or the DeclId or something like that, and then use that ID to look up that function.

cc @otrho in case you have any thoughts/tips on this :)

In implementing basic initial support for `#[test]` and `forc test`, I managed to get through without dealing with this as it turned out to be potentially useful to have entry information in the IR itself, so in the end I just detected tests by finding entry points that weren't main or abi methods :smiling_face_with_tear:

**Comment by kayagokalp** [comment]
> Perhaps ideally, we'd have some way of mapping the generated test entry points to their matching function declarations

Nice, I was basically implementing this but collecting the whole declaration struct, collecting type/decl id instead sounds cool!
