### ISSUE TITLE
Provide compiler support for rename LSP functionality

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#327]
This will help with #325 

The language server needs a way to know the following two `foo` symbols are different:
```rust
let foo = 12;
let bar = {
    let foo = 13;
    foo + 131
}

let x = foo + foo;
```

One possible solution would be to include some sort of key with variable expressions that is unique based on the declaration it refers to. This could be a reference to the declaration itself, the declaration's span, or some other kind of key.

**Comment by JoshuaBatty** [comment]
The language server can now be able to handle code like this. As we track the declaration of each token, we can call functions such as [`all_references_of_token`](https://github.com/FuelLabs/sway/blob/master/sway-lsp/src/core/session.rs#L110) which understands token references and scopes etc..
