### ISSUE TITLE
Illegal use of a generic crashes compiler

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#3270]
As a victim of "Find and Replace", I have stumbled upon a case that crashes the compiler.

The illegal use of trying to call a function from a generic such as `new()`  will make the compiler panic:

```
    fn test_function(self, value: T) {
        T::new();
    }
```
![illegal_use_of_generic](https://user-images.githubusercontent.com/54727135/199768274-44a45c43-85ad-4255-8314-efc6ac7fb62c.png)

**Comment by mohammadfawaz** [comment]
> entered unreachable code

Well clearly that code is reachable 🤣
