### ISSUE TITLE
Document `raw_ptr` in the Sway book

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3299]
Given that `raw_ptr` is now a primitive type, it would be nice to mention it in the book. We really don't want end users to use this but library authors might want to (to build heap type data structures for example) so it needs a spot somewhere in the book.

**Comment by AlicanC** [comment]
Hmm, do we really? I thought this and `raw_slice` were too unsafe for us so we'd rather get rid of them ASAP in favor of their typed variants.

**Comment by mohammadfawaz** [comment]
Closing - these types may be temporary and they should probably go in the reference if anything.
