### ISSUE TITLE
ICE on simple code with returns statements in `if/else`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3303]
Code:
```rust
contract;

abi MyContract {
    fn foo() -> u64;
}

impl MyContract for Contract {
    fn foo() -> u64 {
        let x: u64 = if true {
            return 0;
        } else {
            return 1;
        };

        return 2;
    }
}
```
This is a reduced version of a project provided by someone in Discord. The intent was to write this:
```rust
    fn foo() -> u64 {
        let x: u64 = if true {
            0
        } else {
            1
        };

        return 2;
    }
```
which works, but the original code should not cause an ICE either.
ICE:
```console
error: Internal compiler error: Verification failed: Store value and pointer type mismatch.
```

**Comment by otrho** [comment]
I'm starting to think that `return` isn't worth it.  If you can't refactor your functions into single expressions with implicit returns then you're not worth your salt.

Ha, ha, I kid.  Yeah, of course we need `return`. :roll_eyes: But I am getting a bit annoyed with this diverging stuff.  Andrew's `never` primitive is probably a good alternative which we should add sooner rather than later, as a primitive type.

**Comment by emilyaherbert** [comment]
>  Hrmm, actually no, I guess the above code wouldn't type-check, since the type of x would be ! instead of the ascribed u64.

I think we are thinking about "never types" the wrong way---the code you're talking about should type check because there is a type ascription. If we instead define the never type to be `TypeInfo::Never(TypeId)` and type check `return 0;` (and `return 1;`) to `TypeInfo::Never(TypeInfo::Uknown)`, then the statement type checks appropriately because the type ascription would allow for type inference to unify the type of `u64` with `TypeInfo::Uknown`. If there were no type ascription, the type of `x` would type check to `TypeInfo::Never(TypeInfo::Uknown)`.

**Comment by otrho** [comment]
So you're saying multiple `!`s which normally coerce to any other type would coerce to each other down into `()`?

I haven't checked but I imagine this is what's happening now in the IR -- it's trying to assign `unit` to `x`.

So this issue as it currently stands, forgetting `never` for a minute, is still a type checking issue and not about IR gen or verification.

**Comment by emilyaherbert** [comment]
Hi @otrho, sorry for the delayed reply---OOO.

Let me back up (and slightly change what I said in my previous comment). It's not clear to me what is currently happening under the hood to produce this bug, but here is my belief of what should be happening, in a perfect world: The expression `return 0` should type to the `never` type, although the statement `return 0;` (note the `;`) should type to `TypeInfo::Tuple(vec!())`. If this were to be the case, then our existing typing rules are sufficient for resolving this bug.

**Comment by vaivaswatha** [comment]
This program

```rust
script;                                                                                                                                                                                                      
                                                                                                                                                                                                             
use std::logging::log;                                                                                                                                                                                       
                                                                                                                                                                                                             
fn main() -> u64 {                                                                                                                                                                                           
    let x: u64 = if true {                                                                                                                                                                                   
        return 0;                                                                                                                                                                                            
    };                                                                                                                                                                                                       
    return 2;                                                                                                                                                                                                
}
```

fails to compile with the error
```error
  --> /home/vaivaswatha/c/working/sway1/src/main.sw:6:18
   |
 4 |   
 5 |   fn main() -> u64 {
 6 |       let x: u64 = if true {
   |  __________________^
 7 | |         return 0;
 8 | |     };
   | |_____^ Mismatched types.
expected: u64
found:    ().
help: Variable declaration's type annotation does not match up with the assigned expression's type.
 9 |       return 2;
10 |   }
   |
____
```

So this just looks like a bug in `if_expression::instantiate_if_expression`. Assigning myself to fix.

**Comment by vaivaswatha** [comment]
> This program
> 
> ```rust
> script;                                                                                                                                                                                                      
>                                                                                                                                                                                                              
> use std::logging::log;                                                                                                                                                                                       
>                                                                                                                                                                                                              
> fn main() -> u64 {                                                                                                                                                                                           
>     let x: u64 = if true {                                                                                                                                                                                   
>         return 0;                                                                                                                                                                                            
>     };                                                                                                                                                                                                       
>     return 2;                                                                                                                                                                                                
> }
> ```
> 
> fails to compile with the error
> 
> ```
>   --> src/main.sw:6:18
>    |
>  4 |   
>  5 |   fn main() -> u64 {
>  6 |       let x: u64 = if true {
>    |  __________________^
>  7 | |         return 0;
>  8 | |     };
>    | |_____^ Mismatched types.
> expected: u64
> found:    ().
> help: Variable declaration's type annotation does not match up with the assigned expression's type.
>  9 |       return 2;
> 10 |   }
>    |
> ____
> ```
> 
> So this just looks like a bug in `if_expression::instantiate_if_expression`. Assigning myself to fix.

This is an incorrect example and my thoughts (and assumptions) on this were wrong. We want the original code snippet to actually compile (as it does in rust) and not throw a type error (which is what I incorrectly understood based on the comments above).
