### ISSUE TITLE
Add documentation and examples for std lib

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#3313]
There are many functions in the standard library which have no documentation. None of them have any examples

Eg documentation
```
/// Inserts a key-value pair into the map.
/// 
/// # Arguments
///
/// * `key` - The key to which the value is paired
/// * `value` - The value to be stored
///
/// # Examples
/// 
/// ```
/// storage {
///     map: StorageMap = StorageMap {} 
/// }
/// 
/// fn foo() {
///     let key = 5_u64;
///     let value = true;
///     storage.map.insert(key, value);
///     let retrieved_value = storage.map.get(key);
///     assert(value == retrieved_value);
/// }
/// ```
#[storage(write)]
fn insert(self, key: K, value: V) {
    let key = sha256((key, __get_storage_key()));
    store::<V>(key, value);
}
```

**Comment by JoshuaBatty** [comment]
Nice, will be really great to have more documentation on standard library types. These now show as formatted markdown when hovering in the editor since #3084 landed. 

Note, I would recommend tagging the examples with ` ````sway` so that the examples have syntax highlighting relevant to sway.
