### ISSUE TITLE
Revamp the `storage` library to use the new capabilities of storage opcodes

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3318]
Specifically, the `$rB` registers now tells whether the given storage slot has already been set or not (See [`SRW`](https://fuellabs.github.io/fuel-specs/master/vm/instruction_set.html#srw-state-read-word), [`SRWQ`](https://fuellabs.github.io/fuel-specs/master/vm/instruction_set.html#srwq-state-read-sequential-32-byte-slots), [`SWW`](https://fuellabs.github.io/fuel-specs/master/vm/instruction_set.html#sww-state-write-word), and [`SWWQ`](https://fuellabs.github.io/fuel-specs/master/vm/instruction_set.html#swwq-state-write-sequential-32-byte-slots)). This is useful because we can now return an `Option` from storage operations in the standard library. Tasks required:

### Update Storage Intrinsics
Currently, storage intrinsics look like:
* `__state_load_word(key: b256) -> u64;`
* `__state_store_word(key: b256, value: u64);`
* `__state_load_quad(key: b256, addr: u64);`
* `__state_store_quad(key: b256, addr: u64);`
Change them to the following:
* `__state_load_word(key: b256) -> (u64, bool);` or `__state_load_(key: b256, addr: u64) -> bool;`
* `__state_store_word(key: b256, value: u64) -> bool;`
* `__state_load_quad(key: b256, addr: u64) -> bool;`
* `__state_store_quad(key: b256, addr: u64) -> bool;`
In each case, the `bool` represent the registers `$rB`.

### Update `store` and `get` in `std::storage`
Update `store` and `get` to look like:
```rust
pub fn store<T>(key: b256, value: T) -> Option<T>;
pub fn get<T>(key: b256) -> Option<T>;
```
The `bool` value returned from the intrinsics have to be ANDed (or ORed?) and the result is used to decide whether to return `Some` or `None`. Typically, `store` would return `Some(previous_value)` if the key was written before, and `None` otherwise, but this is potentially too expensive because we would have to always read the storage location first before writing. One alternative is to make two versions of `store`: one that doesn't return anything and one that returns `Option<T>`. We can also have `store` return a bool:
```rust
pub fn store<T>(key: b256, value: T) -> bool; // The `bool` tells us whether the `key` is already paired with a value or not.
```

For `get`, the `Option` is very useful and doesn't require any extra reads or writes to generate.

### Update `StorageMap`
Update `insert` and `get` to also return an `Option`:
```rust
    fn insert(self, key: K, value: V) -> Option<V>;
    fn get(self, key: K) -> Option<V>;
}
```
Again, `insert` is now a bit too expensive because it requires an extra storage read, but the API above matches Rust's `HashMap`. We may decided to create two versions of `insert`: one that doesn't return anything and simply writes or overwrites the current value blindly, and another one that returns `None` or `Some(previous_value)`. We can also have `insert` return a `bool`:
```rust
fn insert(self, key: K, value: V) -> bool; // The `bool` tells us whether the `key` is already paired with a value or not.
```

### Use `SCWQ`
Using `scwq`, we can implement
```rust
fn remove(self, key: K) -> Option<V>;
```
which calls `scwq` under the hood to erase the storage slots corresponding to `key`. Again, we can also tell, from register `$rB`, whether we're clearing an existing slot or not and return `Option<V>` accordingly. `remove` can also return a `bool`:
```rust
fn remove(self, key: K) -> bool; // The `bool` tells us whether the `key` was already paired with a value or not.
```

**Comment by mohammadfawaz** [comment]
@vaivaswatha @otrho regarding:
> `__state_load_word(key: b256) -> (u64, bool);` or `__state_load_(key: b256, addr: u64) -> bool;`

I was playing around with this and faced some issues with the first option. Basically, getting the type of `StateLoadWord` is now an `Aggregate` (`(u64, bool)`) which needs construction via `new_struct`, which needs a mutable `context`, but `get_type` doesn't take `&mut context`. I didn't want to go for a nuclear option and change that. 

Thoughts? Do we support returning aggregates like that well? One alternative is to just use an `asm` block instead of `__state_load_word` in the standard library until aggregates are reworked as I know some work is being done there.

**Comment by vaivaswatha** [comment]
> @vaivaswatha @otrho regarding:
> 
> > `__state_load_word(key: b256) -> (u64, bool);` or `__state_load_(key: b256, addr: u64) -> bool;`
> 
> I was playing around with this and faced some issues with the first option. Basically, getting the type of `StateLoadWord` is now an `Aggregate` (`(u64, bool)`) which needs construction via `new_struct`, which needs a mutable `context`, but `get_type` doesn't take `&mut context`. I didn't want to go for a nuclear option and change that.
> 
> Thoughts? Do we support returning aggregates like that well? One alternative is to just use an `asm` block instead of `__state_load_word` in the standard library until aggregates are reworked as I know some work on them is currently underway.

Coincidentally (or not) I'm working on merging the `Aggegate` type into `Type`, and with that `get_type` might end up needing a mutable ref too. I think just using ASM is better at the moment.
