### ISSUE TITLE
Audit the language server to ensure we are collecting 100% of tokens 

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#3319]
Before we can support the LSP rename capability, we need to make sure we are collecting all of the tokens in the users' project. If we enable rename before then, this could lead to the feature causing the users code to break if the type being renamed exists in a location where the language server can not access during token collection. 

I have previously outlined a few examples of where we currently can't access tokens is #2486.

We should write a test in the server that does the following:

- loops over all the examples in either the sway/examples or e2e language folder
- traverse and collect all tokens from `sway_parse`, excluding keywords and punctuation tokens
- traverse the `ParseProgram` and collect tokens
- traverse the `TypedProgram` and collect tokens
- iterate over all tokens collected from `sway_parse` and assert that the parsed and typed programs have a matching `Span`
- collect all tokens that failed to find a match and report them.

**Comment by sdankel** [comment]
Using Josh's trick for highlighting uncollected tokens:

```
"editor.semanticTokenColorCustomizations": {
        "rules": {
            "string": "#000000",
            "number": "#000000",
            "namespace": "#000000",
            "type": "#000000",
            "struct": "#000000",
            "class": "#000000",
            "interface": "#000000",
            "enum": "#000000",
            "enumMember": "#000000",
            "typeParameter": "#000000",
            "function": "#000000",
            "method": "#000000",
            "property": "#000000",
            "variable": "#000000",
            "parameter": "#000000",
            "generic": "#000000",
            "boolean": "#000000",
            "keyword": "#000000",
            "builtinType": "#000000",
        }
    },
```

Manually went through the tests in `should_pass/language` and opened [issues](https://github.com/FuelLabs/sway/issues?q=is%3Aissue+LSP+missing+tokens+).

**Comment by JoshuaBatty** [comment]
All the issues that were opened as a result of this audit can now be tracked at #3732 and #3733.
