### ISSUE TITLE
`insert()` into `StorageMap` triggers two CEI pattern check warnings

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3355]
Example:
```rust
contract;

dep external;

use external::*;

use std::auth::msg_sender;

abi MyContract {
    #[storage(read, write)]
    fn withdraw();
}

storage {
    balances: StorageMap<Identity, u64> = StorageMap {}
}

impl MyContract for Contract {
    #[storage(read, write)]
    fn withdraw() {
        let sender = msg_sender().unwrap();
        let bal = storage.balances.get(sender);

        assert(bal > 0);

        let caller = abi(OtherContract, 0x3dba0a4455b598b7655a7fb430883d96c9527ef275b49739e7b0ad12f8280eae);
        caller.external_call();

        storage.balances.insert(sender, 0);
    }
}
```
<img width="936" alt="image" src="https://user-images.githubusercontent.com/59666792/201494524-38d216c7-9d92-4868-9a4b-d4c380913a8d.png">

The reason is that `storage.balances.insert()` requires first "reading" `storage.balances`. However, because `balances` is an empty struct (being a `StorageMap {}`), no storage reads ever show up in the bytecode for it. 

We should modify the CEI pattern check analysis to check if a `StorageAccess` is of type `struct { }`, in which case, we shouldn't consider it a _real_ storage read.

**Comment by anton-trunov** [comment]
Is it correct that the `__get_storage_key` intrinsic does not read from storage?

**Comment by mohammadfawaz** [comment]
> Is it correct that the `__get_storage_key` intrinsic does not read from storage?

That is correct.
