### ISSUE TITLE
Disallow `while` loops in predicates in the frontend

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3357]
This shouldn't compile:
```rust
predicate;

fn main() -> bool {
    let x = 0;
    while true { x += 1; }

    true 
}
```
https://github.com/FuelLabs/sway/pull/3291 will disallow this in codegen. It would be better to disallow this in the frontend, potentially along with other things like storage intrinsics etc.

**Comment by anton-trunov** [comment]
Looks like this could be achieved by refactoring the language into a *core*, which could be somewhat pure language (no loops, no storage effects, no contract calls(?), only local state modification is allowed, etc.) and the rest of it. This would greatly simplify developing static analyses for Sway, formal verification for Sway etc.

**Comment by mohammadfawaz** [comment]
https://github.com/FuelLabs/sway/pull/3400 Closes this
