### ISSUE TITLE
Unable to read logs from sway tests.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#3363]
When running `forc test` to run in-language tests, any calls to the `log` function or `__log` intrinsic will trigger the following error:

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/17053076/201775061-afc81adf-5a3c-416f-a092-24fcde02b1ed.png">

To repro, build the following lib and run `forc test`:
```
library log_bug;

use std::logging::log;

fn my_func() {}

#[test()]
fn my_test() {
    my_func();
    log(1);
}
```

**Comment by nfurfaro** [comment]
Reopening as this is still an issue.

**Comment by vaivaswatha** [comment]
@nfurfaro on the latest `master`, I created a project with the code in the original report above and did `forc build` and `forc test`. they both succeeded.

```
Bytecode size is 36 bytes.
   Running 1 tests
      test my_test ... ok (711.227µs)
   Result: OK. 1 passed. 0 failed. Finished in 711.227µs.
```

**Comment by nfurfaro** [comment]
@vaivaswatha I should probably update this issue in light of that.
As you mentioned, using `log` in a test no longer throws an error, but they log doesn't show up anywhere, so it's more of a tooling issue. cc @kayagokalp

**Comment by kayagokalp** [comment]
Hmm it is highly likely that we are not collecting any receipts back from the interpreter instance, I think we are currently only looking the final state of the VM to see if anything reverted or not. I will look into this, thanks for issue! @nfurfaro

**Comment by mohammadfawaz** [comment]
> Hmm it is highly likely that we are not collecting any receipts back from the interpreter instance, I think we are currently only looking the final state of the VM to see if anything reverted or not. I will look into this, thanks for issue! @nfurfaro

Yeah seems like the missing piece here is the collection of receipts and displaying the `Log` and `LogData` ones.

**Comment by kayagokalp** [comment]
> Yeah seems like the missing piece here is the collection of receipts and displaying the Log and LogData ones.
Yep, I will open a PR tomorrow which adds a flag to `forc test` so that it will show logs of tests. 👍

**Comment by mohammadfawaz** [comment]
Created a separate `enhancement` issue: https://github.com/FuelLabs/sway/issues/3807 and will close this one since this particular bug has been fixed.
