### ISSUE TITLE
`ContractCaller` type looks weird in inlay hints

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3366]
E.g.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/59666792/201971586-4b7fc0a7-19e3-4e48-b43d-1983086f94d2.png">

Likely an issue in the compiler when displaying the `ContractCaller` type.

**Comment by JoshuaBatty** [comment]
Match on if the type_info is a contract caller, if so we might need to edit it manually. just display ContractCaller.

**Comment by JoshuaBatty** [comment]
closing this as we are tracking this in #4314 now
