### ISSUE TITLE
LSP stops after going to definition in another project

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#3372]
When using LSP and going to the definition of a function in another project/library, when returning to the original project LSP no longer runs.

Example:

1. Open the Sway-libs test project `nft_core`. 
2. Go to the definition of any function the uses the NFT library within the contract. This will go to the NFT library within the repo.
3. Return to the `nft_core` test project.

LSP will now stop running.

**Comment by mohammadfawaz** [comment]
If I'm not mistaken, this is related to the the `lazy_statics` issues which is being solved in https://github.com/FuelLabs/sway/pull/3353
