### ISSUE TITLE
Add new kind of effects (balance tree modification) to CEI analysis

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#3395]
The following description is from an internal discussion.

It looks like there are 3 more opcodes we have to think about for the CEI pattern analysis: `tro`, `tr`, and `smo`. These opcodes are considered “effects”. We need to document, in the Sway Book, what operations are considered effects and what the warning looks like etc.

A few notes:
- `tr` and `tro` are are not exactly storage accesses. They do update the “state” but not the general purpose state tree. They update the *balance tree*. They should have their own type of warning. Same with `bal` which only reads from the balance tree.
- `smo` might also needs its own warning because it doesn’t update any trees but may have serious effects if the user sends arbitrary bytes that “do something”. While `smo` definitely has effects, it looks like they would be write only. It doesn’t write to contract storage though; just creates a new `Output::Message` which could have implications on Ethereum if a system has been implemented to receive these messages.

**Comment by mohammadfawaz** [comment]
> `tr` and `tro` are are not exactly storage accesses. They do update the “state” but not the general purpose state tree. They update the balance tree. They should have their own type of warning. Same with `bal` which only reads from the balance tree.

Indeed, I expect `tr` and `tro` to raise warning that mentions both a read and write because they first require reading from the balance tree (to check if there's enough assets etc.) and _then_ writing to it. `bal` on the other hand is just a read. There are no instructions that only write the the balance tree AFAIK.
