### ISSUE TITLE
Negative e2e tests: check that certain warnings do not appear in the output

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#3396]
Currently we don't have this feature in the e2e tests. It looks like it would be really useful to have to test static analyses, e.g. to check there are no false positives.

**Comment by mohammadfawaz** [comment]
Does the `not` directive from `FileCheck` not work directly if used in `test.toml`?

**Comment by anton-trunov** [comment]
Indeed this works, here is the relevant link from an internal discussion: https://docs.rs/filecheck/latest/filecheck/#directives
