### ISSUE TITLE
Add reference type ID to `MessageOut` receipt

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/sway#3409]
### Issue
- The Fuel Indexer allows users to index a [`MessageOut` receipt](https://github.com/FuelLabs/fuel-specs/blob/master/src/protocol/abi/receipts.md#messageout-receipt)
- This `MessageOut` receipt is important -- one of the most important receipts -- because the messages are bridge messages
- This receipt includes a hexadecimal payload field `data` that contains the byte payload sent in the receipt
- Currently, we (using the indexer) have no way of deserializing that `data` payload into some type of struct/object
- The [`LogData` receipt](https://github.com/FuelLabs/fuel-specs/blob/master/src/protocol/abi/receipts.md#logdata-receipt) works a bit similarly in that it also has a `data` payload that can be deserialized
- However, the difference between `LogData` and `MessageOut` is that `LogData` includes a reference type ID -- that allows us to know which entity/object to deserialize the data payload to

### Recommended Solution
- We should add some reference type ID to the `MessageOut` receipt, so that users know which type the `MessageOut` `data` payload will deserialize to
- @adlerjohn Suggested merely appending the 64-bit reference type ID to the beginning of the `MessageOut` `data` payload in the `stdlib`

CC @nfurfaro because this might involve stdlib
CC @mohammadfawaz because this is Sway-related
CC @deekerno

**Comment by ra0x3** [comment]
- There seems to be a somewhat related issue here https://github.com/FuelLabs/sway/issues/3401 
  - This  ☝️  seems to have reached a resolution - with @mohammadfawaz suggesting we don't have a register to keep track of the reference type ID
    - However, the solution suggested by John asks if we can just prefix the data payload with the type ID

**Comment by ra0x3** [comment]
@mohammadfawaz Just following up on this :)

**Comment by mohammadfawaz** [comment]
I believe this can be closed now after https://github.com/FuelLabs/sway/pull/3564
