### ISSUE TITLE
Possible non-deterministic behaviour related to use of `log` opcode

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#3436]
In the following snippet, commenting/uncommenting the call to `log()` changes the returned value.

```
script;

fn main() -> u8 {
    let mut x = Vec::new();
    x.push(1);
    let val = asm(r1: x.buf.ptr(), r2) {
        lb r2 r1 i7;
        r2: u8
    };
    // log(val);
    val
}

```

**Comment by mohammadfawaz** [comment]
So certainly replacing `lb` with `lw r2 r1 i0` works fine and probably just as efficient. The issue with the `log` reproduces with any other instruction... basically `lb r2 r1 i7` just returns garbage data for whatever reason and that garbage depends on the bytecode.

The assembly generated seems perfectly fine and I think the `lb r2 r1 i7` is correct given that `lb` expected an immediate that counts in bytes (not words like `lw`). So this is saying give my the 8th bytes starting from `r1` which should give us the `u8` itself which is 1.
