### ISSUE TITLE
Rename `Forc.toml` and `Forc.lock` to `forc.toml` and `forc.lock`?

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3438]
One thing I've always found a little strange about cargo's design is the use of capitalised file names for the `Cargo.toml` and `Cargo.lock` - a convention that we have followed with our own `Forc.toml` and `Forc.lock` files.

This seems inconsistent with almost all other file naming conventions within Rust - e.g. modules are generally named with kebab-case or snake_case, all directories (src, tests, target) are lowercase, all `target`/`out` artifacts are also lowercase, and further the `rust-toolchain.toml` file (read by rustup) uses kebab-case.

I think it's worth considering renaming `Forc.toml` and `Forc.lock` to lowercase (`forc.toml` and `forc.lock`) for consistency with the rest of our file and directory naming.

## Cargo's reasoning

Supporting `cargo.toml` was proposed long ago:

- https://github.com/rust-lang/cargo/issues/45
- https://internals.rust-lang.org/t/can-we-rename-cargo-toml/380

The reasoning for requiring the capital C was:

> Capital letters group it together with other similar configuration files and avoids it from being interspersed with other files and directories.

IMO this is a pretty weak justification - there is no written configuration standard that recommends configuration files start with capital letters, and there is no shortage of configuration files that do not adhere to this (including Rust's own `rust-toolchain.toml` file).

There are still folks commenting on those threads asking to support `cargo.toml`, but that ship has long sailed for Cargo.

## Implementation (non-breaking)

We could make this change in a non-breaking manner. It would look something like:

1. Changing the `const`s that declare the `str`s for the manifest and lock files (used when `init`ing and loading projects).
2. Make sure that when loading manifest files, we still check for the old names.
3. Provide a warning to users if their file uses the old Capital case name.
4. Find and replace sway repo for any other references to `Forc.toml` and `Forc.lock`.
5. Update Sway book and Fuel book.

**Comment by adlerjohn** [comment]
Regardless of justification for `Cargo.toml`, `cargo.toml` isn't supported currently by Cargo, right?

**Comment by mitchmindtree** [comment]
> Regardless of justification for Cargo.toml, cargo.toml isn't supported currently by Cargo, right?

Correct.

To be sure, I just created a new project and renamed the `Cargo.toml` to `cargo.toml`, ran `cargo build` and got this output:

```console
$ cargo build
error: could not find `Cargo.toml` in `/home/mindtree/programming/rust/test-crate` or any parent directory, but found cargo.toml please try to rename it to Cargo.toml
```
