### ISSUE TITLE
Add `forc contract-id` and `forc predicate-id` commands

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3444]
These would be super simple commands on top of `forc build` that produce the associated contract/predicate ID.

An optional `--salt` flag can be provided for each.

Each should check that the program type is valid for the given command and produce a friendly error otherwise.

Configuration time constants ala https://github.com/FuelLabs/sway-rfcs/pull/19 would make the `forc contract-id` command trickier as we would need to specify values for each of the constants (or fall back to defaults) to produce a useful ID.

**Comment by mohammadfawaz** [comment]
I think the terminology is
- Contract ID
- Script bytecode hash (not too important)
- Predicate root

**Comment by mitchmindtree** [comment]
Thanks for clarifying @mohammadfawaz!

Perhaps `forc predicate-root` makes more sense here.

Then again, I wonder if there's a good case for the differing terminology here? I've seen ID, address, root, bytecode hash. I wonder if there's a chance to improve on naming consistency here, or if these are necessarily different for each of the program types?
