### ISSUE TITLE
Cannot perform bitwise operations on implicitly upcasted u32 -> u64

### ISSUE THREAD

**Issue by tkporter** [FuelLabs/sway#3449]
To my understanding, there is only implicit upcasting from u32 -> u64. I also believe bitwise operations are only possible for u64.

If I have a u32 that I want to upcast to u64 so I can perform bitwise operations, I'm unable to do so. Despite explicitly declaring a variable as u64, the compiler still thinks it's a u32 somewhere under the hood:

```
contract;

pub fn test_function() {
    let some_u32: u32 = 4u32;

    let some_u64: u64 = some_u32;
    let foo = some_u64 & 1u64;
}
```

When compiling, this gives:
```
$ forc build
  Compiled library "core".
  Compiled library "std".
error
 --> /Users/trevor/fuel/u32-bitwise/src/main.sw:7:24
  |
5 |
6 |     let some_u64: u64 = some_u32;
7 |     let foo = some_u64 & 1u64;
  |                        ^ No method named "binary_and" found for type "u32".
8 | }
  |
____

  Aborting due to 1 error.
Error: Failed to compile u32-bitwise
```

**Comment by mohammadfawaz** [comment]
> To my understanding, there is only implicit upcasting from u32 -> u64

This is correct.

> I also believe bitwise operations are only possible for u64.

This should be rectified. There is no good reason for not allow bitwise operations for `u32`, `u16`, and `u8`.

>  Despite explicitly declaring a variable as u64, the compiler still thinks it's a u32 somewhere under the hood.

This, I believe, is a bug that can also be exercised with this simple example:
```rust
fn main() -> u8 {
    let x: u8 = 4u32;
}
```
I think we're not updating the type of `x` in the type engine, as per [this comment](https://github.com/FuelLabs/sway/blob/master/sway-core/src/type_system/unify.rs#L555-L560). @emilyaherbert can you shed some light here as to why we're not updating the concurrent slab at all?

**Comment by mohammadfawaz** [comment]
Actually just found https://github.com/FuelLabs/sway/pull/1540

**Comment by mohammadfawaz** [comment]
So I'm proposing something in https://github.com/FuelLabs/sway/pull/3458
