### ISSUE TITLE
Implement bitwise operations for `u8`, `u16`, `u32` in `sway-lib-core`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3456]
The traits `BitwiseAnd`, `BitwiseOr`, and `BitwiseXor` are only implemented for `u64` (and `b256`) but not for `u8`, `u16`, and `u32`. I don't see a good reason for not implementing those.

**Comment by ef3n9r98** [comment]
Hi @mohammadfawaz, Fuel has a _ton_ of open issues in the Sway repo. Are these meant for team members of Fuel or for all devs? And would you be willing to compensate devs if they solve an issue?

**Comment by otrho** [comment]
https://github.com/FuelLabs/sway/issues/3174#issuecomment-1347571454

**Comment by jtriley-eth** [comment]
Most bitwise `u64` tests are here:
https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops

However specifically bitwise-not tests are here:
https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not

---

It seems the best approach here would be to add a test directory for `u32`, `u16`, and `u8` (same layout as `u64_ops`):

- `test/src/e2e_vm_tests/test_programs/should_pass/language/u64_ops`
- `test/src/e2e_vm_tests/test_programs/should_pass/language/u32_ops`
- `test/src/e2e_vm_tests/test_programs/should_pass/language/u16_ops`
- `test/src/e2e_vm_tests/test_programs/should_pass/language/u8_ops`

then place each bitwise-not test in their respective type's file, removing the `test/src/e2e_vm_tests/test_programs/should_pass/language/bitwise_not` directory altogether.

**Comment by otrho** [comment]
Yep sure, although maybe a common subdirectory `ops` would be good.  `.../should_pass/language/ops/u64_ops`, etc.
