### ISSUE TITLE
Parts of the formatter use destructive methods

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3473]
We should avoid using `.pop()` and the like, and find work arounds for the current use cases that implement it. This will help us avoid creating unparsable code resulting in vague errors.

It might be a good idea if the pop is necessary that we have a function that uses a token as a guard so that we only pop in cases where it is absolutely necessary and we know it is safe to do so.

**Comment by anton-trunov** [comment]
Good point! What would be a typical workaround for lists of arguments with a separator where the separator should not appear at the end, i.e. `foo, bar, baz`. I think that's a common use case for `.pop()` in the formatter: we add the separator at each iteration and then `.pop()` the last one after the loop.

**Comment by eureka-cpu** [comment]
> Good point! What would be a typical workaround for lists of arguments with a separator where the separator should not appear at the end, i.e. `foo, bar, baz`? I think that's a common use case for `.pop()` in the formatter: we add the separator at each iteration and then `.pop()` the last one after the loop.

In an instance where _do_ want to get rid of something like this, I think we should at least perform some kind of check before committing to it. In that specific instance we can use a peekable iterator and check for the last remaining item in a list.

**Comment by eureka-cpu** [comment]
It's tricky, the AST gives us sometimes an optional final value, and other times the final value is in the primary list of items.
