### ISSUE TITLE
Chained methods & fields that should be multiline need logic to handle vertical formatting

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3474]
```rust
fuelcoin.really_long_field.other_really_long_field.foo().bar().baz().quux();
```
should be:
```rust
fuelcoin
    .really_long_field
    .other_really_long_field
    .foo()
    .bar()
    .baz()
    .quux();
```

To elaborate further, this applies only to `swayfmt`. Logic needs to be added to handle the formatting of Sway code so that chained methods & fields that exceed a certain length (IIRC it's 60 but we are using the `rustfmt` standard which you can find [here](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=chain#chain_width)) are formatted as multiline chains.

`rustfmt` has a file dedicated to handling formatting of chains, [here](https://github.com/rust-lang/rustfmt/blob/master/src/chains.rs).

**Comment by AliJafriETH** [comment]
hey @eureka-cpu, is the issue still open, i'd like to try to solve this issue?

**Comment by eureka-cpu** [comment]
> hey @eureka-cpu, is the issue still open, i'd like to try to solve this issue :))

Please, feel free!

**Comment by eureka-cpu** [comment]
Take a look at how we handle import statements for some general direction

**Comment by AliJafriETH** [comment]
Hey @eureka-cpu, sorry for such a late response but i'm not able to find the issue? Could you please help me out?

**Comment by eureka-cpu** [comment]
I would start by adding a few tests to `swayfmt/src/formatter/mod.rs`. Then check `swayfmt/src/utils/language/expr/mod.rs`, you should find everything you need there. Hopefully this clarifies _where_, but if you still need help feel free to reach out.

**Comment by AliJafriETH** [comment]
Hey @eureka-cpu, thank you so much for the help, I'll update you with the progress :))

Thanks 💯
