### ISSUE TITLE
Format #[doc(foobar)] annotations in its original syntax, not as ///foobar?

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#3475]
### Preamble

Rust uses `#[doc(foobar)]` annotations to control how code docs are rendered and it uses another syntax as an alternative to the triple slash `///`: `#[doc = " This is a doc comment."]`.

### Issue

In Sway, currently, I believe, it's not possible to write useful comments using the `#[doc(foobar)]` annotations, because the parser expects `foobar` to be an identifier, and the user cannot put a string there.

Moreover, `#[doc(foo,bar,baz)]` gets printed as `///baz` by the Sway formatter.

### Possible solution

My proposal would be to
- stop printing `#[doc(foobar)]` as `///foobar` and print it in its original syntax,
- add a new attribute kind (let's say `doc-comment`) and parse `/// foo bar baz` into this new attribute kind, hence decoupling doc comments from doc controlling annotations.

Any comments on this proposal are more than welcome.

**Comment by mitchmindtree** [comment]
Another alternative might be to desugar `/// foobar` into a nested `comment` attribute like `#[doc(comment(foobar))]`? This might make it a little easier to keep all `doc` related attributes together when they get forwarded to `forc-doc`, as `forc-doc` would only need to check for `AttributeKind::Doc` (and not an extra `AttributeKind::DocComment`)?

Either way, this sounds fine to me :+1:

**Comment by anton-trunov** [comment]
@mitchmindtree It turned out to be way simpler to introduce a new attribute kind so I went with that option (we don't the support for nested attributes at the moment).

@tritao @mitchmindtree Thank you for the discussion!
