### ISSUE TITLE
Initial setup and testing for EVM backend

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3498]
This involves many things including things like
- Setting up and learning how to use a Rust-implementation of the EVM
- Testing infrastructure
- CI

**Comment by adlerjohn** [comment]
when https://twitter.com/gakonst/status/1595648232226291712 is out, it might be worthy to give it to try

**Comment by mohammadfawaz** [comment]
I think we can close this issue as most of the tooling stuff and the testing infra is done. Going forward, the remaining EVM backend work should be tracked in separate issues.
