### ISSUE TITLE
Add language server support for the Helix IDE

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#3505]
We need to look at adding a config file that users can install into [Helix](https://helix-editor.com/)

LSP is supported already within the IDE, should just be a matter of getting it to identify `.sw` files and pointing it to the sway-lsp executable.

**Comment by JoshuaBatty** [comment]
I had a quick play-around today and got the lsp working. 

my `languages.toml` is:

```
[[language]]
name = "sway"
scope = "source.sway"
injection-regex = "sway"
file-types = ["sw"]
language-server = { command = "forc", args = ["lsp"] }
roots = ["Forc.toml", "Forc.lock"]
indent = { tab-width = 4, unit = "    " }
comment-token = "//"
grammar = "rust"
```

It's using the same grammar as rust for now so we can syntax kind of working.

**Comment by sdankel** [comment]
Added a new repo for the tree-sitter grammar: https://github.com/FuelLabs/tree-sitter-sway/

PR to add sway to helix: https://github.com/helix-editor/helix/pull/6023

**Comment by sdankel** [comment]
Sway support should be included in the next helix release.
