### ISSUE TITLE
Auto generate a doc comment template on functions

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#3521]
This idea came from @Braqzen 

You could specify a file or a function and it would create a basic template that includes your function args so that there's less to do e.g. it could look something like:

```
/// Function summary here
///
/// # Arguments
///
/// * `parameter name 1` - 
/// * `parameter name 2` -
///
/// # Returns
///
/// * `SomeStruct` - 
/// * `bool` - 
/// * `bool` -
```

There wouldn't actually be a summary but there would be some placeholder instead. Also, if it returns anything then it would specify that too in the same order, similar to the params.

This should be fairly easy to do, we can already pass out the name, args, and return type of a function in a similar way to how it is being handled in #3464

**Comment by JoshuaBatty** [comment]
Open to bike-shedding the exact layout of the style for the template if anyone has any input.

**Comment by K1-R1** [comment]
This is great, the addition of a `Reverts` section would be ideal. eg:
```
///
/// # Reverts
///
/// * When the constructor is called more than once.
```

**Comment by sdankel** [comment]
Done in https://github.com/FuelLabs/sway/issues/4571
