### ISSUE TITLE
Failure to return a proper type error when using mixed generic types.

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#3530]
error: Internal compiler error: Verification failed: Type mismatch found for call to 'push_181'.
Please file an issue on the repository and include the code that triggered this error.

```#[storage(read)]
    pub fn to_vec(self, key: K) -> Vec<V> {
        // The length of the vec is stored in the sha256((key, __get_storage_key())) slot
        let k = sha256((key, __get_storage_key()));
        let len = get::<u64>(k);
        let mut i = 0;
        let mut vec = Vec::new();
        while len > i {
            let k = sha256((key, i, __get_storage_key()));
            let item = get::<K>(k);
            vec.push(item);
            i += 1;
        }
        vec
    }
```
    
This code seems to have caused the error.

**Comment by SwayStar123** [comment]
The problem is that the item uses get::<K> instead of get::<V>. The error message can be improved tho

**Comment by mohammadfawaz** [comment]
Yeah that should be caught much earlier in the compiler. Good catch.

**Comment by otrho** [comment]
I thought I'd try and make a simpler repro and tried this:
```rust
struct Item<I> {
    item: I,
}

fn test<A, I>(arg: A) -> Item<I> {
    Item {
        item: arg,
    }
}

fn main() {
    let i: Item<u64> = test(true);
}
```
And it really should complain that you can't initialise `Item<u64>::item` with a `bool`, or maybe you can't initialise an `Item<u64>` with an `Item<bool>` but it compiles fine, not even the ICE from above.

**Comment by mohammadfawaz** [comment]
And if you skip the type ascription altogether `Item<u64>`, you get:
```
0 | unknown source location
 | ^^^^^^^^^^^^^^^^^^^^^^^ Internal compiler error: Generic type cannot be resolved in IR.
Please file an issue on the repository and include the code that triggered this error.
```

**Comment by emilyaherbert** [comment]
Note that this should give an error like: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ea27a3df14e58a5e2341db21056879d6
