### ISSUE TITLE
Implement the `Eq` trait for `Option`

### ISSUE THREAD

**Issue by Rubyt0x** [FuelLabs/sway#3542]
The `Identity` implements the `Eq` trait: 
https://github.com/FuelLabs/sway/blob/716b34f7a22ff2dbbcc2505debcdb5892aaedf7c/sway-lib-std/src/identity.sw#L13-L21

I would like the same thing to exist for `Option` so I can compare Options.

**Comment by mohammadfawaz** [comment]
Thanks @Rubyt0x. To do this, we need to write
```rust
impl<T> core::ops::Eq for Option<T>
where
    T: Eq {
    fn eq(...) -> bool {
        ...
    }
}
```
which is currently blocked by https://github.com/FuelLabs/sway/issues/1162

**Comment by brandonsurh** [comment]
I don't believe this is blocked anymore. Will see what I can do.
