### ISSUE TITLE
Publish output from `forc doc` for `sway-lib-std` on ghpages

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3549]
As we refactor CI to publish both "The Sway Book" and "The Sway Reference" under ghpages (rather than just the former), we should also add a std reference generated by `forc doc`.

In the long-run, we can take some inspiration from docs.rs and automate the generation of all pkg documentation from the hypothetical future package registry. #865

**Comment by eureka-cpu** [comment]
#3930 is a critical fix for #3923 

There is also another critical bug at #3929
