### ISSUE TITLE
Add the `Sway Reference` to the `README.md`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#3559]
The [documentation](https://github.com/FuelLabs/sway#documentation) section mentions the `Sway Book`. We should add the reference as well. The link to the reference is https://fuellabs.github.io/sway/master/reference .

**Comment by yash251** [comment]
@Braqzen Please check and let me know

**Comment by AliJafriETH** [comment]
Hey @Braqzen, is this issue still open?

**Comment by Braqzen** [comment]
@AliJafriETH ah, it looks like #3599 did not use the correct closing keyword so this issue did not get closed when that PR was merged in. I'll close this now.
