### ISSUE TITLE
`Sway Reference` typo for Advanced Enum Concepts

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#3560]
The reference has a section for advanced concepts as seen below

![2](https://user-images.githubusercontent.com/103777923/206666309-f2c86e34-9b13-4cea-a42c-64bbc23a7fd7.png)

At the bottom of the page there is an example which mentions the `unit` type in the last sentence when it should state that a `u64` is used.

![1](https://user-images.githubusercontent.com/103777923/206666442-0ab47ae6-87d3-40d9-90ca-6d861490039d.png)

Change the last sentence from

"Instantiating the `unit` type"

to

"Instantiating the `u64` type"

**Comment by ef3n9r98** [comment]
Hi @Braqzen, Fuel has a _ton_ of open issues in the Sway repo. Are these meant for Fuel team members or for all devs? And would you be willing to compensate devs if they solve an issue?

**Comment by otrho** [comment]
https://github.com/FuelLabs/sway/issues/3174#issuecomment-1347571454

**Comment by AliJafriETH** [comment]
Hey @Braqzen, i'd love to work on this issue, could you please assign it to me?

**Comment by AliJafriETH** [comment]
Hey @Braqzen, i've made the required changes, kindly review the `pull request` & *hopefully* merge it:))

Thank you so much for assigning this issue to me, this is my first time contributing to a Web3 Repo 💯💯💯
