### ISSUE TITLE
Internal compiler error: Program erroneously uses uninitialized virtual registers.

### ISSUE THREAD

**Issue by Reimao** [FuelLabs/sway#3580]
Getting this error when trying to compile the `vault` module.

![image](https://user-images.githubusercontent.com/52012346/207218228-a0eda41d-a8be-4f2e-858b-a6ead4600ef7.png)

**Reproduce**: https://github.com/Reimao/Kitsch/tree/refactor/system-design

**Comment by otrho** [comment]
Aha!  This is the new check actually finding something.  But why, that is the question. :slightly_frowning_face:

**Comment by Reimao** [comment]
Confirmed. I get the same error @otrho 

![image](https://user-images.githubusercontent.com/52012346/207225037-1aecfc11-e1b6-4d50-af9f-5448e0798cbf.png)

![image](https://user-images.githubusercontent.com/52012346/207225082-49eb0263-f235-4884-b9ea-ec94a6720fe8.png)

**Comment by otrho** [comment]
Uh, it might help if _I_ was running the latest `master` when trying to repro.  :facepalm: Sorry.

Can now confirm the failure, I'll take a closer look.

**Comment by Reimao** [comment]
Wow. Amazing turnaround time! Thank you, @otrho :vulcan_salute:
