### ISSUE TITLE
Cannot use turbofish generic syntax 

### ISSUE THREAD

**Issue by tritao** [FuelLabs/sway#3585]
Take the following code:

```rust
script;

pub enum Option<T> {
    None: (),
    Some: T,
}

impl<T> Option<T> {
    pub fn none(self) -> Option<T> {
        Option::<T>::None
    }
}

fn main() {
    Option::Some(5).none();
}
```

Works fine in Rust but gives the following error in Sway:

```
error
  --> /sway/test-case/src/main.sw:10:17
   |
 8 | 
 9 |     pub fn none(self) -> Option<T> {
10 |         Option::<T>::None
   |                 ^^^ generics are not supported here
11 |     }
12 | }
   |
____
```

**Comment by mohammadfawaz** [comment]
I think we support `Option::None::<T>`?

**Comment by mohammadfawaz** [comment]
Hmm yeah but this works `Option::None::<T>()` and we don't want this to work as per https://github.com/FuelLabs/sway/issues/3375 so this is certainly an issue.

**Comment by esdrubal** [comment]
With the changes of #3743 we will support ```Option::None::<T>``` without the parenthesis.

Nontheless Rust still supports the code below:
```rust
let n = Option::<u64>::None;
```
We still doesn't support it. Do we want to support it?

**Comment by otrho** [comment]
The answer usually is 'if Rust does it, then we should do it too'. 🙂  I think it's the more idiomatic form too.
