### ISSUE TITLE
Use macros to reduce boilerplate code in Sway formatter tests

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#3597]
The file [swayfmt/src/formatter/mod.rs](https://github.com/FuelLabs/sway/blob/master/swayfmt/src/formatter/mod.rs) contains a bunch of formatter tests which follow the following common pattern:

```
    #[test]
    fn test_foobar() {
        let sway_code_to_format = r#"
<original Sway code>
"#;
        let correct_sway_code = r#"
<formatted Sway code>
"#;
        let mut formatter = Formatter::default();
        let formatted_sway_code =
            Formatter::format(&mut formatter, Arc::from(sway_code_to_format), None).unwrap();
        assert_eq!(correct_sway_code, formatted_sway_code);
        assert!(test_stability(formatted_sway_code, formatter));
    }
```

It looks like we could use Rust macros to reduce the boilerplate here. WDYT?

**Comment by bingcicle** [comment]
Circling back to this as I am taking a look at issues labeled under the formatter, def +1.

I think we can probably take inspiration from ripgrep's [macros](https://github.com/BurntSushi/ripgrep/blob/fe97c0a152cabc1bc07ec36b4b1e27cd230c3014/tests/macros.rs) here.

I've been working with the formatter and the default diff resulting from `assert_eq!` can be hard to read, so `eqnice!` is a helpful macro to have here. We can do all the setup in another macro like `rgtest!` as well (setup expected vs actual code, setup stability test)

How does this sound?

**Comment by mitchmindtree** [comment]
Sgtm!
