### ISSUE TITLE
Generic Result Method Failure

### ISSUE THREAD

**Issue by jtriley-eth** [FuelLabs/sway#3623]
Generic Result method fails when explicitly two assertions are in the same test function.

```rs
enum Result<T, E> {
    Ok: T,
    Err: E,
}

impl<T, E> Result<T, E> {
    pub fn unwrap_or(self, default: T) -> T {
        match self {
            Result::Ok(inner_value) => inner_value,
            Result::Err(_) => default,
        }
    }
}

// REVERTS
pub fn test_unwrap_or<T>(val: T, default: T)
where
    T: Eq
{
    assert(Result::Ok::<T, T>(val).unwrap_or(default) == val);
    assert(Result::Err::<T, T>(val).unwrap_or(default) == default);
}

// PASSES
pub fn test_unwrap_or_ok<T>(val: T, default: T)
where
    T: Eq
{
    assert(Result::Ok::<T, T>(val).unwrap_or(default) == val);
}

// PASSES
pub fn test_unwrap_or_err<T>(val: T, default: T)
where
    T: Eq
{
    assert(Result::Err::<T, T>(val).unwrap_or(default) == default);
}
```

## Reproduce

https://github.com/jtriley-eth/test-proj

## Version Information

Forc version: 0.32.2
Cargo Version: 1.68.0-nightly (cc0a32087 2022-12-14)
Cargo Generate version: 0.17.4
Mac OS Montery (M1) Version 12.6

**Comment by mohammadfawaz** [comment]
I was facing a similar issue yesterday and I think there is an issue with the implementation of `eq` that is chosen for `T`. In my case, when I tried logging the left and right sides of the `==`, they were indeed equal, but the equality check itself fails which tells me that the implementation of `eq` that is "discovered" for `T` is wrong. This points to an issue in trait constraints.

**Comment by esdrubal** [comment]
This issue no longer occurs with the changes from PR #3621. The PR improves consistency between inserting and getting stored trait implementations this allows to retrieve trait implementation when it was not possible before because the call paths wouldn't match.

Added this repro to PR #3621.
