### ISSUE TITLE
Bug with duplicate impl blocks defined for the same type with different type parameters.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#3633]
The following code won't compile. The error is:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/17053076/208316674-8cdb952e-d80e-4304-bddd-8b7a9b5b16ba.png">

```
library bug;

pub trait Convert<T> {
    fn convert(t: T) -> Self;
}

pub struct A {
    a: u64,
}

pub struct B {
    b: u64,
}

pub struct C {
    c: u64,
}

impl Convert<B> for A {
    fn convert(t: B) -> Self {
        A {
            a: t.b
        }
    }
}

impl Convert<C> for A {
    fn convert(t: C) -> Self {
        A {
            a: t.c
        }
    }
}
```

**Comment by mohammadfawaz** [comment]
@emilyaherbert I think in @nfurfaro's example, `B` and `C` are not meant to be generic parameters. This is the use case that he's thinking of: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dad181001f80f61c5fd47994f3e6e067

The use case here is being able to implement `From` for `ContractId` from multiple types.

**Comment by nfurfaro** [comment]
@mohammadfawaz is correct; sorry if my attempt at a simple repro is misleading.

**Comment by emilyaherbert** [comment]
Oh I see, apologies for my mistake! Thanks so much for clarifying @mohammadfawaz  and @nfurfaro.

Yes in this case the original bug description is correct 😄

**Comment by emilyaherbert** [comment]
> sorry if my attempt at a simple repro is misleading and/or incorrect.

No no, just a brain fart on my end haha.

**Comment by nfurfaro** [comment]
@esdrubal It looks like you may have a fix for this in the works?
I'm blocked by this again, and it will keep happening with more frequency until resolved. :)

**Comment by esdrubal** [comment]
@nfurfaro yes #3676 should fix this. Updated it now to remove merge conflicts. I hope it will be merged soon.
