### ISSUE TITLE
`TyEnumVariant` `type_span` contains the entire span of the variant

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3634]
I may be assuming incorrectly, but should this not be the span of only the type of the variant? If not there is already a `span` field which has the entire span.

Found while working on #3607 the expected result is `UnauthorizedUser: ()` but instead got `UnauthorizedUser: UnauthorizedUser: ()`

Source: https://github.com/FuelLabs/sway/blob/master/sway-core/src/language/ty/declaration/enum.rs#L110

**Comment by mohammadfawaz** [comment]
I think the `span` field contains the span for the variant itself? Isn't that enough?

**Comment by eureka-cpu** [comment]
> ~I think the `span` field contains the span for the variant itself? Isn't that enough?~
> 
> Correction: I now understand what you mean. Yes I think you're right.

I could have worded this a little better haha 😅
