### ISSUE TITLE
Implement common contracts & patterns in Sway

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#364]
This is meant to be a single place to track all the things we want to build in sway to extend the examples given provided in the docs. 
(I'm not attached to using an Issue to track this. A github projects kanban board may be a better fit for example.)

This can be things like:
- how to achieve common patterns in sway
- more contract examples
- multi-contract patterns

The List:
- [x] FizzBuzz
- [x] Subcurrency example (#299)
- [x] Wallet smart contract
- [ ]  Fungible token (same as OZ)
- [ ] Non-fungible token (same as OZ)
- [ ] Flash loan for fungible tokens
- [ ] access-control (ie: ownable, RBAC)
- [ ] Uniswap v1
- [ ] Auction
- [ ] Upgradeable contracts ?
- [ ] using the authentication module.
- [ ] returning results and errors
- [ ] token faucet
- [ ] staking contract
- [ ]

**Comment by Braqzen** [comment]
Some of these are being implemented in [sway apps](https://github.com/FuelLabs/sway-applications) since an example should be simple and present common usage of the standard library. 
This issue needs to be reconsidered since a bunch of time has passed since then.

**Comment by adlerjohn** [comment]
Yeah this has essentially been superseded by the sway-applications repo.
