### ISSUE TITLE
Convert `expect()` messages in `forc doc` to `anyhow::Result`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3655]
import `anyhow::Result` where necessary and remove the `expect` messages in favor of `Result`

**Comment by mohammadfawaz** [comment]
I'm assigning this to @eureka-cpu because I can't assign it to @gr00vytvniks

**Comment by eureka-cpu** [comment]
@gr00vytvniks if you leave a comment I can assign you to this if you'd like

**Comment by gr00vytvniks** [comment]
Ok thanks!
