### ISSUE TITLE
Create a `forc doc` HTML formatter for Sway code blocks

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3657]
This type of formatter would be specialized to just types & methods since the point is to have links in formatted code.

As a loose example, this `struct` code span... 
```rust
struct Foo {
    field1: Type1,
    field2: Type2,
}
```
could become something like:
```html
<pre>
  <code>
    "struct " <a href="path to Foo">Foo<a/> " {"
    <br>
    "    field1: " <a href="path to Type1">Type1<a/> ","
    <br>
    "    field2: " <a href="path to Type2">Type2<a/> ","
    <br>
    "}"
  </code>
</pre>
```

This is just an assumption, I would need to look more closely at how `cargo doc` renders code blocks but this gets the point across.

**Comment by eureka-cpu** [comment]
This issue is a product of working toward #3173

**Comment by eureka-cpu** [comment]
This is almost complete via #3173

**Comment by JoshuaBatty** [comment]
Closing this, @eureka-cpu is going to open another issue later that better describes the state of it in forc doc.
