### ISSUE TITLE
LSP missing tokens: raw identifier syntax (r#)

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#3722]
Unable to access span information for raw identifier syntax (r#)

![image](https://user-images.githubusercontent.com/47993817/211123919-e163f863-045a-47a4-a8e7-461dd90926da.png)

**Comment by JoshuaBatty** [comment]
Just been looking into this. The lexer actually ignores these `r#` tokens when creating the `Ident` but sets a `is_raw_ident` flag to true. I think it's fine to keep this behavior, and instead, we can check if `is_raw_ident` is true in the language server and take the `r#` prefix into account when we do things like renaming. 

Closing for now.
