### ISSUE TITLE
LSP missing tokens: parent trait in trait inheritance

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#3723]
Unable to access span information for parent trait in trait inheritance

![image](https://user-images.githubusercontent.com/47993817/211123941-e99351c8-4cfc-47df-9178-a24757ca4016.png)

![image](https://user-images.githubusercontent.com/47993817/211123949-01b5d934-4e4b-4900-a3f2-183776b043a5.png)

**Comment by JoshuaBatty** [comment]
It would be great if there was a `TySuperTrait` type that stored the `Ident` of the supertrait, as well as the `TypeInfo` so the original trait declaration could easily be looked up in the langauge server.
