### ISSUE TITLE
[Tracking] Collect missing tokens in the Language Server (compiler team). 

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3733]
Below are the remaining tokens that need addressing before we can collect all tokens in the language server.

## To-do

- [x] #3723 
- [x] #3612 
- [x] #3718
- [x] #3716
- [x] #3713 
- [x] #3613
- [x] #3719 
- [x] #3614 
- [x] #3616 
- [x] #4030
- [x] #4051
- [x] #4052
- [x] #4053
- [x] #4054
- [x] #4055
- [x] #4056
- [x] #4060
- [x] #4063 
- [x] #4064
- [x] #4166

**Comment by IGI-111** [comment]
@JoshuaBatty We're out of tasks on this so I'm closing but feel free to reopen if you find more edge cases we don't handle.

**Comment by JoshuaBatty** [comment]
Thanks for all the great work @IGI-111,has been massively appreciated. Hopefully that's the last all of the tokens now but i'll let you know if I come across any more. Cheers :)

**Comment by JoshuaBatty** [comment]
Sorry @IGI-111, found one more.

**Comment by mohammadfawaz** [comment]
Closing this again.. hopefully for good this time 🤞
