### ISSUE TITLE
Initial sway LSP support for `vscode.dev`

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#3771]
Look into what would be involved in order to compile a sway project with [vscode.dev](https://vscode.dev/)

After we can compile projects, then look into modifying `sway-lsp` so it can also run in the editor. I think this will involve modifying the server to use WebSockets instead of std::io for JSON-RPC communication.

**Comment by sdankel** [comment]
If we want fully-featured sway dev environments on the web, people can use [github codespaces](https://github.com/features/codespaces) would provide this out of the box.

In this [codespace](https://sdankel-jubilant-space-telegram-w56xgrq7q5fv4g4.github.dev/), I was able to install the sway vscode plugin as-is, install the fuel toolchain, and build sway projects.

![image](https://user-images.githubusercontent.com/47993817/222034959-4872aea4-4d7a-45e2-85ec-96048404c98b.png)

**Comment by JoshuaBatty** [comment]
> It sounds like vscode.dev is best for web development. I think a good outcome for sway in vscode.dev is plugging in the tree-sitter grammar for syntax highlighting and the other features tree-sitter enables. Thoughts? @JoshuaBatty

Ok, yeah let's start by adding in tree-sitter grammar. It seems to give a good enough experience for syntax highlighting and goto definition support for rust projects.  

I hadn't heard of codespaces before. Looks like an interesting option. The fact it costs money might be prohibitive for us at the moment but good to know it exists.

**Comment by sdankel** [comment]
Sounds good. I'll first need to set up CI to publish tree-sitter to NPM. https://github.com/FuelLabs/tree-sitter-sway/issues/4

**Comment by sdankel** [comment]
PR adding sway tree-sitter to vscode.dev https://github.com/microsoft/vscode-anycode/pull/64
