### ISSUE TITLE
`forc doc`: Problem formatting `self` in function parameters of trait methods

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3805]
This has to do with #3657 

I hastily made a formatter for trait methods, and in doing so inadvertently birthed this issue. I plan to tackle this while handling the aforementioned issue, but I'm opening this for consistency.

**Comment by gr00vytvniks** [comment]
I think I can take this on

**Comment by eureka-cpu** [comment]
> I think I can take this on

cool (: by all means
