### ISSUE TITLE
Hashing of `Bytes` type

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#3809]
The `Bytes` type was recently introduced as a way to tightly pack bytes. A common use case for this is hashing as a way to avoid padding of types such as `u8` to a full word. This is explicitly done in the [Merkle Proof library](https://github.com/FuelLabs/sway-libs/blob/27215d1829d2fd03d78d31a7d00cd70675cbc8fc/sway_libs/src/merkle_proof/binary_merkle_proof.sw#L22) where the concatenation of a single `u8` to the front of a `b256` is needed to follow the RFC-6962 specification.

However, the current [`sha256()`](https://github.com/FuelLabs/sway/blob/f18197f0c040d1223968ca046edf12e053a3568a/sway-lib-std/src/hash.sw#L4) function in the hash library does not allow for hashing of the tightly packed bytes. The `Bytes` type stores a length along with the `RawBytes` type which contains a pointer to the bytes. 
For example, when calling `sha256(my_bytes)` where `my_bytes` is a `Bytes` struct, the `sha256()` method will call `__size_of` upon the struct. As a result, I did not just hash the tightly packed bytes but instead hashed the struct itself. 

To avoid developers having to create their own asm blocks, there should be an easy method to hash these bytes. 

I believe the best way to handle this would be to add a hashing function to the `Bytes` type. A developer would then call the function in the same manor that `.join()` and `.push()` are called. 

cc @nfurfaro

**Comment by nfurfaro** [comment]
I think adding `.keccak256()` & `.sha256()` methods to the `Bytes` type makes sense.

**Comment by adlerjohn** [comment]
At the risk of necroing, would it be better to have something like a `Serializable` trait?

**Comment by bitzoic** [comment]
> At the risk of necroing, would it be better to have something like a `Serializable` trait?

I think a `Serializable` trait could be used in place of https://github.com/FuelLabs/sway/issues/3561

**Comment by nfurfaro** [comment]
@john  would you mind commenting on the issue #3561 as to why `Serializable` might be preferable to reusing `From`?
I had starting down the road to implementing a `Packable` trait, but after some discussing, it was decided that just reusing `From` was the preferred approach.
cc @sezna
