### ISSUE TITLE
Some Weird Logging/Generics ICE

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/sway#3812]
Compiling `amm` of [this branch](https://github.com/sway-libs/concentrated-liquidity/tree/controlc/ice_ice_baby) of `concentrated-liquidity` results in the following error (actually it's `forc test`)

```
error
 --> /Users/controlc/.forc/git/checkouts/std-57e47d01450577b4/2b2b4b117c4f6a5e762e368af0dfc6896fa31e7d/sway-lib-std/src/logging.sw:8:5
  |
6 | 
7 | pub fn log<T>(value: T) {
8 |     __log::<T>(value);
  |     ^^^^^^^^^^^^^^^^^ Internal compiler error: Unable to determine ID for log instance.
Please file an issue on the repository and include the code that triggered this error.
9 | }
  |
____

  Aborting due to 1 error.
Error: Failed to compile cl_libs
```

I will also note, you must be using a `master` branch sway compiler or you will encounter another ICE which has now been fixed

**Comment by mohammadfawaz** [comment]
I can reproduce on `master` 🤔 - taking a look.

**Comment by mohammadfawaz** [comment]
Right so the issue is with nested libraries using `log`. You're not directly using a `log` here, but some test use some methods that have `require` which itself uses `log` under the hood. This is a bug that we need to fix of course, but as a workaround, use `assert` instead of `require` until this is fixed.

**Comment by mohammadfawaz** [comment]
Here's a small reproducer:
```
// top level library in `main.sw`
library lib;

dep inner;
```
and 
```
// Some inner library in `inner.sw`
library inner;

#[test]
fn some_test() {
    std::logging::log(1);
}
```
