### ISSUE TITLE
Sway unit tests are run multiple times

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#3813]
In my current project, some(but not all) of the unit tests run twice.
One thing to note with my project (a library) is that the tests are currently spread across multiple files/libraries.
I haven't managed to create a minimal repro yet, but here is a link to my branch: https://github.com/FuelLabs/sway-applications/tree/furnic/add-abi-and-contract/chess-game 

Here is a sample of the output. Note that there are actually only 5 unique tests being run here:
```
Bytecode size is 1700 bytes.
   Running 16 tests

   tested -- lib_chess

      test test_new_bitstack ... ok (229µs)
      test test_new_bitstack ... ok (99.875µs)
      test test_to_u8 ... ok (321.125µs)
      test test_to_u8 ... ok (321.25µs)
      test test_multimask ... ok (2.139291ms)
      test test_new_board ... ok (164.291µs)
      test test_increment_half_move_counter ... ok (211.958µs)
      test test_to_u8 ... ok (352.75µs)
      test test_new_bitstack ... ok (215.166µs)
      test test_to_u8 ... ok (347.708µs)
      test test_to_u8 ... ok (338µs)
      test test_multimask ... ok (2.069458ms)
      test test_new_board ... ok (138.083µs)
      test test_increment_half_move_counter ... ok (156.333µs)
      test test_to_u8 ... ok (312.375µs)
      test test_to_u8 ... ok (310.208µs)
   Result: OK. 16 passed. 0 failed. Finished in 7.726871ms.
```

 cc @kayagokalp

**Comment by kayagokalp** [comment]
Hey @nfurfaro thanks for the issue. I am trying to debug this but having some troubles. I think your repo does not build with latest(`0.33`) `forc`, right? Do you have the version of `forc` you are using?

**Comment by nfurfaro** [comment]
@kayagokalp Hmm, it does for me?
<img width="731" alt="image" src="https://user-images.githubusercontent.com/17053076/213578564-23bf192a-aa2a-4e97-9715-a5a54e7c299f.png">

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/17053076/213578624-b3f0639d-7921-4298-9fcc-af25a8a3dd2c.png">

**Comment by mitchmindtree** [comment]
Ahh, I wonder if this has something to do with picking up tests not only in the top-level project, but in dependencies too? I thought I'd addressed this in the original implementation, but perhaps not.

**Comment by nfurfaro** [comment]
Perhaps? My project is a workspace. All the tests are in multiple .sw library files (all in the same directory) exposed through a single lib.sw file.

**Comment by nfurfaro** [comment]
Bumping this. While the project I'm seeing this in is a side project, it's providing a good stress-test of forc-test. Currently, I have only 9 unique tests, but 81 tests are being run, and they seem to be hanging...
