### ISSUE TITLE
Introduce `Sha256` and `Keccak256` traits to the standard library

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3835]
This would follow how Rust does this for the most part and allows us to implement `sha256()` and `keccak256()` for all primitive types and custom implement them for user types. I don't think we should do this before we can derive a default implementation of these for user types (structs and enums), so we're technically blocked by the [derive system](https://github.com/FuelLabs/sway/issues/2396).

**Comment by otrho** [comment]
Wouldn't it be better to have just the `sha256()` and `keccak256()` functions be generic over an `Into<Bytes>` type, or something similar?  Still needs updates to the type system but I think a trait just for hashing is overkill.

**Comment by mohammadfawaz** [comment]
I think the idea with a trait is similar to rust's `Hash` trait. But really whatever approach allowing users to defined their own hashing methods is fine.
