### ISSUE TITLE
Unrelated error while using unknown generic type parameter.

### ISSUE THREAD

**Issue by esdrubal** [FuelLabs/sway#3865]
While using an unknown generic type with Option::None we get an unrelated error.
```rust
script;

fn main() {
    Option::None::<T>();
}
```
Error thrown:
```
18 |     Option::None::<T>();
   |             ^^^^ Could not find symbol "None" in this scope.
```

**Comment by emilyaherbert** [comment]
@esdrubal, is this because of the presence of the `()`? Maybe this is being parsed as a function call? 🤷‍♀️

**Comment by mohammadfawaz** [comment]
@esdrubal do you mind posting a more elaborate example showcasing the issue?

**Comment by esdrubal** [comment]
The example I provided shows the issue as intended. The type parameter comes from nowhere and the error should be something like `cannot find type T in this scope` as does rust:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5fd076afb54bf14f14c8dcd9f36c1e71

**Comment by esdrubal** [comment]
It looks like we fail to instantiate `maybe_enum` and then the LOC below throws the error:

https://github.com/FuelLabs/sway/blob/97190861deda5958921c6cecbc81d9141179fd22/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs#L1199
