### ISSUE TITLE
We need to decide what should be included in a .sw abi.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#392]
There was some discussion on Slack about what should/can be included in a Sway abi.
There is an example in the sway docs showing a storage variable defined in an abi (https://fuellabs.github.io/sway/latest/examples/wallet_smart_contract.html), and I was wondering about whether we should add the ability to define our events in abis. 
After thinking about this a little more, I have a few recommendations.

- **Storage variables** (including Constants & Immutables):
I don't think these should be included in an abi. They are implementation details, and therefore not something the abi (interface) abstraction needs to be concerned with or even know about.

- **Event structs**:
I think these must be included in the abi, as they are part of the very definition of how users can interact with a contract which implements a given abi. 
Think about  EIP-721 for example (https://eips.ethereum.org/EIPS/eip-721), which defines both the methods and the events a contract will implement.

In Solidity ( and I would assume in Sway as well) there is a distinction between an `interface` which can be inherited by a `contract` which must then implement the interface's (public) methods, and the `json.abi` which is generated from the solidity contract, and  can be used to interact with the deployed contract, ie: from another contract, in Node.js test suites, dApps, etc...

**Comment by mohammadfawaz** [comment]
Closing in favour of https://github.com/FuelLabs/sway/issues/2130
