### ISSUE TITLE
`forc-pkg`: Support workspace-level `[patch]` table

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3958]
Currently, I believe our `[patch]` table support is limited to individual packages (@kayagokalp correct me if I'm wrong :sweat_smile:).

We should match Rust's behaviour, where `[patch]` is applied at the workspace level. This is because the workspace is responsible for the overall package graph and lock file, and when a patch needs to be applied to a package in the graph it is most often applicable for all members of the workspace.

**Comment by kayagokalp** [comment]
This is definitely a must-have! While testing things with huge workspaces (the latest incident was SDK's testing suite workspace 😄) I find myself going in each `Forc.toml` and adding an explicit std dependency so that I can build with master forc.
