### ISSUE TITLE
Add handling of implementations to `forc doc`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3972]
Currently `ImplTrait`s are commented out and unhandled. I mention in a comment [here](https://github.com/FuelLabs/sway/blob/bdfae6cd478e28e0ca57fb0f89b5ecd9ebd16f12/forc-plugins/forc-doc/src/descriptor.rs#L205) that we should find a way to link implementations to their respective documents. This may mean either a hacky solution or update the AST to provide the implementations on said types.

**Comment by mitchmindtree** [comment]
Tentatively added to current milestone :)
