### ISSUE TITLE
Support URL links in LSP hover popups.

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#3973]
For example, It would be nice to have links to pages in the sway reference that people could click on to find out more information. 

Below is an example from rust-analyzer rust.

![Screenshot from 2023-02-03 09-47-37](https://user-images.githubusercontent.com/1289413/216468746-5547e62e-c275-4a8d-a791-2f3197788c2f.png)

**Comment by sdankel** [comment]
This is supported, although not many of the sway docs have links.
![image](https://github.com/user-attachments/assets/ae6d000a-e450-4da6-94d1-829fa101b64d)
