### ISSUE TITLE
Update `mdbook` version in CI

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3980]
https://github.com/FuelLabs/sway/blob/c84790e126f24a3dc34ea11c924da0caef073899/.github/workflows/ci.yml#L134

https://github.com/FuelLabs/sway/blob/c84790e126f24a3dc34ea11c924da0caef073899/.github/workflows/gh-pages.yml#L42

**Comment by eureka-cpu** [comment]
current version is `0.4.25`

**Comment by eureka-cpu** [comment]
current version is `0.4.25`

**Comment by gr00vytvniks** [comment]
Opening a PR for this today
