### ISSUE TITLE
Update Sway book `README`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3981]
https://github.com/FuelLabs/sway/blob/c84790e126f24a3dc34ea11c924da0caef073899/docs/book/README.md#building-from-source

```sh
cargo install --path ./forc-plugins/forc-fmt
cargo install --path ./forc-plugins/forc-lsp
cargo install --path ./forc-plugins/forc-explore # forc explore can't be installed this way since it is not in the forc-plugins folder
cargo install --path ./forc-plugins/forc-doc
```
- `+ cargo install forc-explore`

`mdbook build` doesn't specify that you need to give a path to a `book.toml`, we could add that to the description above the command or add a comment like so `# path to book.toml`

`MDBOOK_preprocessor__FORC_documenter__STRICT="true" mdbook build docs` This command fails even when in the root directory, we could remove `docs` and add the same as above.

The same applies to `mdbook serve`

https://github.com/FuelLabs/sway/blob/c84790e126f24a3dc34ea11c924da0caef073899/docs/book/README.md#generating-documentation-for-forc-commandsplugins

There is a broken link at `mdbook-forc-documenter README`

**Comment by gr00vytvniks** [comment]
Opening a PR for this today

**Comment by eureka-cpu** [comment]
> Opening a PR for this today

nice thanks!

**Comment by bingcicle** [comment]
Technically, the `mdbook build` instruction isn't incorrect. The instruction either uses the current working directory by default, or a given path. Perhaps we could clarify this instead - will write more in the PR.
