### ISSUE TITLE
`Self` in contracts always mean `Contract`, even inside traits

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#3994]
The following piece of code:

```contract;

trait MySuperTrait {
    fn foo();
}

trait MyTrait : MySuperTrait {
    fn bar();
} {
    fn baz() {
        Self::foo()      // Self should mean MyTrait here?
    }
}
```

fails with this error:

```
error
  --> /Users/anton/fuel/sway/supertraits_for_traits/src/main.sw:12:15
   |
10 |
11 |     fn baz() {
12 |         Self::foo()
   |               ^^^ No method named "foo" found for type "contract".
13 |     }
14 | }
   |
____
```

Looks like in contracts `Self` always means `Contract`, even though I it should mean `MyTrait` inside `baz`.

**Comment by emilyaherbert** [comment]
Hi @anton-trunov, I'm not able to recreate this bug on master. Or rather, this test case does not fail for me on master.

**Comment by anton-trunov** [comment]
@emilyaherbert Thanks for looking into this. Indeed, you are right, that's a bug in my branch. Sorry for the noise, closing this.
