### ISSUE TITLE
Warnings for `impl` blocks contain entire code_block span

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#4000]
This was partly addressed in #3769, looks like `impl` blocks are still showing warnings over the entire code block.

![Screenshot from 2023-02-07 08-49-49](https://user-images.githubusercontent.com/1289413/217096352-b48f6655-b86b-47fa-bd07-f0dfe8146c21.png)

**Comment by sdankel** [comment]
This is the same issue as https://github.com/FuelLabs/sway/issues/3803
