### ISSUE TITLE
Not possible to use associate function call of trait impl method.

### ISSUE THREAD

**Issue by esdrubal** [FuelLabs/sway#4025]
@nfurfaro found an issue while doing https://github.com/FuelLabs/sway/pull/3882 that can be reproduced by the following sway script:

```rust
script;

trait From2<T> {
    fn into(self) -> T;
}

struct S1 {
    s1: u64
}

struct S2 {
    s2: u64
}

impl From2<S1> for u64 {
    fn into(self) -> S1 {
        S1{s1: self}
    }
}

impl From2<S2> for u64 {
    fn into(self) -> S2 {
        S2{s2: self}
    }
}

fn main() {
    let s1: S1  = 42.into();

    // throws Mismatched types.
    let s2: S2  = 42.into();
    
    // Associate function call not supported in sway.
    // throws Unknown type name "From2"
    let s2: S2  = From2::<S2>::into(42);
}
```

The following rust [playgroud](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2efe4d98c686bde483e73ef714cf2312) shows how this works in rust. The error `multiple applicable items in scope` is thrown when calling `into` directly but it is still possible to use the associate function call.

This issue should be addressed by:
  1. ensure that `into` methods can be called by associate function call.
  2. throw a proper error like `multiple applicable items in scope` when `into` is called.

**Comment by nfurfaro** [comment]
Just giving this a little bump. :)
