### ISSUE TITLE
Constant value evaluation in the AST needed.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#407]
Constant expressions are used in the language in a couple of areas, two I can think of are the RHS initialisers of `const` declarations and also the length specifier in a static array type declaration or initialiser.

```rust
const FOO: u32 = 0x12345678;
const MASK: u32 = 0x00FFFF00;
const FOO_MIDDLE: u32 = FOO & MASK;

const X_SIZE: u64 = 4;
const Y_SIZE: u64 = 2;
let ary = [false; X_SIZE - Y_SIZE + 1];
```

So for us to be able to perform semantic analysis these constant expressions need to be evaluated first.  It's also complicated a bit by the fact that we de-sugar our binary operators into trait methods in `std::ops`.

**Comment by mohammadfawaz** [comment]
Adding the "language feature" label even though this doesn't introduce changes to the language itself.
