### ISSUE TITLE
Use `Path` & `PathBuf` in `ModuleInfo` path creation functions

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#4070]
>The reason why the distinction is important is that paths work differently on different OSes, whereas URLs are the same. E.g. paths on Windows use the `\` separator (so the `join("/")` would be invalid), while Unix uses `/`. In URLs, both use `/`. It looks like this function is only used for URLs though? If that is the case, it might be clearer to call this `file_url_from_location` or similar. Not super important as we don't test for Windows support atm anyways.

_Originally posted by @mitchmindtree in https://github.com/FuelLabs/sway/pull/4017#discussion_r1103903023_

**Comment by mitchmindtree** [comment]
Do I remember this getting resolved by another PR recently? :thinking: Just doing some triage - feel free to ignore if not!

**Comment by JoshuaBatty** [comment]
Also closing this as we don't support windows.
