### ISSUE TITLE
Conservatively disallow nesting a package within a package

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#4072]
In today's tooling sync there was some discussion w.r.t. some ambiguities in forc behaviour around handling packages that are nested within another package.

E.g. currently, there's nothing stopping a user nesting a package within the src directory of another package. This makes it tricky for tools like `forc fmt` to reliably only operate on workspace *members* without actually parsing the sway files to learn what modules are a part of the project, and which ones aren't.

For now, we may wish to conservatively disallow nesting a forc package within another package to avoid these ambiguous situations.

We could use a simple function where given a path to a package's forc.toml, we walk the directory and ensure that there are no other occurences of a `forc.toml` throughout the package.

We should avoid doing this a lot unnecessarily as some users might have large package directories and the walk could be expensive. We probably only want to call this once for each member at the beginning of a command invocation, after the initial workspace or package manifest is loaded.

**Comment by bingcicle** [comment]
To add to this, here's an example:

```console
$ tree -L 2
proj1
├── proj2
│   ├── Forc.lock
│   ├── Forc.toml
│   ├── out
│   └── src
├── Forc.lock
├── Forc.toml
├── out
│   └── debug
└── src
    └── main.sw

6 directories, 5 files
```

`forc build` on `proj1` will build only `proj1` and `forc build` on `proj2` will build only `proj2`.

To clarify, this is easily fixable on the formatter's end, just some changes needed in the way we search for packages to format. I have an issue open at https://github.com/FuelLabs/sway/issues/4050 that has a summary about this.
