### ISSUE TITLE
ec_recover doesn't take the signature.v recovery-byte

### ISSUE THREAD

**Issue by Lukasz2891** [FuelLabs/sway#4076]
The ```ec_recover``` function from ```ecr.sw``` doesn't take the signature.v (recovery byte) as a parameter. So there is not possible to recover public address of all signatures having the byte ```v=1c/28``` at the end. For these ending with ```1b/27``` the function recovers public address properly.

For example:
signature: 
```
r = e0e77e9808e3caf0b18b3d6eddab4f3578f38b4e73d473c236454da14e42f527
s = 6098265e1b5b0a62bc6bd9c8e39ff7e63f4361abc269181faaa5683bca386cb6
v = 1c
```

should return the public key ```f5f035588502146774d0ccfd62ee5bf1d7f1dbb96aae33a79765c636b8ec75a36f5121931b5cc37215a7d4280c5700ca92daaaf93c32b06ca9f98b1f4ece624e``` with address ```0x2c59617248994D12816EE1Fa77CE0a64eEB456BF``` but it returns ```8a23206e9d015958ca2eb9bff813c209e8405926cfd9a6865cd752b029c51987caa350ba73a9059393c7165ae4f5f8ef83b95433b9b60e76247b52db2ba9e9cd```with address ```0xf5968C300AAeF8a314597bE042501a2f502dC3B4``` because the ```v```-value is skipped.

**Comment by nfurfaro** [comment]
@Lukasz2891 Fuel uses the "Compact Signature Representation" as per:
 https://eips.ethereum.org/EIPS/eip-2098

This allows us to pack a signature into 64 bytes rather than needing 65.
Let me know if this makes sense :)

**Comment by Lukasz2891** [comment]
It does, thanks :) 

I missed it in the documentation or it's just not written clear enough ;)

But maybe it's also worth to create a constructor of the signature B512 by using the "common" r,s,v ;)

**Comment by nfurfaro** [comment]
>maybe it's also worth to create a constructor of the signature B512 by using the "common" r,s,v

Would this even be useful in Sway? In our testing of ec_recover, all signature generation is done off-chain in Rust.
It would be pretty easy to write a helper function that takes in those 3 params and builds a B512 from them, but if you already have all the params it can be done in Rust. Example: https://github.com/FuelLabs/sway/blob/74bf48c8b81eaf4868992fd1f1916d6b022da3d3/test/src/sdk-harness/test_projects/ec_recover/mod.rs#L28
