### ISSUE TITLE
docs: `forc fmt` command not documented in the `--help`

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/sway#4091]
Running `forc --help` doesn't list `fmt` as one of the possible commands, even though it is super useful.

**Comment by brandonsurh** [comment]
This is because `forc` and `forc --help` only list the available commands. If installed, `forc-fmt` is one of the plugins that can be seen when running the command `forc plugins`. If a user has not installed `forc-fmt`, it will not run.

See more: https://docs.fuel.network/docs/forc/plugins/

**Comment by JoshuaBatty** [comment]
closing, as @brandonsurh mentioned above, this can be seen running

```
❯ forc plugins
Installed Plugins:
forc-crypto
forc-deploy
forc-doc
forc-fmt
forc-lsp
forc-run
forc-submit
forc-tsgen
forc-tx
```
