### ISSUE TITLE
Formatter moving comments below empty function

### ISSUE THREAD

**Issue by camiinthisthang** [FuelLabs/sway#4092]
I'm writing simple examples and defined functions with only a comment in the body. On save, the formatter moves the comment under the function and moves the closing curly brace next to the opening one. For example:

```
fn on_even(num: u64) {
 // do something with even numbers
}
```

to
```
fn on_even(num: u64) {}
    // do something with even numbers
```

I'm on the nightly version of the toolchain, using` forc-lsp : 0.35.0+nightly.20230215.f7cbf83bd5`

**Comment by sdankel** [comment]
This seems related to https://github.com/FuelLabs/sway/issues/3904

When there are comments in the empty block, we should preserve their position inside the block.
