### ISSUE TITLE
Parsing/typechecking weirdness wrt. paths/enums

### ISSUE THREAD

**Issue by canndrew** [FuelLabs/sway#411]
Something I noticed when diving into parsing/typechecking is that compiler distinguishes between `func(arg)` and `module::func(arg)`. One is parsed as a `FunctionApplication` whereas the other is parsed as a `DelineatedPath` with arguments. These are the same thing though. That is `module::func(arg)` should get parsed and typechecked into a function application with function `module::func` and args `(arg)`. This should also work for enum variants. That is, in rust, if you have an enum:

```rust
enum Foo {
    Variant(u32),
}
```

Then the expression `Foo::Variant(0u32)` is just an application of the function `Foo::Variant` to the argument `0u32`. That is, every tuple-like enum variant defines an injective function into the enum type.

I think it should work like this in Sway too. That is, multi-component paths (without args) should get parsed as expressions with single-component variable names just a special case. `TypedExpressionVariant::EnumInstantiation` shouldn't contain an argument and should represent the function that creates the respective enum variant.

I can start implementing this though I'm not sure if it should be blocked on waiting for the new parser, since it will involve changes to the parser.

**Comment by emilyaherbert** [comment]
Does #75 fix this issue? In particular, functions of the format `module::fn_name(args)` now get parsed as delineated paths.

See: https://github.com/FuelLabs/sway/blob/fd6a093d50b8148f6dcd0e75dfbf8d39d43102d0/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs#L1118

And: https://github.com/FuelLabs/sway/blob/fd6a093d50b8148f6dcd0e75dfbf8d39d43102d0/sway-core/src/sway.pest#L72

**Comment by sezna** [comment]
I think #75 / #472 fixed this, as all function items are parsed as call paths. The reason we use delineated paths is because it is impossible to know if `a::b()` is an enum instantiation or a function call until type checking.

Closing for now, but feel free to reopen if you think there's still an issue here.
