### ISSUE TITLE
Sway book: Missing info about contract interaction and deployment

### ISSUE THREAD

**Issue by cold-briu** [FuelLabs/sway#4120]
I've just deployed the counter example from the book. However I have found tutorial about throwing basic interaction from cli. In the same way, there's no tutorial to properly sign and deploy a new contract. 

I can help with these but I might need more examples of forc-run to have a better understanding.

**Comment by kayagokalp** [comment]
We have [the following section](https://fuellabs.github.io/sway/master/book/forc/plugins/forc_client/index.html#signing-transactions-using-forc-wallet-cli) in the sway book explaining how to sign a transaction created by `forc-client` (`forc-deploy`, `forc-run`), and we have a [developer quickstart ](https://fuellabs.github.io/fuel-docs/master/developer-quickstart.html) if you need more like a step-by-step approach.

Is this what you are looking for?

**Comment by kayagokalp** [comment]
I am closing as we already have this documentation in place but feel free to re-open if you feel like if:

1. It is not what you are looking for
2. It is not sufficient
