### ISSUE TITLE
No error lines in Sway Plugin

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#4124]
The following code does not produce any error lines in the Sway Plugin. Running `forc build` correctly fails to compile.

Plugin: `0.2.9`
Forc: `0.35.1`

```rust
contract;

use std::block::timestamp;

abi MyContract {
    fn test_function() -> bool;f
    dfsdf
}

impl MyContract for Contract {
    fn test_function() -> bool {
        log(timestamp());
        true
    }
}
```

![1 (1)](https://user-images.githubusercontent.com/103777923/219797752-883598a2-ba38-44ac-a3ac-db9c1a9cd449.png)

**Comment by AbhinavMir** [comment]
Probably can close this issue and discuss this over in https://github.com/FuelLabs/sway-vscode-plugin/issues/141
