### ISSUE TITLE
Internal compiler error: Destination arg for load/store is not valid.

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#4158]
forc v0.35.3

The example below is a minimal repro of what is happening [here](https://github.com/FuelLabs/sway/blob/a71fc7953f8f2755ce84fbda71fb66f0ed9d3a15/sway-lib-std/src/bytes.sw#L646) in the `Bytes` library when using `Bytes` as an underlying type. The ICE does not occur when the `Bytes` type performs this swap functionality on its own and not as an underlying type.

***Note*** This bug is preventing anyone from wrapping the `Bytes` type and calling the `append()` function. This functionality is needed for the `String` type. 

```rust
contract;

pub struct My_Underlying_Struct {
    val: u64
}

impl My_Underlying_Struct {
    pub fn my_swap(ref mut self, ref mut other: self) {
        self = other
    }
}

pub struct MyStruct {
    my_struct: My_Underlying_Struct
}

impl MyStruct {
    pub fn my_swap(ref mut self, ref mut other: self) {
        self = other
    }

    pub fn my_swap_underlying(ref mut self, ref mut other: self) {
        self.my_struct.my_swap(other.my_struct)
    }
}

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {

        let mut my_struct1 = MyStruct { my_struct: My_Underlying_Struct { val: 0} };
        let mut my_struct2 = MyStruct { my_struct: My_Underlying_Struct { val: 0} };

        // Perfectly okay
        my_struct1.my_swap(my_struct2);

        // Internal compiler error
        my_struct1.my_swap_underlying(my_struct2);
        my_struct1.my_struct.my_swap(my_struct2.my_struct);

        true
    }
}
```

![CompilerError](https://user-images.githubusercontent.com/54727135/220679283-8b56dd46-bed8-43d7-8fe0-fac53e97f7cb.png)

**Comment by otrho** [comment]
This is strongly related to the stuff I'm working on now and hope to have in soon.

**Comment by bitzoic** [comment]
This seems to have been resolved in the latest release of forc.
