### ISSUE TITLE
Forc fails to parse library when docs before module definition

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#4160]
Given the following project structure, we would like to add `my_library` as a dependency to `my_contract`.

```
my_project/
├── my_contract
|    └── src/main.sw
|    └── Forc.toml
├── my_library
|    └── src/lib.sw
|    └── Forc.toml
└── Forc.toml
```

If we add docs before the module definition of `my_library`, forc fails to parse `my_library`. 

![dependencyError](https://user-images.githubusercontent.com/54727135/220692842-a2958dd1-d84b-46aa-8d75-c1e2bdeebb32.png)

Example library:

```rust
/// This doc causes the error
library my_library;

abi MyContract {
    fn test_function() -> bool;
}
```

Example contract:

```rust
contract;

use my_library::MyContract;

impl MyContract for Contract {
    fn test_function() -> bool {
        true
    }
}
```

The following is the `Forc.toml` file that adds `my_library` as a dependency:

```rust
[project]
authors = ["Cam Fuel"]
entry = "main.sw"
license = "Apache-2.0"
name = "my_contract"

[dependencies]
my_library = { path = "../my_library" }
```

Tested using forc v0.35.3. This was not an issue on forc v0.35.1

**Comment by sdankel** [comment]
When I tried this, I got the following error.
<img width="902" alt="image" src="https://github.com/FuelLabs/sway/assets/47993817/3e86fd13-c0dc-458c-9e90-c7aa201b9c73">

I'm going to close this since it seems like it was just missing a helpful error message.
