### ISSUE TITLE
Enable usage of injected contract ids from contract dependencies in multi contract calls 

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#4162]
from #4156:

> There is contract_a which declares contract_b as a contract dependency. Because of this relation forc-pkg inserts CONTRACT_ID constant into namespace and we can address the contract id of contract_b from contract_a using let id = contract_b::CONTRACT_ID;. Since these are both contracts that we want to test, forc-test injects CONTRACT_ID into their namespaces for them to be able to make contract calls. After this step using let id = contract_b::CONTRACT_ID; in contract_a would result id taking the contract id of contract_a. This looks like a bug with the way we resolve constants or the way we inject stuff into namespaces.

**Comment by mitchmindtree** [comment]
> Contract dependency is an information we are holding in the edges of the build plan graph as it is a feature of a package relative to another package. This means that contract id of a contract dependency is relative to the package it is a contract dependency to. On the other hand the id we are injection for test execution is not relative to any other package.

Ahhhh I think I see the issue.

I think this indicates that we want to build each contract not just *once* without tests, but once for each time it is uniquely depended on by an edge from a dependent contract. Almost always this will still only be once, as even if a contract is depended on by more than one other contract, they'll almost certainly use the same salt anyway.

I don't think we should need a separate `TEST_CONTRACT_ID` - as long as we use the salt specified in the manifest, there should be no reason for the contracts (when built without tests) to have different IDs right?

**Comment by kayagokalp** [comment]
> Almost always this will still only be once, as even if a contract is depended on by more than one other contract, they'll almost certainly use the same salt anyway. (Edit: I guess technically we shouldn't have to do the whole build again for each unique edge, just create a unique contract ID for each edge 🤔).

Yeah exactly! 

Currently this is not a problem as (if i recall correctly) we do not allow separate salt declarations for the same contract but I think we should, as a user might want to interact with two different deployments of the same contract. Each contract id injection should be done relative to the calling package so calling `pkg_a::CONTRACT_ID` from `pkg_b` which declares `pkg_a` as a contract dependency with zeroed salt, and from `pkg_c` which declares `pkg_a` as a contract dependency with non zero salt should yield different ids. Because that might be actually intentional. 

For example I would imagine there will be some fuel standards for NFTs and people deploy these contracts lots of time, I guess I might want to interact with two different NFTs deployed with different salts from my scripts?


This leads to this problem again the id injected for test execution and contract dependency id injection might differ as we don't know which salt declaration to use if we have multiple of them.

On top of this discussion there is an apparent bug:

Currently if i declare `pkg_a` as a contract dependency to `pkg_b` and build with tests `let id = pkg_a::CONTRACT_ID` becomes the contract id of `pkg_b` injected for test execution. I am guessing this is a bug in the compiler but somehow the same const name causes the submodule declarations to get shadowed even though they are accessed explicitly..

**Comment by kayagokalp** [comment]
Closed by #4219
