### ISSUE TITLE
Weird formatting with commented out functions and docs

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#4185]
When commenting out a function and there is a doc above the function, we see the following weird formatting behavior. 

This is our code before formatting:

```rust
    /// This is documentation for a commented out function
    // fn commented_out_function() {
    //}

    fn test_function() -> bool {
        true
    }
```

After formatting we have the following:

```rust
    /// This is documentation for a commented out function

        // fn commented_out_function() {
    //}
fn test_function() -> bool {
        true
    }
```

Tested with v0.35.3

**Comment by bitzoic** [comment]
Using forc v0.37.0 I used this input:

```rust
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    /// This is documentation for a commented out function
    // fn commented_out_function() {
    //}

    fn test_function() -> bool {
        true
    }
}
```

This is the following formatting output:

```rust 
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    /// This is documentation for a commented out function

    // fn commented_out_function() {
    //}
    fn test_function() -> bool {
        true
    }
}
```

**Comment by bitzoic** [comment]
> In `v.0.37.1` after having commented out some number of lines it adds lot of empty lines before the commented code :)
> 
> ```rust
> library;
> 
> use std::{u256::U256, vec::*};
> use ::utils::vec::sort;
> use ::utils::numbers::*;
> 
> // pub fn aggregate_results(results: Vec<Vec<U256>>) -> Vec<U256> {
> //     let mut aggregated = Vec::new();
> 
> //     let mut i = 0;
> //     while (i < results.len) {
> //         let values = results.get(i).unwrap();
> //         aggregated.push(aggregate_values(values));
> 
> //         i += 1;
> //     }
> 
> //     return aggregated;
> // }
> ```
> 
> is formatted to
> 
> ```rust
> library;
> 
> use std::{u256::U256, vec::*};
> use ::utils::vec::sort;
> use ::utils::numbers::*;
> 
> 
> 
> 
> 
> // pub fn aggregate_results(results: Vec<Vec<U256>>) -> Vec<U256> {
> //     let mut aggregated = Vec::new();
> 
> //     let mut i = 0;
> //     while (i < results.len) {
> //         let values = results.get(i).unwrap();
> //         aggregated.push(aggregate_values(values));
> 
> //         i += 1;
> //     }
> 
> //     return aggregated;
> // }
> ```

I have seen this in a number of files in the sway-libs repository as well

**Comment by bingcicle** [comment]
Thank you for the examples/repros! Would be super helpful in fixing these bugs @bitzoic @Lukasz2891

**Comment by bingcicle** [comment]
Created a new issue #4473 for @Lukasz2891 's bug, because they're separate issues.
