### ISSUE TITLE
[forc-doc] The Sway logo should be linked to the project root

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#4195]
Currently, if I click the logo from https://fuellabs.github.io/sway/master/std/address/struct.Address.html , It takes me to https://fuellabs.github.io/sway/master/std/address/index.html

I would expect it to take me to https://fuellabs.github.io/sway/master/std/index.html#

**Comment by eureka-cpu** [comment]
Ref #3996 currently the logo will go back a module until you reach the parent module. This is a known issue, will have a PR up soon!
