### ISSUE TITLE
[forc-doc] Shows version 0.0.0

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#4197]
This doesn't seem right.

![image](https://user-images.githubusercontent.com/47993817/221710138-c6268a95-c18b-4112-9b17-e42fe03d175b.png)

**Comment by eureka-cpu** [comment]
That is the forc version, if it's unspecified it is version `0.0.0`. I could add `Forc` to the beginning so that it is more clear or remove it entirely?

**Comment by eureka-cpu** [comment]
The reason this might be important is that the user may not be using the latest toolchain, so seeing the version when deploying the docs can be helpful. The way rust does this, is instead they use the version of the program itself but we do not yet support semver for Sway projects.
