### ISSUE TITLE
[forc-doc] Links to field types

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#4198]
Example: https://fuellabs.github.io/sway/master/std/low_level_call/struct.CallParams.html#fields

Currently there is no way to click into the field types. For example, there should be a link to the docs for `ContractId` that I can click into to see what that type is.

![image](https://user-images.githubusercontent.com/47993817/221710381-8e4d1c8d-7b48-4305-8112-260adc1600ac.png)

**Comment by eureka-cpu** [comment]
Closed by #3173
