### ISSUE TITLE
[forc-doc] Link to the usages of a struct

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#4199]
It would be useful to have a link to the usages of a struct in the std library. 

For example, if I'm looking at https://fuellabs.github.io/sway/master/std/low_level_call/struct.CallParams.html#, I want to see all of the functions that accept this struct as a parameter.

**Comment by eureka-cpu** [comment]
Hm, I'm not sure that the rust docs do this do they? I know the inverse is true and I have a PR open for it, eg you can click a param in a function that will take you to the data type

**Comment by mitchmindtree** [comment]
Yeah this sounds like a cool stretch goal - imagining something a bit like [hoogle](https://hoogle.haskell.org/), where you can search for functions across a package (or all of docs.sw).

**Comment by sdankel** [comment]
I think I was thinking of trait implementations, which have now been added.
