### ISSUE TITLE
Constants in the root module override other constants with the same name in the submodules 

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#4217]
## Problem 

Constants in submodules overriden by the root module if they share the same name. To give an example:

main.sw:

```rust
contract;

dep pkga;

const TEST_CONST: u64 = 20;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        true
    }
}

#[test(should_panic)]
fn test_success() {
  assert(TEST_CONST == pkga::TEST_CONST)
}
```

pkga.sw:
```rust
library pkga;

pub const TEST_CONST: u64 = 10;
```

If `forc test` is run with this setup , the test would be failing but it shouldn't as it is a should revert test and `TEST_CONST` had to be different. Logging them shows that both of them is `20`, the value at the root submodule.

## Possible cause

We had a chat with @mitchmindtree yesterday and made a quick investigation in the compiler. It might be possible that problem is arising from `compile_const_decl` function which compiles const expression to a `Value`. It only accepts a constant name and some look-up variables which contains the namespace. The function then searches the namespace only using the name but in the example above although we are explicitly using  the constant from submodule the name is still `TEST_CONST`. This causes the symbol checking in the namespace to found the `TEST_CONST` in the root module (instead of `pkga::TEST_CONST`)

## Possible solution

`compile_const_decl`  should also be accepting the `path`, and module look-up function should accept the path and the name of the variable so that it can differentiate between the symbols that has the same name in root and submodules.

This is blocking me in #4156. Related to #4162

**Comment by mohammadfawaz** [comment]
Seems critical to me. We'll get to it asap.
