### ISSUE TITLE
`Self` does not work when qualifying an enum variant in a `match` statement

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#4263]
Example:
```rust
script;
enum Foo {
    X: u64,
}

impl Foo {
    fn foo(self) -> bool {
        match self {
            Self::X(_) => true, // Complains that `Self` does not exist
        } 
    }
}

fn main() {}
```
Rust equivalent that works: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fb615cf6f202e2e307c9e6d4bb7b6fe4

**Comment by kayagokalp** [comment]
Hey @mohammadfawaz, is this related to `forc-test` or did that tag slipped-in? 👀

**Comment by mohammadfawaz** [comment]
Sorry! Yeah meant to add `frontend` not `forc-test`.
