### ISSUE TITLE
Tuple de-structuring does not error out on mismatch tuple types

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#4270]
Example:
```rust
script;

fn foo() -> (u64, u64, u64) { (0, 0, 0) }

fn main() {
    let (x, y) = foo(); // Should be `let (x, y, z) = ..`
}
```
compiles fine but it shouldn't.

**Comment by IGI-111** [comment]
It doesn't look like we're checking the type ascription for tuples in destructuring, except as a byproduct of checking the fields. I think we can get away with fixing this without a wrapper.
