### ISSUE TITLE
Mutable arrays

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#428]
#18 and #424 introduced const arrays but mutable arrays still need to be done

A part of this may be to introduce the `IndexMut` trait and to call it (instead of the `Index` trait) for mutable values for types other than static arrays.  See #429

**Comment by mohammadfawaz** [comment]
@otrho do we still need this if we're going to have `Vec`?

**Comment by adlerjohn** [comment]
Ref: #1118

**Comment by otrho** [comment]
This would be having
```rust
let mut counters: [u64; NUM_COUNTERS] = [0; NUM_COUNTERS];
...
counters[THING_IDX] += 1;
...
```
So, I would say yeah, it'd be useful, but low priority.

**Comment by mohammadfawaz** [comment]
@tritao looks like https://github.com/FuelLabs/sway/issues/429 already exists to track `Index` and `IndexMut`. Will close this again in favor of that one. I also restored the old title.
