### ISSUE TITLE
Split `storage.sw` into modules

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#4304]
## Motivation

The file has multiple types and it's starting to become large.
We should split the file into modules and reexport to maintain functionality but compartmentalise the code.

**Comment by mohammadfawaz** [comment]
It would be nice to do this after https://github.com/FuelLabs/sway/issues/3487 is closed so that importing items from the storage sub-libraries is not too verbose (assuming we're splitting `storage.sw` into submodules inside a `storage` folder).
