### ISSUE TITLE
Improve inlay hints and hover for ABI caller

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#4314]
@SilentCicero wrote:
> getting an odd bit of live formatting/code suggestion with the VCCode extension regarding Sway unit testing (it's a little annoying):
Not sure what this is trying to highlight for me, but it was a very weird experiencing having it popup like this. I'd say remove it or move it to another location where it doesn't get in the way of writing code.

![image](https://user-images.githubusercontent.com/47993817/226425311-89754f91-e284-45e1-8a10-fac0e7ef72db.png)

The inlay hint here should show `ContractCaller<Counter>`

There’s one example with the explicit type of contract caller here: `test/src/e2e_vm_tests/test_programs/should_pass/language/contract_caller_dynamic_address/src/main.sw`

**Comment by mohammadfawaz** [comment]
Oh yeah - flagged this a while ago: https://github.com/FuelLabs/sway/issues/3366

Likely a simple update to `TypeInfo::ContractCaller` fixes this.

**Comment by sdankel** [comment]
It's a problem for hover docs as well: 
![image](https://user-images.githubusercontent.com/47993817/226439104-88cf8b48-b048-435e-85d9-a2bd6f6a29c6.png)

**Comment by sdankel** [comment]
I wrote `TypeInfo::display_name` because I wasn't sure if it was safe to update TypeInfo's `fmt` implementation directly. Do you think it would be alright to update these in `fmt`? The only reason not to is if the additional data (e.g. the ABI caller's contract address) is needed in logging or some other context where `fmt` is used

**Comment by mohammadfawaz** [comment]
I think for the `ContractCaller` type specifically, it's safe to update `DisplayWithEngines::fmt` as you wish.

**Comment by sdankel** [comment]
> I think for the `ContractCaller` type specifically, it's safe to update `DisplayWithEngines::fmt` as you wish.

Good to know that's an option. I'm thinking there will be other edge cases like this since the LSP needs to get the user-friendly type name for many different LSP features. I'm thinking about changing all of these `DisplayWithEngine` implementations to `DebugWithEngine` and replacing all of the existing usages to use the debug formatter (changing `"{}" to `{:?}`). And then writing new `DisplayWithEngine` implementations that show the type names that the user will see. I think this would help us avoid a lot of extra code and tricky edge cases in the LSP going forward. What do you think?

**Comment by mohammadfawaz** [comment]
> It seems like it will be useful too for the compiler team to still have a way to easily print out debug information for every type. What do you think?

Seems reasonable to me! @emilyaherbert what do you think?
