### ISSUE TITLE
Add a `forc-crypto` plugin exposing a CLI for common-use cryptographic operations

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#4318]
Raised by @SilentCicero in slack.

The idea is to expose common-use fuel cryptographic functions like `sha256`, `keccak256`, `ecrecover` via forc plugin(s).

The original proposal was for a `forc utils` subcommand with a broader scope, though I'm thinking it could be worth having more descriptive plugins for each set of tools.

A forc-crypto plugin might include commands like the following:

- `forc crypto sha256 ...`
- `forc crypto keccak256 ...`
- `forc crypto ecrecover ...`
- `forc crypto bech32-to-hex ...`
- `forc crypto hex-to-bech32 ...`

Commands like `sha256` and `keccak256` should support both file and string arguments. The same likely goes for the ecrecover message.

The plugin should likely be shipped by `fuelup` as a part of the default set of components.

This plugin should go in its own repo, but we can use this issue to track until then.

**Comment by JoshuaBatty** [comment]
Here are some examples where the SDK has these conversions:

Some examples here:
https://github.com/FuelLabs/fuels-rs/blob/257a77cfdc7e2829df7b9ab88d91e949a6b59aa5/examples/wallets/src/lib.rs#L360
https://github.com/FuelLabs/fuels-rs/blob/12cd13305123de7ceb6c9e4689e76289eeff05ea/examples/types/src/lib.rs#L90-L96
Docs: http://rust.fuel.network/v0.41.1/types/bech32.html

**Comment by Voxelot** [comment]
Also consider migrating some of the fuel-core-keygen functionality over: https://github.com/FuelLabs/fuel-core/blob/master/bin/keygen/src/keygen.rs

**Comment by Voxelot** [comment]
any updates?

**Comment by cr-fuel** [comment]
@Voxelot A PR will be uploaded in a few hours.

**Comment by block0xhash** [comment]
Hi is this plugin available by any chance to try out ?

**Comment by JoshuaBatty** [comment]
We just added the binary to `fuelup`. It should be available on the `nightly` toolchain from tomorrow.
