### ISSUE TITLE
test faucet does not work

### ISSUE THREAD

**Issue by Kathi-cloud** [FuelLabs/sway#4342]
fuel1aegtycplgqgyz8h059nekm2vvyxljszc4yjyajns69ecjjcde6sqtua0k0

and wallet creation is without everything, nothing to store

**Comment by otrho** [comment]
Hi @Kathi-cloud.  This isn't really a Sway issue and perhaps should be directed towards https://github.com/FuelLabs/faucet.

At the same time I think the Faucet is currently running on the beta1 network which is quite out of date and so perhaps the Faucet will be getting some love soon to bring it up to date.

**Comment by kayagokalp** [comment]
I am closing this issue as it is not related to sway but thanks for reporting!
