### ISSUE TITLE
Add a better instruction inserter to IR.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#4344]
There are a few places in the 'demotion' passes introduced in #4336 where we need an instruction inserter as opposed to the instruction appender we have now.

The `InstructionInserter` in `sway-ir/src/instruction.rs` isn't an actual inserter as it only appends an instruction to a block.  And that's just a single instruction at a time.  We currently create a new `InstructionInserter` for each instruction we add.

Ideally we should be able to have a utility which takes a block and either an index or an existing instruction indicating where to insert new instructions (or `None` to indicate appending), and it can then be re-used to insert or append many instructions at a time.

**Comment by vaivaswatha** [comment]
Also, with #4608 instructions refer to this parent blocks. This means manually modifying a block's instruction list (removing / adding / replacing) must be done with care. Ideally that field must be made private and a safe API provided.
