### ISSUE TITLE
Improve IR copy propagation using data flow analysis.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#4345]
The copy propagation optimisation introduced to `memcpyopt` in #4336 is very conservative and has much room for improvement, but is an important optimisation overall.  It currently will not merge copies across blocks or copies to opaque values such as those used by ASM blocks when they are actually viable.

To determine whether those less safe copies we need proper data flow analysis which can tell us whether a memory location is used in multiple locations and when and/or where it is mutated, or which dependencies a location may have.

There is also currently a bug in `memcpyopt` `load_store_to_memcopy` which also requires data flow analysis.  It is possible for a value to be loaded, mutated and then the original stored elsewhere.  `load_store_to_memcopy` will replace the `store` with a `mem_copy` and end up copying the mutated value.  _This is currently possible_ though fairly unlikely, and needs to be addressed promptly.

**Comment by vaivaswatha** [comment]
>copies to opaque values such as those used by ASM blocks when they are actually viable

For example,
```
local b256 a;
local b256 b;

entry:
initialize a;
memcpy b a;
asm (b) {
    ...
}
```

Since `b` is "volatile", we can't replace `b` with `a`. But in this case, if `a` has no other use other than the `memcpy`, then we could replace `a` with `b`.
