### ISSUE TITLE
`forc doc`: Add `--url` flag that makes all links URLs 

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#4372]
`forc doc` creates links to things using the file system which via #4070 will break the doc navigation if they are generated by a Windows machine and deployed. Adding this tag would bypass the system specific file navigation and use `/` only so deploying the docs will work as intended even on Windows systems.

**Comment by mitchmindtree** [comment]
Maybe we should use `url` in general for all builds - not just `--release` flags?

I'm thinking it might be a bit confusing for users to see a `--release` flag for `forc doc` when it's normally used to specify a build profile for the code itself :thinking: Thoughts?

**Comment by eureka-cpu** [comment]
Yeah I agree the tag name there is confusing, maybe `--url` would be better. The way forc doc opens things in the browser is `file///home/user/path/index.html` and with the issue that would make the path render differently depending on the system type it would break.

**Comment by JoshuaBatty** [comment]
Closing for now. If we decide to support windows in the future then this would be relevant.
