### ISSUE TITLE
Formatter comments out next line after `// // Comment`

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#4373]
After a double commented out line, the formatter moves the comment to the next line.

![Mar-28-2023 21-49-09](https://user-images.githubusercontent.com/47993817/228430077-459348bc-53e9-4b84-8d17-3a1d750d4f30.gif)

**Comment by bingcicle** [comment]
Hmm for some reason I can't repro this on master or on 0.35.5 myself :thinking:

**Comment by sdankel** [comment]
I believe this was actually a problem with on_enter functionality in the LSP, which should now be fixed.
