### ISSUE TITLE
Bug: ArithmeticOverflow when multiplying two large U256 numbers

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/sway#4376]
I've run into an issue where multiplying two large U256 numbers results in an ArithmeticOverflow error, when the numbers should multiply correctly.

I've put together a simple repo to reproduce the problem:

https://github.com/dmihal/sway-bigint-issue

This repo contains:

* A Sway test that is currently failing
* A Rust test that implements the same operation, and passes successfully

**Comment by dmihal** [comment]
This appears to still be an issue with different inputs

I've created another reproduction on the [`second-issue` branch](https://github.com/dmihal/sway-bigint-issue/tree/second-issue) of my repo.

**Comment by rostyslavtyshko** [comment]
https://github.com/FuelLabs/sway/pull/4441
