### ISSUE TITLE
A contract should revert when no fn selector matches

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/sway#444]
ATM, when you specify an invalid function selector when calling a contract, the contract just ends up doing a `RET $r0`. A revert sounds better.

**Comment by sezna** [comment]
We seem to have a disagreement here with this comment:

https://github.com/FuelLabs/sway/issues/97#issuecomment-875871742

@adlerjohn -- what do you think? `RVRT` or `RET` with some error code that represents "no selectors matched"? If the latter, we should make an issue to standardize error codes.

**Comment by adlerjohn** [comment]
I personally prefer **returning** a `Result` or something. Then the caller can handle as it wants, instead of forcing the panic.

**Comment by sezna** [comment]
I agree that using `Result` directly would be leaky, but what Rust does is it has a trait which types can opt into for converting program error types into standard out return codes.  E.g., `Result<_, _>` will return a non-zero exit code if it is an `Err`. 

We could do something like that, but unless we have a separate opcode or domain separator metadata, it will be impossible for the caller to know if the contract wanted to return that integer value as a genuine result of computation or as an error code.

There's a lot of ambiguity here, I think the cleanest and safest option would be `RVRT`. Thoughts?

**Comment by adlerjohn** [comment]
Cleanest is definitely `RVRT` for now.
