### ISSUE TITLE
Compiler panics with compiler_constants::TWELVE_BITS

### ISSUE THREAD

**Issue by Lukasz2891** [FuelLabs/sway#4450]
The compiler v.0.37.0+ panics with the following error:

`thread 'main' panicked at 'assertion failed: var_stack_offs <= compiler_constants::TWELVE_BITS', sway-core/src/asm_generation/fuel/functions.rs:700:13
`

which means: 

```rust
            assert!(var_stack_offs <= compiler_constants::TWELVE_BITS);
```

So why is it for and why it can't be working as in 0.35.5?

**Comment by mohammadfawaz** [comment]
@Lukasz2891 do you mind providing a small reproducer?

**Comment by Lukasz2891** [comment]
I'd like to do it, but I don't know if I can for now (and also I will try to find a small reproducer, because my program is quite big with lot of operations).

**Comment by Lukasz2891** [comment]
For 0.36.0 I have now:
```json
[
  {
    "Panic": {
      "contract_id": null,
      "id": "0000000000000000000000000000000000000000000000000000000000000000",
      "is": 10344,
      "pc": 33860,
      "reason": {
        "instruction": 676668416,
        "reason": "MemoryOverflow"
      }
    }
  },
  {
    "ScriptResult": {
      "gas_used": 109969,
      "result": "Panic"
    }
  }
]
```

The 0.37.0 panics as above.

**Comment by mohammadfawaz** [comment]
@Lukasz2891 I think a large program is fine as well. Maybe link to a public repo that we can reproduce the problem on?

**Comment by Lukasz2891** [comment]
Yes, I'll ask my friends if I can publish it :)

**Comment by Lukasz2891** [comment]
At the beginning, I'd like to notice that the code below is a part of the bigger system and I cannot reproduce it having it only extracted without the whole program. So I suppose that's related to the global number of instruction. But...

```rust
impl b256 {
    fn try(b: Bytes) -> b256 {
        let mut val = 0x0000000000000000000000000000000000000000000000000000000000000000;

        // let ptr = __addr_of(val);
        // b.buf.ptr().copy_to::<b256>(ptr, 1);
        val
    }
}

pub fn recover_signer_address(signature_bytes: Bytes, signable_bytes: Bytes) -> EvmAddress {
    let r_bytes = Bytes::new();
    let r_number = b256::try(r_bytes);

    return EvmAddress {
        value: 0x0000000000000000000000000000000000000000000000000000000000000000,
    }
}
```

that one crashes (with the `'assertion failed: var_stack_offs <= compiler_constants::TWELVE_BITS'`) but the following one DOES NOT:

```rust
impl b256 {
    fn try(b: Bytes) -> b256 {
        let _[no mut here]_ val = 0x0000000000000000000000000000000000000000000000000000000000000000;

        // let ptr = __addr_of(val);
        // b.buf.ptr().copy_to::<b256>(ptr, 1);
        val
    }
}

pub fn recover_signer_address(signature_bytes: Bytes, signable_bytes: Bytes) -> EvmAddress {
    let r_bytes = Bytes::new();
    let r_number = b256::try(r_bytes);

    return EvmAddress {
        value: 0x0000000000000000000000000000000000000000000000000000000000000000,
    }
}
```

Maybe it will be easier for you to figure out where the issue starts in the bigger system. 
I'm still waiting to an answer about publishing the repo :)

The header of the minimized file is:

```rust
library;

use std::{b256::*, bytes::*, vm::evm::evm_address::EvmAddress};

```

**Comment by Lukasz2891** [comment]
That's a link for the `sway` part of the repo&branch:

https://github.com/redstone-finance/redstone-oracles-monorepo/tree/sway-0.36/packages/fuel-connector/sway

I was using `fuel`: `git+https://github.com/fuellabs/sway?tag=v0.37.1#83e5479462ed2883591669a42552606ac25f0a04`

you can invoke the issue by using:
`make test`
or 
`make contract`

**Comment by Lukasz2891** [comment]
Still exists in the code above (for `make test`, not compiling for `make contract` due to breaking changes in 0.38.0).

git+https://github.com/fuellabs/sway?tag=v0.38.0#2d16d70ab9d5ab0de0255941048f811b6d07c6b

**Comment by Lukasz2891** [comment]
I don't have permissions for reopening ;/

**Comment by vaivaswatha** [comment]
A smaller, independent repro:

```rust
script;

use std::u256::U256;

struct M1 {
  a: U256,
  b: U256,
  c: U256,
  d: U256,
}

struct M2 {
  a: M1,
  b: M1,
  c: M1,
  d: M1,
}

const m1: M1 = M1 { a: U256::new(), b: U256::new(), c: U256::new(), d: U256::new() };
const m2: M2 = M2 { a: m1, b: m1, c: m1, d: m1 };

const MARR : [M2; 6] =
    [
       m2, m2, m2, m2, m2, m2
    ];

fn bar() -> ([M2; 6], [M2; 6]) {
   let mut a = MARR;
   let mut b = MARR;
   (a, b)
}

fn main() -> [M2; 6] {
   let mut b = bar();
   b.0
}```

**Comment by vaivaswatha** [comment]
While the above PR fixes the crash, I also suggest that the authors not use `[U256; 50]` values directly (as they eat up stack space, eventually at some point going past limits) but instead use `Vec<U256>`.

**Comment by Lukasz2891** [comment]
Definitely I don't like `[U256; 50]` (especially that shouldn't be limited) but the `Vec<U256>` was not supported by typescript sdk.
