### ISSUE TITLE
Sway formatter removes a new line

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#4453]
In the sway application repository the escrow has a formatting bug [here](https://github.com/FuelLabs/sway-applications/blob/914e12fda34136fec1f7bf7e7481554de945bf30/escrow/project/contracts/escrow-contract/src/main.sw#L303-L304).

The functions do not have a new line between them. Running `forc fmt` with the toolchain file on version `0.37.0` does not add a new line and in fact once a blank line is added the formatter removes it.

**Comment by sdankel** [comment]
This doesn't appear to be happening anymore with the latest version of forc. It formats it properly with a single newline in between functions, regardless of how the spacing was before formatting.
