### ISSUE TITLE
Compiler panics with "can't do more than 6 args yet" 

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#4477]
Originally raised in https://forum.fuel.network/t/struct-initialization-errors-unexpectactly/2410

Reproducer:

```rust
contract;

abi MyContract {
    fn test_function() -> bool;
}

struct Foo {
    a: u64,
    b: u64,
    c: u64,
    d: u64,
    e: u64,
    f: u64,
}

impl Foo {
    fn new(
        a: u64,
        b: u64,
        c: u64,
        d: u64,
        e: u64,
        f: u64,
    ) -> Self {
        Self {
            a,
            b,
            c,
            d,
            e,
            f,
        }
    }
}

impl MyContract for Contract {
    fn test_function() -> bool {
        let bar1 = Foo::new(0,0,0,0,0,0);
        // let bar2 = Foo::new(0,0,0,0,0,0);
        true
    }
}
```

Methods with more than 6 args should technically be supported with a fallback mechanism.

**Comment by esdrubal** [comment]
This might be related to when a method is inlined or not. I disabled inlining optimization and the test below was falling with the same panic.
https://github.com/FuelLabs/sway/blob/e99b7880e920109a548c3f3edd35a215c2d05a7b/test/src/e2e_vm_tests/test_programs/should_pass/language/basic_func_decl/src/main.sw#L44-L46
