### ISSUE TITLE
Formatter fails when it sees `mod` opcode in assembly block.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#4490]
I get the following error when trying to format code which includes the `mod` opcade in an asm block:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFileError([Parse { error: ParseError { span: Span { src (ptr): 0x564bf31d8420, path: None, start: 145, end: 148, as_str(): "mod" }, kind: ReservedKeywordIdentifier } }])', swayfmt/src/comments.rs:155:10
```
I have a bunch of assembly code using the `mod` opcode (which conflicts with the `mod` keyword.
forc build still works with the following workaround; the `mod` opcode must be written as `r#mod`.
My guess is that forc-fmt doesn't recognize the `r#`.

Note: I believe @mohammadfawaz recently made a change so that `asm` blocks now have their own namespace.

**Comment by sdankel** [comment]
I tried this out on `test/src/e2e_vm_tests/test_programs/should_pass/language/asm_expr_basic/src/main.sw` which includes the `mod` opcode in an asm block. `forc fmt` runs without any errors and correctly formats the file. Feel free to reopen if this is still reproducible.
