### ISSUE TITLE
Parser crashes on empty file 

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#4505]
If there is an empty sway file, the parser will crash. This should instead present an error message. 

For example, we have the following directory structure:

```
my_project/
├── src/
|    └── main.sw
└── Forc.toml
```

And the `my_project/src/main.sw` is empty, we get the following error:

![parser_error](https://user-images.githubusercontent.com/54727135/234959760-f3dd1537-b4e1-4480-98bd-ae7b347b8952.png)

**Comment by IGI-111** [comment]
I can't seem to reproduce that exact error, instead I get 
```
thread 'main' panicked at 'attempt to subtract with overflow', sway-parse/src/parser.rs:45:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
@bitzoic which version of forc were you using there?
