### ISSUE TITLE
Signatures of structs and tuples

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/sway#454]
Previously, in both fuels-rs and -ts, we were encoding both tuples and structs as `(u64,u64,..)`. It seems like in Sway, these are `t(u64,u64,..)` and `s(u64,u64,..)`.

For this example:
```rust
struct StructA {
  a: bool,
  b: u64
}

struct StructB {
  a: bool,
  b: u64
}

abi TestContract {
  fn fn_a(arg1: u64, arg2: StructA) -> u64;
  fn fn_b(arg1: u64, arg2: StructB) -> u64;
}
```

We have three options:
- `fn_a(u64,(bool,u64))`, naked
- `fn_a(u64,s(bool,u64))`, with struct/tuple identifier
- `fn_a(u64,s StructA(bool,u64))`, also with name

We should discuss which one to pick.

**Comment by sezna** [comment]
@emilyaherbert what's the status of this issue? Doing some cleaning...

**Comment by mohammadfawaz** [comment]
The table in https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/abi.md#function-signature summarizes the current state of things and matches the current behavior of the compiler. I don't think there's much else to be done here.
