### ISSUE TITLE
Flaky std lib test: `can_get_input_message_predicate_length`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#4555]
As it can be seen from [this](https://github.com/FuelLabs/sway/actions/runs/4935896799/jobs/8822779155) run `can_get_input_message_predicate_length` test is failed, but after re-running the job ([here](https://github.com/FuelLabs/sway/actions/runs/4935896799/jobs/8824162190)), the test passed

**Comment by sdankel** [comment]
Assuming this hasn't happened recently, the last examples are so old the links expired. Closing since this is no longer actionable.
