### ISSUE TITLE
Duplicate function definitions do not throw errors with traits

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#4563]
When implementing a trait for a struct that has duplicate function definitions, no error is thrown. 

NOTE: Preventing this may conflict with multiple `From` trait implementations.

Minimal repro using two identical traits:

```rust
pub struct MyStruct {}

pub trait MyTrait {
    #[storage(read, write)]
    fn write(self, val: u64);
    #[storage(read, write)]
    fn read(self);
}

pub trait MyTrait2 {
    #[storage(read, write)]
    fn write(self, val: u64);
    #[storage(read, write)]
    fn read(self);
}

// No error
impl MyTrait for MyStruct {
    #[storage(read, write)]
    fn write(self, val: u64) {
        
    }

    #[storage(read, write)]
    fn read(self) {
        
    }
}

// No error but these function definitions have already been implemented
impl MyTrait2 for MyStruct {
    #[storage(read, write)]
    fn write(self, val: u64) {
        
    }

    #[storage(read, write)]
    fn read(self) {
        
    }
}
```

In the following example, we see this sort of implementation in the `StorageBytes` type in the standard library. We have two implementations of `MyStruct`. The first uses a trait and the second does not. When using the trait, no error is thrown. When implementing without a trait an error is thrown as expected.

A consequence of this is a user writing a special storage type, adding `read` and `write` functions, and not being informed that the implementations will be overwritten by the `StorageKey` type.

```rust 
use std::storage::storage_api::*;

pub struct MyStruct {}

pub trait MyTrait {
    #[storage(read, write)]
    fn write(self, val: u64);
    #[storage(read, write)]
    fn read(self);
}

// Does not throw a duplicate definition error
impl MyTrait for StorageKey<MyStruct> {
    #[storage(read, write)]
    fn write(self, val: u64) {
        write(self.slot, 0, val);
    }

    #[storage(read, write)]
    fn read(self) {
        let val = read::<u64>(self.slot, 0).unwrap_or(0);
    }
}

// Throws duplicate definition error as expected
impl StorageKey<MyStruct> {
    #[storage(read, write)]
    fn write(self, val: u64) {
        write(self.slot, 0, val);
    }

    #[storage(read, write)]
    fn read(self) {
        let val = read::<u64>(self.slot, 0).unwrap_or(0);
    }
}
```

Tested with forc v0.38.0

**Comment by anton-trunov** [comment]
> A consequence of this is a user writing a special storage type, adding read and write functions, and not being informed that the implementations will be overwritten by the StorageKey type.

There should be no implementation override in this case and Rust has the same semantics in this case.

Let's consider the `StorageKey` example from the original post. Then `s.read()` should resolve to the struct impl method call even in the presence of a trait with the same method and if the user wants to call the `read` method of the `MyTrait` trait then they would have to specify explicitly <StorageKey as MyTrait>::read(s):

```
    let s: StorageKey<MyStruct> = StorageKey {
             slot: 0x0000000000000000000000000000000000000000000000000000000000000000,
             offset: 0,
             field_id: 0x0000000000000000000000000000000000000000000000000000000000000000,
         };
    s.read();  // calls std::storage::storage_key::StorageKey::read
    <StorageKey as MyTrait>::read(s);
```

**Comment by anton-trunov** [comment]
Does everyone agree we should close this issue?

**Comment by anton-trunov** [comment]
Closing as this is expected behavior
