### ISSUE TITLE
Organize tests into subdirs based on what feature is being tested.

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#460]

**Comment by ControlCplusControlV** [comment]
Is there a reason this issue is still open? Tests currently seem to be organized into subdirs depending on the bug they are testing for

**Comment by otrho** [comment]
I think the original idea was to organise them a bit further.  E.g., tests which should succeed, tests which should fail, tests which require deployment could all be separated.  And then, maybe parser, core and backend tests could be organised even more.
