### ISSUE TITLE
Script transaction collision with forc-run

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#4602]
raised by @lostman over slack:

> I have a simple counter contract and a script to interact with it. When I run the same script twice, I get an error:
> ```
> 2023-05-30T11:33:47.528720Z ERROR new{name=}:initialize_loop{service="PoA"}: fuel_core_poa::service: 219: During block 
> production got invalid transaction Script(Script { gas_price: 0, gas_limit: 100000000, maturity: 0, script: 
> 90000004470000000000000000..., script_data: , inputs: [Contract { utxo_id: UtxoId { tx_id: 
> 0000000000000000000000000000000000000000000000000000000000000000, output_index: 0 }, balance_root: 
> 0000000000000000000000000000000000000000000000000000000000000000, state_root: 
> 0000000000000000000000000000000000000000000000000000000000000000, tx_pointer: TxPointer { block_height: 0, 
> tx_index: 0 }, contract_id: 4665c9137566b2d906573c4074965e1357c91999759af1def3f08eb7d9f5d7bc }], outputs: [Contract { 
> input_index: 0, balance_root: 0000000000000000000000000000000000000000000000000000000000000000, state_root: 
> 0000000000000000000000000000000000000000000000000000000000000000 }], witnesses: [], receipts_root: 
> 0000000000000000000000000000000000000000000000000000000000000000, metadata: Some(ScriptMetadata { 
> common: CommonMetadata { id: 01806011f13022a3d0eeadbc2ee9d0e36bdd1b1368b021fde08d2eef1a16184c, inputs_offset: 
> 296, inputs_offset_at: [296], inputs_predicate_offset_at: [None], outputs_offset: 456, outputs_offset_at: [456], witnesses_offset: 
> 536, witnesses_offset_at: [] }, script_data_offset: 296 }) }) with error 
> TransactionIdCollision(01806011f13022a3d0eeadbc2ee9d0e36bdd1b1368b021fde08d2eef1a16184c)
> ```
> The script is:
> ```sway
> fn main() {
>     let counter = abi(Counter, CONTRACT_ID);
>     counter.incr(124);
> }
> ```
> If I run the script twice but change counter.incr(X) to a different X each time, it succeeds.
> Is this the expected behavior?

**Comment by kayagokalp** [comment]
I haven't had the chance to look this in detail so not sure if this is something expected and missing a nice error message or a bug, will try to come-back to this issue.

**Comment by sdankel** [comment]
This is expected behavior; running the same script twice creates the same transaction ID.

If you are testing with a local fuel-core you can work around this issue by starting it with `fuel-core run --db-type in-memory`

**Comment by sdankel** [comment]
For more context, forc run doesn't create unique inputs for each transaction. If the whole transaction is identical, fuel-core rejects the duplicate transaction.
