### ISSUE TITLE
Use "RFC 2528: type-changing struct update syntax" when it is stabilized 

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#463]
I recently refactored a lot of `semantic_analysis` to use a struct called `TypeCheckArguments`. This provides a consistent interface across our many type checking functions.

I wanted to be able to do something like this:

```rust
  TypedExpression::type_check(TypeCheckArguments {
      checkee: lhs.clone(),
      help_text: Default::default(),
      mode: Mode::NonAbi, opts,
      ..arguments
  }),
```

However, this implicit cast of `arguments` from `TypeCheckArguments<T>` to `TypeCheckArguments<R>` is experimental, and nightly only: https://github.com/rust-lang/rust/issues/86555

Without that cast, we have to write this:
```rust
    TypedExpression::type_check(TypeCheckArguments {
        checkee: lhs.clone(),
        help_text: Default::default(),
        mode: Mode::NonAbi, opts,
        self_type,
        namespace,
        crate_namespace,
        return_type_annotation,
        build_config,
        dead_code_graph,
        dependency_graph,
    })
```

This could save us a ton of LOC -- we are currently manually plumbing parameters in lots of places. Once the above issue gets to rust stable, we should refactor these calls to use this syntax.

**Comment by mohammadfawaz** [comment]
https://github.com/FuelLabs/sway/pull/2004 switched all instances of `TypeCheckArguments` to use a context instead. I believe this can be closed now.
