### ISSUE TITLE
Compiler using invalid memory ranges for the heap

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/sway#4632]
This issue appears to be related to some missing changes related to https://github.com/FuelLabs/fuel-vm/pull/377.

Specifically, while attempting to upgrade the ts-sdk to fuel-core 0.18 and sway 0.40.1 some memcpy opcodes were generated by the compiler that tried to access `[HP+1 .. VM_MAX_RAM + 1]` instead of `[HP .. VM_MAX_RAM]`, causing a panic due to memory bounds checks.

A test that repros this issue here: https://github.com/FuelLabs/fuels-ts/blob/dp/fuel-core-0.18.1/packages/fuel-gauge/src/contract.test.ts#L132

This is an urgent issue as it is blocking the ability to upgrade the bridge for audit.

**Comment by vaivaswatha** [comment]
@Voxelot How can I get a standalone contract / script from the test above, so that I can compile it and see the assembly.

**Comment by vaivaswatha** [comment]
This is a TS SDK bug and is being fixed by https://github.com/FuelLabs/fuels-ts/pull/1057/files#diff-f0c3c3b228615cba8f0dd7e366b4da1ac24aeb5695c676ee4ca105cae9ffb620L17. Closing.
