### ISSUE TITLE
ABI function should accept a ContractId type

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#465]
The following fails to compile because `abi(...)` expects a `b256` as the second param, but we now have a new `ContractId` type.
```
// the deployed fuel_coin contract
let fuelcoin_id = ~ContractId::from(0xad6aaaa1d6fd78f91693ee2cc124fd43d25bd1c015b88b675ee43d6b5e140586);
let fuel_coin = abi(TestFuelCoin, fuelcoin_id);
```
Here is the error:
```
let fuel_coin = abi(TestFuelCoin, fuelcoin_id);
   |                                       ^^^^^^^^^^^ Mismatched types.
```
cc @emilyaherbert 

Note: the same issue applies to contract calls, which have  `gas`, `coins` and `color` params. The color is currently a b256, but we should probably be using the `ContractId` type here as well.

In gereral, what's the best way forward here? 
We can access the inner value of a ContractId type and just pass it to abi(... but then we lose the type-safety.

**Comment by adlerjohn** [comment]
Since this issue is superseded by actually removing the fixed parameters, and can be worked around pretty simply with `.into()`, I'm closing.
