### ISSUE TITLE
Deploy an IPFS node operated by Fuel

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#4659]
This is a critical part of our registry design. For performance reasons a fuel operated node will be a great option to use instead of the public gateway. Public gateway (ipfs.io) would still be an option but we can channel people to use fuel operated node for better fetch times. 

Other than making it faster, ipfs node is also needed for our package registry stuff to work. Because there is no way of ensuring package publishers pins their packages.

**Comment by sdankel** [comment]
We don't need to host it ourselves, we can use a hosted IPFS service like Pinata.
