### ISSUE TITLE
Get `forc-util` to not use `fuel-tx` with default features 

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/sway#4667]
- I have opened up a similar issue on the SDK - feel free to read it over
  - https://github.com/FuelLabs/fuels-rs/issues/1005
- I'm opening up an issue in forc because [`fore-util` is doing something similar](https://github.com/FuelLabs/sway/blob/master/forc-util/Cargo.toml#L18)
  - It is including default features from `fuel-tx`
- Is it possible to use `forc-util` in a more WASM friendly way? 
- I need to use `forc-util` util but I need `forc-util` to not include `fuel-tx` default features if at all possible
- As a workaround, we're just copying the files we need from `forc-util` 🥲 

CC @kayagokalp

**Comment by kayagokalp** [comment]
Hey @ra0x3 thanks for the issue will see what we can do about it!
