### ISSUE TITLE
Comment continuation isn't working anymore?

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#4728]
I'm just getting everything set up on my new machine and noticed that `on_enter` isn't adding `//` or `///` in the editor even though I have both settings set to on. 

![Screenshot 2023-07-03 at 12 34 00 pm](https://github.com/FuelLabs/sway/assets/1289413/7dad7699-5983-4d52-a150-30c1f33dccab)

![Screen Recording 2023-07-03 at 12 41 57 pm](https://github.com/FuelLabs/sway/assets/1289413/f478dce4-ccf1-4809-a260-301a5939ab9d)

@sdankel not sure if this is happening for you also?

**Comment by sdankel** [comment]
This is happening for me too! Doc comment continuation is still working, but not comment continuation. Looking into it.
