### ISSUE TITLE
Add bash completions for forc

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#482]
- [x] #702
- [ ] Add `forc locate-project` that prints out manifest file location, similar to `cargo locate-project`
- [x] Port https://github.com/rust-lang/cargo/blob/47b869c107fbe0aa42444f46d59f4ba03ffa15fe/src/etc/cargo.bashcomp.sh over

**Comment by sezna** [comment]
With regards to `--list` -- we have `forc --help`. However, `cargo --list` lists plugins and extensible commands that have been installed. We don't really have that functionality in `forc`. Do we want that?

**Comment by adlerjohn** [comment]
Eventually we probably want plugins, but for now simply listing commands just like `cargo --list` is probably good enough IMO.

**Comment by Voxelot** [comment]
Since the default shell for MacOS is `zsh`, we should also consider a `zsh` plugin similar to the rust completion one: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/rust

**Comment by ControlCplusControlV** [comment]
Going to start working on implementing a `forc -list`

**Comment by JoshuaBatty** [comment]
Hey @ControlCplusControlV , i'm working on the shell autocompletions FYI. But perhaps you could have a go at `forc locate-project` along with `forc --list`

**Comment by mitchmindtree** [comment]
Closed by #864

**Comment by paulrberg** [comment]
> Since the default shell for MacOS is `zsh`, we should also consider a `zsh` plugin similar to the rust completion one

Yes, please! An Oh My Zsh plugin for Forc would be great.
