### ISSUE TITLE
Closing brace for a method with a comment as its body gets incorrect indentation

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#4824]
The following snippet
```sway
contract;

abi MyAbi {
    fn foo();
}

impl MyAbi for Contract {
    fn foo() {
        // ... logic ...
    }
}
```

gets formatted as follows

```sway
contract;

abi MyAbi {
    fn foo();
}

impl MyAbi for Contract {
    fn foo() {
        // ... logic ...
} // <---- wrong indentation here
}
```

**Comment by sdankel** [comment]
I can't reproduce this. What version of forc are you using? Is there a specific repo where this is happening?

**Comment by sdankel** [comment]
This seems to be one of a class of many bugs - almost any kind of nested code block that only a comment will either mess up the indentation or remove the comment entirely.
