### ISSUE TITLE
Sway Book: 404 links for library implementations

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#4921]
https://fuellabs.github.io/sway/v0.43.2/book/sway-program-types/libraries.html?highlight=string#reference-sway-libraries

`String` has been moved into the `std` so it's no longer in the libs repo.
`StorageMapVec` has been removed so it shouldn't be mentioned at all.

**Comment by AnmolSirola** [comment]
@Braqzen Can I work on this issue.

**Comment by Braqzen** [comment]
@AnmolSirola it looks like this has been fixed a long time ago and this issue has not been closed so there is no work to be done.

Closing the issue
