### ISSUE TITLE
Add helpful error message when detecting Rust style enums

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#4942]
Users moving from Rust might be tempted to use the Rust enum syntax:

```rust
enum A {
    Foo,
    Bar(u32),
}
```

When the correct Sway syntax is: 

```sway
enum A {
    Foo: (),
    Bar: u32,
}
```

This is surprising, so we should have an error message that detects this pattern and asks the developer if they meant the latter.

**Comment by jjcnn** [comment]
> Plus the additional Sway specific in-source help message saying, e.g. "Did you mean `Foo: ()`?" or "Did you mean `Bar: u32`?"

This help message requires a way for `ParseErrorKind` to format a `sway_ast::ty::Ty`, and I can't to find a formatter for that type. 

Is it worth the trouble to implement one, or should we instead go with something like "Enum kinds have the form 'Foo : ()' or 'Bar : u32'"?

**Comment by ironcev** [comment]
Indeed you are right, the type formatter is available further down in the type checking phase. I don't think that it's worth the trouble. Let's skip the specific in-source help and display just the general hint how enum variants can look like.
