### ISSUE TITLE
Implement new allocator and support garbage collection

### ISSUE THREAD

**Issue by tritao** [FuelLabs/sway#4994]
For supporting long-term compilation sessions (for LSP use) we want to support garbage collecting the engines.

Right now this is not possible due to our current slab allocator not supporting removing previously allocated ids.

We should re-implement the slab allocator using either an optimized slot map, or the buddy allocator algorithm.

(Tests using a slotmap crate based implementation proved to be 15-20% slower than the current allocator.)

Additionally we can move to a multiple allocator model, where we setup a slab per module, and allow cross-linking of type/decl ids.

This will also allow for easier incremental compilation as well as less transient caching due to a more straight forward cache serialization.

**Comment by JoshuaBatty** [comment]
Hey @tritao just wondering which slot map crate you tried already that gave you those results?
