### ISSUE TITLE
`ecr1` signature recovery in `std`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5034]
When the compiler supports the opcode we ought to add `std` support for `ecr1` according to the [specs](https://specs.fuel.network/master/fuel-vm/instruction-set.html#cryptographic-instructions)

**Comment by bitzoic** [comment]
Dependent on https://github.com/FuelLabs/sway/issues/5125

**Comment by bitzoic** [comment]
Closed by https://github.com/FuelLabs/sway/pull/5133
