### ISSUE TITLE
`ed19` signature verification

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5035]
When the compiler supports the opcode we ought to add `std` support for `ed19` according to the [specs](https://specs.fuel.network/master/fuel-vm/instruction-set.html#cryptographic-instructions)

**Comment by bitzoic** [comment]
Dependent on https://github.com/FuelLabs/sway/issues/5125

**Comment by bitzoic** [comment]
Closed by https://github.com/FuelLabs/sway/pull/5133
