### ISSUE TITLE
Emit compile error if the same match arm variables in alternatives are not of the same type

### ISSUE THREAD

**Issue by ironcev** [FuelLabs/sway#5081]
At the moment there is no error if match arm variables with the same name in match arm alternatives are not of the same type. The type of the variable in the last alternative will win.

```Rust
struct S {
    x: bool,
    y: u64
}

...
let _x = match s {
    S { x: y, y: x, .. } | S { x, y, .. } => x, // No type mismatch error but it should be.
           ^                      ^ y is u64 here
           |
           y is bool here 
    ...
}
```

**Comment by anton-trunov** [comment]
This example is not allowed anymore after the recent PR, or did I misunderstand this?

**Comment by ironcev** [comment]
The PR (#5085) was about duplicates. In this issue in general we do not need to have duplicates. All alternatives must have the same variables and _a single variable must be of the same type in all of the alternatives_. In the above example, there are no duplicates, just two variables `x` and `y` in both alternatives, which is fine. But their types are not the same and that's the issue.

I see now that I could have gone for a more understandable example, naming the variables `a` and `b` or similar. This was one of the crazy constellations I used in brainstorming and tests. Definitely not the best one for describing the issue :-)

So, this example was never supposed to be allowed, regardless of the duplicates, but the consistency of types was never checked.

**Comment by ironcev** [comment]
For the record, here is the Rust error on the same issue:

```Rust
error[E0308]: mismatched types
  --> src/main.rs:10:39
   |
9  |     let _x = match s {
   |                    - this expression has type `S`
10 |         S { x: y, y: x, .. } | S { x, y, .. } => x,
   |                -                      ^ expected `bool`, found `u64`
   |                |
   |                first introduced with type `bool` here
   |
   = note: in the same arm, a binding must have the same type in all alternatives
```

**Comment by anton-trunov** [comment]
Got it, thanks @ironcev :)
