### ISSUE TITLE
Process Management -- No way to list or stop running `fuel-core` nodes from Forc

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway#515]
There is no nice way to list, stop or start running fuel-core nodes nicely started by `Forc`.

As proposed earlier in my target, this can get quite annoying when you're doing a lot of stop/start like testing and doing basic node management.

I propose this be implemented sooner rather than later to manage this:
https://github.com/FuelLabs/sway/issues/423#issuecomment-979185301

**Comment by adlerjohn** [comment]
Closing this for multiple reasons.

1. The proposed solution of using PID files is Linux-specific. Building out a generic solution that works across platforms is non-trivial.
2. Nodes don't need to be started and stopped by users for testing, ever. The SDK will handle launching and shutting down a node as needed.
3. The only time nodes need to be started and stopped during testing is by the protocol developers. Forc is meant for end-users, and should not have features that are only relevant to the protocol developers and not users.
4. Node management is infrastructure-related, and is not relevant to Sway and dapp development. A separate binary should be development if there is a concrete and actionable need to manage infrastructure.
