### ISSUE TITLE
How do we return a StorageVector in function? 

### ISSUE THREAD

**Issue by BladeRunner713** [FuelLabs/sway#5171]
Basically I want to get the storagevector in frontend using ts-sdk

Looks like the signature needs to be StorageKey<StorageVec<V>> 

```
storage {
    some_storage_vec: StorageVec<AssetId> = StorageVec {},
}

fn get_vec() -> StorageKey<StorageVec<AssetId>> {
        return storage.some_storage_vec;
    }
```

When I try to call the function in front-end, I got StorageKey. Not sure is there a way to get the StorageVec or convert to it.

**Comment by bitzoic** [comment]
Please be sure to use the [Fuel Forum](https://forum.fuel.network/) for any questions going forward such that they have better visibility and can get a faster response. 

In terms of your question here, `Vec` is a heap type while `StorageVec` is a storage type. While you can retrieve a `StorageKey`, it does not provide you with much value besides the hashes.

You can use the newly introduced `load_vec()` function to load a `StorageVec` into the heap and then return it as a `Vec`.

```sway
storage {
    some_storage_vec: StorageVec<AssetId> = StorageVec {},
}

fn get_vec() -> Vec<AssetId> {
        return storage.some_storage_vec.load_vec();
}
```
