### ISSUE TITLE
Forc's git dependency handling should be able to handle git revs and tags

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#523]

**Comment by sezna** [comment]
Do we already handle this actually? https://github.com/FuelLabs/sway/blob/master/forc/src/utils/dependency.rs#L90

cc @digorithm because you're on the blame

**Comment by adlerjohn** [comment]
If yes, then it needs to be documented!

**Comment by digorithm** [comment]
> Do we already handle this actually? https://github.com/FuelLabs/sway/blob/master/forc/src/utils/dependency.rs#L90
> 
> cc @digorithm because you're on the blame

Yeah, IIRC it works just fine with revs/tags. 

Just tested it locally to confirm:

```
std = { git = "http://github.com/FuelLabs/sway-lib-std", version = "3c9b9c53fa95fe586d2e1bdabfaccbd01526dae9" }
```

```
test-remote-deps forc build
  Compiled library "core".
  Downloading "std" ("/Users/rodrigoaraujo/.forc/std/3c9b9c53fa95fe586d2e1bdabfaccbd01526dae9")
  Compiled library "core".
  Compiled library "lib-std".
  Compiled script "test-remote-deps".
  Bytecode size is 3220 bytes.
  ```

**Comment by nfurfaro** [comment]
It seems that While this works locally:
`"core" = { git = "http://github.com/FuelLabs/sway-lib-core", version = "v0.1.0" }`
if I want to use the latest code and not a published version, this does **Not** work locally:
`"core" = { git = "http://github.com/FuelLabs/sway-lib-core" }`

The workaround I use is:
`"core" = { path = "../sway-lib-core" }`
but I have to remember to change it back to using the git import before I push.

**Comment by adlerjohn** [comment]
> this does Not work locally

Is that only because you already have that dependency download in `~/.forc`?

**Comment by nfurfaro** [comment]
I'm not sure what's going on here yet.

**Comment by sezna** [comment]
try nuking the entire `~/.forc` directory?

**Comment by nfurfaro** [comment]
>try nuking the entire ~/.forc directory?

testing now...

**Comment by nfurfaro** [comment]
`rm -r ~/.forc` resolves the issue.

**Comment by sezna** [comment]
It forces a fresh download. I believe `"core" = { git = "http://github.com/FuelLabs/sway-lib-core" }` will just accept whatever the last version you pulled was.
