### ISSUE TITLE
Discussion: Creating a local client/relayer 

### ISSUE THREAD

**Issue by cr-fuel** [FuelLabs/sway#5252]
## Goal

The main goal of having an external process is to centralize the key-management, outside of a browser, and potentially start throw-away local networks eventually. Having the keys living outside of the browser, inside a `forc` plugin or Visual Studio allows interaction from many tools, including web wallets and browser extensions, through the same funnel and exporting the management of keys to this foreign process.

This external process should be capable of creating a local network with sane defaults, or broadcast transactions to the testnet. It should be easily configurable.

## Context

The easiest way to interact with an external process from the browser (either as a website or extension) is creating a webserver on the host machine (either in Visual Studio or in Rust). 

Here is what the happy path would look like:

```mermaid
sequenceDiagram
    Browser ->>+ HTTP/1.1: Are you a fuel wallet server?
    HTTP/1.1->>+Browser: Yes, here is the proof
    Browser ->>+ HTTP/1.1: API Call
    HTTP/1.1 ->>+ Browser: Response
```

The unhappy path would be like this, and in that case, the browser should use its own client and should manage its own keys.

```mermaid
sequenceDiagram
    Browser ->>+ HTTP/1.1: Are you a fuel wallet server?
    HTTP/1.1-->>+Browser:  Error or timeout
```

The main goal is to offer the same APIs as available from the typescript SDK through a restful API, and expect the external webserver to reply. The main goals for the webserver are two:

1. Manage all the keys, adding some security and ease of use, having all the keys in a single place
2. Abstract interacting with the network (either testnet, prod or localhost). It's up to the web server, the client in the browser will rely on them.

## Prior art

I was part of a project in a fairly popular alternative to Dropbox. The user may have installed a local binary that will create a webserver making every interaction the user may have from the browser faster and more reliable.

The user may have this binary installed for another reason (to sync their files with the cloud) but in having so, the browser clients may also benefit from interacting with a native SDK instead of a javascript one.

The webserver would work as follows:

1. The binary the user installs would create an HTTP web server on a pre-established non-standard port, but it binds to `127.0.0.1`
2. Assuming the project was `foo.com`, a sub-domain `local-server.toolbar.foo.com` was created. This subdomain would have an A record that will resolve to `127.0.0.1`. A valid SSL cert would be embedded into each binary.
3. The web server will have the CORS setup to receive calls from `*.foo.com`

The usage was straightforward:

1. The browser client would do a `ping` request to `local-server.toolbar.foo.com`. If the user did not have the binary running that request would eventually fail, and the browser client can fallback to interacting with the cloud through their normal javascript SDK
2. If that request comes successfully, the browser client would use that local webserver as their API server for all communication forward. It will also perform other operations, such as I/O to write files way more efficiently.

## Technical details

The local webserver can be created from rust (through any forc binary) or in nodejs and it can be embedded from Visual Studio. The idea is to provide a better a better usage experience.

1. The webserver should create a HTTPs server. Communicating to an http server from a https page is not possible and it will make the page fail.
2. The web wallet and web-extensions fire off a `ping` API call to `https://forc.localsevrer.fuel.network:49201` (which resolves to `127.0.0.1`). If there is a successful reply that API endpoint can be used to communicate. Perhaps it should be wise to authorize new connections

### Authorization 

Upon a new connection, the webserver should warn the user about this new connection and should request their permission. This manual step should happen once, and it is how is webserver protects itself from any unrecognized request. Upon approval, the webserver should return a https-only cookie that shouldn't expire. As long as the cookie is included and it is valid (i.e. the user hasn't revoked the permission) that request is trusted and the webserver should trust any incoming API from that cookie. 

The user may remove any session from their cli or Visual Studio interface.

### Network

The external service should be able to start one or many local networks or proxy towards production or a testnet. The API usage should be made aware of all available networks and should choose to which network they'd like to interact.

The clients (web site or browser extension) has no access to the private keys, instead they have an API where they send an unsigned transaction and, if they are authorized, the signed version will be broadcasted to the chosen network.

**Comment by JoshuaBatty** [comment]
We don't have any plans to implement this sort of feature. We can re-open if that changes.
