### ISSUE TITLE
Forc ABI generation doesn't fail for scripts

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#526]
Forc version: v0.1.6

Running `forc json-abi` for a `script` project gives the following output instead of an error:

```console
$ forc json-abi
  Compiled library "core".
  Compiled library "core".
  Compiled library "lib-std".
  Compiled script "foo".
[]
```

Only contracts have an ABI, so `forc json-abi` should fail with an explanative error otherwise.

**Comment by eureka-cpu** [comment]
@adlerjohn can you think of any other instance where the `json-abi` output would be empty?

**Comment by adlerjohn** [comment]
Empty, or error?

**Comment by eureka-cpu** [comment]
> Empty, or error?

Maybe I'm misinterpreting, it is giving an empty `json abi` output, right? This is should give an error message: `Cannot generate JSON ABI for non-contracts`. But if there are any other reasons the command would produce an empty output, would we want it to catch that as an `error` too, or just leave as is?

**Comment by eureka-cpu** [comment]
Essentially, I'm asking if we actually need to check if it's a script, or if we can assume based on the empty output that it's a `non-contract`?

**Comment by adlerjohn** [comment]
You have to check that it's a script or a predicate. It may be the case that a contract with no ABI produces an empty ABI file. That could happen if the contract is meant to be an upgradable implementation for example.
