### ISSUE TITLE
Clarify usage of configurables in const declarations

### ISSUE THREAD

**Issue by ironcev** [FuelLabs/sway#5272]
Consts are compile-time constants. Configurables are deploy-time constants. Allowing configurables to be used in declaring consts leads to the paradox demonstrated below.

This behavior can lead to unexpected and difficult to spot errors, because "what you see" (two same values) is not "what you got" (potentially same, but who knows).

```
configurable {
    CONFIG_X: u64 = 42,
}

...

impl Test for Contract {
    fn test() {
        const X = CONFIG_X; // 42.
        let   x = CONFIG_X; // ?? (Whatever gets configured.)

        assert(X != x);     // !!!!!!!! This assert passes :-o
    }
}
```

We need to clarify what to do in this case:
1. Emit an error: Configurables are deploy-time constants and cannot be used to initialize compile time constants.
2. Emit a warning: The value of the constant "X" might be different then the value of the configurable because...

**Comment by ironcev** [comment]
Related to #5261.

**Comment by ironcev** [comment]
> Your option 1. sounds OK to me, makes sense to disallow configurables in compile time constants since they are not really constants at compile time.

I am also in favor of that option.

**Comment by SwayStar123** [comment]
Option one seems fine, considering people can do something like

```
const X: u64 = 42;

configurable {
    CONFIG_X: u64 = X,
}

```

and then just use X wherever they would have wanted to use CONFIG_X's default value
