### ISSUE TITLE
`assembly.sw` module

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5319]
Despite having the preference of abstracting the users away from direct usage of `asm` and opcodes some users may desire to do so which means they must read the spec and experiment.

It would be useful to have a module which consists of wrappers for all opcodes.
Each wrapper would document the utility of the opcode and its usage with appropriate documentation standards making it easier to start using the opcodes.

This may require compiler work because having stand alone opcodes (outside of `asm` blocks) or calling functions inside of `asm` blocks likely is unsupported at this time.

**Comment by IGI-111** [comment]
I don't think this is a good idea for multiple reasons:
* having multiple equivalent means of doing the same thing is bad design
* wrapping assembly does not remove any of the complexity of having to deal translating values to registers
* the standard library should not be this strongly tied in design to a particular virtual machine, implementation and support do require some coupling, but we should avoid it as much as possible so as to retain the ability to support other backends.

A library like that may be a good learning aide but it does not belong in the standard library.
