### ISSUE TITLE
Remove duplicated functionality from `Identity`, `Address` and `ContractId`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5336]
We have stand alone functions for minting and transferring but we have implemented them on the types for UX.

It's code bloat and doesn't add much overhead to having to add 1 import to regain the same functionality.

**Comment by Braqzen** [comment]
Bikeshedding only because I know there's pushback against this.

**Comment by bitzoic** [comment]
Resolved by: https://github.com/FuelLabs/sway/pull/5439
