### ISSUE TITLE
Make debug BuildProfile actually skip compiler optimizations

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#5339]
Currently the debug BuildProfile is identical to the release one. 

There should be an option in the BuildProfile to skip these that the default profile can use. In `sway-core/src/lib.rs`, when this option is true, we should skip running the `pass_mgr`.

**Comment by Voxelot** [comment]
In rust the default opt-level is 0, and is only turned up during release builds.

**Comment by sdankel** [comment]
We may also want to support compiler flags for each pass, so we could support debugging tools like diffs between passes similar to [vscode LLVM](https://github.com/sunxfancy/vscode-llvm)

**Comment by kayagokalp** [comment]
I will take care of it quickly as we already have the context required to implement this.

**Comment by vaivaswatha** [comment]
Closed by #5385
