### ISSUE TITLE
#[public] annotation

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5350]
The annotation would be placed above a field in a struct, enum variant, storage field and perhaps elsewhere.

The annotation would automatically create a getter function to expose the field.

Also, the name may be confusing if you're coming from solidity so we may need a different name.

**Comment by Braqzen** [comment]
Acknowledging that it may be more suitable to have this as functionality within the LSP.

**Comment by IGI-111** [comment]
I think this should either be a macro (once we have metaprogramming) or an LSP convenience to generate getters.

Getters have a cost and need to be part of the interface of their type. I don't like hiding them behind magic syntax. Especially in our usage context.

**Comment by Braqzen** [comment]
Closing in favour of #5387
