### ISSUE TITLE
#[unused] annotation

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5352]
I believe we have a `dead_code` annotation or something like that so this annotation may be useless.

Nevertheless, the functionality would allow us to remove warnings from unused code, such as in libraries that others are meant to import and use but the library itself does not use.

**Comment by ironcev** [comment]
Yes we have the `#[allow(dead_code)]` already. That's why I would close this issue.

Also, if a symbol is public in a library and exported it should never be marked as unused. This would be a bug. We should not need the annotation in that case.
