### ISSUE TITLE
Solidity error syntax

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5357]
Currently we create a struct or enum to represent an error, other types are also possible to be logged.

It would be better to have a specific syntax for errors similar to solidity.

```solidity
// declare
error MyError( .. );

// use
emit MyError( .. );
```

We may alter the syntax from the above.

**Comment by IGI-111** [comment]
I'm strongly against this. Errors should not be special types or have special syntax beyond things like a `?` operator.

Arbitrary types should be usable as runtime errors and `std` should standardize error functionality with an `Error` trait.
