### ISSUE TITLE
`mut` parameters

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5361]
I believe only `self` can be mutable in the parameters.

We should support all params to be mutable.

**Comment by ironcev** [comment]
Exactly. This is planned as a part of implementing the new concept for references. The details are listed in this PR: https://github.com/FuelLabs/sway-rfcs/pull/33

**Comment by IGI-111** [comment]
Closed as duplicate of https://github.com/FuelLabs/sway/issues/5063
