### ISSUE TITLE
`memcpyopt` is removing store and not updating subsequent opcodes

### ISSUE THREAD

**Issue by xunilrj** [FuelLabs/sway#5386]
We found a case where `memcpyopt` removes a `store` but it does not updates subsequent instructions, for example, using the `ir_generation` tests:

```sway
script; 

pub trait Power {
    fn pow(self, exponent: u32) -> Self;
}

impl Power for u256 {
    fn pow(self, exponent: u32) -> Self {
        let one = 0x0000000000000000000000000000000000000000000000000000000000000001u256;

        if exponent == 0 {
            return one;
        }

        let mut exp = exponent;
        let mut base = self;
        let mut acc = one;

        while exp > 1 {
            if (exp & 1) == 1 {
                acc = acc * base;
            }
            exp = exp >> 1;
            base = base * base;
        }

        acc * base
    }
}

fn main(a: u256) -> u256 {
    0x00000000000000000000000000000000000000000000000000000000u256.pow(10);
    a % 0x00000000000000000000000000000000000000000000000000000001u256  
}

// ::check-ir::
// check: main

// ::check-ir-optimized::
// pass: o1
// pass: fuel
// check: main
```

This will enable all "o1" and "fuel" optimization passes.

Just before `memcpyopt` we have the below IR which is running the "wide mod" instruction on `u256`s and returning its result.

```
>         wide mod v44, v45, v46 to v47, !49
>         v48 = load v47, !49
>         store v48 to v0
>         ret ptr u256 v0
```

after `memcpyopt` we have 

```
>         wide mod a, v45, v46 to v47, !44
>         v48 = load v47, !44
>         ret ptr u256 v0
```

The store is gone, but we are still returning `v0` and not `v48`.

see https://github.com/FuelLabs/sway/tree/xunilrj/memcpyopt-bug for the reproducing code.

**Comment by vaivaswatha** [comment]
>The store is gone, but we are still returning v0 and not v48.

This is because `v0` has now been changed to `v0 = get_local ptr u256, __wide_result1` and `v47` also is `v47 = get_local ptr u256, __wide_result1, !45`, i.e., the same variable.

So we're returning a pointer to the source of what was load+store., thus eliminating the copy.

Are you seeing an actual issue with the result value?

**Comment by vaivaswatha** [comment]
The fact that we're returning a pointer to a local stack variable seems odd to me. Let me dig in.

**Comment by vaivaswatha** [comment]
> The fact that we're returning a pointer to a local stack variable seems odd to me. Let me dig in.

And this seems to be explained by this:
https://github.com/FuelLabs/sway/blob/910e33bd015e2ea4571e042a856a0cd5c910b93a/sway-ir/src/optimize/ret_demotion.rs#L40

so overall seems like "not a bug" to me.

**Comment by xunilrj** [comment]
I will take a look at this again, because we have a very strange behavior happening in one version, but not on another.

**Comment by vaivaswatha** [comment]
> I will take a look at this again, because we have a very strange behavior happening in one version, but not on another.

@xunilrj any update on this?

**Comment by xunilrj** [comment]
None. I will ask who reported the bug to try again. In the meantime let us close this.
