### ISSUE TITLE
Use`filter_map()` instead of `filter` and then a`map`

### ISSUE THREAD

**Issue by crodas** [FuelLabs/sway#5436]
I think it may be more efficient to use a `filter_map()` here, no?

_Originally posted by @Braqzen in https://github.com/FuelLabs/sway/pull/5435#discussion_r1442317525_

**Comment by Braqzen** [comment]
Just noticed a race-condition so I'll leave to you to decide which issue should be closed. Ref https://github.com/FuelLabs/sway/issues/5437
