### ISSUE TITLE
Replace `filter().map()` with `filter_map()` in `sway-core`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5437]
In the following [file](https://github.com/FuelLabs/sway/blob/master/sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs) there is usage of a `filter` followed by `map`. It may be more efficient to use a `filter_map` instead.

If that is correct then we may want to expand this to other parts of the codebase that hold higher priority for some optimizations.

**Comment by xunilrj** [comment]
This can be closed, right? @JoshuaBatty
