### ISSUE TITLE
Fix `TyExpression::deterministically_aborts()`, and eliminate its use during IR generation

### ISSUE THREAD

**Issue by jjcnn** [FuelLabs/sway#5438]
The function `TyExpression::deterministically_aborts()` almost certainly computes the wrong result in some cases. The most obvious example is `return break`, which does not abort, but for which `deterministically_aborts()` returns `true`.

Additionally, `deterministically_aborts()` is only supposed to be used during typechecking, but it is currently being used when generating IR for variable declarations as well. During IR generation it should be sufficient to use `Value::is_diverging()`, but removing the single use causes an internal compiler error.

Edit: #5496 has removed the call to `deterministically_aborts()` from IR generation, so that part has been fixed.

**Comment by jjcnn** [comment]
The function `diverge_with_if_else` in the test case `e2e_vm_tests/test_programs/should_pass/language/diverging_exprs/` shows why the call exists in the IR generation.

**Comment by ironcev** [comment]
As explained in #5562 `deterministically_aborts` tried to compensate for the missing bottom type in the type system. Since we want to introduce it, there will be no need for fixing `deterministically_aborts`, we will rather remove it completely.

Closing in favor of #5562.
