### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ebiram63** [FuelLabs/sway#5467]
Hi there when I wanted to test the sway I had a problem take a look 
Fist of all I ran     forc new petition-contract
then
To compile, use `forc build`, and to run tests use `forc test`

----

Read the Docs:
- Sway Book: https://docs.fuel.network/docs/sway
- Forc Book: https://docs.fuel.network/docs/forc
- Rust SDK Book: https://docs.fuel.network/docs/fuels-rs
- TypeScript SDK: https://docs.fuel.network/docs/fuels-ts

Join the Community:
- Follow us @SwayLang: https://twitter.com/SwayLang
- Ask questions on Discourse: https://forum.fuel.network/

Report Bugs:
- Sway Issues: https://github.com/FuelLabs/sway/issues/new

**Comment by kayagokalp** [comment]
Closing as spam.

**Comment by kayagokalp** [comment]
If you have a question please edit the issue and include it
