### ISSUE TITLE
`std` and incorrect sway fmt for curly braces

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5468]
It appears that either CI does not check formatting properly or the formatter has a minor bug as seen

https://github.com/FuelLabs/sway/blob/5d712a083b7f564a777969356a8118696c91e2c5/sway-lib-std/src/storage/storage_map.sw#L56-L59

**Comment by sudhackar** [comment]
Formatter has a bug where the indentation is not matched after `where` when opening brace needs a new-line. Raised a PR
