### ISSUE TITLE
Storage namespacing

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#5490]
In some cases, such as when loading code from a contract within an LDC proxy, it's possible to mix code that uses the same storage context.

For instance, let's say we have a proxy that uses a single storage slot to store the address it's calling into, and a contract it calls that uses an arbitrary amount of storage.

To maintain coherent execution, the callee must leave the first storage slot untouched.

This creates the possibility for a lot of errors, prevents the future extension of the size of the caller storage context and generally is confusing.

We should instead allow contract storage to be optionally parameterized with a namespace string that acts as a salt when calculating the hash of storage slots, thus preventing collision between storage that uses a different namespace argument.

**Comment by IGI-111** [comment]
Borrowing from https://github.com/ethereum/solidity/issues/597 we should probably have two syntactic additions, one to specify a base for a given storage declaration and another to specify the offset of a given slot.
i.e.:
```sway
#[base(0x100)]
storage {
    a: u32, // at slot 100
    #[at(0x150)]
    b: u32, // at slot 150
    c: u32, // at slot 101
}
```

**Comment by dmihal** [comment]
@IGI-111 just curious, any reason to use this syntax

```rust
#[base("foobar")]
storage {
    foo: u32 in "foo", // at slot sha256("storage_foobar_foo")
}
```

...instead of more atrributes?


```rust
#[base("foobar")]
storage {
    #[base("foo")]
    foo: u32, // at slot sha256("storage_foobar_foo")
}
```

Also, why is the decorator called "base" instead of something like "namespace"?
