### ISSUE TITLE
Source location / debug info for actually dead source code

### ISSUE THREAD

**Issue by vaivaswatha** [FuelLabs/sway#5511]
In the recently introduced [support for debug profile](https://github.com/FuelLabs/sway/pull/5385), we still have DCE (and simplifycfg) running. This is because after the demotion and memcpy opt passes (which are more of legalisation than optimizaiton passes), there exists invalid code that must be removed. But this also ends up removing actual dead source code, which is bad for debug profile.

@sdankel has reported the following behaviour:

```
script;

fn main(hi: u64, hi2: u64) -> u64 {
    let h3 = hi + hi2;
    if h3 > 100 {
        return 0;
    }
    h3
}

#[test]
fn test_1() {
    let hi = 1;                    // This line has source maps
    let hey = 2;
    assert_eq(true, true);
}

#[test]
fn test_2() {
    let hi2 = 1;                   // Missing source maps for this line
    let hey2 = 2;
    assert_eq(true, true);
}
```
Work on improving the quality of source locations in such cases.

**Comment by vaivaswatha** [comment]
@sdankel From what I'm seeing, none of the dead code has source maps generated. In your report, you indicated that some of them do and some don't. Can you confirm?

Specifically, I see source location for `h3` in `main`, but not for any of `hi`, `hey`, `hi2` or `hey2`.

**Comment by sdankel** [comment]
@vaivaswatha it turned out I was using the source maps with an incorrect offset. I think your assessment is correct, so we can close this. Thanks!
