### ISSUE TITLE
Update `forc-client` for release mode

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#5607]
1. We should update the build finished message to look more like cargo: 

`Finished release [optimized] target(s) in 0.79s`
`Finished debug [unoptimized] target(s) in 0.79s`

![image](https://github.com/FuelLabs/sway/assets/47993817/c60c07a6-b658-4471-9eff-531834d16c85)

![image](https://github.com/FuelLabs/sway/assets/47993817/e08fc1e4-be42-4e04-8db7-6e90aed1f0c5)
![image](https://github.com/FuelLabs/sway/assets/47993817/249234f5-99bb-4502-bda8-89c217bb303c)

2. The `Compiling` and `contract ... Bytecode size` should only show when in verbose mode `-v`

3. When code is built from `forc deploy`, it should alway be built in release mode.
- should it always, or should it just default to release mode?

**Comment by Kheiriahmadasl** [comment]
1

**Comment by Nar035** [comment]
?
