### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Nemeswat** [FuelLabs/sway#5619]
Unexpected Error
Unexpected errors detected. We're sorry for
the inconvenience.
Would you like to send the following error
logs to Fuel Wallet team?
"error:[
e":t,
"name": "AbortError",
"message": "TimeoutError Transaction timed out
due to inactivity:
"inner":
"reactError":
"timestamp": 1691062037406,
"id": "06f266b0-a890-46ec-a816-
47d271802dca"
"error":/
Send reports
Ignore![Uploading Screenshot_20240215_192731_Kiwi Browser.jpg…]()

**Comment by Bleezysmart** [comment]
Compared to when I first used fuel wallet, it's better now. GOOD WORK GUYS. Its very commendable

**Comment by IGI-111** [comment]
This is the repository for Sway. For wallet related issues you want https://github.com/FuelLabs/fuels-wallet
