### ISSUE TITLE
error

### ISSUE THREAD

**Issue by voland33** [FuelLabs/sway#5646]
after running this command I received an error---npm create fuels

Killed#############) ⠋ reify:next: http fetch GET 200 https://registry.npmjs.org/next/-/next-14.0.1.tgz 155546ms (cache miss)
Error: Command failed: npm install
npm ERR! code 1
npm ERR! path /root
npm ERR! command failed
npm ERR! command sh -c create-fuels

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-22T16_17_13_099Z-debug-0.log

**Comment by IGI-111** [comment]
This is the repository for sway, not fuels-ts
