### ISSUE TITLE
Compiler crash on illegal import syntax

### ISSUE THREAD

**Issue by jjcnn** [FuelLabs/sway#5650]
The following `use` statement is illegal, even if the file `my_internal_mod.sw` is present:

```
script;

use my_internal_mod;

fn main() {
    assert(true);
}
```

Compiling the program causes the compiler to crash:

```
thread 'main' panicked at sway-core/src/semantic_analysis/ast_node/mod.rs:39:49:
index out of bounds: the len is 0 but the index is 0
```

**Comment by cold-briu** [comment]
HI there @jjcnn 

Thanks for sharing this issue, however, it's impossible for us to review without knowing the compiler version. 

Can you please share the result of running $`fuelup show`?

**Comment by jjcnn** [comment]
It's on currrent `master`, and I'm in the process of fixing some issues with imports. I just opened the issue so that I wouldn't forget it was there.
