### ISSUE TITLE
Create Nightly GA Action CI pipeline that runs cargo audit (sway)

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/sway#571]

**Comment by mitchmindtree** [comment]
Closing as this has since been added for the repo.

Find the workflow here:

https://github.com/FuelLabs/sway/blob/master/.github/workflows/nightly-cargo-audit.yml

Find the nightly results here:

https://github.com/FuelLabs/sway/actions/workflows/nightly-cargo-audit.yml
