### ISSUE TITLE
Misspelled variables cause internal compiler error

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#5750]
The following code produces this error: ` Internal compiler error: Verification failed: Type mismatch found for call to 'val_0': () is not a u64.`

```sway
contract;

pub struct MyStruct {
    val: u64
}

impl MyStruct {
    pub fn val(self, new_val: u64) -> u64 {
        0
    }
}

abi MyContract {
    fn test_function(my_struct: MyStruct, val: u64);
}

impl MyContract for Contract{
    fn test_function(my_struct: MyStruct, val: u64) {
        my_struct.val(vel); // Note misspelling of val here
    }
}
```

**Comment by vaivaswatha** [comment]
The latest compiler throws an error "Variable "vel" does not exist in this scope." and exits gracefully. Closing. Please reopen if you continue to see the issue.
