### ISSUE TITLE
Excessive Build Time with Forc 0.51.1 Compiler

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/sway#5769]
### Summary

While attempting to address a separate issue described in [FuelLabs/sway#5768](https://github.com/FuelLabs/sway/issues/5768), we opted to test the new Forc 0.51.1 compiler for our Spark-Perps contract. Unfortunately, this led to a new problem where the build process now takes an unexpectedly long time, approximately 40 minutes.

### Steps to Reproduce

1. Clone the Spark Perps repository and switch to the relevant branch:
    ```bash
    git clone git@github.com:compolabs/spark-perps.git
    cd spark-perps
    git checkout feat-forc-51-1
    forc build
    ```
2. Observe the build time, which extends to about 40 minutes.

### Toolchain Configuration

    ```toml
    [toolchain]
    channel = "nightly-aarch64-apple-darwin"

    [components]
    forc = "0.51.1"
    fuel-core = "0.23.0"
    ```

### Expected Behavior

The expectation for the build process, especially with newer compiler versions, is to either maintain or improve build times, making development efficient and streamlined.

### Actual Behavior

The actual build time with Forc 0.51.1 extends to about 40 minutes, which significantly hinders development speed and efficiency.

### Additional Information

- If further diagnostic logs or details are required, please let me know. I'm available for direct messages on Telegram ([@defi_defiler](https://t.me/defi_defiler)) for additional coordination or to provide more details.

Thank you for your attention and support in resolving this issue.

Alex, Composability labs

**Comment by ironcev** [comment]
@chlenc Thanks for reporting the issue! Just a quick question, is there any difference in compilation time when you compile in `release` mode: `forc build --release`?

Of course, regardless of the build settings, the compilation must not take that long, but just to narrow the possible source of issues.

Thanks!

**Comment by chlenc** [comment]
Gm @IGI-111 @ironcev 
Are there any updates?
