### ISSUE TITLE
Allow definition of addresses/asset ids in the manifest file

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#577]
Manually updating `b256` values in code is tedious and annoying -- we should instead be able to define these addresses in the manifest, for easy updatability, and refer to them in the project as constants.

Ideally, in `Form.toml`, something like:

```

[aliases]
DEPLOYED_CONTRACT = 0xfff....
DEPLOYED_CONTRACT_2 = 0xaaa....
ASSET_ID = 0x123456....
```

and in the code:
```rust

fn main() {
  let caller = abi(MyAbi, DEPLOYED_CONTRACT);
}

```

**Comment by nfurfaro** [comment]
Note that this related issue aims to change the type from `b256` to `ContractId`: https://github.com/FuelLabs/sway/issues/465

**Comment by nfurfaro** [comment]
Any progress on this? 
As my tests are getting more complex involving more than 1 contract which need to call each other, hardcoded `ContractId`s in the ABI casts are becoming a real limitation.

**Comment by sezna** [comment]
No progress has been made but I believe this should be unblocked now. 

This issue is referring to using expressions that evaluate to `b256`s in an `abi` cast. Are you referring to that, or injecting contract addresses from the SDK/`Forc.toml` level and referring to them in the code as a name?

**Comment by nfurfaro** [comment]
@sezna 
I think we're on the same page here...
I currently have to do the following:
`let auth_contract = abi(AuthTesting, 0x31339370c797efcecd4d33d4e36d95dc19479917afde2a930d44c04b37b4c368);`
When I would really rather do this:
`let auth_contract = abi(AuthTesting, auth_contract_id);`

The added friction here has been minimal until recently.
Now that I'm testing with more than 1 contract, my workflow involves (for example):
1. compiling contract A and generated an `abi.json` file
2. run a test using only Contract A and log it's ID
3. hardcode ID A into contract B's abi-cast
4. compile contract B and generated an `abi.json` file
5. Proceed to run my full test suite.

**Comment by mohammadfawaz** [comment]
If this is unblocked now, I'd like to do this. Fits with what I've been doing recently and I've suffered the pain of having to manually update the contract IDs for every minor change in the bytecode of a contract.

**Comment by mohammadfawaz** [comment]
Update: I've tried using variables instead of hardcoded contract IDs and I don't see any issues. The receipt I'm getting back is correct. I've tried other things like grabbing the ID from a library or from the result of a function call.

That being said, we should still test the case where the contract ID is not known at compile time. @nfurfaro is helping out with that. I won't close this issue until we have confirmation that such a case is okay.

**Comment by sezna** [comment]
I'm going to rename this issue to allowing config-level contract IDs. This will still need some design/spec work

**Comment by mitchmindtree** [comment]
I'm not quite sure I follow the motivation behind this - is the idea that writing something like this in sway:

```rust
const DEPLOYED_CONTRACT = ContractId(0xfff....);
const DEPLOYED_CONTRACT_2 = ContractId(0xaaa....);
const ASSET_ID = ContractId(0x123456....);
```

is a bit too verbose, and instead you'd like to be able to write something like this:

```toml
[aliases]
DEPLOYED_CONTRACT = 0xfff....
DEPLOYED_CONTRACT_2 = 0xaaa....
ASSET_ID = 0x123456....
```
in the `Forc.toml`, and have `forc` translate this table into the sway code above and include it in scope of the Sway code?

**Comment by adlerjohn** [comment]
It's not about verbosity, it's about being able to specify _configuration-time_ constants, i.e. constants that _may change_ at compile time. This allows you to e.g. deploy one contract then feeds its contract ID as a constant into a second contract.

**Comment by adlerjohn** [comment]
Also cc @digorithm on the conversation here, as the SDK will also have to allow users to specify these configuration-time constants for testing etc.

**Comment by adlerjohn** [comment]
> Right, we already have `call(...).set_contracts(&[...])`, but that's per call.

This issue isn't about run-time parameters, but about configuration-time constants.

I forgot that the SDK no longer compiles contracts. In that case it would be difficult for it to set configuration-time constants without some changes. Well, bikeshedding that feature can be done in fuels-rs.

**Comment by mitchmindtree** [comment]
> This allows you to e.g. deploy one contract then feed its contract ID as a constant into a second contract without having to hardcode anything.

Ahhhh interesting! Is easily updating the ID for newly deployed contracts the primary use-case?

It might be nice to list all the known use-cases that go beyond just declaring/updating a constant in case it makes some other potential workflow more apparent.

---

I wonder if this idea of passing through contract IDs could add motivation for having something similar to cargo's `[workspace]` feature to forc?

E.g. if there were multiple contracts in a workspace that interact, would it be useful to have some way of automatically passing through contract IDs at the time of `forc deploy`? The idea would be to avoid having to run the commands for each manually and keep updating the `Forc.toml` for dependents, which might produce a bit of diff noise. As a very rough example I'm imagining something like:

```toml
[contract-ids]
CONTRACT_FOO = "contract-foo"
CONTRACT_BAR = "contract-bar"
CONTRACT_BAZ = 0x123456...
```

where `contract-foo` and `contract-bar` are other sway contract projects within the same workspace, and `CONTRACT_BAZ` refers to some previously deployed 3rd-party/external contract. Then during a workspace-wide `forc deploy`, forc could construct a contract-id dependency graph to determine the order in which contracts need to be built, then deploy each in order, passing the deployed contract IDs through to the dependents.

I'd imagine we'd also want a way to specify fallback IDs in the case that upstream contract IDs are not yet known (for local tests, or just checking compilation). Maybe something like:

```toml
[contract-ids]
CONTRACT_FOO = { package = "contract-foo", default = 0xFFFF... }
```

If we go down this route, we'd possibly also benefit from settling on a standard way of pinning a project's last known deployed contract ID too. E.g. maybe we generate some `contract-id.lock` file at the end of successfully deploying a contract that can be used when deploying or testing dependent contracts individually.

Let me know if I'm totally missing the mark here!

**Comment by adlerjohn** [comment]
We probably to want the notion of a workspace and workspace tests, but that's the subject of a future yet-to-be-filed issue!

Another usecase for being able to set constants at configuration time is changing durations from e.g. days (as it would be in prod) to seconds (to test). There's a bunch of other ones. While you could use contract storage and some sort of `init` routine in the contract, that would be very expensive since it would involve state reads all the time, rather than just being in the final compiled bytecode.

**Comment by mitchmindtree** [comment]
I wonder if we could use a combination of "profiles" and modules to solve this in a manner that doesn't require repeatedly updating a config table? E.g. I'm imagining being able to do something like:

*config_debug.sw*
```rust
const DURATION = 10;
const ASSET_ID = 0x1324...;
const CONTRACT_ID = 0x5678...;
```
*config_release.sw*
```rust
const DURATION = 1000;
const ASSET_ID = 0x8149...;
const CONTRACT_ID = 0x9852...;
```
*main.sw*
```rust
#[profile(debug)]
dep config_debug as config;
#[profile(release)]
dep config_release as config;

fn foo() {
    // Do stuff with `config::DURATION`, `config::ASSET_ID`, `config::CONTRACT_ID`
}
```

The idea here is that when built with the `debug` profile, `config` will refer to the `config_debug` module and when built with a `release` profile, `config` will refer to the `config_release` module.

The profile to use would be specified via a `--profile` flag rather than manually updating the `Forc.toml` each time e.g. `forc build --profile debug` would use `config_debug` and `forc build --profile release` would use `config_release`. Like Rust, we could have `debug` and `release` be default profiles, and perhaps have `forc build` and `forc test` default to `debug`, while `forc deploy` defaults to release. We'd probably also want to support declaring custom profiles in `Forc.toml` too.

This approach is kind of similar to how many cross-platform Rust projects work like `winit` or `cpal`, however they instead use something like `#[cfg(target_os = "linux")]` to gate `platform` modules based on the target architecture rather than using profiles to gate config modules as in the example above.

**Comment by nfurfaro** [comment]
The only tooling I have experience with that relates to this topic is working with Hardhat + the hardhat-deploy plugin.
I think the following are examples of workflows that we may want to accommodate, and so might influence the way this is implemented.

A few things that are relevant here...hardhat-deploy aims to make the deployment process simple, configurable and shareable. A few things it provides to achieve this include:

1. Named Accounts: https://github.com/wighawag/hardhat-deploy#1-namedaccounts-ability-to-name-addresses
- allows you to associate names to addresses and have them configured per chain
- tests & scripts can refer to addresses by name, and the name resolves to the correct address depending on the current network.
```
{
    namedAccounts: {
        deployer: {
            default: 0, // here this will by default take the first account as deployer
            1: 0, // similarly on mainnet it will take the first account as deployer. Note though that depending on how hardhat network are configured, the account 0 on one network can be different than on another
            4: '0xA296a3d5F026953e17F472B497eC29a5631FB51B', // but for rinkeby it will be a specific address
            "goerli": '0x84b9514E013710b9dD0811c9Fe46b837a4A0d8E0', //it can also specify a specific netwotk name (specified in hardhat.config.js)
        },
        feeCollector:{
            default: 1, // here this will by default take the second account as feeCollector (so in the test this will be a different account than the deployer)
            1: '0xa5610E1f289DbDe94F3428A9df22E8B518f65751', // on the mainnet the feeCollector could be a multi sig
            4: '0xa250ac77360d4e837a13628bC828a2aDf7BabfB3', // on rinkeby it could be another account
        }
    }
}
```

2. Deploy Scripts: https://github.com/wighawag/hardhat-deploy#deploy-scripts
- running `hardhat deploy` will execute all deploy scripts present. 
- dependency tags added to these scripts ensure they are executed in the proper order (allowing the address from a contract deployed in one script to be used in another script).
- the deploy scripts are context-aware( they know what the current network is).
- If a contract has already been deployed on the current network && the bytecode has not changed, it won't be deployed again.
- a deploy script can deploy a contract, then call it and initialize storage values, transfer ownership from the deployer to a multisig wallet, call initializer functions on upgradeable contracts, etc...

3. Deployments:
- all contracts deployed are saved to the `deployments` directory, along with metadata.
- deployments are tracked by git, so there's always a record of the deployed address (on testnets and mainnet) for each contract
- metadata like the hash of the bytecode allows for an easy check to see if the bytecode for a contract has changed, and whether it needs to be redeployed or use the existing deployed address.

**Comment by mohammadfawaz** [comment]
Deprecating in favour of https://github.com/FuelLabs/sway/issues/845
