### ISSUE TITLE
SwayFmt: Allow alignment of struct/enum field/variant types

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#578]
This is purely preference, but I much prefer enums/structs to be formatted like this:
```rust
enum InventoryEvent {
    CustomerPurchase : Receipt,
    ItemLoss         : Claim,
    CustomerReturn   : Refund,
}
```

rather than the Rust default which doesn’t align things. I find this much more readable. Would this be easy to implement, perhaps configurably (and as the default)?

**Comment by adlerjohn** [comment]
If configurable, then depends on https://github.com/FuelLabs/sway/issues/605

**Comment by eureka-cpu** [comment]
> If configurable, then depends on #605

We can make it configurable, but I think the intention was to make it the standard. Correct me if I'm wrong @sezna ?

**Comment by eureka-cpu** [comment]
I went ahead and added you as well @adlerjohn . Currently awaiting amendments from Alex to what I already have, which you can find [here](https://github.com/eureka-cpu/field-formatter)

**Comment by sezna** [comment]
> > If configurable, then depends on #605
> 
> We can make it configurable, but I think the intention was to make it the standard. Correct me if I'm wrong @sezna ?

The idea is to make it configurable, but the default. We could implement it with a basic toggle boolean for now and hook it up to the toml when that becomes available. 

> Would this be easy to implement, perhaps configurably (and as the default) [...]

**Comment by leviathanbeak** [comment]
I would recommend we first review and accept #622 
after that @eureka-cpu can try to tackle this one.

For configuration, we can have a Config Struct passed to the formatter,
currently the tab size is the only parameter that is passed there so we can create something like this

```
struct FmtConfig {
   tab_size,
   format_enums_acorrding_to_alex,
   ...
```

**Comment by adlerjohn** [comment]
The general opinion from #677 seems to be that this diverges from Rust, and so it would be very opinionated (in a bad way) to have.
