### ISSUE TITLE
Support configurable base_asset_id in forc plugins

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/sway#5785]
Forc tooling currently assumes a base asset id of 0x000..., however since the network supports custom base asset id's the tooling should dynamically load the base asset ID.

**Comment by dmihal** [comment]
@kayagokalp mentioned that the wallet & deployment tools use the SDK, therefore not much should be needed.

I'll leave this open for now, but it's blocked by the SDK changes. Once those changes are added, the tooling will need to switch from the `BASE_ASSET_ID` constant to the `provider.base_asset_id()` function.

**Comment by kayagokalp** [comment]
Places we manually need to fix:

1. forc-deploy
2. forc-tx

**Comment by kayagokalp** [comment]
Blocked by #5981

**Comment by sdankel** [comment]
@kayagokalp Is this unblocked?

**Comment by kayagokalp** [comment]
closed by https://github.com/FuelLabs/sway/pull/5987

**Comment by kayagokalp** [comment]
Forc clients that are interacting with node uses sdk for the most case and only part that we do things with ASSET_ID is updated to take it from the node by querying it first
