### ISSUE TITLE
Incorrect function chaining behaviour?

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#5805]
Forc `0.52.0`

Unsure if this is the intended behaviour but it seems like a bug based on my subjective expectations.

The line `a = a.field.action()` is expected to assign `B` onto `a.field` but instead it takes it up the chain and overwrites `a`.
There is a commented out function which behaves as expected, perhaps my expectations are incorrect and the uncommented function exhibits correct behaviour.

```sway
contract;

struct A {
    field: B
}

struct B {
    field: u64
}

impl B {
    pub fn action(self) -> Self {
        self
    }
}

abi MyContract {
    fn test_function() -> A;
}

impl MyContract for Contract {
    fn test_function() -> A {
        let mut a = A { field: B { field: 5 } };
        a = a.field.action();
        a // Returns B instead of A // does not compile
    }

    // fn test_function() -> A {
    //    let a = A { field: B { field: 5 } };
    //    a.field.action();
    //    a // Returns A as expected but it isn't mut, should this not compile, haven't check if the value would change correctly?
    //}
}
```

**Comment by IGI-111** [comment]
I don't understand how this is supposed to be unexpected.

`a` is a local of `test_function` and all the assignment `a = a.field.action()` does is replace value `A { field: B { field: 5 } }` with a copy of `a.field.action()`, which is to say with `B { field: 5 }`.

It sounds like you want some kind of referential behavior but this isn't the default semantics of Sway. We as of now are copy by default, as C++.
