### ISSUE TITLE
Add a flag to forc contract-id command to show it in bech32 format

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#5842]
Currently forc-contract-id show the contract id in hex format but it is possible that users may want to get in bech32 format as well. We should have a flag for this

**Comment by ADTmux** [comment]
Hey, I would like to work on this!

**Comment by kayagokalp** [comment]
> Hey, I would like to work on this!

Sounds great! go for it :) assigned to you

**Comment by ADTmux** [comment]
Hey, quick question, I recently tried to modify `https://github.com/FuelLabs/sway/blob/master/forc/src/ops/forc_contract_id.rs` and I wanted to test my modifications to the command, could you please lead me to the right part of the documentation that would help me modify the forc binary installed to get started on this

**Comment by kayagokalp** [comment]
> Hey, quick question, I recently tried to modify `https://github.com/FuelLabs/sway/blob/master/forc/src/ops/forc_contract_id.rs` and I wanted to test my modifications to the command, could you please lead me to the right part of the documentation that would help me modify the forc binary installed in my setup to get started on this

Great to hear that you are making progress! You can build your version of forc with `cargo build` and use forc with absolute path `./target/debug/forc` from the root of the sway repo. Or you can remove your current forc installation (if you installed it through cargo check your ./cargo/bin/ or if you installed it from fuelup check your ./fuelup/bin) and install your modified version with `cargo install`. Also consider opening a PR once you feel like it to start review process.

**Comment by ADTmux** [comment]
Hi, I did integrate the flag, I wanted a hint on how the `forc contract-id --help` command prints out information so that I could integrate a line on `--bech32` 

<img width="687" alt="Screenshot 2024-04-21 at 5 46 43 AM" src="https://github.com/FuelLabs/sway/assets/165437009/7f265155-367a-4b0d-acaa-520fa5f51ef8">

**Comment by ADTmux** [comment]
Hi @kayagokalp could you assist me with this last bit? :)

**Comment by kayagokalp** [comment]
Hey @ADTmux please open a PR so that i can see your WIP and assist you better. You should add this new flag to  https://github.com/FuelLabs/sway/blob/daee1c247c86038bf9a3faefbca80d0aca4ebf0e/forc/src/cli/commands/contract_id.rs#L18C12-L18C19

**Comment by sdankel** [comment]
@kayagokalp Can we close this since we are removing Bech32 format from the wallet?

**Comment by kayagokalp** [comment]
Yes that seems reasonable to me :)
