### ISSUE TITLE
Mistyping a test name doesn't error

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#585]
```console
$ cargo run --bin test foobar
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/test foobar`
_________________________________
Tests passed.
```

**Comment by otrho** [comment]
This is because the test name is a regex.  If it matches no tests, no tests are run, all zero tests passed.

We can put in a little footer to declare the number of tests run to make it more obvious, or even a message declaring the regex didn't match anything.

**Comment by adlerjohn** [comment]
Both of those sound like nice features!
