### ISSUE TITLE
Heap types with greater than 8 length consuming huge amount of gas when using experimental encoding

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/sway#5866]
In the TS SDK, we have the following contract function that echos a dynamic string:

https://github.com/FuelLabs/fuels-ts/blob/7457e535f9271ab3d89371ea2d9057077d4b9709/apps/docs-snippets/test/fixtures/forc-projects/echo-std-string/src/main.sw#L12-L14

We test it by passing `Hello Fuel`, a string  in the following test:

https://github.com/FuelLabs/fuels-ts/blob/7457e535f9271ab3d89371ea2d9057077d4b9709/apps/docs-snippets/src/guide/types/std-string.test.ts#L28-L38

Under the new encoding, this test is now throwing `OutOfGas`:

```th
 FAIL  apps/docs-snippets/src/guide/types/std-string.test.ts > StdString > should retrieve a std string from a contract
FuelError: The transaction reverted with reason: "OutOfGas".

You can read more about this error at:

https://docs.rs/fuel-asm/latest/fuel_asm/enum.PanicReason.html#variant.OutOfGas
 ❯ extractTxError packages/account/src/account.ts:1645:10
 ❯ TransactionResponse.waitForResult packages/account/src/account.ts:3522:13
 ❯ Function.build packages/program/src/utils.ts:579:22
 ❯ apps/docs-snippets/src/guide/types/std-string.test.ts:34:23
     32|     const stdString: StdString = 'Hello Fue';
     33|
     34|     const { value } = await contract.functions.echo_string(stdString).call();
       |                       ^
     35|
     36|     expect(value).toEqual(stdString);
```

During transaction estimation, I can see this call has used `0x985526` or `9983270` units of gas, hence the tx is running out of gas.

If the same function is called with a string with less than 8 values. the test will pass and uses significantly less gas. For example, 'Hello Fu' consumes `0x271` or `625` units of gss.

The same is happening for out [bytes](https://github.com/FuelLabs/fuels-ts/blob/7457e535f9271ab3d89371ea2d9057077d4b9709/packages/fuel-gauge/test/fixtures/forc-projects/bytes/src/main.sw#L91-L99) and [vec](https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/test/fixtures/forc-projects/vectors/src/main.sw) tests.

**Comment by MujkicA** [comment]
Might not be a compiler issue since we don't encounter this on the Rust SDK side:
https://github.com/FuelLabs/fuels-rs/pull/1341

**Comment by danielbate** [comment]
Closing as this has now been proved as working in the TS SDK.
