### ISSUE TITLE
`break` and `continue` keywords

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#587]
`break` should abort a while loop, and `continue` should jump back to evaluating the condition for another loop. Those jump labels already exist, so this issue involves new keywords and jumping back to those jump labels.

I do _not_ think we should be able to `break` on a value like in Rust. That adds a lot of type-checking complexity for not a lot of benefit, IMO. Maybe someday...but just vanilla `break` and `continue` should be good for now.

**Comment by mohammadfawaz** [comment]
I'll do this next.
