### ISSUE TITLE
Expand Storage Implementations to Handle Advanced Nested Storage Types

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#5879]
Implementation for advanced nested storage with heap types should be added:

- `StorageMap<T, StorageString>` 
- `StorageMap<T, StorageVec<T>>`
- `StorageMap<T, StorageString>` 
- `StorageMap<T, StorageBytes>` 

- `StorageVec<StorageString>`
- `StorageVec<StorageBytes>`
- `StorageVec<StorageMap<T, Y>>`
- `StorageVec<(T, T)>`

- `(StorageVec<T>, StorageVec<T>)`
- `(StorageString, StorageString)`

**Comment by bitzoic** [comment]
> This is a duplicate of [FuelLabs/sway-rfcs#34](https://github.com/FuelLabs/sway-rfcs/issues/34) or rather of its implementation whenever the RFC lands. I'll close this since we're working on it and it's already captured in other issues.

Will this be included by the testnet?

**Comment by bitzoic** [comment]
> This is a duplicate of [FuelLabs/sway-rfcs#34](https://github.com/FuelLabs/sway-rfcs/issues/34) or rather of its implementation whenever the RFC lands. I'll close this since we're working on it and it's already captured in other issues.

Is there a timeline on when this would be included?

**Comment by IGI-111** [comment]
Given where we are now, it's at least a month or two out. More if other things take priority.
