### ISSUE TITLE
Formatter should format inline asm opcodes aligned to 4 chars

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#590]
The maximum size of each opcode is 4 characters. The formatter should pad with extra spaces such that the "opcode" part of each line is 4 characters.

**Comment by mohammadfawaz** [comment]
@eureka-cpu adding this to the `swayfmt-v2` project. It's probably not a huge deal but would be nice to have.

**Comment by eureka-cpu** [comment]
Would you mind giving an example of what this should look like?

**Comment by mohammadfawaz** [comment]
For example, something like
```
move buffer sp; // Make `buffer` point to the current top of the stack
cfei i8; // Grow stack by 1 word
sw buffer ptr i0; // Save value in register at "ptr" to memory at "buffer"
k256 hash buffer eight_bytes; // Hash the next eight bytes starting from "buffer" into "hash"
cfsi i8; // Shrink stack by 1 word
hash: b256 // Return
```
would become:
```
move buffer sp; // Make `buffer` point to the current top of the stack
cfei i8; // Grow stack by 1 word
sw   buffer ptr i0; // Save value in register at "ptr" to memory at "buffer"
k256 hash buffer eight_bytes; // Hash the next eight bytes starting from "buffer" into "hash"
cfsi i8; // Shrink stack by 1 word
hash: b256 // Return
```

**Comment by eureka-cpu** [comment]
In total there's 3 spaces including the naturally placed space. Just out of curiosity, it doesn't seem to really affect readability much, what's the advantage of adding the extra space?

**Comment by mohammadfawaz** [comment]
This would match the behavior of `-print-finalized-asm`:
```
lw   $ds $is 1
add  $$ds $$ds $is
lw   $r0 data_0               ; literal instantiation
ret  $r0
```
For a long list of `asm` opcodes, I imagine readability is slightly better if the opcodes are all aligned.

This is probably low-ish priority so it shouldn't block the MVP, but I'll let you handle its prioritization :)
