### ISSUE TITLE
Predicate compilation succeeds when it should not

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#5966]
A simple predicate with an unwrap contains the revert opcode, which should fail compilation but does not

This later fails with (looks like a VM error)
```
Transaction(Validation("PredicateVerificationFailed(PanicInstruction(PanicInstruction { reason: ContractInstructionNotAllowed, instruction: RVRT { value: 0x0 } (bytes: 36 00 00 00) }))"))
```

**Comment by xunilrj** [comment]
The error seems to be coming from https://github.com/FuelLabs/fuel-vm/blob/a3f4f1e9ca57d3960c90e50cb7b1b22de15cbc2a/fuel-vm/src/interpreter/executors/instruction.rs#L94

The VM checks what opcodes are allowed at https://github.com/FuelLabs/fuel-vm/blob/master/fuel-asm/src/lib.rs#L688, we check which are NOT allowed at https://github.com/FuelLabs/sway/blob/master/sway-core/src/asm_generation/fuel/checks.rs. 

Maybe it is worthy to do the same as the VM and avoid future problems.

**Comment by xunilrj** [comment]
We will implement a static check at https://github.com/FuelLabs/sway/issues/5986
