### ISSUE TITLE
Create Github Action for Delay Crate Publish

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/sway#600]
Create Github Action for Delay Create Publish based on this PR- https://github.com/katyo/publish-crates/pull/370

**Comment by adlerjohn** [comment]
Ideally this should simply be a PR against https://github.com/katyo/publish-crates, since we don't want to maintain a crates publishing action.

**Comment by rfuelsh** [comment]
@adlerjohn - how should i track this on the Fuel board ?

**Comment by adlerjohn** [comment]
Can you probably keep this issue, then reference it in the PR that's opened against the upstream repo. That way we at least have _something_ on the project board.

**Comment by adlerjohn** [comment]
FYI, this is no longer needed as per https://github.com/katyo/publish-crates/pull/370#issuecomment-1010338019
