### ISSUE TITLE
Configurables cannot be used in `storage` block

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#6009]
With the new encoding, configurables may no longer be used in a `storage` block. This breaks certain design implementations such as the [SRC-5 example implementation](https://github.com/FuelLabs/sway-standards/blob/master/examples/src5-ownership/initialized_example/src/initialized_example.sw).

Minimal Repo:

```sway

pub enum MyEnum {
    Varient1: (),
    Varient2: u64,
}

configurable {
    MY_U64: u64 = 1,
}

storage {
    my_val: MyEnum = MyEnum::Varient2(MY_U64)
}
```

**Comment by xunilrj** [comment]
This is by design.

Before encoding v1, storage would be initialized with the default value, and not with the new configurable value. Creating a silent bug.

Vanilla consts still work and have the same behavior as before.
