### ISSUE TITLE
Forc should warn when a new version of Fuel dependencies are available

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#601]
1. If a new semver-compatible version of Fuel dependencies w.r.t. the Cargo lockfile is available on `crates.io` (maybe checkable with https://doc.rust-lang.org/cargo/commands/cargo-update.html), a warning should be emitted.
2. Instructions to update should also be included: the Cargo lockfile should be removed so that new versions of dependencies can be downloaded.

**Comment by sdankel** [comment]
Fuel dependencies are managed via [fuelup](https://github.com/FuelLabs/fuelup) or [fuel.nix](https://github.com/FuelLabs/fuel.nix)
