### ISSUE TITLE
Newlines in str array in `configurable` block crash compiler

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#6021]
With the new configurable encoding, if including a new line in a str array the compiler will crash. This is used in the [SRC-11; Security Information Standard example](https://github.com/FuelLabs/sway-standards/blob/bd1e8ea041b94f4ea95ba2b35a6b0f11e992ec44/examples/src11-security-information/hardcoded-information/src/main.sw#L24) which hardcodes data into the `configurable` block. This resulting in the `Entered unreachable code: non encoded configurable inside encoding v1` error.

Minimal Repo:

```sway
contract;

configurable {
    MY_CONFIG: str[3] = __to_str_array("a
    b"),
}

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        true
    }
}
```

<img width="628" alt="Screenshot 2024-05-16 at 11 11 17 AM" src="https://github.com/FuelLabs/sway/assets/54727135/8a9ba026-dc65-41ae-a026-41f362318226">

**Comment by xunilrj** [comment]
I will look into this.

**Comment by xunilrj** [comment]
I think this is a problem with the error message on your compiler version. `master` version correctly points out that the string slice actually has 7 chars (all the identation tabs). Removing them, it worked for me.

![image](https://github.com/FuelLabs/sway/assets/83425/37af01c5-cae2-41a6-b390-140410831cf5)

![image](https://github.com/FuelLabs/sway/assets/83425/c61248f2-6590-4dfb-bdd1-8389cb617e19)
