### ISSUE TITLE
Forc deploy should support (and enhance the userflow while) using proxy contracts

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#6068]
We have an rfc: https://github.com/FuelLabs/sway-rfcs/pull/39 that describes the desired behaviour.  Basically we want forc-deploy to be aware of contracts with proxy contract requirements and support deploying a proxy contract automatically if it is enabled. If no proxy contract was already deployed for the contract we will deploy a new "default" proxy implementation. Otherwise we will update the already deployed proxy contract.

**Comment by sdankel** [comment]
Blocked on fuel-core 0.27 upgrade in sway

**Comment by sdankel** [comment]
Blocked on https://github.com/FuelLabs/fuels-rs/pull/1396

**Comment by kayagokalp** [comment]
closed by #6069
