### ISSUE TITLE
Match expression arms don't support simple expressions.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#609]
E.g.,
```
fn main() -> bool {
    match false {
        true => false,
        foo => foo,
    }
}
```
This produces errors:
```
warning
 --> main.sw:0:17
  |
...
4 |         true => false,
  |                 ----- This returns a value of type bool, which is not assigned to anything and is ignored.
  |
warning
 --> main.sw:0:17
  |
...
5 |         foo =>  foo ,
  |                 --- This returns a value of type bool, which is not assigned to anything and is ignored.
  |
error
 --> main.sw:0:11
  |
...
3 |       match false {
  |  ___________^
4 | |         true => false,
  | |____________^ No method named "eq" found for type "bool".
  |
error
 --> main.sw:0:17
  |
...
4 |         true => false,
  |                 ^^^^^ Mismatched types.
expected: bool
found:    ().
```
This final error is repeated a few more times.

All of the type errors go away if the match arm expressions are bracket code blocks, e.g., `true => { false },`.

The warning about `no method named "eq" for type "bool"` is separate; looks like we need to implement `Ord` for `bool` still.

**Comment by otrho** [comment]
I've made https://github.com/FuelLabs/sway-lib-core/issues/8 for the `eq` thing.

**Comment by emilyaherbert** [comment]
This has to do with how the parser interprets implicit return statements. The fix is probably in changing how we handle implicit returns.
