### ISSUE TITLE
Fuelet wallet showing black 

### ISSUE THREAD

**Issue by Bettercalljoe4crypto** [FuelLabs/sway#6113]
### Related Component

compiler

### Problem

Hi,

my Fuelet wallet is showing black on Google browser. Does not let me log in. 
![4E86DC51-AE44-429A-802D-A44AA84141C0](https://github.com/FuelLabs/sway/assets/128833168/675b2696-5af5-4b35-be2c-2305d3752faa)

### Steps

Uninstalled and installed it again
Same issue.
Also would be nice use iOS phone to buy a domain check out my repositories please 

### Possible Solution(s)

Might be a problem with the bits or Google overload 

### Installed components

```console
Fuelup check
```

**Comment by IGI-111** [comment]
This is an issue with the fuel wallet, not Sway or Sway tooling, do not report it here but on the wallet's repository.
