### ISSUE TITLE
Include `ptr` , `len` and bytes in ABI Receipts 

### ISSUE THREAD

**Issue by maschad** [FuelLabs/sway#6115]
### Related Component

compiler

### Problem you are trying to solve

On beta5, when decoding a contract call from a transaction ABI receipt, one could have used the previous `Param1` to determine the function selector. 

Now with the [new encoding for contract calls](https://github.com/FuelLabs/sway/commit/c24d7319ab4b983a3abe59b6a6d99e09450a45ba) the contract calls first param is now encoded [using the pointer](https://github.com/FuelLabs/sway/blob/master/sway-lib-core/src/codec.sw#L33-L48) and so consumers can no longer determine the function selector from the transaction receipt.

### Solution you'd like

<img width="232" alt="Screenshot 2024-06-12 at 12 55 50 PM" src="https://github.com/FuelLabs/sway/assets/9755286/da25e7e9-76d9-4541-a67b-f6aa47441deb">

As shown in the screenshot above from the [following transaction](https://next-app.fuel.network/tx/0x0ec0390a47eb248d579c74861d747259c2a2a3f4c5c4cdccf049f0670b9a4485/advanced), given that `Param1 ` and `Param2` are pointers, they will always return the same values, and more importantly they are meaningless without access to the VM memory (which a consumer can't access at this point). 

One solution could be to return thee `ptr`, `len` and bytes when returning the ABI Receipt.

**Comment by IGI-111** [comment]
This should be convenience provided by the SDK when it reports the receipts, not a change in how the VM or Sway works.

The problem is not that it's a pointer, but that you didn't have the value recorder before giving up access to VM memory.

**Comment by maschad** [comment]
I see, would it be possible to return the entire call data? I don't the we would be able to record this value and so our best bet would be to deref the pointer and examine if it points to a particular `u64` value.

**Comment by maschad** [comment]
Thanks for clarifying. As it turns out I may have overcomplicated this as we can actually access the `scriptData` in contract calls and thus we can slice the encoded selector offset. Closing as this is no longer relevant.
