### ISSUE TITLE
Compiler panics and no DCA warning when a configurable is never used

### ISSUE THREAD

**Issue by ironcev** [FuelLabs/sway#6118]
The configurable `MAX_SUPPLY` is never used and optimized away but there is no dead code warning generated and that confuses the developers.

Additionally, the code compiles without warnings or errors on Sway v0.60.0 but the compiler panics on the current master:
```
thread 'main' panicked at sway-core/src/semantic_analysis/ast_node/declaration/configurable.rs:106:18:
called `Result::unwrap()` on an `Err` value: ErrorEmitted { _priv: () }


```

```Sway
contract;

abi Test {
    fn test() -> bool;
}

configurable {
    MAX_SUPPLY: u64 = 3,
}

impl Test for Contract {
    fn test() -> bool {
        true
    }
}
```

**Comment by Dr-Maxwell** [comment]
Possible Solution
Prevent Optimization of Constants:
Ensure constants like MAX_SUPPLY are not optimized away by using them in a way that the compiler recognizes as necessary. For example:
const MAX_SUPPLY: u64 = 1000;

fn main() {
    println!("MAX_SUPPLY is: {}", MAX_SUPPLY); // Dummy usage to prevent optimization
    // Your application logic
}
Enable Dead Code Warnings:
Ensure dead code warnings are enabled in your development environment to catch unused constants and other dead code. Add the following to Cargo.toml:
[profile.dev]
rustflags = ["-Awarnings"]
Handle Errors Properly:
Avoid using unwrap() on Result types where an Err could occur. Instead, handle errors using match or the ? operator for proper error propagation and handling.

i hope this helps
