### ISSUE TITLE
[FORC-BUILD] Configurables empty on ABI generation

### ISSUE THREAD

**Issue by TheHustler0** [FuelLabs/sway#6134]
### Related Component

compiler

### Problem you are trying to solve

`forc build` generates an abi with `configurables: []` when configurable fields are not used in the Sway contract.

Using latest versions:
```
Default host: x86_64-unknown-linux-gnu
fuelup home: /home/hustler/.fuelup

installed toolchains
--------------------
latest-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
testnet-x86_64-unknown-linux-gnu

active toolchain
----------------
latest-x86_64-unknown-linux-gnu (default)
  forc : 0.60.0
    - forc-client
      - forc-deploy : 0.60.0
      - forc-run : 0.60.0
    - forc-crypto : 0.60.0
    - forc-debug : 0.60.0
    - forc-doc : 0.60.0
    - forc-explore : 0.28.1
    - forc-fmt : 0.60.0
    - forc-lsp : 0.60.0
    - forc-tx : 0.60.0
    - forc-wallet : 0.7.1
  fuel-core : 0.26.0
  fuel-core-keygen : 0.26.0

fuels versions
--------------
forc : 0.62.0
forc-wallet : 0.62.0
```

### Solution you'd like

Might be interesting to warn developers on compile-time or literally block compiling until removed.

**Comment by IGI-111** [comment]
This is expected behavior. Unused constants are not part of the end result because configuring them would have no effect.

Unused configurables already produce "This declaration is never used" warnings.
