### ISSUE TITLE
Loops involving entry block are not properly handled. 

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#6148]
* Dominance frontier [analysis](https://github.com/FuelLabs/sway/blob/master/sway-ir/src/analysis/dominator.rs#L229) may panic if entry block has more than one in edge

* Infinite loops may occur in simplify_cfg while [chaining](https://github.com/FuelLabs/sway/blob/master/sway-ir/src/optimize/simplify_cfg.rs#L245) blocks

* mem2reg may incorrectly [optimize](https://github.com/FuelLabs/sway/blob/master/sway-ir/src/optimize/mem2reg.rs#L252) ir and produce code that executes to different results.

**Comment by ironcev** [comment]
Below are the sample scripts demonstrating the three issues. By the definition of the `entry` block, it cannot have any predecessors. We are currently not checking that invariant in the IR verifier. It is the lack of that check which actually causes the below three issues because they are based on an invalid IR that is not reported as such.  

```
//Issue 1: dominance frontier
script {
 fn main() -> () {
    entry():
    br block0()

    block0():
    br entry()

    block1():
    br entry()
  }
}

//Issue 2 : simplify-cfg
script {
  fn main() -> bool {
    entry():
    br entry()
}

// Issue 3: mem2reg
script {
  fn main(x: bool) -> u64 {
    local u64 S = const u64 3

    entry(x: bool):
    v0 = get_local ptr u64, S
    v1 = load v0
    cbr x, block0(x, v1), block2(x, v1)

    block0(x: bool, y: u64):
    v0 = get_local ptr u64, S
    v1 = const u64 1
    store v1 to v0
    br block1(x)

    block1(x: bool):
    z = const bool false
    br entry(z)         // <<<----- Branching back to `entry`.

    block2(x: bool, y: u64):
    ret u64 y
  }
}
```
