### ISSUE TITLE
out of bound read on clear for Vec and Bytes

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#6158]
`Vec` and `Bytes` both performs an out of bound read on clear. In the worst case this may lead to unexpected reverts. ([1](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/vec.sw#L423)) / ([2](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/bytes.sw#L421))

**Comment by vaivaswatha** [comment]
```
#[test]
    fn bytes_remove_oob_read() -> () {
      let mut a = Bytes::with_capacity(1);
      a.push(1);
      a.remove(0);
      ()
    }
    #[test]
    fn vec_remove_oob_read() -> () {
      let mut a = Vec::<u64>::with_capacity(2);
      a.push(1);
      a.push(2);
      a.remove(0);
      ()
    }
```
