### ISSUE TITLE
StorageVec improperly handles small values

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#6159]
StorageVec.load_vec / store_vec does not properly handle element types with size < 8 bytes. ([1](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/storage/storage_vec.sw#L823)) / ([2](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/storage/storage_vec.sw#L872))

**Comment by bitzoic** [comment]
Closed by https://github.com/FuelLabs/sway/pull/6166
