### ISSUE TITLE
width of constants doesn't match between fuel-vm, sway and spec

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#6161]
The uint width for MAX_INPUTS / MAX_WITNESS / MAX_MESSAGE_DATA_LENGTH / MAX_PREDICATE_LENGTH / MAX_PREDICATE_DATA_LENGTH  does not match between fuel-vm / sway / spec. There probably isn't any immediate impact due to the configurations being set within the range of the smallest used type, but we'd recommend unifying those to prevent future issues. ([1](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/inputs.sw#L123)) / ([2](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/inputs.sw#L314)) / ([3](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/inputs.sw#L342)) / ([4](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/inputs.sw#L438)) / ([5](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/inputs.sw#L540)). (vm [impl](https://github.com/FuelLabs/fuel-vm/blob/v0.49.0/fuel-tx/src/transaction/consensus_parameters.rs#L657))

**Comment by bitzoic** [comment]
Closed by https://github.com/FuelLabs/sway/pull/6108
