### ISSUE TITLE
Remove logic duplicatation between forc-client and sdk

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#6199]
We are already depending on sdk for some features, and for others we are re-implementing them from scratch creating two places to update for each change in fuel-core. We should make our best to re-use logic from sdk.

**Comment by sdankel** [comment]
@kayagokalp  I know you replaced some duplicate logic as part of https://github.com/FuelLabs/sway/pull/6250, is there more? What code specifically?

**Comment by kayagokalp** [comment]
Examples are everywhere we construct the transaction itself, rather than using the transaction builders from SDK. So it is intentionally wide and the issue is more like a tracking one rather than a specific task. 

Lately this got better as we transitioned deployment and run transactions to SDK owned builders especially with #6250 . I agree that we can close this for now and open individual parts we find later on separately
