### ISSUE TITLE
ABI Encoding data structures yields unexpected results

### ISSUE THREAD

**Issue by Mantas-M** [FuelLabs/sway#6217]
### Related Component

other

### Problem

When trying to encode the following data structures: u32, b256 and str, I would expect:
- The first value gets encoded in a plain packed way
 - The second value gets encoded in a plain packed way and is added to the previous encoding
 - The third value gets encoded with it's length and gets added to the previous encoding
 
 In practice, the following happens
 - The first value gets encoded with the length of the u32
 - The second value gets encoded in a plain way and is added to the previous encoding, and also adds it's length to the initial length of the encoding
 - The third value gets encoded with it's length and is added to the previous encoding and additionally also adds the length to the overall encoded bytes
 
 For example:
 ```
 let number: u32 = 1;
 let address: b256 = 0x0000000000000000000000002222222222222222222222222222222222222222;
 let suffix: str = "SOMETHING";
 
 
 let buffer = number.abi_encode(buffer); // Encodes "000000000000000400000001", expected "00000001"
 let buffer = address.abi_encode(buffer); // Encodes "0000000000000024000000010000000000000000000000002222222222222222222222222222222222222222", expected "000000010000000000000000000000002222222222222222222222222222222222222222"
 let buffer = suffix.abi_encode(buffer); // Encodes "00000000000000350000000100000000000000000000000022222222222222222222222222222222222222220000000000000009534f4d455448494e47", expected "0000000100000000000000000000000022222222222222222222222222222222222222220000000000000009534f4d455448494e47"
 ```
 
 Additionally, if I would try to remove the length encoding from the final value "00000000000000350000000100000000000000000000000022222222222222222222222222222222222222220000000000000009534f4d455448494e47" by cutting off the initial 8 bytes "0000000000000035" it does not seem to work as well
 
 ```
     let mut bytes = Bytes::from(buffer.as_raw_slice());
    bytes = bytes.split_at(8).1; // Should cut off the start 
```

Expected - "0000000100000000000000000000000022222222222222222222222222222222222222220000000000000009534f4d455448494e47"
Actual - "000000000000002d000000000000000022222222222222222222222222222222222222220000000000000009534f4d455448494e47"

A similar issue as the one presented above is faced when trying to remove the length encoding of the str.

### Steps

```
let number: u32 = 1;
let address: b256 = 0x0000000000000000000000002222222222222222222222222222222222222222;
let suffix: str = "SOMETHING";

let buffer = Buffer::new();
let buffer = origin.abi_encode(buffer);
let buffer = mailbox.abi_encode(buffer);
let buffer = suffix.abi_encode(buffer);

// General encoding issue
let bytes = Bytes::from(buffer.as_raw_slice());
log(bytes);

// Byte removal issue
let mut bytes = Bytes::from(buffer.as_raw_slice());
bytes = bytes.split_at(8).1; // Should cut off the start
log(bytes);

```

 

### Possible Solution(s)

The issue may have something to do with the code being defined in a library and run inside the forc test. 

Another component in the project is utilizing similar logic, is defined as contract logic and is run using a rust generated Sway testing harness and works as expected.

### Notes

The functionality is defined as a forc library and is being exectuted as a forc test.

### Installed components

```console
Encountered on both
  forc - Update available : 0.60.0 -> 0.61.2
  fuel-core - Update available : 0.26.0 -> 0.28.0
  fuel-core-keygen - Update available : 0.26.0 -> 0.28.0
fuelup - Up to date : 0.25.1

And

forc - Up to date : 0.61.2
  fuel-core - Up to date : 0.28.0
  fuel-core-keygen - Up to date : 0.28.0
fuelup - Up to date : 0.25.1
```

**Comment by xunilrj** [comment]
I think there is a misunderstanding here. The line `log(bytes)` will actually log the slice, that is why you are seeing the length at the beginning: `log(encoded_bytes)` is different from `log(some_primitive_datatype)`.

We have this test here (https://github.com/FuelLabs/sway/blob/master/sway-lib-core/src/codec.sw#L5075) that is doing something very similar to what you are trying and it is encoding the primitive data types correctly.

**Comment by Mantas-M** [comment]
@xunilrj Pretty sure that was the issue, at least it resolved it for me, thanks.
