### ISSUE TITLE
lost aseets

### ISSUE THREAD

**Issue by mariogramltd** [FuelLabs/sway#6241]
### Related Component

compiler

### Problem

all about the sway farm, signed in to the farm, planted seeds and harvested tomatoes from the farm to get coins, but at some point later, my whole balances all went to 0, no tomatoes, no coins, no plants and all_

### Steps

1. database to keep track of all users interactions so they can get along with their previous interactions, other than starting all over

### Notes

all going well, just the bug i noticed

### Installed components

```console
don't know what component and version
```

**Comment by kayagokalp** [comment]
This is not related to sway but it is about the sway farm: https://github.com/FuelLabs/sway-farm
