### ISSUE TITLE
forc build - Too many arguments error

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#6264]
### Related Component

compiler

### Problem

Error

```
thread 'main' panicked at sway-core/src/asm_generation/fuel/functions.rs:121:30:
Too many arguments, cannot handle.: Immediate12TooLarge { val: 4348, span: Span { src (ptr): 0x559144d90710, source_id: None, start: 0, end: 0, as_str(): "" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps

1. git clone https://github.com/FuelLabs/sway-applications
2. cd escrow
3. change fuel-toolchain.toml to forc 0.65.1
4. forc build

### Installed components

```console
forc 0.65.1
```

**Comment by sdankel** [comment]
Hi @SwayStar123 thanks for the report. There isn't yet a `v0.65.1` of forc - `0.63.0` is about to be released. 

I was able to repro this with `forc = "0.60.0"`, but it appears to be fixed with the current version `forc = "0.62.0"`. Feel free to reopen if this happens again with newer versions.
