### ISSUE TITLE
Implement subtraits and supertraits

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/sway#628]
Currently an implementation cannot depend on a another trait for the same type

so
```
impl ge for u64 {
    fn ge(self, other: Self) -> bool {
        self.gt(other) || self.eq(other)
    }
}
 ```
 
 will not work if eq and gt are implemented and defined in other traits, even if all for the same datatype. Allowing an implementation to require a trait so that it can reference functions implemented for that trait would allow for a lot better code organization

**Comment by sezna** [comment]
In Rust, this is accomplished via subtraits:
```rust
trait Eq: PartialEq + Ord {
...
}
```

We should follow the same model.

**Comment by otrho** [comment]
Note that the implementation of `Eq` in the Sway core lib should be updated to use supertraits as per Alex's example above when this issue is resolved.
