### ISSUE TITLE
Implement tuple access syntax via destructuring and indexing

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#632]

**Comment by emilyaherbert** [comment]
I think that this issue encompasses two different issues.

# 1 "if-lets" in general (#624)
```
let x = if let (a,b) = (1,2) {
  a
} else {
  0
};
```

# 2 tuple indexing:
```
let a = (0,1);
a.0
```

Is this what you had in mind @sezna ?

**Comment by sezna** [comment]
point 1 there isn’t exactly as intended. 

For this issue, tuple destructuring is like `let (a, b) = (1, 2);`. If lets are a bit different — they let you do this with enums. `if let Option::Some(x) = foo`. If lets are not necessary for tuple destructuring. 

Point 2 is what I meant though, yep!

**Comment by emilyaherbert** [comment]
Gotcha!
