### ISSUE TITLE
Forc contract calls feature

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/sway#635]
`forc` should have a new command to enable calling contracts straight from the CLI, something like this:

```
forc abi import <name> <path to json file>

forc call <abi name> <address or address name> <method name> <arg[n]> <network or node ID>
```

For instance,

```
forc abi import token token.abi.json

forc call token dai totalSupply
```

**Comment by adlerjohn** [comment]
`forc` is a developer tool, not a user tool. See how [Foundry](https://github.com/gakonst/foundry) split up their developer too (Forge) and user tool (Cast) into two separate binaries? This feature belongs in a separate user binary.
