### ISSUE TITLE
Forc node feature

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/sway#636]
`forc` should have a command to enable local node management, such as running local nodes and running operations on them. For instance:

```
# Running a Node
forc node start --local

        Fuel node started...
        
        Node w/ GraphQL Running at: http://localhost:3000/graphql
       
# List the Fuel nodes running      
forc node list

        Num       PID       Name
        [0]       647       fuel-core-plus

# Stop a Fuel node
forc node stop 0

```

**Comment by adlerjohn** [comment]
Node management is simply not necessary for developing contracts. `forc` is a developer tool, not a user tool. See how [Foundry](https://github.com/gakonst/foundry) split up their developer too (Forge) and user tool (Cast) into two separate binaries? This feature belongs in a separate user binary.

**Comment by digorithm** [comment]
Right, that makes sense. It would be good to keep track of all the ideas mentioned here https://github.com/FuelLabs/sway/issues/423 (which sounded like it would be extra `forc` features). 

Seems like we'll need to come up with a name for another binary/tool soon.
