### ISSUE TITLE
Return Path Analysis Can Be Bypassed

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#6369]
CS-FSSA-003

At the end of the semantic analysis, a return path analysis is performed to ensure that all paths that are
required to return a value do so. This analysis is performed on a return path graph generated for each
function. The function ensure_all_paths_reach_exit performs this check by traversing the graph
node by node and making sure that all end nodes with no neighbors reach the exit node or the return
type of the function is unit in which case the function does not return a value.

However, if the graph has a depth of more than 50, the return path analysis will always succeed. This is
because a fixed depth of 50 is used to limit the traversal of the graph.
The following code snippet shows how an invalid function can be compiled by bypassing the return path
analysis check :

```sway
script;
fn main(){
}
fn f() -> bool {
 if true {
 return true;
 } else {
 return false;
 };
 // Repeat the above block 50 times
 // Now anything can be returned here.
}
```
The absence of this check can lead the execution to undefined behavior.

**Comment by jjcnn** [comment]
I am unable to reproduce this error.

I have tried to compile the example program, and it correctly reports the following error:

```
          520 |     // Not a bool - should not be allowed
          521 |     return 42 
              |            ^^ Mismatched types.
          expected: bool
          found:    numeric.
          help: Return statement must return the declared function return type.
          522 | }
 ```

**Comment by jjcnn** [comment]
The test program I used can be found here: https://github.com/FuelLabs/sway/compare/master...jjcnn/no_limit_to_return_path_analysis

**Comment by jjcnn** [comment]
Ah, found the problem: The issue isn't that an incorrect type can be returned, but rather that it's possible to not return a value at all.
