### ISSUE TITLE
Forc manifest should forbid spaces and special characters in name and org

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#641]
Whitespace should be forbidden in the name and organization fields for the Forc manifest file. Specifically, the strictest of these rules should be enforced:

> The name must use only alphanumeric characters or - or _, and cannot be empty. Note that cargo new and cargo init impose some additional restrictions on the package name, such as enforcing that it is a valid Rust identifier and not a keyword. crates.io imposes even more restrictions, such as enforcing only ASCII characters, not a reserved name, not a special Windows name such as "nul", is not too long, etc.

([source](https://doc.rust-lang.org/cargo/reference/manifest.html#the-name-field))

**Comment by sezna** [comment]
https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs#L166

**Comment by sezna** [comment]
https://github.com/rust-lang/cargo/blob/master/src/cargo/util/restricted_names.rs

**Comment by eureka-cpu** [comment]
do we have a complete list of reserved keywords, and possible future keywords for Sway? also are there any here that shouldn’t be included? 

> "Self", "abstract", "as", "async", "await", "become", "box", "break", "const", "continue",
        "crate", "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if",
        "impl", "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv",
        "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true", "try",
        "type", "typeof", "unsafe", "unsized", "use", "virtual", "where", "while", "yield"

**Comment by sezna** [comment]
Of the ones you listed, I'd say the following are unnecessary:
1. `crate`. We don't call them crates, so I can't see how this would ever be needed.
2. `mod`. We don't use `mod` syntax -- we use `dep`. I don't see a reason we would need to change that.


To be in line with Rust, the rest are reasonable to anticipate that we might use them _some day_, and it is better to have the option to use them than to not have that option.

**Comment by adlerjohn** [comment]
`async` can probably go as well, as things kind of need to be synchronous.
