### ISSUE TITLE
Implement storage value access with storage syntax

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#645]
- [ ] impurity must be checked and verified by the compiler
- [ ] there should be a warning if a function is declared as impure but it doesn't need to be

**Comment by sezna** [comment]
We designed storage access to have initializer values:
```rust
storage {
   my_storage_val: TypeName = InitializerExpression;
}
```
Some axioms:
1. This is in anticipation of initialization being allowed within the transaction at contract-creation time. 
1. As far as I'm aware, we don't have any "contract-deploy-time" runtime in which we could evaluate these values and store them in storage. 
1. Omitting initializers is not an option due to lack of well-defined behavior on zeroed-out types.

The only way I can see of doing this, then, is inserting into the preamble (before the function selector) another initialization preamble. This initialization preamble would:

`PROGRAM_START`:

1. Check some bit `HAS_BEEN_INITIALIZED` that is set in storage to see if initialization has happened yet.
1. If initialization has not happened, jump to `INITIALIZATION_CODE_START` label. Otherwise, jump to `CONTRACT_FUNCTION_SELECTOR`

`INITIALIZATION_CODE_START`:

1. execute all initialization expressions.
1. assign the results of those expressions to their storage slots.
1. flip `HAS_BEEN_INITIALIZED` to true
1. jump to `CONTRACT_FUNCTION_SELECTOR`

`CONTRACT_FUNCTION_SELECTOR`:
1. do the function selection, etc., normal program from here on out.


I have a couple concerns. 

One, this is complex and opens us up to the state of "contract has been deployed, but not yet initialized". Theoretically, that's okay because the first comparison/jump statement should handle initialization. However, it is brittle, and one small compiler/VM/whatever bug could lead to undefined/unanticipated behavior in contract calls. Complexity necessarily opens up risk.

Two, this introduces a bit of overhead to the beginning of every contract call. I'm not _as_ concerned about this, but we do need to load `HAS_BEEN_INITIALIZED` and do a `jnei` each time.

**Comment by adlerjohn** [comment]
Contract storage can be implement in the VM asap to avoid having to write code that will be thrown away later. Proposed spec change here: https://github.com/FuelLabs/fuel-specs/pull/276

Note that `InitializerExpression` should probably be constant-evaluatable for now (possibly forever), since there's no notion of runtime initcode.
