### ISSUE TITLE
Log decoding fails with `log id missing`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#6468]
```sway
#[test]
fn math_u16_overflow_mul() {
    disable_panic_on_overflow();
    
    let a = (u16::max() / 2 ) + 1;
    let b = a * 2;

    log(b);
    assert(b == 0_u16)
}

#[test]
fn math_u32_overflow_mul() {
    disable_panic_on_overflow();
    
    let a = (u32::max() / 2 ) + 1;
    let b = a * 2;
    
    log(b);
    assert(b == 0_u32)
}
```

This code fails with `error: log id is missing` when run with `forc test --logs --decode`.

Reported by @SwayStar123

**Comment by sdankel** [comment]
This repros in the core library tests as well: 

```
cd sway-lib-core/src && forc test ok_abi_encoding --logs --decode
```

**Comment by sdankel** [comment]
It looks like this is a problem in libraries because logged_types is always [None](https://github.com/FuelLabs/sway/blob/507870a386103d7a72035f44da5f4dcd35fbca6c/sway-core/src/abi_generation/fuel_abi.rs#L191).
