### ISSUE TITLE
Inconsistent ABI metadata types with aliased types

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/sway#6488]
### Summary

When defining [alias types](https://docs.fuel.network/docs/sway/advanced/advanced_types/) in Sway, we obtain inconsistent results in the generated ABI between inline and alias types.

Consider the following contract:

```sw
type AliasedTuple = (u64, u64);

abi MyContract {
    fn tuple(arg1: (u64, u64)); // Inline
    fn aliased tuple(arg1: AliasedTuple); // Alias
}
```

This came from the following [forum post](https://forum.fuel.network/t/typescript-typegen-doesnt-support-some-types/6546/7).

### Expected

We expect both metadata types to be equal, with a type of `(_, _)`.

### Actual

We actual get two distinct metadata types, with types as follows:
- Inline: `(_, _)`
- Aliased: `(u64, u64)`

### Reproduction

A minimal reproduction can be found [here](https://github.com/petertonysmith94/sway-type-aliases).

**Comment by IGI-111** [comment]
These types are valid, just don't contain the same amount of information, I don't see a bug here.

If you want to compare them for equality or something, you have to use the concrete types. The metadata is produced with best effort from the compiler and not guaranteed to be this consistent.

**Comment by IGI-111** [comment]
I suppose there is an issue in that this is producing types that the SDK isn't used to handling. But I'm not sure if we should make the alias types give you less direct information or have the SDK handle the more complete ones.

**Comment by petertonysmith94** [comment]
From my understanding of the [spec](https://github.com/FuelLabs/fuel-specs/blob/master/src/abi/json-abi-format.md#tuple), the metadata type for a tuple would be `(_, _)` and the concrete type would `(u64, u64)`. I would have thought a type alias would follow the same principles.

**Comment by IGI-111** [comment]
Good point, the spec actually enforces this. We should fix this then.
