### ISSUE TITLE
forc-crypto: Vanity Address generation

### ISSUE THREAD

**Issue by zees-dev** [FuelLabs/sway#6664]
## Related Component

another forc plugin

## Problem you are trying to solve

Common wallet CLI tools such as [`cast`](https://book.getfoundry.sh/reference/cast/cast-wallet-vanity) and [`solana-keygen`](https://www.quicknode.com/guides/solana-development/getting-started/how-to-create-a-custom-vanity-wallet-address-using-solana-cli#using-solana-keygen) support vanity address/pubkey generation given desired prefix and/or suffix.

The forc tooling should also support such a feature such that users can bruteforce (at the expense of their own compute) vanity addresses for fuel network.

## Requirements

1. Must be able to specify a prefix
2. Must be able to specify a suffix
3. The mnemonic phrase should be displayed in plaintext (not hash or ciphertext) to stdout
4. The private key should be displayed in plaintext to stdout
5. The vanity constraints apply to the final checksummed address
6. Use the CLI subcommand `forc-crypto vanity`

## Constraints

- Either the prefix or suffix must be provided
- The prefix and suffix must be valid hexadecimal strings

## Future improvements or stretch goals

1. `--json` flag can be provided, this will display a JSON object with the following structure:

```json
{
    "accounts": [
        {
            "address": "<vanity_address>",
            "private_key": "<vanity_private_key>",
            "mnemonic": "<vanity_mnemonic>"
        }
    ]
}
```

This is useful to simply output stdout to json file.

2. Support for regular expression that can be matched by the generated address

**Comment by kayagokalp** [comment]
Hey @zees-dev I think we should close this issue as #6661 is merged. Feel free to re-open if I am missing something :) 

Maybe we can open a follow-up issue in `forc-wallet` to discuss further incorporating this feature into there, that is if we still plan to do so, (instead of this issue which seems solved to me!)
