### ISSUE TITLE
Visibility check for modules is broken

### ISSUE THREAD

**Issue by jjcnn** [FuelLabs/sway#6673]
The visibility of modules is currently checked incorrectly.

The following module structure illustrates the problem:

```
               root module (public by default)
                          |
                          |
                      module b  (private)
                    /         \ 
                   /           \ 
       module c (public)     module d 
```

Currently any item declared in `c` is invisible to `d`, because the visibility of `b` is private. This is incorrect, since `d` is behind the same visibility "wall" as `c`, namely the privacy of `b`.

My understanding is that items from `c` should also be visible in `b`, but I'm not 100% sure of that. We should check what Rust does here.

**Comment by abdegenius** [comment]
Hey good day @jjcnn  can i be assign this issue please? thank you!

**Comment by maxtalantsev** [comment]
cool
