### ISSUE TITLE
`forc build` crashes when compiling and exits with `Killed`  

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/sway#678]
Was trying to compile my most recent [BentoBox Build](https://github.com/ControlCplusControlV/Sushi-Sway) but upon attempting to compile with forc build the compile process exits with Killed instead of a byte size or an error when compiling

```
controlC@my-pc:~Sushi-Sway$ forc build
  Compiled library "core".
  Compiled library "core".
warning
 --> FuelLabs-sway-lib-std-15bed83/src/result.sw:0:5
  |
...
3 |     Ok: T,
  |     -- Enum variant Ok is never constructed.
  |
warning
 --> FuelLabs-sway-lib-std-15bed83/src/result.sw:0:5
  |
...
4 |     Err: E,
  |     --- Enum variant Err is never constructed.
  |
  Compiled library "lib-std" with 2 warnings.
Killed
```
I am not cancelling the process with control c or any other keystrokes, so I am not sure why it is resulting in a Killed message rather than any other error message

**Comment by ControlCplusControlV** [comment]
So I have been able to fix this error with some changes to my code, by returning a value (which was specified in the ABI but I wasn't doing in the function) and I didn't specify the type for a couple of my variable declarations (startingBal and updatedBal)

**Comment by adlerjohn** [comment]
@ControlCplusControlV can you link to an exact commit that can repro?

**Comment by ControlCplusControlV** [comment]
https://github.com/ControlCplusControlV/Sushi-Sway/tree/3e509900b30ab364d3aa34555be91bdb376e57fa
