### ISSUE TITLE
Source mapping

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#70]
## Problem

We need source mapping (going between Sway code and bytecode) to do debugging properly (e.g. set breakpoint at a certain line, continue up to a certain line), in addition to code coverage.

## Proposal

Add support for dumping source mapping to a defined file. It must be a file in order to be consumable easily without the need for inter-process communication.

- [x] Configurable file via manifest (default might be `build/source_mapping`)
- [x] Define source mapping format for consumption by other tools
- [x] Dump source mapping to file (#656)

**Comment by vaivaswatha** [comment]
Can we close this (by #5521) @IGI-111 ?

**Comment by IGI-111** [comment]
Yep.
