### ISSUE TITLE
Add `forc --list`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#702]
Lists commands, similar to `cargo --list`

**Comment by adlerjohn** [comment]
@ControlCplusControlV has requested to work on this, ref: https://github.com/FuelLabs/sway/issues/482#issuecomment-1021603180

**Comment by adlerjohn** [comment]
This is no longer necessary to implementation completions, though it may be independently useful.

**Comment by mitchmindtree** [comment]
I think this would still be quite useful for downstream tooling. E.g. the `forc-documenter` could use this to generate all the modules (rather than having to list them in the index.md).

We should also consider including available plugin commands in the output (I think `cargo --list` does this) so that downstream tools can process these altogether. Perhaps a flag could be provided for omitting plugins from the output.

**Comment by ra0x3** [comment]
- Gonna unassign myself (for now) due to this largely being covered in https://github.com/FuelLabs/sway/issues/1215. 
- Of course we can always come back and complete this if the need is there

**Comment by mitchmindtree** [comment]
Labelled as low-priority as `forc-documenter` will use distinct `forc --help` and `forc plugins` commands for documenting each anyway, and this isn't really blocking anything, but will still be useful command to have in the future.

**Comment by bingcicle** [comment]
Would it be a good time to prioritise this issue perhaps? I think as we start to move plugins into their own repos (#2608, #2609 ) we might get more questions of "why is XYZ feature not listed under `forc help`?", which we are already starting to get now, since `forc deploy` and `forc run` have been moved into the `forc-client` plugin. We also have [forc-wallet](https://github.com/FuelLabs/forc-wallet) which already does not show up as a command in core forc.

cargo prompts you to 'see all commands with --list', which I think we can follow as a guide here perhaps.

![Screenshot 2022-09-08 at 5 24 34 PM](https://user-images.githubusercontent.com/25565268/189086299-55286bad-1995-4b0a-a987-524744620646.png)

**Comment by mitchmindtree** [comment]
@bingcicle we do have the `forc plugins` command, e.g.

```
[mindtree@minddesk:~/programming/nix/fuel]$ forc plugins
Installed Plugins:
forc-deploy
forc-run
forc-fmt
forc-explore
forc-wallet
forc-lsp

[mindtree@minddesk:~/programming/nix/fuel]$ forc plugins --describe
Installed Plugins:
  forc-deploy           No description found for this plugin.
  forc-run              Run script project. Crafts a script transaction then sends it to a running node
  forc-fmt              Forc plugin for running the Sway code formatter.
  forc-explore          Forc plugin for running the Fuel Block Explorer.
  forc-wallet           A forc plugin for generating or importing wallets using BIP39 phrases.
  forc-lsp              Forc plugin for the Sway LSP (Language Server Protocol) implementation.

[mindtree@minddesk:~/programming/nix/fuel]$ forc plugins --paths --describe
Installed Plugins:
  /nix/store/x7zxpmqp10mgh5jcx22v4l7naxl3jwsd-fuel-latest/bin/forc-deploy               No description found for this plugin.
  /nix/store/x7zxpmqp10mgh5jcx22v4l7naxl3jwsd-fuel-latest/bin/forc-run          Run script project. Crafts a script transaction then sends it to a running node
  /nix/store/x7zxpmqp10mgh5jcx22v4l7naxl3jwsd-fuel-latest/bin/forc-fmt          Forc plugin for running the Sway code formatter.
  /nix/store/x7zxpmqp10mgh5jcx22v4l7naxl3jwsd-fuel-latest/bin/forc-explore              Forc plugin for running the Fuel Block Explorer.
  /nix/store/x7zxpmqp10mgh5jcx22v4l7naxl3jwsd-fuel-latest/bin/forc-wallet               A forc plugin for generating or importing wallets using BIP39 phrases.
  /nix/store/x7zxpmqp10mgh5jcx22v4l7naxl3jwsd-fuel-latest/bin/forc-lsp          Forc plugin for the Sway LSP (Language Server Protocol) implementation.
```

It is a little minimal and janky, but perhaps this is enough to get by for now? That said, if you'd like to improve this as a part of your fuelup plugin standardization work I think that makes sense. In retrospect, `plugins` probably isn't the best name for this command as it lists the plugin *commands*, not the plugins themselves. 

If we do go with `list` instead, I think it could be worth separating those commands provided by plugins from those that are native to forc, as I think `cargo --list` can be a little confusing as it's unclear which commands are native and which are provided by plugins.

**Comment by bingcicle** [comment]
> if you'd like to improve this as a part of your fuelup plugin standardization work

Nope, this doesn't affect fuelup standardization work and I don't think it's some urgent work, it was just something that came up in my mind. It's true that `forc plugins` exist but I think it isn't immediately obvious that `forc deploy` as a command comes as part of `forc-client` which is a plugin, and that people expect `deploy` to show up as a command when they do `forc help`.

But yeah, you're right, we can let people know that those commands are plugins and they can see them using the `forc plugins` command.

**Comment by adlerjohn** [comment]
This issue was initially meant as a stepping stone to #482, which was implemented by other means. Can this issue be closed?

**Comment by bingcicle** [comment]
Sounds good, I revived the issue again with my comment above after noticing some devs running into the `no such subcommands: 'deploy'` error message, especially after the deploy and run commands were extracted out of `forc`. We can always open this back if up if we think a feature like this is useful.
