### ISSUE TITLE
Update the Sway test suite to use `sway-lib-core` `v0.1.0`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#706]
There have been breaking changes to the api of the `Ord` trait. It no longer contains an `eq` method. 
`Eq` is now a distinct trait.
The test-program manifests should be updated to use the newer version of `lib-core`, and thetests should be updated to use the new api.

**Comment by mitchmindtree** [comment]
Closing in favour of #875 now that #825 has landed
