### ISSUE TITLE
Nesting C-style comments leads to a parsing error

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#710]
The following code fails to compile:
```
script;

/*
comment 
/* nested comment */
comment
*/

fn main() {
}
```
Error message:
```
error
 --> my-fuel-project/src/main.sw:0:1
  |
...
5 | comment
  | ^ Error parsing input: expected one of [EOI, include_keyword, non_var_decl, use_statement]
  |
  Aborting due to 1 error.
Error: "Failed to compile my-fuel-project"
```
This is not very important but I assume that's unexpected behavior.

**Comment by adlerjohn** [comment]
Isn't that expected to not parse, since the code after removing comments is

```rust
script;

comment
*/

fn main() {
}
```

?

**Comment by mohammadfawaz** [comment]
Here's the same code in Rust: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e0fc0565b6c9748691173a56dea80b9e

**Comment by mohammadfawaz** [comment]
The idea is that whatever is inside the top level `/* ... */` should be commented regardless of what it is.

**Comment by mohammadfawaz** [comment]
Actually, it would be interesting to see if our VSCode plugin shows that everything is properly commented. I should try that.

**Comment by mohammadfawaz** [comment]
No longer an issue with the new parser.
