### ISSUE TITLE
Can't return a Result from 2 functions

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#716]
I initially noticed this buggy behaviour when trying to return the `Result` type from 2 different functions in the auth module.
I've managed to reproduce it in the code below, using a `Rezult` type to avoid the need to import anything.

```
library result_bug;

pub enum Rezult<T, E> {
    Ok: T,
    Err: E,
}

pub enum DumbError {
    Error: (),
}

pub fn func_a() -> Rezult<u8, DumbError> {
    if 1 == 2 {
        Rezult::Err(DumbError::Error)
    } else {
        Rezult::Ok(1u8)
    }
}

pub fn func_b() -> Rezult<bool, DumbError> {
   if 1 == 2 {
        Rezult::Err(DumbError::Error)
    } else {
        Rezult::Ok(true)
    }
}

```

The issue here is that `func_b`'s return type is not "seen", or is overshadowed by `func_a`'s return type (here I mean the inner `Ok` value of the Rezult. Trying to compile the example gives this error:
```
❯ forc build
  Compiled library "core".
error
  --> sway-lib-std/src/result_bug.sw:5:20
   |
 0 | library result_bug;
 1 |
 2 | pub enum Rezult<T, E> {
 3 |     Ok: T,
...
25 |     } else {
26 |         Rezult::Ok(true)
   |                    ^^^^ Mismatched types.
expected: u8
found:    bool.

   |
  Aborting due to 1 error.
Error: "Failed to compile lib-std"
```

**Comment by nfurfaro** [comment]
Adding some comments from Slack here for completeness:
>Toby Hutton 
OK, looks like the type checker is too strict and expects the exact same type/variant from all return paths.

>Alex Hansen
Looks like it isn't monomorphizing there. What is supposed to happen is it copies the type definition and fills in the "blanks", i.e. the type ids which are generic. If a single type id is not properly cloned, though, it can "taint" the original type definition.
armchair diagnosis is a failed/forgotten call to monomorphize somewhere, likely in function return types

**Comment by nfurfaro** [comment]
@sezna I see here the definition for monomorphize: https://github.com/FuelLabs/sway/blob/3f475fcde7c719f504f8a6676574181d82cf245f/sway-core/src/semantic_analysis/ast_node/declaration/function.rs#L292

but I'm not sure where it is being called (or in the case of `return_type`, not called...)

**Comment by sezna** [comment]
Every type has a `TypeId` in the type engine. When a generic is defined, it also has type ids. Consider the following example:
```rust
Result<T, E> {
 Ok: T,
 Err: E,
}
```

There are two inner types here, each with a `TypeId`. For the sake of example, let's use `T = TypeId(1)` and `E = TypeId(2)`.

When a function calls this with instantiated types, e.g.
```rust
fn foo() -> Result<u32, ErrorType> { ... }
```

The type engine resolves `TypeId(1)`  to `u32` and `TypeId(2)` to `ErrorType`. To monomorphize, what we _actually_ want is to first _copy_ the type definition of `Result`, such that it has fresh `TypeId`s. Then, we can resolve those types without impacting the original definition, which we want to remain generic.

This happens by initially calling `monomorphize` which then calls `copy_types` on all relevant type ids.

**Comment by mohammadfawaz** [comment]
Also happens with function parameters. The code below does not compile due to the same reason.
```rs
script;

struct Foo<T> {
    foo: T,
}

fn func_a(a: Foo<u8>) -> u8 {
  a.foo
}

fn func_b(b: Foo<bool>) -> bool {
  b.foo
}

fn main() {
}
```
