### ISSUE TITLE
Document the use of the `dep` keyword in the Sway book

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#721]
In the [`Libraries` section ](https://fuellabs.github.io/sway/latest/sway-on-chain/libraries.html), it would be nice to document how to use the `dep` keyword to include a library file. Also, how to include a library file in `Forc.toml`, though I think this is mentioned somewhere else.

Also, we can probably now remove this setence:
      "Note that multiple imports are not yet supported: https://github.com/FuelLabs/sway/issues/563"
from the section on Libraries since the issue has been closed.

**Comment by ControlCplusControlV** [comment]
I can add this, which section do you think would be the most appropriate?

**Comment by adlerjohn** [comment]
Maybe the libraries page for now? https://github.com/FuelLabs/sway/blob/11d4f534088e9272af1399cc8a0fe417f56af5a1/docs/src/sway-on-chain/libraries.md

**Comment by ControlCplusControlV** [comment]
Pushed PR #735 which should hopefully fix this
