### ISSUE TITLE
`forc fmt` doesn't format arrays very well.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#726]
Here's what it did to a recent PR of mine:
```diff
diff --git a/src/b512.sw b/src/b512.sw
index 2bcf573..ff5f664 100644
--- a/src/b512.sw
+++ b/src/b512.sw
@@ -4,7 +4,8 @@ library b512;
 /// Stores two b256s in contiguous memory.
 /// Guaranteed to be contiguous for use with ec-recover: std::ecr::ec_recover().
 pub struct B512 {
-    bytes: [b256; 2],
+    bytes: [b256;
+    2],
 }

 // @todo use generic form when possible
@@ -19,7 +20,8 @@ pub trait From {
 impl From for B512 {
     fn from(h: b256, l: b256) -> B512 {
         B512 {
-            bytes: [h, l],
+            bytes: [h,
+            l],
         }
     }
 }
@@ -30,7 +32,7 @@ impl B512 {
     fn new() -> B512 {
         B512 {
             bytes: [0x0000000000000000000000000000000000000000000000000000000000000000,
-                    0x0000000000000000000000000000000000000000000000000000000000000000],
+            0x0000000000000000000000000000000000000000000000000000000000000000],
         }
     }
 }
```

**Comment by eureka-cpu** [comment]
@leviathanbeak I just made a draft #1054  for this, but I'm running into the `+/+` symbol and I'm wondering if you have an insight on how to get around it? Here's a snippet for example: `r"library b512;
    
    pub struct B512 {
        bytes: [b256; 2],+/+
    }
    impl B512 {
        fn new() -> B512 {
            B512 {
                bytes: [0x0000000000000000000000000000000000000000000000000000000000000000,+/+ 0x0000000000000000000000000000000000000000000000000000000000000000],
            }
        }
    }";`

**Comment by leviathanbeak** [comment]
@eureka-cpu check this file: https://github.com/FuelLabs/sway/blob/master/sway-fmt/src/constants.rs
that "+/+" is added in the first pass,

from what I see here:
https://github.com/FuelLabs/sway/blob/master/sway-fmt/src/code_builder.rs#L134

"," - comma, is considered a line breaker so it creates a newline,
one thing you could do is to add a flag `is_array` (maybe a bit more generic name if some other things behave similarly)
and then not break into newline here
https://github.com/FuelLabs/sway/blob/master/sway-fmt/src/code_builder.rs#L137

you could also add the logic to check the length of the current CodeLine, and if it's above 60 or whatever then actually go into newline.

`is_array()` could also be part of the CodeLine
just like `is_string()` is
https://github.com/FuelLabs/sway/blob/master/sway-fmt/src/code_line.rs#L45

just in this case maybe something more generic `is_collection()` would be more appropriate
