### ISSUE TITLE
Unhelpful error message when you forget the `self` inside a `fn` inside an `impl`.

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#755]
Given this code:

```rust
script;

struct Checker {}

impl Checker {
    fn two_of_the_same<T>(a: T, b: T) -> T {
        b
    }
}

fn main() {
    let checker = Checker {};
    let foo = checker.two_of_the_same(1, 2);
}
```

The compiler gives you back this error message, which I feel isn't very helpful for figuring out what the issue is:

<img width="980" alt="Screen Shot 2022-02-07 at 7 35 23 PM" src="https://user-images.githubusercontent.com/17410721/152901451-a4786100-375a-419b-861e-a863d27c5a6a.png">

**Comment by mohammadfawaz** [comment]
@tritao this seems related to the work that you've been doing recently. Do you think this is fixed now?

**Comment by tritao** [comment]
With latest master, this code now outputs:

```rust
error
  --> main.sw:13:15
   |
11 | 
12 |     let checker = Checker {};
13 |     let foo = checker.two_of_the_same(1, 2);
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot call associated function "two_of_the_same" as a method. Use associated function syntax instead.
14 | }
   |
____

  Aborting due to 1 error.
```

Which I think is definitely an improvement over before.

Can this be closed now @emilyaherbert?

**Comment by emilyaherbert** [comment]
Yep!
