### ISSUE TITLE
Generate ABI json file when running forc build

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#764]
After running `forc build` users then need to run a separate command such as `forc-json-abi -o my_contract_abi.json` in order to have a valid ABI to feed into tests. 

It would be nice if running `forc build` also generated this file for you. 

Perhaps we could have the file default to the same name as the project, eg `my_project_abi.json` but also allow for another flag to be passed when building to specify a custom name for the abi file. eg `forc build --json-abi unique_name_abi`

**Comment by mitchmindtree** [comment]
> Perhaps we could have the file default to the same name as the project, eg my_project_abi.json

I haven't tested any multi-contract projects yet, but I think what we might want is to generate one ABI `.json` file per contract? In that case, we could name each generated file after each contract.

Before any of this though, we might want to work out a standard location for `forc`'s build artifacts in general (something equivalent to rust's `target` directory). I might open a dedicated issue for this if we don't have one already.

**Comment by JoshuaBatty** [comment]
> I haven't tested any multi-contract projects yet, but I think what we might want is to generate one ABI `.json` file per contract? In that case, we could name each generated file after each contract.

True, that makes sense and simplifies everything from the end users point of view as well. 

> Before any of this though, we might want to work out a standard location for `forc`'s build artifacts in general (something equivalent to rust's target directory). I might open a dedicated issue for this if we don't have one already.

Yeah that sounds good. Spamming the root directory with generated `.json` files doesn't sound like a fun time.

**Comment by mitchmindtree** [comment]
> I haven't tested any multi-contract projects yet...

Ah just reading through [Program Types](https://fuellabs.github.io/sway/latest/sway-on-chain/program_types.html#program-types) in the sway book now and it mentions

> A project can have many libraries within it, but only one contract, script, or predicate.

So it looks like there can be only one per forc project anyways! Unless we end up with something similar to Rust `[workspace]`s one day that is
