### ISSUE TITLE
Implement "or" match patterns in match expressions.

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#769]
The "or" pattern is the one shown below:

```rust
let x = 1;
match x {
  0 | 1 => true,
  _ => false
}
```

**Comment by mohammadfawaz** [comment]
@emilyaherbert can this be implemented using a simple de-sugaring of
```
0 | 1 => true,
```
into
```
0 => true,
1 => true,
```
?
Or is there a better way?

**Comment by emilyaherbert** [comment]
> can this be implemented using a simple de-sugaring

Short answer: Yep!

Long answer for bookkeeping: Yes we can can and probably should do this in the short term. But in the long term we will want to add this feature in a more official capacity. This is because de-sugaring in this position may interact with other features in a non-favorable way---e.g. macro expansion inside of the `0 | 1 => { .. },` match arm. Also a note, we currently have [support for or-patterns inside of the match expression exhaustivity checker](https://github.com/FuelLabs/sway/blob/f6616ed2b276e3ed9aeda4d5933115afd9786f4d/sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs#L110) just by how that algorithm is implemented, although exposing a "non-desugared or-pattern" to users in such a way as to hit that code path, would be considered untested.
