### ISSUE TITLE
Compute Forc home directory in only one place

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#778]
#674 uses manually computed home directory paths. The Forc home directory (default `$HOME/.forc/`) should be a thing that's computed/set once, and usable everywhere in the codebase.

**Comment by mitchmindtree** [comment]
#674 uses `~/.fuel`, while @adlerjohn your suggestion above uses `~/.forc`.

I can see how `.fuel` makes sense in that its related to the Fuel VM, however I think there's a strong case for using `.forc` in that `explorer` is a part of the `forc` tooling and we already use `.forc` for checking out dependencies.

@alex-matthe what are your thoughts on having the current `~/.fuel/explorer` directory moved to `~/.forc/explorer`?

I'm thinking I'll tackle this soon, but just wanted to get a consensus on the directory location first.
