### ISSUE TITLE
A semicolon is always expected at the end of a `if/else` block

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#784]
The following fails to compile:
```rust
script;

fn foo() -> bool {
    let mut b = false;
    if true {
        b = true;
    }
    b
}

fn main() {}
```
because a semicolon is expected at the end of the `if` code block. I assume the reason for that is that `if` is an expression. However, Rust allows the above to compile so this is slightly an unexpected behaviour.

**Comment by otrho** [comment]
See #242 too.

**Comment by mohammadfawaz** [comment]
I should learn to search through open issues before openning new ones! I will close this in favor of https://github.com/FuelLabs/sway/issues/252 (which is referenced from https://github.com/FuelLabs/sway/issues/242)

**Comment by adlerjohn** [comment]
Has it actually been? The documentation hasn't been updated.

**Comment by mohammadfawaz** [comment]
I'm updating the docs right now.
