### ISSUE TITLE
Fuel package manager/compiler/all-in-one tool requirements

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#8]
We can use this issue to track requirements for the package manager/workflow tool.

Writing code:
1. Compiler
1. Search libraries from our registry and
   1. Dependency management (installing dependencies locally, managing resolving SemVer compatibility)
1. Search on-chain deployed libraries
1. Generate docs -- lower priority

Testing
1. Fork test chain to local
2. Run unit/integration tests
3. Debugger

Deployment
1. Deploy libraries to our registry
1. Deploy to test chain
1. Deploy to main chain
1. Yank a previous deployment (preventing new usages)
1. Add audit signatures to a library

**Comment by adlerjohn** [comment]
I think this issue has mostly run its course and any missing features are tracked elsewhere.
