### ISSUE TITLE
Functional issue with a while loop that has a dynamic trip count

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#800]
The following code doesn't seem functional (i.e. the `assert` fails). However, when I replace `trip_count` with `10` directly in the `while` loop condition, the `assert` passes. I imagine there is some issue affecting `while` loops with dynamic trip counts (though 10 should really be constant-propagated here and the loop should not really have a dynamic trip count, but that's a missed optimization that I'm sure we're going to fix when the IR is fully ready).
```rust
script;
use std::chain::*;
use core::ops::*;

fn main() {
    let mut b = 0;
    let trip_count = 10;
    while b < trip_count {
        b = b + 1;
    }
    assert(b == 10);
}
```

**Comment by otrho** [comment]
Right, I thought I'd reproduce to see what `b` actually is in this case.  And it's `1`, which is weird.  It definitely is `10` if you use a constant instead of variable for `trip_count` (e.g., `while b < 10 { ... }`).

**Comment by mohammadfawaz** [comment]
I haven't looked closely at the intermediate assembly, but that would probably be a good place to start.
