### ISSUE TITLE
Running forc fmt adds "--" chars before use keyword

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway#811]
Here's a short scree recording demoing what happens when I run `forc fmt`:

https://user-images.githubusercontent.com/17053076/154551876-43a961b7-1f97-4059-954c-70cf90af95d1.mov

**Comment by adlerjohn** [comment]
This should have been fixed with #684. Are you using the latest release or `master` @nfurfaro?

**Comment by nfurfaro** [comment]
@adlerjohn ahh, ok. I'm on the latest release. Closing
