### ISSUE TITLE
Pipeline check to ensure that the branch can build the latest sway standard library

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#813]
We should add some sort of pipeline stage that would have caught that building the latest standard library returned a non-zero exit code with `forc`.  #812 for details.

**Comment by mohammadfawaz** [comment]
Is this is still an issue given that we have std-lib tests running in CI now?

**Comment by adlerjohn** [comment]
I don't think so, no.

**Comment by mohammadfawaz** [comment]
Closing then.
