### ISSUE TITLE
Can't import two libraries that declare the same trait

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#819]
Code:

```rust
script;

use std::address::*;
use std::contract_id::*;

fn main() {
}
```

Output:

```console
error
  --> FuelLabs-sway-lib-std-8df8829/src/contract_id.sw:10:11
   |
 8 | 
 9 | // @todo make this generic when possible
10 | pub trait From {
   |           ^^^^ The name "From" imported through `*` shadows another symbol with the same name.
11 |     fn from(b: b256) -> Self;
12 | } {
   |
  Aborting due to 1 error.
```

Maybe not a bug with the compiler, but with the libraries???

**Comment by mohammadfawaz** [comment]
What is the desired behavior here? What if the two traits have different interfaces? Do we want this to work only if the traits are defined in the exact same way?

**Comment by adlerjohn** [comment]
I'm not sure if the desired behavior is to be able to star-import both `std::address` and `std::contract_id`. Maybe, maybe not? I don't inherently mind not being able to star-import from the standard library, but so far that's how we've been doing it.

**Comment by mohammadfawaz** [comment]
Shouldn't the trait `From` be only defind once in a common `utils` library that is used by both `address.sw` and `contract_id.sw`? If we do that, then the error should not really show up (I don't know if it will still show up or not, but it really shouldn't).

**Comment by adlerjohn** [comment]
cc @sezna for how this should be done

**Comment by sezna** [comment]
> Shouldn't the trait From be only defind once in a common utils library that is imported by both address.sw and contract_id.sw? If we do that, then the error should not really show up (I don't know if it will still show up or not, but it really shouldn't).

This is how we should define `From`, but the bigger issue of traits with the same name could remain.

Rust considers this an issue and throws an error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3559e21f3dc2002d6048025e05661423

**Comment by adlerjohn** [comment]
Okay, so this is an issue with the standard library rather than the compiler?

**Comment by sezna** [comment]
I'd say so. And I think our error message in this case is pretty good, actually.

**Comment by mohammadfawaz** [comment]
Agreed. Many confusing cases can arise when the same symbol is defined (or imported) multiple times in the same scope. We explicitly banned this here https://github.com/FuelLabs/sway/pull/739 for all types of imports and even when aliases are used 
(e.g. this is bad and we rightfully error out on it:
```
use ::bar::Bar1 as Bar2;
use ::bar::Bar2;
```
)
