### ISSUE TITLE
Function bodies not monormophized

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#827]
In particular cases, referencing a generic type produces an error. For example, this bit of code https://github.com/FuelLabs/sway/blob/cb9dd8bf92286dd1f6a6c8f018e78c78146c57d8/test/src/e2e_vm_tests/test_programs/size_of/src/main.sw#L28 should be able to find the size of the generic, but instead it gives an error.

I did some preliminary debugging and found something that may be related. If you have Sway like this:

```rust
fn the_same<T>(elem: T) -> T {
    let x: T = elem;
    x
}
```

Then inside of code gen for variable declarations, if you add a call to `println!("{:?}", crate::type_engine::look_up_type_id(var_decl.type_ascription);` inside of this function https://github.com/FuelLabs/sway/blob/323b4e17f7b32cd9709e1a5f29cb99e2da4e0171/sway-core/src/asm_generation/declaration/var_decl.rs#L10, you will see that the result is an `UnknownGeneric` which should not be the case.

**Comment by otrho** [comment]
I'm seeing `UnknownGeneric` pop up in the IR, which I don't think should be a thing, post- type checking monomorphisation.

**Comment by mohammadfawaz** [comment]
I wonder if my change https://github.com/FuelLabs/sway/pull/736 is related here - I can if this was an issue before.

**Comment by sezna** [comment]
I'll provide some clarity here -- I feel some responsibility as the generics system is perhaps not as well documented as it could be. Sorry about that! 

`UnknownGeneric` is a generic that has not yet been monomorphized. @emilyaherbert , in your code example, the compiler would have no way to know what `T` is, so it is unknown. What behavior would you be expecting? For example, the below code _does_ compile and work, because the type annotation `::<u64>` provides enough information to know the type of `T`:

```rust
script;
fn main() {
  let x = size_of::<u64>();
  let y = test::<u64>(42u64);
  let z: u64 = test(42u64);
}
fn size_of<T>() -> u64 {
  5u64
}
// another example
fn test<T>(x: T) -> T {
  let a: T = x;
  a
}
```

@otrho: As for it popping up in the IR, that means that the user provided insufficient information for the type to be inferred, or you're looking at a definition that was never monomorphized. Perhaps you can either filter those types out beforehand, or throw an error from the IR generation stage if one is encountered.

**Comment by otrho** [comment]
@sezna The IR is aborting when seeing one, but the regular backend doesn't mind, so some E2E tests are failing only for IR.  But I have a feeling it's actually getting addressed with other bugs and might go away.  Still investigating at the moment.

**Comment by emilyaherbert** [comment]
I think that there is a bug here as well as a design decision that we need to consider.

# Bug

Given this Sway code:

```rust
script;

fn return_the_same<T>(elem: T) -> T {
  let x: T = elem;
  x
}

fn main() -> u64 {
    let foo = return_the_same(7u64);
    let bar = return_the_same::<u64>(7u64);
   1
}
```

this code compiles, however in both cases at code gen time the variable declaration `let x: T = elem` reveals that `T` is still an `Unknown Generic T`. It is my understanding that you are suggesting that the `bar` declaration should be providing enough type information via the type params to eliminate the `Unknown Generic T` from the variable declaration. But it is not, so this is a bug.

This had previously been a silent bug, but now it is manifesting itself in the implementation of `size_of` (#818). Expanding this example (and checking out the `emilyaherbert/sizeof` branch), if we have this Sway:

```rust
script;

use std::chain::assert;

fn find_the_size_of_the_type<T>(elem: T) -> u64 {
  size_of::<T>()
}

fn main() -> u64 {
    assert(find_the_size_of_the_type(7u64) == 8);
    assert(find_the_size_of_the_type::<u64>(7u64) == 8);
    1
}
```

this code fails to compile and the compiler gives back an `Unknown type "T"` error in both cases.

> What behavior would you be expecting?

As the user, I expect it to behave like the equivalent Rust code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6d8af185403ad73c83d9c1e7b9cb3547

# Design decision

I feel that the current language design is insufficient for dealing with generics. It is currently possible at the language level to write a function that has insufficient type information without really understanding that it has insufficient type information, or even worse the insufficient type information failing silently. I feel that this should not be possible. This could be fixed by either:

1. If you are suggesting that functions with type arguments can only have enough type information if they are given type parameters, then it should be impossible to write such a function without passing type parameters.
2. It should be possible to infer the type information for the generic types from the arguments, and type parameters are only necessary when the information for the generic types cannot be inferred. Like in this example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cceebeb3174c83af1345763015357469

Personally, I like (2) as it feels more Rust-like and more friendly. (2) would also solve the bug described above.

**Comment by mohammadfawaz** [comment]
So basically I guess the problem boils down to: inferring generic types from function arguments does not work today. Here's another example that fails to compile with: `no method named "eq" found for type "numeric"`.
```rust
fn foo<T>(x: T) -> T{
    x
}

fn main() {
    assert(foo(7) == 7);
}
```
It passes if I change `foo(7)` to `foo::<u64>(7)`.

**Comment by emilyaherbert** [comment]
@mohammadfawaz  I think that is failing for a different reason.

The example that you provided passed because `foo(7)` is implicitly converting a numeric to a u64 on the `7`, which is totally fine as they both use u64 under the hood. Then `foo(7) == 7` is also doing an implicit conversion from a numeric to a u64 on the second `7`, which is again totally fine. There is an impl for `Eq` for u64 so there is no error.

However if you have this:

```rust
script;

use std::chain::assert;

fn foo<T>(x: T) -> T{
    x
}

fn main() {
    assert(foo(7u8) == 7);
}
```

This gives you a warning that you are converting a u64 to a u8 which will lose precision. But again there is an impl for `Eq` for u64 so there is no error.

**Comment by sezna** [comment]
@emilyaherbert what version of forc are you on? @mohammadfawaz's example fails for me on the latest master, perhaps related to some of the `numeric` changes

**Comment by emilyaherbert** [comment]
@sezna this fails for me on the latest master:

```rust
script;

use std::chain::assert;

fn foo<T>(x: T) -> T{
    x
}

fn main() {
    assert(foo(7) == 7);
}
```

this passes for me on the latest master:

```rust
script;

use std::chain::assert;

fn foo<T>(x: T) -> T{
    x
}

fn main() {
    assert(foo::<u64>(7) == 7);
}
```

**Comment by sezna** [comment]
(re: the larger comment) Thanks for the clarification @emilyaherbert, that makes a lot of sense. yes the parameters should absolutely be inferred from the arguments. I have checked and I believe that is the case currently. When you said you checked the types at codegen, what do you mean by they still say "unresolved generic"? I have run a couple of tests and I'm seeing the types all having known sizes at codegen time, and known types. To provide some clarity, monomorphizing makes a copy of the declaration in order to assign types, so the original declaration will indeed still say it is a generic. 

In general, at codegen time, if any type was underspecified, there is an error since the compiler won't know how much space to allocate. The lack of such an error suggests that the types are indeed known in time, and not unknown at codegen time.


Re: the smaller, more recent comment: yes I believe that's related to #832 ? since you're casting the `numeric` directly into a `u64`

**Comment by emilyaherbert** [comment]
> yes the parameters should absolutely be inferred from the arguments. I have checked and I believe that is the case currently

Ah so maybe the bug is in type inference 😄 Although that makes me more confused as to why earlier you claimed that the generic functions would not have enough type information without specifying type params 😕 

> When you said you checked the types at codegen, what do you mean by they still say "unresolved generic"?

Checkout my branch `emilyaherbert/generics-bug-demo`. I have an example of what I mean there:

Given this Sway code:

```rust
script;

fn return_the_same<T>(elem: T) -> T {
  let x: T = elem;
  x
}

fn main() -> u64 {
    let foo = return_the_same(7u64);
    let bar = return_the_same::<u64>(7u64);
   1
}
```

adding this line: https://github.com/FuelLabs/sway/blob/52d2d4c0daa079d5059f4d25b7465a4fb3328ed3/sway-core/src/asm_generation/declaration/var_decl.rs#L15

produces the output:

```bash
"foo": UnsignedInteger(
    SixtyFour,
)
"x": UnknownGeneric {
    name: Ident {
        name_override_opt: None,
        span: Span {
            span: Span {
                str: "T",
                start: 28,
                end: 29,
            },
            path: Some(
                "generics_bug_demo/src/main.sw",
            ),
        },
    },
}
"bar": UnsignedInteger(
    SixtyFour,
)
"x": UnknownGeneric {
    name: Ident {
        name_override_opt: None,
        span: Span {
            span: Span {
                str: "T",
                start: 28,
                end: 29,
            },
            path: Some(
                "generics_bug_demo/src/main.sw",
            ),
        },
    },
}
```

This output is telling me that there was indeed two versions of `return_the_same` put through codegen, but there is a bug in monomorphization where the variable declaration inside `return_the_same` is not being given the correct type ascription. But, thus far, this bug has been totally irrelevant because the code gen function doesn't look at the type ascription at all:
https://github.com/FuelLabs/sway/blob/52d2d4c0daa079d5059f4d25b7465a4fb3328ed3/sway-core/src/asm_generation/declaration/var_decl.rs#L21

**Comment by sezna** [comment]
OhhhHHHhHHh I think I see what is going on here. I think this is related to how we hold on to function declarations inside of every application. _that_ copy of the function declaration is _not_ the monomorphized one. OhhhHH.

I'll have to do a bit more investigation here to confirm this is indeed the case...

**Comment by otrho** [comment]
I think that would explain how it's leaking into IR... :slightly_smiling_face:
