### ISSUE TITLE
Change forc's `git` dependencies to not rely on the GitHub REST API. Use git tags to pin to versions instead.

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#829]
Currently `forc` doesn't really support `git` dependencies generally, but rather calls into the GitHub REST API.

As a part of https://github.com/FuelLabs/sway/pull/825, I'm aiming to switch us to a more genuine/generalised git support like cargo has, however doing so will mean changing the way we pin to specific versions for git dependencies.

The current way that `std` and `core` git dependencies are pinned relies on using the GitHub-specific REST API to fetch the pinned "release" tarball. Under cargo git dependencies (and git itself), the term "version" doesn't really mean anything, as git dependencies are normally pinned to a particular commit either directly (`rev`), under a `tag` or under a given git `branch`. In order to emulate the current behaviour where we pin `std` and `core` to a particular `version`, I'd recommend we instead add a git tag to the commit that publishes the new version and pin the dependency using the version tag (e.g. `tag = "v0.1.0"`).

**Comment by adlerjohn** [comment]
> we instead add a git tag to the commit that publishes the new version and pin the dependency using the version tag

I don't think we need to separately do that; cutting a release on GitHub automatically creates a tag.

**Comment by mitchmindtree** [comment]
I did notice that we already had the necessary tags late last night! I've added a commit to the WIP build plan PR [here](https://github.com/FuelLabs/sway/pull/825/commits/82ecdc30018ba7aa2e3a0beb94a7ad30485d9186) that makes use of the new `tag` field (replacing the `version` field) in the tests.
