### ISSUE TITLE
`numeric` type cannot look up any methods

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#832]
With the introduction of a `numeric` type, which is castable to any unsigned integer type, we have been able to infer a lot about integer widths and remove a lot of downcasting warnings.

Unfortunately, we are unable to look up methods for this type. 
```rust
29 |
30 |     // should return 15
31 |     if let Result::Ok(y) = x { y + 10 } else { 1 }
   |                                  ^ No method named "add" found for type "numeric".
32 | }
```

I think it would be reasonable to either cast `numeric` to a `u64` when looking up methods, or, check all numeric types starting from `u64` and going down, then casting it to the first type that had a matching method.

For anybody who encounters this issue, the workaround is to just define the number  as a concrete type. E.g. `let x = 5u64` or `let x: u64 = 5`.

**Comment by mohammadfawaz** [comment]
I wonder if this happens because `y` does not have an explicit `let y = ` and is instead defined via pattern matching. I'm not seeing this issue with something like:
```rust
script;
struct S {
  foo: u64,
}
fn main() -> u64 {
    let y = 1; 
    let s = S { foo: y + 10 };
    y + 15
}
```

**Comment by sezna** [comment]
Hm, this could be a bug in my `if let` implementation then...I'll investigate and, if it is, I'll close this.

**Comment by emilyaherbert** [comment]
@sezna I wasn't able to re-create this bug and as it is from Feb 2022, I believe it is likely resolved. Can you confirm? I have a PR here: #3700 . CC @mohammadfawaz
