### ISSUE TITLE
Allow access of script data via arguments in the main function

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#845]
Script data is currently inaccessible without using `asm` to extract it from the call frame. Ideally, the compiler should magically handle that as a language feature and expose it to the user. 

This should probably take the form of arguments to the main function, e.g.:
```rust
fn main(a: u64, b: bool, c: etc...) -> bool { ... }
```

Where `a`, `b`, and `c` are script data. 

The compiler should probably revert if these values are not provided in the script data as expected.

**Comment by adlerjohn** [comment]
> The compiler should probably revert if these values are not provided in the script data as expected.
For stack-only types, this can maybe be done with a single check against the `scriptDataLength` field of the tx.

Types that aren't full-width might also have to be checked to be `0` on their high bits.

**Comment by nfurfaro** [comment]
For reference, we have this in the stdlib that could be removed when this issue is closed:
https://github.com/FuelLabs/sway-lib-std/blob/2c4f9ff384917442d4c2bf5cce530953673de59f/src/chain.sw#L54

**Comment by simonr0204** [comment]
This seems to "just work" with predicates:

https://github.com/FuelLabs/sway-applications/blob/simon-otc-swap-predicate/otc-swap-predicate/src/main.sw#L17

Was this implemented separately to scripts or is my code not doing what I think it's doing ?

**Comment by mohammadfawaz** [comment]
@AlicanC would be nice to generalize this to predicates as well. See https://github.com/FuelLabs/sway/issues/2581

I expect the work to be basically identical.

**Comment by simonr0204** [comment]
> For reference, we have this in the stdlib that could be removed when this issue is closed: https://github.com/FuelLabs/sway-lib-std/blob/2c4f9ff384917442d4c2bf5cce530953673de59f/src/chain.sw#L54

This probably _shouldn't_ be removed, as other contexts might want to inspect the script data (e.g. a predicate spent by a given script might want to check the script data and bytecode). These wouldn't have access to the `main()` args directly as it's a different VM instance.
