### ISSUE TITLE
Introduce intrinsics for VM operations.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/sway#855]
See FuelLabs/sway#1074

ASM blocks are very hard to optimise for and are generally error prone, as they are untyped and the author often needs to make assumptions about the compiler code generation.  In an effort to minimise the need for ASM blocks in the standard library we can make compiler intrinsics which wrap useful VM opcodes such as `MCP` & `MEQ` or `BAL` & `BURN`, etc.

**Comment by mohammadfawaz** [comment]
Relevant links:
https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Other-Builtins.html#Other-Builtins
https://en.wikipedia.org/wiki/Intrinsic_function

**Comment by mohammadfawaz** [comment]
We can basically have them all start with `__builtin` like C/C++ to minimize collision and make it clear that they are an advanced feature.

**Comment by mohammadfawaz** [comment]
@vaivaswatha now that https://github.com/FuelLabs/sway/pull/2100 is close to be merged and we have a prototype of how these things can look like, maybe it's a good time to step back a bit and write up an RFC for the full feature and its implementation. This serves multiple purposes:
1. Thinking through the big picture and the scope of this project: what intrinsics do we want to support, What IR instructions do we need to add, Interactions with the different data types, Testing plan, etc.
2. Document all the intrinsics in one place (addresses the last point in https://github.com/FuelLabs/sway/pull/2100#discussion_r908096738)
3. Uncover any overlooked issues in the existing implementation (hopefully there are none!)
4. Lay out the benefits of this project in terms of type checking and future optimizations.

**Comment by otrho** [comment]
We have intrinsics and an RFC now.
