### ISSUE TITLE
Forc version seems to be gone

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#881]
`forc --version` should display the version. It seems to have been removed at some point.

**Comment by mitchmindtree** [comment]
The [`built` crate](https://crates.io/crates/built) could be handy for this and ensuring `version` is always up to date (unless `clap` already provides some way of automating this that is).

*Note: If we do use `built` we should be conservative about what we include from it and only use it for what we need (i.e. pulling the `version` from the Cargo.toml), as including some of its other features like build-timestamps can make achieving reproducible binaries near-impossible in case we ever want to go down that road.*
