### ISSUE TITLE
Move book-worthy content from READMEs into The Sway Book

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#883]
As mentioned in #873.

We could potentially link to the relevant book section under each README instead of doubling content too.

**Comment by binggh** [comment]
hey, would like to contribute to this issue if it's left open.

Looked through the READMEs, seems like only the one mentioned within #873 is long enough to warrant its own section. My suggestion is to insert a `Forc` section before `Testing` section within the book, and have subsections dedicated to each forc command, with usage, args, options and examples shown. Much like what [the cargo book](https://doc.rust-lang.org/cargo/commands/index.html) does.

How does this sound?

**Comment by adlerjohn** [comment]
Yeah, that sounds good

**Comment by SilentCicero** [comment]
Related: https://github.com/FuelLabs/fuels-rs/issues/216

**Comment by mitchmindtree** [comment]
Re-opening as we still need to move actual README content :joy:

**Comment by binggh** [comment]
> Re-opening as we still need to move actual README content 😂

All of the content within [forc/README.md](https://github.com/FuelLabs/sway/blob/master/forc/README.md) has been copied into the relevant forc command's page under an examples section (see: [forc init](https://fuellabs.github.io/sway/latest/forc/commands/forc_init.html)) - unless what you meant was there needs to be a dedicated section for the content in the forc README rather than inserting the examples within each command's page

**Comment by mitchmindtree** [comment]
I think all we need now is to replace the majority of the content in the README with a link to [the relevant `forc` chapter](https://fuellabs.github.io/sway/latest/forc/index.html) in the sway book. E.g. the README should now just be something like:

```
# forc

Forc is the Fuel Orchestrator.

Find out everything you need to know about Forc under [its chapter in the Sway book][1]:

[1]: https://fuellabs.github.io/sway/latest/forc
```

**Comment by binggh** [comment]
makes sense, I probably should've done that in the original PR so that there wasn't a need to maintain the README anymore, since it might cause confusion to devs and maintainers alike. Will open a quick PR for that
