### ISSUE TITLE
Rename `sway-server` crate to `sway-lsp`?

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#891]
Was having a chat with @JoshuaBatty and we're thinking it might be nice to make the name a little more specific?

**Comment by otrho** [comment]
I see a lot of LSP servers on GitHub calling themselves `LANG-language-server` which is even more verbose but unambiguous.  https://langserver.org/

**Comment by mitchmindtree** [comment]
My personal preference would be for `sway-lsp` - I think it's probably clear enough (the top google result for LSP is language server, then lumpy space princess :laughing:), in the same way that `sway-ir` is pretty clear and it's nice not having to read/write `sway-intermediate-representation` everywhere.

**Comment by adlerjohn** [comment]
Anything is better than the current `sway-server` 😂
