### ISSUE TITLE
Uncertainty around enum memory layout

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#896]
Currently, enums and structs lay out memory in a suboptimal way. If an enum contains a struct, we actually put pointers inside of those data structures. For example, the enum `Result::Ok(some_struct)` -- you might expect the memory layout to look like this:
```
[enum tag][       some_struct       ]
[ 1 word ][sizeof(some_struct) words]
```
What it actually looks like is this:
```
[enum tag][   ptr to some_struct    ]
[ 1 word ][sizeof(some_struct) words]
```
This is not _incorrect_ per se, but it is not ideal. Although, we do actually reserve `sizeof(some_struct)` space in many cases and just put the pointer in that large space.

This only happens with nested things. I think we can either think of something clever in the old codegen to solve this, or, let it be for now since there are no correctness issues and wait for IR to fix this. cc @otrho what does the IR do here?

**Comment by otrho** [comment]
I'm 99% sure the IR does the former and embeds structs in each other.  An enum is always lowered to a tagged union struct, as above.  The IR itself definitely embeds, and the `sway-core` code measures the size of structs as if they're embedded, but I'd have to double check the actual ASM output before being 100% sure.
