### ISSUE TITLE
Functional issue with accessing tuples defined inside a struct

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#904]
Consider the script below:

```rust
script;
use std::chain::*;

struct S1 {
    t: (u64, u64), 
}

struct T {
    x0: u64,
    x1: u64
}
struct S2 {
    t: T, 
}

fn main() {
    let s1 = S1 {
        t: (0, 1)
    };
    let t1 = s1.t;
    assert(t1.0 == 0);
    assert(t1.1 == 1);

    let s2 = S2 {
        t: T {
            x0: 0, 
            x1: 1, 
        }
    };
    let t2 = s2.t;
    assert(t2.x0 == 0);
    assert(t2.x1 == 1);
}
```
Basically, the first two asserts fail while the last two pass. The two parts of the code are quite similar except that one part uses a tuple and the other uses a struct.

I'm fairly certain that the problem is here: https://github.com/FuelLabs/sway/blob/aa7d00091ecb69a44bc04d186d830a15b2573968/sway-core/src/asm_generation/expression/subfield.rs#L157 
The function `is_copy_type()` returns `true` for tuples, and therefore, we treat tuples like primitive types when accessing them from a struct. This is incorrect because tuples may not always fit in a single register.

**Comment by otrho** [comment]
As an aside, this is not a problem in the IR currently.  But you already have a fix ready anyway, so...  ¯\_(ツ)_/¯

**Comment by mohammadfawaz** [comment]
Ahhh well. That's good news!
