### ISSUE TITLE
Tuples with a single element cause some issues

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#906]
Simple example:
```rust
script;
use std::chain::*;

struct S {
    t: (u64),
}

fn main() {
    let s = S {
        t: (2)
    };
}
```
I get the following compile error:
```
 8 |
 9 |     let s = S {
10 |         t2: (2)
   |              ^ Mismatched types.
expected: (u64)
found:    numeric.

11 |     };
12 | }
```
Can't get it to work even if I change `(2)` to `2`, `(2u64)`, or `2u64`.

**Comment by emilyaherbert** [comment]
I investigated this some and found that this Sway code passes on the #1592 branch:

```rust
script;

struct S {
    t: (u64,),
}

fn main() {
    let s = S {
        t: (2,)
    };
}
```

The relevant parsing code is here: https://github.com/FuelLabs/sway/blob/786413b7b7a1bc47bd73169d90fa8abd762ea103/sway-parse/src/expr/mod.rs#L907

Ultimately, I don't know if there is a good way to determine if a user wants to parse something as parens or as a one-arity tuple, without forcing the trailing comma.

Python suffers from this same problem: https://www.w3schools.com/python/gloss_python_tuple_one_item.asp
And Rust: "Table B-8: Tuples" from https://doc.rust-lang.org/book/appendix-02-operators.html

So we need to decide:
1) Do we want to support one-arity tuples at all?
2) How will they be parsed? Is the comma necessary for creating a one-arity tuple?
2) How should we let users know that they may have made missed the trailing comma, without just showing them a type error? Rust chooses to show a warning that the parens are not necessary around the type argument, which is a good compromise: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4e7d46dae23194d07eb563413a678d7e
