### ISSUE TITLE
The compiler does not prevent assigning a data member of a non-mutable struct

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#908]
Here's a simple example. The code compiles and the `assert` passes. I'm not supposed to be able to write to `S.x` here since `S` is not declared as mutable.
```rust
script;
use std::chain::*;

struct S { x: u64 }

fn main() {
    let s = S { x: 0 }; // Non-mutable!!
    s.x = 1;
    assert(s.x == 1);
}
```
Reassigning the whole struct causes an error but reassigning parts of it does not.

**Comment by otrho** [comment]
Nice find!

**Comment by mohammadfawaz** [comment]
Fixing this is simple and I did it here: https://github.com/FuelLabs/sway/compare/mohammadfawaz/908?expand=1

However, this rightfully breaks the following:
```
struct A {
    a: u64,
}

impl A {
    fn f(self) {
        self.a = 42;
    }
}
```
because `self` is not mutable. The solution would be to add `mut` as such:
```rust
impl A {
    fn f(mut self) {
        self.a = 42;
    }
}
```
but that's not possible today.

**Comment by adlerjohn** [comment]
Is there an issue tracking adding `mut self`?

**Comment by mohammadfawaz** [comment]
Similarly, this doesn't work anymore:
```rust
fn bla(a: u64) {
    a = 0;
}
```
for the same reason.
