### ISSUE TITLE
Two new E2E tests don't work with `--use-ir`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#912]
The following tests fail with `--use-ir`. I actually get ` Panic` receipt when running `forc run --use-ir`.
* https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests/test_programs/tuple_in_struct
* https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests/test_programs/nested_structs

**Comment by otrho** [comment]
Have been fixed somewhere along the line.
