### ISSUE TITLE
Do not output nulls when generating ABI JSON

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/sway#926]
Currently an ABI JSON can contain nulls (`"components": null`):
```json
[
  {
    "type": "function",
    "inputs": [],
    "name": "read_counter",
    "outputs": [
      {
        "name": "",
        "type": "u64",
        "components": null
      }
    ]
  }
]
```

But our upstream on fuels-ts doesn't like them and expects no nulls (= no `"components": null`):
```json
[
  {
    "type": "function",
    "inputs": [],
    "name": "read_counter",
    "outputs": [
      {
        "name": "",
        "type": "u64"
      }
    ]
  }
]
```

Forc shouldn't output nulls.

**Comment by mohammadfawaz** [comment]
> Do you mean serde here? Wouldn't #[serde(skip_serializing_if = "Option::is_none")] work?

Didn't know about that! That would indeed make the JSON file a bit more condensed and readable.

@digorithm @adlerjohn @vnepveu thoughts about this?

**Comment by mohammadfawaz** [comment]
@AlicanC is this still an issue? In the [spec](https://fuellabs.github.io/fuel-specs/master/protocol/abi.html#json-abi-spec), we mention that arrays like `typeParameters`, `components` and `typeArguments` are `null` when they are not needed.

**Comment by AlicanC** [comment]
Not an issue ATM.
