### ISSUE TITLE
Error running `forc clean` with no Cargo manifest

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#932]
With no Cargo manifest file, running `forc clean` produces:

```console
$ forc clean
error: could not find `Cargo.toml` in `/home/john/local/fuellabs/sway-lib-std` or any parent directory
```

**Comment by mitchmindtree** [comment]
Good spot, the `forc_clean` op should first check if a `Cargo.toml` exists.

**Comment by eureka-cpu** [comment]
What do we want it to do if it doesn't find one?

**Comment by adlerjohn** [comment]
Presumably it should still do everything else fine, and not emit an error.
