### ISSUE TITLE
Contract method parameters not converted correctly to asm when IR is used

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#941]
e.g.
```rust
contract;

abi TestAbi {
    fn foo(x: u64) -> u64;
}

impl TestAbi for Contract {
   fn foo(y: u64) -> u64 {
        y
    }
}
```

Resulting IR is correct:
```rust
contract {
    fn foo<cb3307c8>(y !1: u64) -> u64 {
        entry:
        ret u64 y
    }
}

!0 = filepath "storage_access/src/main.sw"
!1 = span !0 93 94
```

Resulting intermediate asm is incorrect.
```
.program:
jump .0
noop
data section offset placeholder         ; data section offset
.0                                      ; end of metadata
data section register load placeholder
add $$ds $$ds $is
                                        ; Begin contract ABI selector switch
lw $r1 $fp i73                          ; load input function selector
lw $r2 data_0                           ; load fn selector for comparison
eq $r3 $r1 $r2                          ; function selector comparison
jnei $zero $r3 .1                       ; jump to selected function
rvrt $zero                              ; revert if no selectors matched
.1
ret $r0
.data:
data_0 .u32 0xcb3307c8
```
Note that we retur `$r0` which is never defined.

**Comment by mohammadfawaz** [comment]
@otrho not sure if this is one of the issues you're already working on. If so, feel free to close :)

**Comment by otrho** [comment]
This is what I'm working on next -- contract calls aren't working in general. :)

**Comment by mohammadfawaz** [comment]
@otrho I assume you're going to add an IR instruction for contract calls from scripts? (i.e. an instruction that becomes `CALL` in assembly). Note that I explicitly create a struct to wrap the user parameters in the old CodeGen and provide a pointer to it to `CALL`. I suspect we're going to have to do the same in IR (either in the IR generator or in the IR->ASM part).

**Comment by otrho** [comment]
Yeah, I'm also assuming a `CCALL` instruction will be needed.  It doesn't make sense to generalise the existing `CALL` to support contracts.

**Comment by adlerjohn** [comment]
Wait, why does calling _from_ a script or contract make a difference?

**Comment by otrho** [comment]
While at the moment there are still some problems with contract calls, they are tracked in other issues.  This issue was about adding the `contract_call` instruction which is done now.
