### ISSUE TITLE
Consider whether the `ContractCaller` type name should be exposed in Sway

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#947]
Should a `ContractCaller` type name be exposed to the user in the language? If we do this, this would allow returning an `abi` cast from a function.  See FuelLabs/sway#1081.

**Comment by otrho** [comment]
I still need to wrap my head around the exact machinations of contract calling, but when looking at it for IR I was thinking of just using the contract address to represent the caller object.  I wonder if this is feasible for Sway too, though it might be a bit convoluted under the hood -- translating an address to `ContractCaller` in the type system.
