### ISSUE TITLE
Implement generic traits

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#948]
E.g.
```
pub trait From<T> {
    fn from<T>(v: T) -> self;
}
```
Not sure if this is the syntax we agreed on. I'll let @sezna and @emilyaherbert comment.

**Comment by emilyaherbert** [comment]
I think that this syntax will work for Sway. In it's context, I am picturing:

```rust
script;

pub trait From<T> {
    fn from<T>(v: T) -> self;
}

struct Option<T> {
  ..
}

struct Result<T, E> {
  ..
}

impl<T, E> From<Option<T>> for Result<T, E> {
  ..
}

fn main() -> bool {
 ..
}
```

**Comment by adlerjohn** [comment]
The above syntax works today @emilyaherbert ?

**Comment by emilyaherbert** [comment]
> The above syntax works today @emilyaherbert ?

It shouldn't. Generic traits should be a parse failure on master right now. If not, then that is a bug.
