### ISSUE TITLE
Functions dealing with `manifest` files shouldn't be in `sway-util`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#955]
As discussed in #945 

>I think we should move these functions into the `forc-util` crate as `sway-core` is unaware of the concept of a manifest file, and only deals with source code.

- `find_parent_dir_with_file()`
- `find_manifest_dir()`
- `find_cargo_manifest_dir()`

**Comment by mitchmindtree** [comment]
Technically these functions are in `sway-utils`, but yeah I think these would be better suited to the `forc-util` crate.

**Comment by eureka-cpu** [comment]
> Technically these functions are in `sway-utils`, but yeah I think these would be better suited to the `forc-util` crate.

Will update title!
