### ISSUE TITLE
Automatically fetch latest Fuel deps when initializing manifest

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#972]
Related: #601

## Context

Running `forc init` creates a default Cargo manifest file that includes some Fuel dependencies for testing purposes.

https://github.com/FuelLabs/sway/blob/7b51e653177bdc58bed454447c8dc43d9a4147f6/forc/src/utils/defaults.rs#L35-L42

Unfortunately, this 1) must be manually updated and 2) cannot be updated until a new version of the SDK is released, which first requires a new version of certain `sway-*` crates to be released, i.e. a circular dependency.

## Proposal

1. If online, the latest tag of the Fuel dependencies is fetched from their respective repositories and used.
2. If offline, a default Cargo manifest file is generated with whatever hard-coded Fuel dependency versions are in `defaults.rs`.

## Considerations

The latest version of Fuel dependencies is not guaranteed to be compatible with the version of `forc` that happens to be used; indeed, if a user downloads an older version of `forc` then it's almost certain to not be compatible with the latest version of `fuel-core`.

This might be indicative that _what generates the Cargo manifest file_ shouldn't in fact be `forc`, but should maybe be a separate binary installed as a plugin that's distributed via `fuels-rs` for example.

**Comment by adlerjohn** [comment]
cc @mitchmindtree @digorithm

**Comment by digorithm** [comment]
Tricky issue. Blindly pulling the latest tags will definitely break things on a user's project, especially for now that we're pushing lots of breaking changes. Plus the considerations you mentioned.

> This might be indicative that what generates the Cargo manifest file shouldn't in fact be forc, but should maybe be a separate binary installed as a plugin that's distributed via fuels-rs for example.

I like this idea, though we have to be careful when introducing more complexity to the toolchain and to the users 🤔

**Comment by adlerjohn** [comment]
Circular dependencies between Sway and fuels-rs have been alleviated, and fuels-rs will export everything as a single crate so this is less relevant.
