### ISSUE TITLE
CI is not running tests on `std` and `core` libraries

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/sway#983]
CI should be running cargo test on the standard and core libraries to make sure that they still compile and are working properly

**Comment by adlerjohn** [comment]
I think this is done? cc @nfurfaro

**Comment by nfurfaro** [comment]
@adlerjohn CI is now running tests for the stdlib , but I'm not sure about core. I can check tomorrow,  but there are most likely tests for core ib the sway e2e test suite.

**Comment by mitchmindtree** [comment]
Yeah `core` doesn't have a dedicated suite of tests afaik, but gets tested thoroughly as a part of the E2E tests. I believe it was just the `std` tests we were missing.

Closing, but feel free to re-open if anyone discovers any untested core tests that I've missed.
