### ISSUE TITLE
Move `abort_control_flow` test in root test dir

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#988]
https://github.com/FuelLabs/sway/tree/9105896a3561db90d0de8019c7468640109f6415/test/src/e2e_vm_tests/test_programs/abort_control_flow

**Comment by sezna** [comment]
Ah. It should actually be deleted.
https://github.com/FuelLabs/sway/tree/9105896a3561db90d0de8019c7468640109f6415/test/src/e2e_vm_tests/test_programs/should_pass/language/abort_control_flow

I moved it but did not add the removed path.
