### ISSUE TITLE
Formatting contract call arguments

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#992]
The formatter turns contract calls into something that looks like this:
```rust
caller.method {
    gas: 10000
}
();
```
I think it's better to have the `()` next to the `}`, so:
```rust
caller.method {
    gas: 10000
} ();
```

**Comment by mohammadfawaz** [comment]
@eureka-cpu is this being tracked somewhere for `fmt v2`?

**Comment by eureka-cpu** [comment]
> @eureka-cpu is this being tracked somewhere for `fmt v2`?

It is not but feel free to add this to the MVP!

**Comment by eureka-cpu** [comment]
@mohammadfawaz @adlerjohn @sezna do we want a space between the curly braces and parenthesis?
```rust
fuel_coin.burn {
        gas: default_gas
    } (7);
```
or keep it like all of the rest of the method calls:
```rust
fuelcoin_id.into()

fuel_coin.burn {
        gas: default_gas
    }(7);
```

**Comment by mohammadfawaz** [comment]
I'd go for no space before and after. We can always change it later if we don't like how it looks.

**Comment by eureka-cpu** [comment]
> I'd go for no space before and after. We can always change it later if we don't like how it looks.

Currently I have so that normal method calls like `fuelcoin_id.into()` have no space, and then ones wrapped in curly braces have the space between like in your original comment.

**Comment by sezna** [comment]
I vote for no space to be consistent with function applications, IMO. The single line structure format looks fine to me, but again, I think the space before the left banana should be omitted. Just my two cents...

**Comment by eureka-cpu** [comment]
@sezna since these are technically structs, do we also want to have field alignment for all instances of structs, including this one?

```rust
fuel_coin.burn {
    foo    : thing1,
    barbaz : thing2,
```

**Comment by sezna** [comment]
I mean....personally I love field alignment...so I vote yes
